<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="11" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">第8章 熱意を込めてコピーを書く方法</h1><div class="content-wrapper"><div class="section"><h2 class="section-title"><i class="fas fa-fire"></i>          熱意は説得力の源泉        </h2><div class="section-content"><p class="quote">「説得力のあるコピーを書く秘訣は、自分自身がその製品やサービスに対して熱意を持つこと」</p><p>◆ バイオメディカル企業の新株をセールスする若者の例：<span class="highlight">熱意だけで成功</span></p><p>◆ 書く前に<span class="highlight">製品を知り尽くす</span>ことの重要性：営業マンへの事前説明が顧客への説得につながる</p><p>◆ 熱意が顧客に<span class="highlight">伝播</span>する：売り手の確信が買い手の確信に変わる</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-balance-scale"></i>          熱意とバランスの取れた表現        </h2><div class="section-content"><div class="dos-donts"><div class="dos"><p class="step-title">効果的な熱意の表現</p><div class="list-item"><i class="fas fa-check-circle green-icon"></i><p>実体験や実話からの引用</p></div><div class="list-item"><i class="fas fa-check-circle green-icon"></i><p>自己投資を示す姿勢</p></div><div class="list-item"><i class="fas fa-check-circle green-icon"></i><p>証拠や具体的な数字を伴う確信</p></div><div class="list-item"><i class="fas fa-check-circle green-icon"></i><p>読者の立場に立った共感的表現</p></div></div><div class="donts"><p class="step-title">避けるべき表現</p><div class="list-item"><i class="fas fa-times-circle red-icon"></i><p>過度な誇張や虚偽</p></div><div class="list-item"><i class="fas fa-times-circle red-icon"></i><p>根拠のない美辞麗句</p></div><div class="list-item"><i class="fas fa-times-circle red-icon"></i><p>信頼性を損なう過剰表現</p></div><div class="list-item"><i class="fas fa-times-circle red-icon"></i><p>自分自身が信じていない言葉</p></div></div></div><p style="margin-top: 15px;">信念と信頼性のバランス：<span class="highlight">「まず自分が信じる」</span>ことが説得力の第一歩</p></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-wrapper {      display: flex;      flex-direction: column;      flex: 1;    }    .section {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      margin-bottom: 25px;    }    .section-title {      font-size: 22px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 15px;      display: flex;      align-items: center;      border-bottom: 2px solid #e6f0ff;      padding-bottom: 8px;    }    .section-title i {      margin-right: 10px;      color: #0d4d8c;    }    .section-content {      font-size: 16px;      line-height: 1.6;      color: #333;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 500;    }    .quote {      border-left: 4px solid #0d4d8c;      padding-left: 15px;      font-style: italic;      margin: 10px 0;    }    .steps {      display: flex;      justify-content: space-between;      margin-top: 10px;    }    .step {      background-color: #f8f9fa;      border-radius: 8px;      padding: 12px;      width: 48%;    }    .step-title {      font-weight: 700;      margin-bottom: 8px;      color: #0d4d8c;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .dos-donts {      display: flex;      justify-content: space-between;      margin-top: 15px;    }    .dos, .donts {      width: 48%;      background-color: #f8f9fa;      border-radius: 8px;      padding: 15px;    }    .dos {      border-left: 4px solid #28a745;    }    .donts {      border-left: 4px solid #dc3545;    }    .list-item {      display: flex;      align-items: flex-start;      margin-bottom: 8px;    }    .list-item i {      margin-right: 10px;      margin-top: 3px;    }    .green-icon {      color: #28a745;    }    .red-icon {      color: #dc3545;    }
</style>
