<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="12" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">第9章 コピーの出だしはこう書く</h1><div class="content-wrapper"><div class="section"><h2 class="section-title"><i class="fas fa-pen-fancy"></i>          セールスマンシップ・イン・プリント        </h2><div class="section-content"><p class="quote">「コピーを書くという仕事の定義は、活字でのセールスマンシップである」</p><p>◆ 冒頭から<span class="highlight">読者の関心事に直行</span>する</p><p>◆ <span class="highlight">美辞麗句より具体情報</span>：機能、価格、利点を明示する</p><p>◆ 「生気のない」コピーや「お利口すぎる」コピーは避ける</p><p>◆ 読者が店頭で尋ねる質問に即答するつもりで書く</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-exclamation-triangle"></i>          失敗するコピーの共通点        </h2><div class="section-content"><div class="steps"><div class="step"><p class="step-title">NGの出だし</p><p>✖ 広告らしい大げさな表現</p><p>✖ 抽象的な話から始める</p><p>✖ 業界用語やジャーゴン</p><p>✖ 自社視点の内容</p></div><div class="step"><p class="step-title">効果的な出だし</p><p>✓ 関心を引く<span class="highlight">具体的な事実</span></p><p>✓ <span class="highlight">ニュース価値</span>のある情報</p><p>✓ 読者の<span class="highlight">問題解決</span>につながる提案</p><p>✓ <span class="highlight">数字</span>や<span class="highlight">事例</span>で信頼性を高める</p></div></div><p style="margin-top: 15px;">「最初の10語で読者を捕まえられなければ、その広告は失敗」（ケープルズ）</p></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-wrapper {      display: flex;      flex-direction: column;      flex: 1;    }    .section {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      margin-bottom: 25px;    }    .section-title {      font-size: 22px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 15px;      display: flex;      align-items: center;      border-bottom: 2px solid #e6f0ff;      padding-bottom: 8px;    }    .section-title i {      margin-right: 10px;      color: #0d4d8c;    }    .section-content {      font-size: 16px;      line-height: 1.6;      color: #333;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 500;    }    .quote {      border-left: 4px solid #0d4d8c;      padding-left: 15px;      font-style: italic;      margin: 10px 0;    }    .steps {      display: flex;      justify-content: space-between;      margin-top: 10px;    }    .step {      background-color: #f8f9fa;      border-radius: 8px;      padding: 12px;      width: 48%;    }    .step-title {      font-weight: 700;      margin-bottom: 8px;      color: #0d4d8c;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }
</style>
