<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="14" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">第11章 コピーの売込み効果を高める20の方法</h1><div class="content-wrapper"><div class="section"><h2 class="section-title"><i class="fas fa-pen-fancy"></i>    効果的なコピーの基本原則</h2><div class="section-content"><div class="method-grid"><div class="method-item"><p class="method-title"><i class="fas fa-check-circle"></i>現在形・あなた中心で書く</p><p>「お客様が感じる」（✓）vs「人々が感じる」（✗）</p><p>自社視点より<span class="highlight">読者視点</span>を優先する</p></div><div class="method-item"><p class="method-title"><i class="fas fa-check-circle"></i>小見出しの効果的活用</p><p>ページを<span class="highlight">視覚的に分割</span></p><p>本文をスキャンする読者を誘導する<span class="highlight">看板</span>の役割</p></div><div class="method-item"><p class="method-title"><i class="fas fa-check-circle"></i>具体性と数字の活用</p><p>「多数の人が」より「<span class="highlight">92%の顧客が</span>」</p><p>具体的数字は信頼性と記憶に残りやすさを向上</p></div><div class="method-item"><p class="method-title"><i class="fas fa-check-circle"></i>CTAを明確に</p><p>「詳しくは」より「<span class="highlight">今すぐ申し込む</span>」</p><p>行動の障壁を下げる明確な指示</p></div></div></div></div><div class="section"><h2 class="section-title"><i class="fas fa-star"></i>    実践テクニック</h2><div class="section-content"><div class="method-grid"><div class="method-item"><p class="method-title"><i class="fas fa-check-circle"></i>繰り返しの効果的活用</p><p>重要ポイントは<span class="highlight">戦略的に繰り返す</span></p><p>特に冒頭・本文・結びの3箇所での反復が効果的</p></div><div class="method-item"><p class="method-title"><i class="fas fa-check-circle"></i>P.S.の戦略的配置</p><p>最も読まれる場所の一つ</p><p>緊急性や<span class="highlight">特典</span>を配置して反応率向上</p></div><div class="method-item"><p class="method-title"><i class="fas fa-check-circle"></i>長文コピーの活用</p><p>テスト結果：<span class="highlight">詳細な情報を求める顧客</span>も多い</p><p>スキャン読みとじっくり読みの両方に対応</p></div><div class="method-item"><p class="method-title"><i class="fas fa-check-circle"></i>読みやすさの確保</p><p>短い文・段落・行間・<span class="highlight">余白</span>の確保</p><p>文字サイズと行長のバランスに配慮</p></div></div><p class="quote">「何をどう言うかではなく、何を言うかが重要。意味のある内容を単刀直入に伝えよ」 —ケープルズ</p></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-wrapper {      display: flex;      flex-direction: column;      flex: 1;    }    .section {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      margin-bottom: 25px;    }    .section-title {      font-size: 22px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 15px;      display: flex;      align-items: center;      border-bottom: 2px solid #e6f0ff;      padding-bottom: 8px;    }    .section-title i {      margin-right: 10px;      color: #0d4d8c;    }    .section-content {      font-size: 16px;      line-height: 1.6;      color: #333;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 500;    }    .quote {      border-left: 4px solid #0d4d8c;      padding-left: 15px;      font-style: italic;      margin: 10px 0;    }    .method-grid {      display: grid;      grid-template-columns: repeat(2, 1fr);      gap: 15px;    }    .method-item {      background-color: #f8f9fa;      border-radius: 8px;      padding: 12px;    }    .method-title {      font-weight: 700;      color: #0d4d8c;      margin-bottom: 5px;      display: flex;      align-items: center;    }    .method-title i {      margin-right: 8px;      font-size: 14px;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }
</style>
