<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="15" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">第12章 誰もがぶつかる問題を避ける方法</h1><div class="content-wrapper"><div class="section"><h2 class="section-title"><i class="fas fa-lightbulb"></i>          地味な商品の演出法        </h2><div class="section-content"><p class="quote">「面白みのない商品を何とかして広告でイキイキと見せなければならない」</p><p>◆ <span class="highlight">地味な商品の例</span>：統計サービス、除菌剤、のど薬、ミシン、地下納体堂など</p><p>◆ <span class="highlight">想像力を刺激する広告</span>：「数億ドルがドブへ」（統計ミスによる失敗事例）</p><p>◆ 読者の注目を集める<span class="highlight">ドラマチックな表現</span>で専門的・技術的商品も魅力的に</p><p>◆ 「<span class="highlight">歴史に残る見当違い</span>」シリーズ：統計会社が失敗事例を示し自社の価値を訴求</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-magic"></i>          演出の技法        </h2><div class="section-content"><div class="steps"><div class="step"><p class="step-title">ストーリー化の手法</p><p>● <span class="highlight">Before/After</span>：使用前後の対比</p><p>● <span class="highlight">ドラマ化</span>：日常的な問題をストーリーに</p><p>● <span class="highlight">擬人化</span>：商品や機能に人格を与える</p></div><div class="step"><p class="step-title">ベネフィット翻訳</p><p>● <span class="highlight">技術的特徴</span>を<span class="highlight">顧客価値</span>に変換</p><p>● <span class="highlight">損失回避</span>を強調（失敗事例の活用）</p><p>● <span class="highlight">可視化</span>：目に見えない価値を図表や比喩で表現</p></div></div><p style="margin-top: 15px;">重要なのは、商品自体より<span class="highlight">顧客にとっての価値</span>を明確に提示すること</p></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-wrapper {      display: flex;      flex-direction: column;      flex: 1;    }    .section {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      margin-bottom: 25px;    }    .section-title {      font-size: 22px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 15px;      display: flex;      align-items: center;      border-bottom: 2px solid #e6f0ff;      padding-bottom: 8px;    }    .section-title i {      margin-right: 10px;      color: #0d4d8c;    }    .section-content {      font-size: 16px;      line-height: 1.6;      color: #333;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 500;    }    .quote {      border-left: 4px solid #0d4d8c;      padding-left: 15px;      font-style: italic;      margin: 10px 0;    }    .steps {      display: flex;      justify-content: space-between;      margin-top: 10px;    }    .step {      background-color: #f8f9fa;      border-radius: 8px;      padding: 12px;      width: 48%;    }    .step-title {      font-weight: 700;      margin-bottom: 8px;      color: #0d4d8c;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }
</style>
