<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="16" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">第13章 こうすればもっと問合せが増える32の方法</h1><div class="content-wrapper"><div class="section"><h2 class="section-title"><i class="fas fa-balance-scale"></i>問合せ増加の2つのアプローチ</h2><div class="section-content"><div class="comparison"><div class="comparison-col"><p class="comparison-title">1. 広告全体の効果向上</p><p class="bullet-point">関心を引く見出しと長いコピーで<span class="highlight">総合効果</span>を上げる</p><p class="bullet-point">問合せ増加は良質な広告の<span class="highlight">副産物</span>として発生</p><p class="bullet-point">長期的な<span class="highlight">顧客価値</span>と<span class="highlight">ブランド構築</span>に貢献</p><p class="bullet-point">例：実証型訴求、数字使用、具体的ベネフィット</p></div><div class="comparison-col"><p class="comparison-title">2. 問合せのみ増加</p><p class="bullet-point"><span class="highlight">オファー重視</span>で一時的に反応数を増やす</p><p class="bullet-point">広告の総合的な宣伝効果は向上しない場合も</p><p class="bullet-point">短期的な<span class="highlight">数値目標達成</span>に有効</p><p class="bullet-point">例：無料パンフレット訴求、期間限定特典</p></div></div><p class="quote">"コンマ数%の人に反応してもらうために、99%超の人々に不快な思いをさせてはならない" —神田昌典</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-chart-line"></i>問合せ増加の実践テクニック</h2><div class="section-content"><p>◆ <span class="highlight">オファーを見出しに入れる</span>：「無料冊子進呈」「特別価格でご提供」など</p><p>◆ <span class="highlight">複数の返信手段</span>を用意：電話、はがき、ウェブ、来店など選択肢を広げる</p><p>◆ <span class="highlight">期限設定</span>を明示：「9月30日まで」「先着100名様」など緊急性を創出</p><p>◆ <span class="highlight">保証・安心感</span>を提供：「30日間返金保証」「無料お試し」「実績数」</p><p>◆ <span class="highlight">視認性の高いCTA</span>：ボタン、色、配置で「今すぐ申し込む」を強調</p><p>テストの鍵：<span class="highlight">1つの要素だけ</span>を変更して効果測定（A/Bスプリット）</p></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-wrapper {      display: flex;      flex-direction: column;      flex: 1;    }    .section {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      margin-bottom: 25px;    }    .section-title {      font-size: 22px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 15px;      display: flex;      align-items: center;      border-bottom: 2px solid #e6f0ff;      padding-bottom: 8px;    }    .section-title i {      margin-right: 10px;      color: #0d4d8c;    }    .section-content {      font-size: 16px;      line-height: 1.6;      color: #333;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 500;    }    .quote {      border-left: 4px solid #0d4d8c;      padding-left: 15px;      font-style: italic;      margin: 10px 0;    }    .comparison {      display: flex;      justify-content: space-between;      margin-top: 15px;    }    .comparison-col {      background-color: #f8f9fa;      border-radius: 8px;      padding: 15px;      width: 48%;    }    .comparison-title {      font-weight: 700;      margin-bottom: 10px;      color: #0d4d8c;      text-align: center;      font-size: 18px;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .bullet-point {      margin-bottom: 8px;      position: relative;      padding-left: 20px;    }    .bullet-point:before {      content: "•";      position: absolute;      left: 0;      color: #0d4d8c;      font-weight: bold;    }
</style>
