<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="17" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">第14章 小スペース広告で利益を上げる方法</h1><div class="content-wrapper"><div class="section"><h2 class="section-title"><i class="fas fa-compress-arrows-alt"></i>          小スペース広告の重要性        </h2><div class="section-content"><p>◆ 商品によって<span class="highlight">最適なスペース</span>は異なる</p><p>◆ 例：減量ベルト→<span class="highlight">小スペース</span>で利益、育毛剤→<span class="highlight">全面広告</span>が効果的</p><p>◆ 小スペース広告が効果的な理由：費用対効果、読者の心理的負担の少なさ</p><p class="quote">「小スペース広告は、適切な商品とターゲットの組み合わせで、大スペース広告の数倍の効果を発揮することがある」</p><p>◆ スペース料金に対する<span class="highlight">反応率</span>と<span class="highlight">売上</span>の最適バランスを見極める</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-ruler-combined"></i>          効果的なレイアウト技法        </h2><div class="section-content"><div class="steps"><div class="step"><p class="step-title">レイアウト原則</p><p>◆ <span class="highlight">一点集中</span>：1つの訴求ポイントに絞る</p><p>◆ <span class="highlight">ビジュアル</span>は商品を明確に伝えるものを</p><p>◆ <span class="highlight">読みやすいタイポグラフィ</span>を優先</p><p>◆ 余白を恐れない：<span class="highlight">詰め込み過ぎない</span></p></div><div class="step"><p class="step-title">テスト項目</p><p>◆ <span class="highlight">サイズ</span>：異なるサイズでコスト効率を検証</p><p>◆ <span class="highlight">位置</span>：ページ上部・中央・下部の効果差</p><p>◆ <span class="highlight">曜日・媒体</span>：掲載タイミングの最適化</p><p>◆ <span class="highlight">価格表示</span>：明示的か暗示的か</p></div></div><div class="examples"><div class="example"><p class="example-title">商品カタログ型</p><p>商品写真中心、最小限のコピーで商品特性を伝える。価格を明示。</p></div><div class="example"><p class="example-title">ニュース型</p><p>記事風レイアウトで信頼性を高める。専門的情報で関心を引く。</p></div><div class="example"><p class="example-title">クーポン型</p><p>切り取りライン、期限明示でアクションを促す。特典を強調。</p></div></div></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-wrapper {      display: flex;      flex-direction: column;      flex: 1;    }    .section {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      margin-bottom: 25px;    }    .section-title {      font-size: 22px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 15px;      display: flex;      align-items: center;      border-bottom: 2px solid #e6f0ff;      padding-bottom: 8px;    }    .section-title i {      margin-right: 10px;      color: #0d4d8c;    }    .section-content {      font-size: 16px;      line-height: 1.6;      color: #333;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 500;    }    .quote {      border-left: 4px solid #0d4d8c;      padding-left: 15px;      font-style: italic;      margin: 10px 0;    }    .steps {      display: flex;      justify-content: space-between;      margin-top: 10px;    }    .step {      background-color: #f8f9fa;      border-radius: 8px;      padding: 12px;      width: 48%;    }    .step-title {      font-weight: 700;      margin-bottom: 8px;      color: #0d4d8c;    }    .examples {      display: flex;      justify-content: space-between;      margin-top: 15px;    }    .example {      border: 1px solid #e6f0ff;      border-radius: 8px;      padding: 12px;      width: 31%;      background-color: #f8f9fa;    }    .example-title {      font-weight: 700;      color: #0d4d8c;      margin-bottom: 8px;      font-size: 14px;      text-align: center;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }
</style>
