<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="18" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">第15章 どんなレイアウトとビジュアルが1番注目されるか</h1><div class="content-wrapper"><div class="section"><h2 class="section-title"><i class="fas fa-bullseye"></i>売込みが第一、芸術性は二の次</h2><div class="section-content"><p>「広告の最大の役目は<span class="highlight">商品を売り込むこと</span>」</p><p>◆ アートディレクターは「芸術性」よりも「売込み」を優先すべき</p><p>◆ 美術学校出身者が陥りがちな罠：芸術的に美しくても売れない広告</p><p>◆ 時間の経過とともに<span class="highlight">視点が変化する</span>：作品を「見る」から「読ませる」へ</p><p class="quote">「レイアウトやビジュアルを考える際、売込みが第1目的であり、芸術性は二の次」</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-eye"></i>効果的なビジュアル設計</h2><div class="section-content"><div class="steps"><div class="step"><p class="step-title">ビジュアルの優先順位</p><p>1. <span class="highlight">目立つこと</span>：注目を集める</p><p>2. <span class="highlight">視線誘導</span>：Z型やF型の視線の流れを設計</p><p>3. <span class="highlight">商品写真</span>：大きく、明確に</p><p>4. <span class="highlight">キャプション</span>：最も読まれやすいテキスト</p></div><div class="step"><p class="step-title">読みやすさの要素</p><p>1. <span class="highlight">可読性の高い書体</span>（奇抜さより明瞭さ）</p><p>2. <span class="highlight">適切なコントラスト</span>（背景と文字）</p><p>3. <span class="highlight">余白</span>の効果的な活用</p><p>4. <span class="highlight">強調箇所</span>の絞り込み（ハイライト過多を避ける）</p></div></div></div></div><div class="section"><h2 class="section-title"><i class="fas fa-chart-line"></i>テストで判明した効果的な要素</h2><div class="section-content"><p>◆ 価格・オファー・CTAの<span class="highlight">視認性</span>が売上に直結</p><p>◆ <span class="highlight">実物大</span>の商品写真は小さなものより効果的</p><p>◆ <span class="highlight">人物写真</span>は非人物写真より注目度が約25%高い</p><p>◆ <span class="highlight">不自然なレイアウト</span>は逆に注目を集めることがある（ただし乱用は逆効果）</p></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-wrapper {      display: flex;      flex-direction: column;      flex: 1;    }    .section {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      margin-bottom: 25px;    }    .section-title {      font-size: 22px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 15px;      display: flex;      align-items: center;      border-bottom: 2px solid #e6f0ff;      padding-bottom: 8px;    }    .section-title i {      margin-right: 10px;      color: #0d4d8c;    }    .section-content {      font-size: 16px;      line-height: 1.6;      color: #333;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 500;    }    .quote {      border-left: 4px solid #0d4d8c;      padding-left: 15px;      font-style: italic;      margin: 10px 0;    }    .steps {      display: flex;      justify-content: space-between;      margin-top: 10px;    }    .step {      background-color: #f8f9fa;      border-radius: 8px;      padding: 12px;      width: 48%;    }    .step-title {      font-weight: 700;      margin-bottom: 8px;      color: #0d4d8c;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }
</style>
