<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="19" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">第16章 小スペース広告で利益を上げる方法</h1><div class="content-wrapper"><div class="section"><h2 class="section-title"><i class="fas fa-bullseye"></i>          商品ごとに異なる最適スペース        </h2><div class="section-content"><p>◆ <span class="highlight">商品タイプによって最適広告サイズが異なる</span></p><p class="quote">「ある減量ベルトが利益を出して売れたのは、60行1コラム（約2段×1/6）の小スペース広告」</p><p class="quote">「ある育毛剤が通販で売れたのは、雑誌の全面広告のおかげ」</p><p>◆ 小スペース広告が有効な商品：単純構造、理解しやすい、低価格帯</p><p>◆ 大スペース広告が必要な商品：複雑、高価格、説明量が多い</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-compress-alt"></i>          小スペース広告の成功要因        </h2><div class="section-content"><div class="steps"><div class="step"><p class="step-title"><i class="fas fa-heading"></i> 見出し</p><p>・ターゲットを直撃する</p><p>・具体的なベネフィット</p><p>・簡潔で力強い言葉</p></div><div class="step"><p class="step-title"><i class="fas fa-image"></i> ビジュアル</p><p>・商品を明確に示す</p><p>・単純で理解しやすい</p><p>・効果を視覚的に表現</p></div><div class="step"><p class="step-title"><i class="fas fa-tasks"></i> オファー</p><p>・明確な価格提示</p><p>・行動喚起（CTA）</p><p>・連絡先の視認性</p></div></div><p style="margin-top: 15px;">◆ <span class="highlight">テスト重視</span>：媒体、サイズ、位置を常にテストし最適化</p><p>◆ <span class="highlight">ROI測定</span>：小スペース広告は投資対効果の測定が容易</p></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-wrapper {      display: flex;      flex-direction: column;      flex: 1;    }    .section {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      margin-bottom: 25px;    }    .section-title {      font-size: 22px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 15px;      display: flex;      align-items: center;      border-bottom: 2px solid #e6f0ff;      padding-bottom: 8px;    }    .section-title i {      margin-right: 10px;      color: #0d4d8c;    }    .section-content {      font-size: 16px;      line-height: 1.6;      color: #333;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 500;    }    .quote {      border-left: 4px solid #0d4d8c;      padding-left: 15px;      font-style: italic;      margin: 10px 0;    }    .steps {      display: flex;      justify-content: space-between;      margin-top: 10px;    }    .step {      background-color: #f8f9fa;      border-radius: 8px;      padding: 12px;      width: 30%;    }    .step-title {      font-weight: 700;      margin-bottom: 8px;      color: #0d4d8c;      display: flex;      align-items: center;    }    .step-title i {      margin-right: 8px;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .process {      display: flex;      align-items: center;      justify-content: center;      margin: 20px 0;    }    .process-step {      background-color: #0d4d8c;      color: white;      font-weight: 700;      padding: 10px 15px;      border-radius: 8px;      text-align: center;    }    .process-arrow {      color: #0d4d8c;      font-size: 24px;      margin: 0 15px;    }
</style>
