<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="2" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">本書の全体像と対象読者</h1><div class="content-grid"><div class="section"><h2 class="section-title"><i class="fas fa-book"></i>        本書の背景      </h2><div class="section-content"><p><span class="highlight">Tested Advertising Methods</span>の第5版</p><p>70年以上にわたり広告効果を科学的に検証し続けた広告の名著</p><p>著者ジョン・ケープルズは「広告のテスト・科学化」という手法を確立</p><p>レスポンス広告（反応を測定できる広告）の原理を体系化</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-chart-line"></i>        なぜ重要か      </h2><div class="section-content"><p>広告効果の<span class="highlight">50〜75%は見出し</span>に依存している</p><p>感想や個人的意見ではなく、<span class="highlight">テスト結果</span>に基づく手法</p><p>同じ商品でも、異なる訴求方法で<span class="highlight">売上が19.5倍</span>変わる事例も</p><p>ネット時代の今こそ、測定可能なマーケティングが必須</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-users"></i>        対象読者      </h2><div class="section-content"><p>◆ マーケター・広告担当者</p><p>◆ コピーライター</p><p>◆ Webサイト・ランディングページ設計者</p><p>◆ 事業責任者・起業家</p><p>◆ デザイナー・クリエイティブディレクター</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-lightbulb"></i>        読後に得られる変化      </h2><div class="section-content"><p>◆ 見出しとコピーを「基準」で評価できるようになる</p><p>◆ 効果的なオファー設計のノウハウを身につける</p><p>◆ テスト文化を内製化し、継続的な成果改善を実現</p><p>◆ 「広告は教育である」という倫理観の確立</p></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-grid {      display: grid;      grid-template-columns: 1fr 1fr;      grid-gap: 30px;      flex: 1;    }    .section {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      display: flex;      flex-direction: column;    }    .section-title {      font-size: 20px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 15px;      display: flex;      align-items: center;    }    .section-title i {      margin-right: 10px;      color: #0d4d8c;    }    .section-content {      font-size: 16px;      line-height: 1.6;      color: #333;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 500;    }
</style>
