<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="21" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">第18章 質問に答えます</h1><div class="content-wrapper"><div class="section"><h2 class="section-title"><i class="fas fa-question-circle"></i>よくある質問への回答</h2><div class="section-content"><p>コピーライティング初心者からベテランまで、多くの人が抱える疑問に対して、ケープルズの経験に基づく答えを提供しています。</p><p>◆ <span class="highlight">実践的なアドバイス</span>：理論ではなく「売れる」ための具体的なテクニック</p><p>◆ <span class="highlight">テスト結果に基づく</span>：個人的な意見ではなく、何十年もの実証データから導き出された知見</p><p>◆ 業界共通の誤解を解く：広告業界でよくある「神話」の真偽を検証</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-comments"></i>代表的な質問と回答</h2><div class="section-content"><div class="qa-grid"><div class="qa-item"><p class="question"><i class="fas fa-question"></i>長いコピーと短いコピー、どちらが効果的ですか？</p><p class="answer">「安価な商品は短く、高額商品は長く」という常識とは逆に、<span class="highlight">テスト結果</span>では価格に関わらず詳細な情報を提供する長めのコピーが多くの場合効果的です。</p></div><div class="qa-item"><p class="question"><i class="fas fa-question"></i>イメージ広告とレスポンス広告、どちらに投資すべき？</p><p class="answer">両方を組み合わせるのが理想的ですが、予算が限られている場合は<span class="highlight">測定可能な結果</span>を出せるレスポンス広告から始めるべきです。</p></div><div class="qa-item"><p class="question"><i class="fas fa-question"></i>ウェブ広告は印刷広告と何が違いますか？</p><p class="answer">メディアは変わっても<span class="highlight">人間心理の基本</span>は変わりません。本書の原則はオンライン広告でも有効ですが、データ測定とA/Bテストがさらに容易になっています。</p></div><div class="qa-item"><p class="question"><i class="fas fa-question"></i>広告コピーはどこから始めるべきですか？</p><p class="answer">商品理解から始め、顧客の視点で「<span class="highlight">何が得になるか</span>」を明確にしてから、複数の見出し案を作成し、テストしながら改善していくアプローチが効果的です。</p></div></div><p style="margin-top: 15px;">最終的な答え：「<span class="highlight">テストあるのみ</span>」。憶測や個人的好みではなく、市場の反応で判断すること。</p></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-wrapper {      display: flex;      flex-direction: column;      flex: 1;    }    .section {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      margin-bottom: 25px;    }    .section-title {      font-size: 22px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 15px;      display: flex;      align-items: center;      border-bottom: 2px solid #e6f0ff;      padding-bottom: 8px;    }    .section-title i {      margin-right: 10px;      color: #0d4d8c;    }    .section-content {      font-size: 16px;      line-height: 1.6;      color: #333;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 500;    }    .quote {      border-left: 4px solid #0d4d8c;      padding-left: 15px;      font-style: italic;      margin: 10px 0;    }    .qa-grid {      display: grid;      grid-template-columns: repeat(2, 1fr);      gap: 15px;      margin-top: 10px;    }    .qa-item {      background-color: #f8f9fa;      border-radius: 8px;      padding: 12px;    }    .question {      font-weight: 700;      margin-bottom: 8px;      color: #0d4d8c;      display: flex;      align-items: flex-start;    }    .question i {      margin-right: 8px;      margin-top: 3px;      color: #0d4d8c;    }    .answer {      margin-left: 22px;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }
</style>
