<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="22" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">キーセンテンス集</h1><div class="quotes-container"><div class="quote-card"><div class="quote-icon"><i class="fas fa-quote-left"></i></div><p class="quote-text">広告は<span class="quote-highlight">見出しが命</span>。広告効果の<span class="quote-highlight">50〜75%</span>は見出しにある。見出しが目立たなければ、それ以降の素晴らしいコピーも無意味になる。</p><p class="quote-source">第2章：広告は見出しが命</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-quote-left"></i></div><p class="quote-text"><span class="quote-highlight">何を言うか</span>が重要で、どう言うかではない。意味のある内容を単刀直入に伝えるほうが、大して意味のない内容の美辞麗句を連ねるより効果的。</p><p class="quote-source">第3章：どんな見出しが1番注目されるか</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-quote-left"></i></div><p class="quote-text">成功する広告の4つの鍵：<span class="quote-highlight">得になる・新情報・好奇心・簡単</span>。中でも「得になる」は必須要素。</p><p class="quote-source">第4章：効く見出しはこう書く</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-quote-left"></i></div><p class="quote-text"><span class="quote-highlight">テストせよ</span>。憶測をやめ、<span class="quote-highlight">事実で判断</span>せよ。個人的意見に頼っていては、広告予算の大半が無駄になる。</p><p class="quote-source">第7章：「テスト済み広告」と「テストしない広告」</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-quote-left"></i></div><p class="quote-text">強い言葉には影響力があり、<span class="quote-highlight">広告は教育である</span>。言葉の力を知った者は、創造者としての責任も同時に負う。</p><p class="quote-source">神田昌典：監訳者はじめに</p></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .quotes-container {      display: flex;      flex-wrap: wrap;      gap: 25px;      flex: 1;      justify-content: center;    }    .quote-card {      background-color: white;      border-radius: 12px;      padding: 24px;      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.08);      width: calc(50% - 15px);      position: relative;      display: flex;      flex-direction: column;    }    .quote-icon {      position: absolute;      top: -10px;      left: 20px;      font-size: 28px;      color: #0d4d8c;      background-color: #f8f9fa;      width: 40px;      height: 40px;      display: flex;      align-items: center;      justify-content: center;      border-radius: 50%;    }    .quote-text {      font-size: 18px;      line-height: 1.5;      color: #333;      margin-top: 10px;      font-weight: 500;    }    .quote-highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 700;      color: #0d4d8c;    }    .quote-source {      font-size: 14px;      color: #666;      margin-top: 12px;      font-style: italic;      text-align: right;      margin-top: auto;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }
</style>
