<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="23" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">重要用語集</h1><div class="glossary-container"><div class="glossary-item"><div class="glossary-icon"><i class="fas fa-sync-alt"></i></div><div class="glossary-content"><p class="glossary-term">A/Bスプリット</p><p class="glossary-definition">異なるクリエイティブや要素を同時に出稿して比較テストする手法。どの広告パターンが最も効果的かを科学的に判定できる。</p></div></div><div class="glossary-item"><div class="glossary-icon"><i class="fas fa-key"></i></div><div class="glossary-content"><p class="glossary-term">キーコード（カギ付きコピー）</p><p class="glossary-definition">広告別の反応を計測するための識別コード。どの媒体・広告からの反応かを追跡可能にする。</p></div></div><div class="glossary-item"><div class="glossary-icon"><i class="fas fa-gift"></i></div><div class="glossary-content"><p class="glossary-term">ベネフィット</p><p class="glossary-definition">読者が製品・サービスを使用することで得られる価値や利益。機能（Features）ではなく、それによって得られる結果を重視する。</p></div></div><div class="glossary-item"><div class="glossary-icon"><i class="fas fa-paragraph"></i></div><div class="glossary-content"><p class="glossary-term">リード</p><p class="glossary-definition">コピーの冒頭部分。続きを読ませるための導入文で、見出しに次いで重要な要素。</p></div></div><div class="glossary-item"><div class="glossary-icon"><i class="fas fa-align-left"></i></div><div class="glossary-content"><p class="glossary-term">ボディコピー</p><p class="glossary-definition">広告の本文部分。製品・サービスの詳細や特徴、ベネフィットを説明するテキスト。</p></div></div><div class="glossary-item"><div class="glossary-icon"><i class="fas fa-image"></i></div><div class="glossary-content"><p class="glossary-term">キャプション</p><p class="glossary-definition">画像や図版に添える説明文。見出しに次いで最も読まれる要素の一つで、売り込みポイントを含めるべき。</p></div></div><div class="glossary-item"><div class="glossary-icon"><i class="fas fa-tags"></i></div><div class="glossary-content"><p class="glossary-term">オファー</p><p class="glossary-definition">広告の提案内容や特典、条件の総称。期間限定割引、無料サンプル、保証などを含む。</p></div></div><div class="glossary-item"><div class="glossary-icon"><i class="fas fa-chart-line"></i></div><div class="glossary-content"><p class="glossary-term">レスポンス広告</p><p class="glossary-definition">問合せや申込などの直接的な反応を獲得することを目的とした広告。効果測定が可能。</p></div></div><div class="glossary-item"><div class="glossary-icon"><i class="fas fa-mouse-pointer"></i></div><div class="glossary-content"><p class="glossary-term">CTA（行動喚起）</p><p class="glossary-definition">「今すぐお申し込み」など、読者に具体的な行動を促す部分。明確で強力なCTAが成約率を高める。</p></div></div><div class="glossary-item"><div class="glossary-icon"><i class="fas fa-envelope"></i></div><div class="glossary-content"><p class="glossary-term">ダイレクトメール（DM）</p><p class="glossary-definition">特定の名簿に宛てて送る広告物。個人の名前や属性に合わせたパーソナライズが可能。</p></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 25px;      text-align: center;    }    .glossary-container {      display: flex;      flex-wrap: wrap;      gap: 20px;      flex: 1;    }    .glossary-item {      background-color: white;      border-radius: 10px;      padding: 16px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      width: calc(50% - 10px);      display: flex;      align-items: flex-start;    }    .glossary-icon {      color: #0d4d8c;      font-size: 20px;      margin-right: 12px;      margin-top: 2px;    }    .glossary-content {      flex: 1;    }    .glossary-term {      font-size: 18px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 6px;    }    .glossary-definition {      font-size: 15px;      line-height: 1.4;      color: #333;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }
</style>
