<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="24" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">まとめと次アクション</h1><div class="content-wrapper"><h2 class="action-title">実践のための6つのステップ</h2><div class="action-steps"><div class="action-step"><div class="step-number">1</div><p class="step-title">見出し案を最低10本作成</p><p class="step-content">「<span class="highlight">得になる</span>」「<span class="highlight">新情報</span>」「<span class="highlight">好奇心</span>」「<span class="highlight">簡単</span>」の要素を盛り込み、具体的な数字で信頼性を高める</p></div><div class="action-step"><div class="step-number">2</div><p class="step-title">強いオファーを設計</p><p class="step-content"><span class="highlight">保証</span>・<span class="highlight">期限</span>・<span class="highlight">特典</span>の3要素を組み合わせ、行動を促すCTAを明確に</p></div><div class="action-step"><div class="step-number">3</div><p class="step-title">A/Bテスト計画を立案</p><p class="step-content">最初は<span class="highlight">媒体内</span>でテスト→<span class="highlight">媒体間</span>で比較→<span class="highlight">結果を研究</span>する継続的な改善サイクル</p></div><div class="action-step"><div class="step-number">4</div><p class="step-title">レイアウトは「売込み第一」</p><p class="step-content">芸術性より<span class="highlight">可読性</span>を重視。見出し・画像・CTAの視線誘導を設計</p></div><div class="action-step"><div class="step-number">5</div><p class="step-title">倫理的チェック</p><p class="step-content">「<span class="highlight">広告は教育</span>」という視点で、誰をどう変えるメッセージなのかを問う</p></div><div class="action-step"><div class="step-number">6</div><p class="step-title">学習ループで資産化</p><p class="step-content">成功パターンを<span class="highlight">体系化</span>し、自社独自の「テスト済み広告法」を構築</p></div></div><div class="closing-message"><p class="closing-text">「単なる意見には1銭も払わず、<span class="highlight">事実だけに金を払う</span>」</p><p class="closing-text">あなたのコピーが、<span class="highlight">測定可能な成果</span>を生み出す言葉になりますように</p></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-wrapper {      display: flex;      flex-direction: column;      flex: 1;    }    .action-title {      font-size: 22px;      font-weight: 700;      color: #0d4d8c;      text-align: center;      margin-bottom: 20px;      border-bottom: 2px solid #e6f0ff;      padding-bottom: 8px;    }    .action-steps {      display: flex;      flex-wrap: wrap;      gap: 20px;      justify-content: center;      margin-bottom: 25px;    }    .action-step {      background-color: white;      border-radius: 10px;      padding: 16px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      width: calc(33% - 15px);      display: flex;      flex-direction: column;    }    .step-number {      background-color: #0d4d8c;      color: white;      width: 30px;      height: 30px;      border-radius: 50%;      display: flex;      align-items: center;      justify-content: center;      font-weight: 700;      margin-bottom: 10px;    }    .step-title {      font-size: 16px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 8px;    }    .step-content {      font-size: 14px;      line-height: 1.4;      color: #333;    }    .closing-message {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      text-align: center;      margin-top: auto;    }    .closing-text {      font-size: 18px;      font-weight: 500;      color: #333;      line-height: 1.5;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 700;      color: #0d4d8c;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }
</style>
