<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="3" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">まえがきの要点（監訳者・改編者）</h1><div class="content-wrapper"><div class="section"><h2 class="section-title"><i class="fas fa-quote-left"></i>          神田昌典：ネット時代の広告の真実        </h2><div class="section-content"><p class="quote">「言葉が富を生む。単に言葉の選択で収益が何倍もの違いを生む」</p><p>◆ <span class="highlight">レスポンス広告</span>がネット時代にさらに重要に</p><p>◆ 強力な言葉は「<span class="highlight">劇薬</span>」にもなり得る：短期的成果と長期的信頼のバランス</p><p>◆ 企業規模拡大時に広告メッセージと実態の乖離が顧客信頼を毀損する危険性</p><p>◆ 「<span class="highlight">広告は教育である</span>」：影響力の大きさに伴う社会的責任</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-cogs"></i>          ケープルズの3ステップ方式        </h2><div class="section-content"><div class="steps"><div class="step"><p class="step-title">【広告作り】</p><p>1. 見込み客の<span class="highlight">注意を引く</span></p><p>2. 見込み客の<span class="highlight">関心を保つ</span>（ベネフィット訴求）</p><p>3. 見込み客に<span class="highlight">行動を起こさせる</span></p></div><div class="step"><p class="step-title">【広告テスト】</p><p>1. 広告効果を<span class="highlight">科学的</span>にテスト</p><p>2. テスト結果に基づき<span class="highlight">改良</span></p><p>3. 改良版を<span class="highlight">大規模展開</span></p></div></div><p style="margin-top: 15px;">この方式が70年以上の時を経ても通用する理由：<span class="highlight">人間心理の本質</span>は変わらないから</p></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-wrapper {      display: flex;      flex-direction: column;      flex: 1;    }    .section {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      margin-bottom: 25px;    }    .section-title {      font-size: 22px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 15px;      display: flex;      align-items: center;      border-bottom: 2px solid #e6f0ff;      padding-bottom: 8px;    }    .section-title i {      margin-right: 10px;      color: #0d4d8c;    }    .section-content {      font-size: 16px;      line-height: 1.6;      color: #333;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 500;    }    .quote {      border-left: 4px solid #0d4d8c;      padding-left: 15px;      font-style: italic;      margin: 10px 0;    }    .steps {      display: flex;      justify-content: space-between;      margin-top: 10px;    }    .step {      background-color: #f8f9fa;      border-radius: 8px;      padding: 12px;      width: 48%;    }    .step-title {      font-weight: 700;      margin-bottom: 8px;      color: #0d4d8c;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }
</style>
