<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="4" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">第1章 これが新しい広告戦略だ</h1><div class="content-wrapper"><div class="section"><h2 class="section-title"><i class="fas fa-balance-scale"></i>          テスト実践グループ vs 非テストグループ        </h2><div class="section-content"><p class="quote">「広告を打つ理由はただ1つ、つまり、1に売上、2に売上、3に売上だ！」— ジョン・W・ブレイク</p><p>◆ <span class="highlight">テスト実践グループ</span>：広告を常にテストし、各広告が実際にどれだけ成果を挙げているか測定する（通販、案内広告、デパートなど）</p><p>◆ <span class="highlight">テストしないグループ</span>：広告成果テストや測定をまったくしないか、ほとんどしない</p><p>◆ 広告の世界では<span class="highlight">個人的な意見や印象</span>だけで判断されるコピーがあまりに多い</p><p>◆ <span class="highlight">事実</span>に基づく判断：意見には1銭たりとも金を出さず、事実だけに金を出す企業が成功している</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-tasks"></i>          広告宣伝企画の3ステップ        </h2><div class="section-content"><div class="steps"><div class="step"><p class="step-title">【事前テストの流れ】</p><p>1. <span class="highlight">イニシャルテスト</span>：各広告案を同じ媒体内で比較</p><p>2. <span class="highlight">効果拡大テスト</span>：効果のある広告を複数媒体で検証</p><p>3. <span class="highlight">テスト結果の研究</span>：媒体間比較と学習サイクル</p></div><div class="step"><p class="step-title">【実証された効果】</p><p>◆ 訴求ポイントの違いだけで<span class="highlight">売上が19.5倍</span>に</p><p>◆ <span class="highlight">3W</span>（Where/When/What）は憶測でなく事実で決定</p><p>◆ 少ない広告費でも大きな効果：テストと繰り返しの成果</p></div></div><p style="margin-top: 15px;">科学的手法の重要性：「もっと正確で、もっと科学的なものになり、その結果、もっと成果を挙げるものになる」</p></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-wrapper {      display: flex;      flex-direction: column;      flex: 1;    }    .section {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      margin-bottom: 25px;    }    .section-title {      font-size: 22px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 15px;      display: flex;      align-items: center;      border-bottom: 2px solid #e6f0ff;      padding-bottom: 8px;    }    .section-title i {      margin-right: 10px;      color: #0d4d8c;    }    .section-content {      font-size: 16px;      line-height: 1.6;      color: #333;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 500;    }    .quote {      border-left: 4px solid #0d4d8c;      padding-left: 15px;      font-style: italic;      margin: 10px 0;    }    .steps {      display: flex;      justify-content: space-between;      margin-top: 10px;    }    .step {      background-color: #f8f9fa;      border-radius: 8px;      padding: 12px;      width: 48%;    }    .step-title {      font-weight: 700;      margin-bottom: 8px;      color: #0d4d8c;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }
</style>
