<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="5" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">第2章 広告は見出しが命</h1><div class="content-wrapper"><div class="section"><h2 class="section-title"><i class="fas fa-balance-scale"></i>          テスト実践グループ vs テストしないグループ        </h2><div class="section-content"><p class="quote">「広告効果の50〜75%は見出しにある。見出しの売込み力が何よりも重要なのだ」— ドン・ベルディング</p><div class="compare-container"><div class="compare-box test-group"><p class="compare-title">テスト実践グループ</p><p class="compare-content">◆ 広告を常に<span class="highlight">テスト</span>し、成果を測定</p><p class="compare-content">◆ 成果が数値で<span class="highlight">証明</span>された見出し・コピー</p><p class="compare-content">◆ 通販、案内広告、デパートなど</p></div><div class="compare-box no-test-group"><p class="compare-title">テストしないグループ</p><p class="compare-content">◆ <span class="highlight">個人的意見</span>や印象で判断</p><p class="compare-content">◆ 広告成果の<span class="highlight">測定せず</span></p><p class="compare-content">◆ 費用対効果が低い傾向</p></div></div></div></div><div class="section"><h2 class="section-title"><i class="fas fa-microscope"></i>          科学的手法の重要性        </h2><div class="section-content"><p>◆ 見出しは<span class="highlight">広告の命</span>：多くの人は見出ししか読まない</p><p>◆ 見出しで伝える3パターン（効果順）：</p><p>　1. <span class="highlight">「得になる」</span>型：相手の欲しいものを提供</p><p>　2. <span class="highlight">「新情報」</span>型：新製品や新機能を知らせる</p><p>　3. <span class="highlight">「好奇心」</span>型：興味をそそるが単独では弱い</p><p>◆ <span class="highlight">テスト</span>による検証なしに、広告の良し悪しは判断できない</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-chart-line"></i>          実際の成果を重視する姿勢        </h2><div class="section-content"><p>◆ 「いまから30年後の広告は<span class="highlight">もっと正確で科学的</span>になり、その結果、もっと成果を挙げるものになる」</p><p>◆ コピーライターの仕事：感想や個人的意見ではなく、<span class="highlight">事実に基づく</span>判断を</p><p>◆ 効果的な広告は、単なる印象ではなく<span class="highlight">実際の売上</span>で評価される</p><p>◆ すぐれた見出しは、効果的なコピーの土台となる</p></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-wrapper {      display: flex;      flex-direction: column;      flex: 1;    }    .section {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      margin-bottom: 25px;    }    .section-title {      font-size: 22px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 15px;      display: flex;      align-items: center;      border-bottom: 2px solid #e6f0ff;      padding-bottom: 8px;    }    .section-title i {      margin-right: 10px;      color: #0d4d8c;    }    .section-content {      font-size: 16px;      line-height: 1.6;      color: #333;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 500;    }    .quote {      border-left: 4px solid #0d4d8c;      padding-left: 15px;      font-style: italic;      margin: 10px 0;    }    .compare-container {      display: flex;      justify-content: space-between;      margin-top: 15px;    }    .compare-box {      width: 48%;      padding: 15px;      border-radius: 8px;    }    .compare-title {      font-weight: 700;      margin-bottom: 10px;      text-align: center;      font-size: 18px;    }    .compare-content {      font-size: 15px;      line-height: 1.6;    }    .test-group {      background-color: #e6f0ff;    }    .no-test-group {      background-color: #ffe6e6;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }
</style>
