<template>
  <SlidePageWrapper slide-id="4478004536" page-title="" :current-page="6" :total-pages="24">
<div class="slide-container"><div class="bg-accent"></div><h1 class="title">第3章 どんな見出しが1番注目されるか</h1><div class="content-wrapper"><div class="section"><h2 class="section-title"><i class="fas fa-star"></i>成功した見出し10本の分析</h2><div class="section-content"><p>著者のケープルズが分析した長期間効果が持続した見出しには、共通の特徴がありました：</p><p>◆ <span class="highlight">「得になる」</span>要素が全ての見出しに含まれていた</p><p>◆ 半数近くが<span class="highlight">「新情報」</span>を伝えていた</p><p>◆ 多くは<span class="highlight">「好奇心」</span>を活用していた</p><p>◆ 成功例："<span class="highlight">どうやってわざとバカなマネをしてトップセールスマンになったか</span>"</p><p class="quote">「好奇心」だけで効果的な見出しになることはめったにない。「得になる」や「新情報」と組み合わせると強力になる</p></div></div><div class="section"><h2 class="section-title"><i class="fas fa-lightbulb"></i>効果的な見出しの3パターン</h2><div class="section-content"><div class="patterns"><div class="pattern"><p class="pattern-title"><i class="fas fa-gift"></i>得になるタイプ</p><p>読み手の欲しいものを提供する</p><p>最も効果的なパターン</p><div class="example"><p class="example-title">例：</p><p>「さらに50ドルの昇給」</p><p>「55歳で退職」</p></div></div><div class="pattern"><p class="pattern-title"><i class="fas fa-newspaper"></i>新情報タイプ</p><p>新製品や新機能を伝える</p><p>2番目に効果的なパターン</p><div class="example"><p class="example-title">例：</p><p>「フォード・トラックの新機能」</p><p>「出ました→新タイプのハンドクリーナー」</p></div></div><div class="pattern"><p class="pattern-title"><i class="fas fa-question-circle"></i>好奇心タイプ</p><p>疑問を投げかけ興味を引く</p><p>単体では効果に疑問</p><div class="example"><p class="example-title">例：</p><p>「行方不明：3万5,000ドル」</p><p>「この絵のどこが変でしょうか？」</p></div></div></div></div></div><div class="section"><h2 class="section-title"><i class="fas fa-shield-alt"></i>信頼性を高める手法</h2><div class="section-content"><p>見出しが「手っ取り早くて簡単」を訴求しすぎると信頼性を失う危険性があります。</p><p>◆ <span class="highlight">具体的な数字</span>を入れることで信頼性がアップ</p><p>◆ 成功例："<span class="highlight">2年後に3万5,840ドル</span>"、"<span class="highlight">5日ください</span>"、"<span class="highlight">ひと晩で</span>"</p><p>◆ <span class="highlight">科学的な検証結果</span>に基づく評価が重要（広告賞ではなく実際の売上）</p></div></div></div><div class="bottom-accent"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      padding: 40px 60px;    }    .bg-accent {      position: absolute;      top: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }    .title {      font-size: 36px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 30px;      text-align: center;    }    .content-wrapper {      display: flex;      flex-direction: column;      flex: 1;    }    .section {      background-color: white;      border-radius: 10px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);      margin-bottom: 25px;    }    .section-title {      font-size: 22px;      font-weight: 700;      color: #0d4d8c;      margin-bottom: 15px;      display: flex;      align-items: center;      border-bottom: 2px solid #e6f0ff;      padding-bottom: 8px;    }    .section-title i {      margin-right: 10px;      color: #0d4d8c;    }    .section-content {      font-size: 16px;      line-height: 1.6;      color: #333;    }    .highlight {      background-color: #e6f0ff;      padding: 2px 5px;      border-radius: 3px;      font-weight: 500;    }    .quote {      border-left: 4px solid #0d4d8c;      padding-left: 15px;      font-style: italic;      margin: 10px 0;    }    .patterns {      display: flex;      justify-content: space-between;      margin-top: 15px;    }    .pattern {      background-color: #f8f9fa;      border-radius: 8px;      padding: 12px;      width: 32%;    }    .pattern-title {      font-weight: 700;      margin-bottom: 8px;      color: #0d4d8c;      display: flex;      align-items: center;    }    .pattern-title i {      margin-right: 8px;    }    .example {      background-color: #e6f0ff;      border-radius: 5px;      padding: 8px;      margin-top: 10px;    }    .example-title {      font-weight: 500;      margin-bottom: 5px;    }    .bottom-accent {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 12px;      background-color: #0d4d8c;    }
</style>
