<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="脳が一生忘れないインプット術" :current-page="1" :total-pages="21">
<div class='slide-container flex flex-col justify-center items-center px-24 py-16 relative'><!-- 左上の装飾 --><div class='absolute top-0 left-0 w-16 h-16' style='border-top: 8px solid #b83a4b; border-left: 8px solid #b83a4b;'></div><!-- 右下の装飾 --><div class='absolute bottom-0 right-0 w-16 h-16' style='border-bottom: 8px solid #b83a4b; border-right: 8px solid #b83a4b;'></div><!-- メインコンテンツ --><div class='flex flex-col items-center text-center mt-12'><!-- アクセントバー（上） --><div class='accent-bar mb-8'></div><!-- タイトル --><h1 class='title mb-6'>脳が一生忘れないインプット術</h1><!-- サブタイトル --><p class='subtitle mb-12'>科学的根拠に基づく「読む・見る・聞く・覚える」最適化ガイド</p><!-- アクセントバー（下） --><div class='accent-bar mb-16'></div><!-- 著者情報 --><p class='author'>星 友啓</p><p class='text-xl mb-1'>スタンフォード大学・オンラインハイスクール校長</p></div><!-- スタンフォード風ロゴブロック --><div class='stanford-block'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            overflow: hidden;            background-color: #0f2a52;            color: white;            position: relative;        }        .title {            font-size: 68px;            font-weight: 700;            line-height: 1.2;            letter-spacing: 2px;        }        .subtitle {            font-size: 28px;            font-weight: 500;            letter-spacing: 1px;        }        .author {            font-size: 24px;            font-weight: 400;        }        .accent-bar {            width: 140px;            height: 6px;            background-color: #b83a4b;        }        .stanford-block {            position: absolute;            bottom: 40px;            right: 40px;            height: 80px;            width: 200px;            background-color: #b83a4b;        }
</style>
