<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="第3章② 動画学習の最適化" :current-page="10" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>第3章② 動画学習の最適化</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左カラム：実践ガイド --><div class='w-1/2 pr-8'><h2 class='column-title mb-2'>実践ガイド:</h2><div class='accent-line'></div><div class='mt-6'><p class='step-item flex items-center text-xl mb-6'><span class='step-icon'>1</span><span><strong>倍速:</strong> 1.2～1.5倍を目安（理解低下しない範囲で）</span></p><p class='step-item flex items-center text-xl mb-6'><span class='step-icon'>2</span><span><strong>字幕:</strong> 情報過多に注意。必要時は専門用語・数式中心に活用</span></p><p class='step-item flex items-center text-xl mb-6'><span class='step-icon'>3</span><span><strong>チャンク化:</strong> 5～10分で区切り→各ブロック後に要点メモ</span></p><p class='step-item flex items-center text-xl mb-6'><span class='step-icon'>4</span><span><strong>ノイズ遮断:</strong> 広告・おすすめ遮断、要点以外の映像は見ない</span></p><p class='step-item flex items-center text-xl mb-6'><span class='step-icon'>5</span><span><strong>視聴前後:</strong> 概要→視聴→2分ブレインダンプ</span></p></div></div><!-- 区切り線 --><div class='column-divider mx-4'></div><!-- 右カラム：科学的根拠 --><div class='w-1/2 pl-8'><h2 class='column-title mb-2'>科学的根拠:</h2><div class='accent-line'></div><div class='mt-6'><div class='mb-6'><h3 class='text-xl font-bold text-blue-800 mb-2 flex items-center'><i class='fas fa-video video-icon'></i>倍速の限界点</h3><p class='text-lg ml-4'>研究によると1.5倍速以上で急激に理解度と記憶定着率が低下。1.2～1.5倍が最適なバランスポイント。</p></div><div class='mb-6'><h3 class='text-xl font-bold text-blue-800 mb-2 flex items-center'><i class='fas fa-closed-captioning video-icon'></i>字幕の二重処理負荷</h3><p class='text-lg ml-4'>視覚的処理と言語処理の並行作業でワーキングメモリに負荷。必要な場合のみ選択的に活用するのが効果的。</p></div><div class='mb-6'><h3 class='text-xl font-bold text-blue-800 mb-2 flex items-center'><i class='fas fa-puzzle-piece video-icon'></i>注意持続の時間枠</h3><p class='text-lg ml-4'>集中力は約10分で低下し始めるため、短いセグメントに区切り、能動的リトリーバルを挟むことで記憶強化。</p></div></div></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .column-title {        font-size: 28px;        font-weight: 600;        color: #b83a4b;    }    .step-item {        position: relative;        padding-left: 36px;        margin-bottom: 18px;    }    .step-item:before {        content: '';        position: absolute;        left: 0;        top: 8px;        width: 24px;        height: 24px;        background-color: #0f2a52;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        color: white;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 20px;    }    .column-divider {        width: 2px;        background-color: #e2e8f0;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .step-icon {        width: 24px;        height: 24px;        background-color: #0f2a52;        color: white;        border-radius: 50%;        display: inline-flex;        align-items: center;        justify-content: center;        margin-right: 12px;    }    .video-icon {        color: #b83a4b;        margin-right: 8px;    }
</style>
