<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="第3章③ AI・要約ツール活用" :current-page="11" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>第3章③ AI・要約ツール活用</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左カラム：ユースケース --><div class='w-1/2 pr-8'><h2 class='column-title mb-2'>ユースケース:</h2><div class='accent-line'></div><div class='mt-6'><p class='flex items-start text-xl mb-5'><span class='ai-icon'><i class='fas fa-robot'></i></span><span><strong>要約・骨子抽出</strong><br/>長文コンテンツから重要ポイントを抽出し、俯瞰的理解を促進</span></p><p class='flex items-start text-xl mb-5'><span class='ai-icon'><i class='fas fa-book'></i></span><span><strong>用語集生成</strong><br/>専門用語の定義をまとめ、理解の基盤を構築</span></p><p class='flex items-start text-xl mb-5'><span class='ai-icon'><i class='fas fa-question-circle'></i></span><span><strong>クイズ化（自測定）</strong><br/>理解度を確認するための問題生成とリトリーバル強化</span></p><p class='flex items-start text-xl mb-5'><span class='ai-icon'><i class='fas fa-balance-scale'></i></span><span><strong>賛否両論の収集</strong><br/>バイアス確認のための複数視点の整理と比較</span></p></div></div><!-- 区切り線 --><div class='column-divider mx-4'></div><!-- 右カラム：プロンプト例と注意点 --><div class='w-1/2 pl-8'><h2 class='column-title mb-2'>プロンプト例:</h2><div class='accent-line'></div><div class='mt-5'><div class='prompt-box mb-4'><p class='text-lg'><i class='fas fa-angle-right text-blue-800 mr-2'></i>「この論文/記事の要点を5項目で簡潔にまとめてください」</p></div><div class='prompt-box mb-4'><p class='text-lg'><i class='fas fa-angle-right text-blue-800 mr-2'></i>「〜のトピックについて賛否の主要論点を出典付きで教えてください」</p></div><div class='prompt-box mb-6'><p class='text-lg'><i class='fas fa-angle-right text-blue-800 mr-2'></i>「この内容に関する復習用クイズを3問作成してください」</p></div><h2 class='column-title mb-2 mt-8'>注意:</h2><div class='accent-line'></div><div class='mt-4'><p class='text-lg mb-3'><i class='fas fa-exclamation-triangle text-yellow-600 mr-2'></i><strong>ハルシネーション対策:</strong></p><p class='text-lg ml-6 mb-2'>• 出典確認：AI回答の情報源を常に確認する</p><p class='text-lg ml-6 mb-2'>• 一次情報で検証：重要事項は原典にあたる</p><p class='text-lg ml-6'>• 具体例や数値は特に注意して検証する</p></div></div></div><!-- フッター --><div class='footer'></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .column-title {        font-size: 28px;        font-weight: 600;        color: #b83a4b;    }    .step-item {        position: relative;        padding-left: 36px;        margin-bottom: 18px;    }    .step-item:before {        content: '';        position: absolute;        left: 0;        top: 8px;        width: 24px;        height: 24px;        background-color: #0f2a52;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        color: white;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 20px;    }    .column-divider {        width: 2px;        background-color: #e2e8f0;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .ai-icon {        width: 30px;        height: 30px;        background-color: #0f2a52;        color: white;        border-radius: 50%;        display: inline-flex;        align-items: center;        justify-content: center;        margin-right: 12px;    }    .prompt-box {        background-color: #f0f4f8;        border-left: 4px solid #b83a4b;        padding: 12px;        margin-bottom: 12px;        border-radius: 0 4px 4px 0;    }
</style>
