<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="第4章① リトリーバル学習の威力" :current-page="12" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>第4章① リトリーバル学習の威力</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左側：主要コンテンツ --><div class='w-3/4 pr-10'><div class='content-block'><h2 class='section-title'>要点:</h2><div class='accent-line'></div><p class='bullet-point text-xl'>思い出す行為（リトリーバル）が記憶痕跡を強化</p><p class='bullet-point text-xl'>読み返し単独より'想起→フィードバック'が効果的</p><p class='bullet-point text-xl'>記憶定着率を最大50%向上させる実証データあり</p><p class='bullet-point text-xl'>反復練習より「思い出す困難さ」が記憶を強化</p></div><div class='content-block mt-8'><h2 class='section-title'>実践:</h2><div class='accent-line'></div><p class='bullet-point text-xl'>本を閉じて要旨再生→不足のみ確認→再度想起</p><p class='bullet-point text-xl'>自作テスト/口頭説明/空書きで再生練習</p><p class='bullet-point text-xl'>学習後すぐ＋数日後に再度想起練習を設計</p></div></div><!-- 右側：視覚的要素 --><div class='w-1/4 flex flex-col items-center justify-center'><div class='recall-icon mb-6'><span>記憶</span><div class='recall-arrow'></div></div><p class='text-center text-lg font-semibold text-red-700'>思い出すほど</p><p class='text-center text-lg font-semibold text-red-700'>記憶が強化される</p></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .section-title {        font-size: 28px;        font-weight: 600;        color: #b83a4b;    }    .bullet-point {        position: relative;        padding-left: 24px;        margin-bottom: 16px;    }    .bullet-point:before {        content: '';        position: absolute;        left: 0;        top: 12px;        width: 10px;        height: 10px;        background-color: #b83a4b;        border-radius: 50%;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 20px;    }    .content-block {        margin-bottom: 30px;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .recall-icon {        width: 180px;        height: 180px;        border: 3px solid #0f2a52;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        color: #0f2a52;        font-size: 40px;        font-weight: bold;        position: relative;    }    .recall-arrow {        position: absolute;        border-top: 3px solid #b83a4b;        border-right: 3px solid #b83a4b;        width: 30px;        height: 30px;        transform: rotate(45deg);        right: 40px;    }    .recall-arrow:before {        content: '';        position: absolute;        width: 3px;        height: 42px;        background-color: #b83a4b;        transform: rotate(-45deg);        top: -6px;        right: 13px;    }
</style>
