<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="第4章② 効果的な記憶定着テクニック" :current-page="13" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>第4章② 効果的な記憶定着テクニック</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左側：主要コンテンツ --><div class='w-3/4 pr-10'><div class='content-block'><h2 class='section-title'>ブレインダンプ:</h2><div class='accent-line'></div><p class='bullet-point text-xl'>学習直後2分で'覚えていることだけ'を書き出す</p><p class='bullet-point text-xl'>思い出せる内容を整理せずに一気に吐き出す</p><p class='bullet-point text-xl'>定期的な実践で記憶の定着率50%アップ</p></div><div class='content-block mt-6'><h2 class='section-title'>ノールック書き写し:</h2><div class='accent-line'></div><p class='bullet-point text-xl'>小分けにして目を離し、記憶で再現→照合→修正</p><p class='bullet-point text-xl'>見ながら書くより記憶への定着率が高い</p><p class='bullet-point text-xl'>5〜7語のチャンク単位で区切ると効果的</p></div><div class='content-block mt-6'><h2 class='section-title'>ハイライトの最適化:</h2><div class='accent-line'></div><p class='bullet-point text-xl'>線引きは'問い化'して活用（なぜ重要か？根拠は？）</p><p class='bullet-point text-xl'>マーキングだけでは効果薄→質問・関連付けを併用</p></div></div><!-- 右側：視覚的要素 --><div class='w-1/4 flex flex-col items-center justify-center'><div class='memory-icon mb-6'>記憶</div><div class='technique-item'><p class='text-center text-lg font-semibold'>ブレインダンプ</p><p class='text-center text-sm'>学習直後に吐き出す</p></div><div class='technique-item'><p class='text-center text-lg font-semibold'>ノールック</p><p class='text-center text-sm'>記憶から再現する</p></div><div class='technique-item'><p class='text-center text-lg font-semibold'>問い化</p><p class='text-center text-sm'>ハイライトに意味を持たせる</p></div></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .section-title {        font-size: 28px;        font-weight: 600;        color: #b83a4b;    }    .bullet-point {        position: relative;        padding-left: 24px;        margin-bottom: 16px;    }    .bullet-point:before {        content: '';        position: absolute;        left: 0;        top: 12px;        width: 10px;        height: 10px;        background-color: #b83a4b;        border-radius: 50%;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 20px;    }    .content-block {        margin-bottom: 30px;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .memory-icon {        width: 180px;        height: 180px;        border: 3px solid #0f2a52;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        color: #0f2a52;        font-size: 40px;        font-weight: bold;    }    .technique-item {        border-left: 3px solid #b83a4b;        padding-left: 16px;        margin-bottom: 12px;    }
</style>
