<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="第4章③ スペーシングと短期集中の併用" :current-page="14" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>第4章③ スペーシングと短期集中の併用</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左側：主要コンテンツ --><div class='w-3/4 pr-10'><div class='content-block'><h2 class='section-title'>分散学習（例）:</h2><div class='accent-line'></div><p class='bullet-point text-xl'>当日→1日後→3日後→7日後→14日後に短テスト</p><p class='bullet-point text-xl'>各回2～5分の想起テスト＋弱点のみ補強</p><p class='bullet-point text-xl'>テスト形式のリトリーバルで記憶定着率50%向上</p></div><div class='content-block mt-8'><h2 class='section-title'>短期集中の位置づけ:</h2><div class='accent-line'></div><p class='bullet-point text-xl'>直前強化（一夜漬け）は'最後の仕上げ'として限定的に</p><p class='bullet-point text-xl'>試験1～2週間前から分散＋直前集中のハイブリッド</p><p class='bullet-point text-xl'>短期記憶と長期記憶の両方を最適化する設計</p></div></div><!-- 右側：視覚的要素 --><div class='w-1/4 flex flex-col items-center justify-center'><div class='memory-chart mb-6'><div class='chart-line'><div class='chart-dot' style='top: 80px; left: 20px;'></div><div class='chart-dot' style='top: 60px; left: 50px;'></div><div class='chart-dot' style='top: 45px; left: 80px;'></div><div class='chart-dot' style='top: 35px; left: 110px;'></div><div class='chart-dot' style='top: 30px; left: 140px;'></div></div><p class='text-center text-lg font-semibold'>分散学習</p><p class='text-center text-lg font-semibold'>記憶曲線</p></div><p class='text-center text-lg font-semibold text-red-700'>理想は分散＋直前集中</p><p class='text-center text-lg font-semibold text-red-700'>のハイブリッド</p></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .section-title {        font-size: 28px;        font-weight: 600;        color: #b83a4b;    }    .bullet-point {        position: relative;        padding-left: 24px;        margin-bottom: 16px;    }    .bullet-point:before {        content: '';        position: absolute;        left: 0;        top: 12px;        width: 10px;        height: 10px;        background-color: #b83a4b;        border-radius: 50%;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 20px;    }    .content-block {        margin-bottom: 30px;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .memory-chart {        width: 200px;        height: 200px;        border: 3px solid #0f2a52;        border-radius: 50%;        display: flex;        flex-direction: column;        align-items: center;        justify-content: center;        color: #0f2a52;    }    .chart-line {        width: 180px;        height: 90px;        border-bottom: 3px solid #b83a4b;        border-left: 3px solid #b83a4b;        border-right: 3px solid #b83a4b;        border-radius: 0 0 90px 90px;        position: relative;        margin-bottom: 10px;    }    .chart-dot {        position: absolute;        width: 12px;        height: 12px;        background-color: #0f2a52;        border-radius: 50%;    }
</style>
