<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="第5章① モチベーションの2種類と仕組み化" :current-page="15" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>第5章① モチベーションの2種類と仕組み化</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左側：主要コンテンツ --><div class='w-3/4 pr-10'><div class='content-block'><h2 class='section-title'>内発/外発:</h2><div class='accent-line'></div><p class='bullet-point text-xl'>内発（好奇心・自律性）は長期持続に有利</p><p class='bullet-point text-xl'>過度な外的報酬は内発を損なう可能性</p><p class='bullet-point text-xl'>自己決定理論に基づく3要素：有能感・自律性・関係性</p><p class='bullet-point text-xl'>脳科学：ドーパミンと報酬系が関与</p></div><div class='content-block mt-8'><h2 class='section-title'>仕組み化:</h2><div class='accent-line'></div><p class='bullet-point text-xl'>小さな成功の連鎖・進捗の可視化・環境整備</p><p class='bullet-point text-xl'>習慣トリガー（時間/場所/行為）とごほうび設計</p><p class='bullet-point text-xl'>毎日の行動と長期的な目標を紐づける</p><p class='bullet-point text-xl'>セルフアセスメントで軌道修正を習慣化</p></div></div><!-- 右側：視覚的要素 --><div class='w-1/4 flex flex-col items-center justify-center'><div class='motivation-icon mb-6'>動機</div><p class='text-center text-lg font-semibold text-red-700'>内発的動機</p><p class='text-center text-lg'>+</p><p class='text-center text-lg font-semibold text-red-700'>習慣の仕組み化</p><p class='text-center text-lg'>=</p><p class='text-center text-lg font-semibold text-blue-800'>持続可能な学習</p></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .section-title {        font-size: 28px;        font-weight: 600;        color: #b83a4b;    }    .bullet-point {        position: relative;        padding-left: 24px;        margin-bottom: 16px;    }    .bullet-point:before {        content: '';        position: absolute;        left: 0;        top: 12px;        width: 10px;        height: 10px;        background-color: #b83a4b;        border-radius: 50%;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 20px;    }    .content-block {        margin-bottom: 30px;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .motivation-icon {        width: 180px;        height: 180px;        border: 3px solid #0f2a52;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        color: #0f2a52;        font-size: 40px;        font-weight: bold;    }
</style>
