<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="第5章② SMART目標とCAR目標の両輪" :current-page="16" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>第5章② SMART目標とCAR目標の両輪</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左カラム：SMART目標 --><div class='w-1/2 pr-8'><h2 class='column-title mb-2'>SMART（短期の具体化）:</h2><div class='accent-line'></div><div class='mt-6'><div class='flex items-center mb-3'><span class='goal-letter'>S</span><p class='text-xl'><strong>Specific</strong>（具体的に）</p></div><div class='flex items-center mb-3'><span class='goal-letter'>M</span><p class='text-xl'><strong>Measurable</strong>（測定可能に）</p></div><div class='flex items-center mb-3'><span class='goal-letter'>A</span><p class='text-xl'><strong>Achievable</strong>（達成可能に）</p></div><div class='flex items-center mb-3'><span class='goal-letter'>R</span><p class='text-xl'><strong>Relevant</strong>（関連性を持って）</p></div><div class='flex items-center mb-3'><span class='goal-letter'>T</span><p class='text-xl'><strong>Time-bound</strong>（期限を設けて）</p></div><div class='example-box mt-4'><p class='text-lg font-bold'>例:</p><p class='text-lg ml-2'>「3週間で章末要点60個を自力再生できる」</p><p class='text-lg ml-2'>「毎日30分、5日間で教科書3章を要約する」</p></div></div></div><!-- 区切り線 --><div class='column-divider mx-4'></div><!-- 右カラム：CAR目標 --><div class='w-1/2 pl-8'><h2 class='column-title mb-2'>CAR（長期の内発強化）:</h2><div class='accent-line'></div><div class='mt-6'><div class='flex items-center mb-3'><span class='goal-letter'>C</span><p class='text-xl'><strong>Competency</strong>（有能感）</p></div><div class='mb-4 ml-12'><p class='text-lg'>スキルを高める・専門知識を深める</p></div><div class='flex items-center mb-3'><span class='goal-letter'>A</span><p class='text-xl'><strong>Autonomy</strong>（自律性）</p></div><div class='mb-4 ml-12'><p class='text-lg'>自分で選択・決定する余地がある</p></div><div class='flex items-center mb-3'><span class='goal-letter'>R</span><p class='text-xl'><strong>Relatedness</strong>（関係性）</p></div><div class='mb-4 ml-12'><p class='text-lg'>他者とのつながり・貢献を実感できる</p></div><div class='example-box'><p class='text-lg font-bold'>運用:</p><p class='text-lg ml-2'>• SMARTで行動設計 → CARで意義づけ</p><p class='text-lg ml-2'>• 週次でリセット・調整・振り返り</p><p class='text-lg ml-2'>• 小さなSMART達成を積み重ね、CARの充足へ</p></div></div></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .column-title {        font-size: 28px;        font-weight: 600;        color: #b83a4b;    }    .step-item {        position: relative;        padding-left: 36px;        margin-bottom: 18px;    }    .step-item:before {        content: '';        position: absolute;        left: 0;        top: 8px;        width: 24px;        height: 24px;        background-color: #0f2a52;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        color: white;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 20px;    }    .column-divider {        width: 2px;        background-color: #e2e8f0;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .goal-letter {        width: 36px;        height: 36px;        background-color: #0f2a52;        color: white;        border-radius: 50%;        display: inline-flex;        align-items: center;        justify-content: center;        margin-right: 12px;        font-weight: bold;        font-size: 18px;    }    .example-box {        background-color: #f0f5ff;        border-left: 4px solid #0f2a52;        padding: 12px;        margin-top: 16px;    }
</style>
