<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="第6章① 情報リテラシーの基本" :current-page="17" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>第6章① 情報リテラシーの基本</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左カラム：チェック軸 --><div class='w-1/2 pr-8'><h2 class='column-title mb-2'>チェック軸:</h2><div class='accent-line'></div><div class='mt-6'><p class='step-item flex items-center text-xl mb-6'><span class='check-icon'><i class='fas fa-check'></i></span><span><strong>発信元/著者の信頼性・専門性</strong><br/><span class='text-base ml-4'>資格・経歴・所属機関の評判・過去の実績</span></span></p><p class='step-item flex items-center text-xl mb-6'><span class='check-icon'><i class='fas fa-check'></i></span><span><strong>公開日・更新日（鮮度）</strong><br/><span class='text-base ml-4'>最新の研究・情報を反映しているか</span></span></p><p class='step-item flex items-center text-xl mb-6'><span class='check-icon'><i class='fas fa-check'></i></span><span><strong>根拠・出典</strong><br/><span class='text-base ml-4'>一次情報/査読論文/再現性のある証拠の有無</span></span></p><p class='step-item flex items-center text-xl mb-6'><span class='check-icon'><i class='fas fa-check'></i></span><span><strong>他者評価・賛否</strong><br/><span class='text-base ml-4'>偏り・過激表現の有無、反対意見の検証</span></span></p></div></div><!-- 区切り線 --><div class='column-divider mx-4'></div><!-- 右カラム：姿勢と実践 --><div class='w-1/2 pl-8'><h2 class='column-title mb-2'>姿勢:</h2><div class='accent-line'></div><div class='mt-6'><div class='mb-6'><h3 class='text-xl font-bold text-blue-800 mb-2'>目的に合わせた検証</h3><p class='text-lg ml-4'>情報の重要度・影響度に応じて検証の深さを調整。すべての情報を同じ厳密さで調べる必要はない。</p></div><div class='mb-6'><h3 class='text-xl font-bold text-blue-800 mb-2'>バイアス認識</h3><p class='text-lg ml-4'>自分の確証バイアスを意識し、反対意見も積極的に探索。賛否両論をバランスよく確認する習慣化。</p></div><div class='mb-6'><h3 class='text-xl font-bold text-blue-800 mb-2'>階層的検証</h3><p class='text-lg ml-4'>簡易チェック→重要項目の深掘り→一次情報確認という段階的アプローチで効率化。</p></div><div><h3 class='text-xl font-bold text-blue-800 mb-2'>更新の習慣</h3><p class='text-lg ml-4'>「情報には賞味期限がある」という認識。定期的に最新情報で知識をアップデート。</p></div></div></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .column-title {        font-size: 28px;        font-weight: 600;        color: #b83a4b;    }    .step-item {        position: relative;        padding-left: 36px;        margin-bottom: 18px;    }    .step-item:before {        content: '';        position: absolute;        left: 0;        top: 8px;        width: 24px;        height: 24px;        background-color: #0f2a52;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        color: white;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 20px;    }    .column-divider {        width: 2px;        background-color: #e2e8f0;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .check-icon {        width: 24px;        height: 24px;        background-color: #0f2a52;        color: white;        border-radius: 50%;        display: inline-flex;        align-items: center;        justify-content: center;        margin-right: 12px;    }
</style>
