<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="第6章② 実践チェックリストとAIの賢い使い方" :current-page="18" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>第6章② 実践チェックリストとAIの賢い使い方</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左カラム：実践チェックリスト --><div class='w-1/2 pr-8'><h2 class='column-title mb-2'>実践チェック（抜粋）:</h2><div class='accent-line'></div><div class='mt-6'><div class='check-item'><div class='check-box'></div><p class='text-lg'><strong>目的を定義したか</strong> - インプット前に何を得たいかを明確化</p></div><div class='check-item'><div class='check-box'></div><p class='text-lg'><strong>著者/発信元は誰か</strong> - 専門性・立場・信頼性を確認</p></div><div class='check-item'><div class='check-box'></div><p class='text-lg'><strong>日付は新しいか</strong> - 特に科学・技術分野は鮮度が重要</p></div><div class='check-item'><div class='check-box'></div><p class='text-lg'><strong>根拠は一次情報か</strong> - 引用元をたどれるか検証</p></div><div class='check-item'><div class='check-box'></div><p class='text-lg'><strong>他の専門家はどう評価</strong> - 複数の意見を参照</p></div><div class='check-item'><div class='check-box'></div><p class='text-lg'><strong>反対意見も読んだか</strong> - 賛否両論を把握</p></div><div class='check-item'><div class='check-box'></div><p class='text-lg'><strong>過激表現や断定口調に警戒</strong> - 扇情的表現は注意</p></div></div></div><!-- 区切り線 --><div class='column-divider mx-4'></div><!-- 右カラム：AI活用法 --><div class='w-1/2 pl-8'><h2 class='column-title mb-2'>AI活用:</h2><div class='accent-line'></div><div class='mt-6'><div class='ai-item mb-6'><i class='fas fa-robot ai-icon'></i><p class='text-lg'><strong>要点抽出</strong> - 「この記事の主な主張と根拠を5項目でまとめて」というプロンプトで要約させる</p></div><div class='ai-item mb-6'><i class='fas fa-link ai-icon'></i><p class='text-lg'><strong>出典提示</strong> - 「この情報の信頼できる出典を示して」と依頼し検証</p></div><div class='ai-item mb-6'><i class='fas fa-balance-scale ai-icon'></i><p class='text-lg'><strong>賛否整理</strong> - 「〜について賛否両論の主要な論点を教えて」と問い、多角的視点を得る</p></div><div class='ai-item mb-6'><i class='fas fa-question-circle ai-icon'></i><p class='text-lg'><strong>自作テスト生成</strong> - 学んだ内容を「復習用クイズを3問作成して」と依頼</p></div><div class='ai-item'><i class='fas fa-exclamation-triangle ai-icon'></i><p class='text-lg'><strong>重要：</strong> ハルシネーション（AI生成の幻想）に注意し、必ず一次情報で裏取りすること</p></div></div></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .column-title {        font-size: 28px;        font-weight: 600;        color: #b83a4b;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 20px;    }    .column-divider {        width: 2px;        background-color: #e2e8f0;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .check-item {        display: flex;        align-items: flex-start;        margin-bottom: 12px;    }    .check-box {        min-width: 22px;        height: 22px;        border: 2px solid #0f2a52;        border-radius: 4px;        margin-right: 12px;        margin-top: 4px;    }    .ai-item {        position: relative;        padding-left: 36px;        margin-bottom: 18px;    }    .ai-icon {        position: absolute;        left: 0;        top: 2px;        width: 26px;        height: 26px;        color: #0f2a52;        text-align: center;    }
</style>
