<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="キーセンテンス（要旨）" :current-page="19" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>キーセンテンス（要旨）</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左側：要点リスト --><div class='w-3/4 pr-10'><div class='accent-line'></div><div class='summary-container'><p class='key-point'>速く見るより、<span class='highlight-text'>意味をつかむ力の強化</span>が読書効率を左右する</p><p class='key-point'>記憶定着の決め手は<span class='highlight-text'>「思い出す練習」</span>を設計に組み込むこと</p><p class='key-point'>学びは「<span class='highlight-text'>目的→全体像→部分集中→アウトプット</span>」で回す</p><p class='key-point'>モチベーションは<span class='highlight-text'>SMART（行動）とCAR（意義）</span>の両輪で維持</p><p class='key-point'>情報は<span class='highlight-text'>出どころ・根拠・鮮度・賛否</span>で精査し、AIは補助に使う</p></div></div><!-- 右側：視覚的要素 --><div class='w-1/4 flex flex-col items-center justify-center'><div class='summary-icon mb-6'>核心の<br/>5原則</div><p class='text-center text-lg font-semibold text-red-700'>一生忘れない<br/>インプット術</p></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .key-point {        position: relative;        padding-left: 32px;        margin-bottom: 24px;        font-size: 24px;        line-height: 1.4;    }    .key-point:before {        content: '';        position: absolute;        left: 0;        top: 12px;        width: 16px;        height: 16px;        background-color: #b83a4b;        border-radius: 3px;    }    .highlight-text {        color: #b83a4b;        font-weight: 600;    }    .summary-container {        border-left: 4px solid #b83a4b;        padding-left: 24px;        padding-top: 8px;        padding-bottom: 8px;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .accent-line {        width: 80px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 36px;    }    .summary-icon {        width: 180px;        height: 180px;        border: 3px solid #0f2a52;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        color: #0f2a52;        font-size: 32px;        font-weight: bold;        text-align: center;        line-height: 1.2;    }
</style>
