<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="本書の概要と対象読者" :current-page="2" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>本書の概要と対象読者</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左カラム：本書の目的 --><div class='w-1/2 pr-8'><h2 class='subtitle mb-4'>本書の目的</h2><div class='accent-line mb-6'></div><div class='content-item'><p class='bullet-point text-lg mb-3'>科学的に効果が実証されたインプット術を日常に実装する</p><p class='bullet-point text-lg mb-3'>AI時代の情報洪水を賢く扱い、記憶と行動に結びつける</p><p class='bullet-point text-lg mb-3'>脳科学・認知心理学に基づく学習法の実践的解説</p><p class='bullet-point text-lg mb-3'>「読む・見る・聞く」すべてのメディアで効果を出す</p></div></div><!-- 右カラム：対象読者と期待される変化 --><div class='w-1/2 pl-8 border-l border-gray-300'><div class='mb-10'><h2 class='subtitle mb-4'>対象読者</h2><div class='accent-line mb-6'></div><div class='content-item'><p class='bullet-point text-lg mb-3'>学生・社会人・学び直し層・資格受験者・研究/企画職</p><p class='bullet-point text-lg mb-3'>情報収集や記憶定着に課題を感じている方</p><p class='bullet-point text-lg mb-3'>効率的な学習法を求めるビジネスパーソン</p></div></div><div><h2 class='subtitle mb-4'>読後に期待する変化</h2><div class='accent-line mb-6'></div><div class='content-item'><p class='bullet-point text-lg mb-3'>速読神話からの脱却／能動的インプットへの移行</p><p class='bullet-point text-lg mb-3'>リトリーバル中心の学習サイクル構築</p><p class='bullet-point text-lg mb-3'>目的駆動の情報リテラシーとAI活用の定着</p></div></div></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .subtitle {        font-size: 24px;        font-weight: 600;        color: #b83a4b;    }    .content-item {        margin-bottom: 24px;    }    .bullet-point {        position: relative;        padding-left: 18px;    }    .bullet-point:before {        content: '';        position: absolute;        left: 0;        top: 12px;        width: 8px;        height: 8px;        background-color: #b83a4b;        border-radius: 50%;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }
</style>
