<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="重要用語集" :current-page="20" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>重要用語集</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-8'><!-- 左側：用語リスト --><div class='w-3/4 pr-10'><div class='accent-line'></div><div class='terms-container'><div class='term-item'><p><span class='term-name'>リトリーバル:</span> <span class='term-definition'>記憶を能動的に想起して強化する学習法</span></p></div><div class='term-item'><p><span class='term-name'>スペーシング:</span> <span class='term-definition'>間隔をあけて反復し、忘却曲線に抗う手法</span></p></div><div class='term-item'><p><span class='term-name'>ブレインダンプ:</span> <span class='term-definition'>学習直後に覚えている内容を短時間で吐き出す</span></p></div><div class='term-item'><p><span class='term-name'>ノールック書き写し:</span> <span class='term-definition'>見ずに再現→照合→修正の再生練習</span></p></div><div class='term-item'><p><span class='term-name'>メタ認知:</span> <span class='term-definition'>自分の理解度や戦略を客観視して調整する力</span></p></div><div class='term-item'><p><span class='term-name'>リグレッション:</span> <span class='term-definition'>読書中の視線の後退。理解補正の自然反応</span></p></div><div class='term-item'><p><span class='term-name'>SMART目標:</span> <span class='term-definition'>短期行動を具体化する目標設計フレーム</span></p></div><div class='term-item'><p><span class='term-name'>CAR目標:</span> <span class='term-definition'>有能感・自律性・関係性を満たす動機づけ設計</span></p></div><div class='term-item'><p><span class='term-name'>賛否検索:</span> <span class='term-definition'>肯定/否定双方の論拠を集めバイアスを抑える手法</span></p></div></div></div><!-- 右側：視覚的要素 --><div class='w-1/4 flex flex-col items-center justify-center'><div class='glossary-icon mb-6'>科学的<br/>学習用語</div><p class='text-center text-lg font-semibold text-red-700'>記憶と理解を<br/>深めるキーワード</p></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .term-item {        position: relative;        padding-left: 32px;        margin-bottom: 16px;        line-height: 1.3;    }    .term-item:before {        content: '';        position: absolute;        left: 0;        top: 8px;        width: 12px;        height: 12px;        background-color: #b83a4b;        border-radius: 3px;    }    .term-name {        font-weight: 700;        color: #b83a4b;        font-size: 22px;    }    .term-definition {        font-size: 18px;    }    .highlight-text {        color: #b83a4b;        font-weight: 600;    }    .terms-container {        border-left: 4px solid #b83a4b;        padding-left: 24px;        padding-top: 8px;        padding-bottom: 8px;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .accent-line {        width: 80px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 28px;    }    .glossary-icon {        width: 180px;        height: 180px;        border: 3px solid #0f2a52;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        color: #0f2a52;        font-size: 28px;        font-weight: bold;        text-align: center;        line-height: 1.2;    }
</style>
