<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="まとめと次のアクション" :current-page="21" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>まとめと次のアクション</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-8'><!-- 左側：要点リストと実践プラン --><div class='w-3/5 pr-10'><div class='accent-line'></div><div class='section-title'>3つの要点:</div><div class='summary-container mb-6'><p class='key-point'><span class='highlight-text'>目的駆動</span>で全体→部分→アウトプットの学習サイクル</p><p class='key-point'><span class='highlight-text'>リトリーバル＋スペーシング</span>で'忘れない'を設計</p><p class='key-point'>AI時代は<span class='highlight-text'>情報リテラシーと動機設計</span>が必須</p></div><div class='section-title'>14日実践プラン:</div><div class='plan-container'><p class='plan-item'><span class='font-bold'>Day1-2:</span> 目的設定・プレビュー習慣化</p><p class='plan-item'><span class='font-bold'>Day3-7:</span> 読書→2分ダンプ→翌日想起</p><p class='plan-item'><span class='font-bold'>Day8-14:</span> マルチメディア学習＋週次テスト</p></div></div><!-- 右側：行動宣言と視覚要素 --><div class='w-2/5 flex flex-col'><div class='section-title'>行動宣言:</div><div class='action-box'><p class='text-lg mb-3'>今日の学習テーマを設定する:</p><p class='text-lg mb-3'>具体的な到達基準を明確にする:</p><p class='text-lg mb-3'>最初の想起タイミングを決める:</p><p class='text-center text-lg font-bold mt-4'><span class='highlight-text'>今日から始める一歩</span></p></div><div class='flex justify-center items-center mt-4'><div class='text-center'><div class='w-32 h-32 rounded-full border-4 border-red-700 flex items-center justify-center mx-auto mb-3'><p class='text-2xl font-bold text-red-700'>行動が<br/>記憶を<br/>創る</p></div><p class='text-lg text-center font-semibold'>脳が一生<br/>忘れないために</p></div></div></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .key-point {        position: relative;        padding-left: 32px;        margin-bottom: 20px;        font-size: 22px;        line-height: 1.4;    }    .key-point:before {        content: '';        position: absolute;        left: 0;        top: 12px;        width: 16px;        height: 16px;        background-color: #b83a4b;        border-radius: 3px;    }    .highlight-text {        color: #b83a4b;        font-weight: 600;    }    .summary-container {        border-left: 4px solid #b83a4b;        padding-left: 24px;        padding-top: 8px;        padding-bottom: 8px;        margin-bottom: 24px;    }    .plan-container {        border-left: 4px solid #0f2a52;        padding-left: 24px;        padding-top: 8px;        padding-bottom: 8px;    }    .plan-item {        position: relative;        padding-left: 24px;        margin-bottom: 14px;        font-size: 20px;        line-height: 1.3;    }    .plan-item:before {        content: '•';        position: absolute;        left: 0;        top: 0;        color: #0f2a52;        font-weight: bold;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .accent-line {        width: 80px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 24px;    }    .action-box {        border: 3px solid #b83a4b;        border-radius: 8px;        padding: 20px;        background-color: #f9f2f2;        margin-bottom: 20px;    }    .section-title {        font-size: 24px;        font-weight: 700;        color: #0f2a52;        margin-bottom: 16px;    }
</style>
