<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="全体構成（目次）" :current-page="3" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>全体構成（目次）</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左カラム：前半3章 --><div class='w-1/2 pr-8'><h2 class='subtitle mb-4'>書籍の構成（前半）</h2><div class='accent-line mb-6'></div><div class='content-item'><p class='chapter text-lg mb-2'><span class='chapter-number'>第1章</span> 脳はどうやってインプットしているのか？</p><p class='chapter-description'>速読の誤解と脳の理解プロセス。目と脳の仕組み。</p><p class='chapter text-lg mb-2'><span class='chapter-number'>第2章</span> 脳を最大限にエンゲージする「読むインプット」術</p><p class='chapter-description'>プレビュー・目的設定・アクティブリーディング・メモ法</p><p class='chapter text-lg mb-2'><span class='chapter-number'>第3章</span> 現代を生き抜く力！マルチメディアでの学習法</p><p class='chapter-description'>読む・見る・聞く脳科学。動画視聴最適化。AI活用法。</p></div></div><!-- 右カラム：後半3章と巻末 --><div class='w-1/2 pl-8 border-l border-gray-300'><h2 class='subtitle mb-4'>書籍の構成（後半）</h2><div class='accent-line mb-6'></div><div class='content-item'><p class='chapter text-lg mb-2'><span class='chapter-number'>第4章</span> 脳に焼きつく記憶メソッド</p><p class='chapter-description'>リトリーバル学習。記憶定着テクニック。スペーシング。</p><p class='chapter text-lg mb-2'><span class='chapter-number'>第5章</span> インプットの質を上げるモチベーション管理</p><p class='chapter-description'>内発・外発モチベーション。SMART・CAR目標設定。</p><p class='chapter text-lg mb-2'><span class='chapter-number'>第6章</span> スタンフォード式 AI時代の情報の見分け方</p><p class='chapter-description'>情報リテラシー。チェックリスト。AIの賢い活用。</p><p class='chapter text-lg mt-8'><span class='chapter-number'>巻末</span> キーセンテンス／重要用語・総まとめ</p><p class='chapter-description'>核心的要旨と実践への道筋。科学的根拠一覧。</p></div></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .subtitle {        font-size: 24px;        font-weight: 600;        color: #b83a4b;    }    .content-item {        margin-bottom: 24px;    }    .chapter {        position: relative;        padding-left: 18px;        margin-bottom: 16px;    }    .chapter:before {        content: '';        position: absolute;        left: 0;        top: 12px;        width: 8px;        height: 8px;        background-color: #b83a4b;        border-radius: 50%;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .chapter-number {        color: #b83a4b;        font-weight: 700;    }    .chapter-description {        font-size: 16px;        color: #666;        margin-top: 4px;        padding-left: 18px;    }
</style>
