<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="第1章① 速読の誤解と脳の仕組み" :current-page="4" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>第1章① 速読の誤解と脳の仕組み</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左側：主要コンテンツ --><div class='w-3/4 pr-10'><div class='content-block'><h2 class='section-title'>ポイント:</h2><div class='accent-line'></div><p class='bullet-point text-xl'>文字情報は中心窩でしか精密に読めない（視線はサッカードで移動）</p><p class='bullet-point text-xl'>読書時の「視線の後退（リグレッション）」は理解の補正として自然</p><p class='bullet-point text-xl'>目の動き訓練ではなく、意味処理がボトルネック</p><p class='bullet-point text-xl'>読書は文字認識より意味処理が脳の負荷を占める</p></div><div class='content-block mt-8'><h2 class='section-title'>示唆:</h2><div class='accent-line'></div><p class='bullet-point text-xl'>'速く見る'より'深く理解する'に資源を配分</p><p class='bullet-point text-xl'>視線訓練よりも内容理解と文脈把握を重視</p><p class='bullet-point text-xl'>背景知識を増やし、読書の意味処理を効率化</p></div></div><!-- 右側：視覚的要素 --><div class='w-1/4 flex flex-col items-center justify-center'><div class='brain-icon mb-6'>脳</div><p class='text-center text-lg font-semibold text-red-700'>読書時間の8割は</p><p class='text-center text-lg font-semibold text-red-700'>脳の処理に使われる</p></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .section-title {        font-size: 28px;        font-weight: 600;        color: #b83a4b;    }    .bullet-point {        position: relative;        padding-left: 24px;        margin-bottom: 16px;    }    .bullet-point:before {        content: '';        position: absolute;        left: 0;        top: 12px;        width: 10px;        height: 10px;        background-color: #b83a4b;        border-radius: 50%;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 20px;    }    .content-block {        margin-bottom: 30px;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .brain-icon {        width: 180px;        height: 180px;        border: 3px solid #0f2a52;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        color: #0f2a52;        font-size: 40px;        font-weight: bold;    }
</style>
