<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="第2章① 読む前の準備（プレビュー・目的設定）" :current-page="6" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>第2章① 読む前の準備（プレビュー・目的設定）</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左カラム：手順 --><div class='w-1/2 pr-8'><h2 class='column-title mb-2'>手順:</h2><div class='accent-line'></div><div class='mt-6'><p class='step-item flex items-center text-xl mb-6'><span class='step-icon'>1</span><span><strong>目的設定:</strong> 何を・なぜ・どのレベルで理解するか（到達基準）</span></p><p class='step-item flex items-center text-xl mb-6'><span class='step-icon'>2</span><span><strong>プレビュー:</strong> 目次→章タイトル→見出し→図表→章末まとめ</span></p><p class='step-item flex items-center text-xl mb-6'><span class='step-icon'>3</span><span><strong>予測:</strong> 重要概念・不明点・検証したい主張を仮置き</span></p><p class='step-item flex items-center text-xl mb-6'><span class='step-icon'>4</span><span><strong>時間配分:</strong> 必要度に応じて読む深さを決める</span></p></div></div><!-- 区切り線 --><div class='column-divider mx-4'></div><!-- 右カラム：効果と実践 --><div class='w-1/2 pl-8'><h2 class='column-title mb-2'>効果と実践:</h2><div class='accent-line'></div><div class='mt-6'><div class='mb-6'><h3 class='text-xl font-bold text-blue-800 mb-2'>読書効率の向上</h3><p class='text-lg ml-4'>プレビューにより全体像を先に把握することで、理解のフレームワークを構築。詳細へのアクセスがスムーズに。</p></div><div class='mb-6'><h3 class='text-xl font-bold text-blue-800 mb-2'>メタ認知の強化</h3><p class='text-lg ml-4'>「何がわかっていて何がわからないか」を明確化し、自分の理解度を適切に把握できる。</p></div><div><h3 class='text-xl font-bold text-blue-800 mb-2'>スキーマ形成の促進</h3><p class='text-lg ml-4'>事前に構造を理解することで、新情報が既存知識と結びつきやすくなり、長期記憶への定着率が向上。</p></div></div></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .column-title {        font-size: 28px;        font-weight: 600;        color: #b83a4b;    }    .step-item {        position: relative;        padding-left: 36px;        margin-bottom: 18px;    }    .step-item:before {        content: '';        position: absolute;        left: 0;        top: 8px;        width: 24px;        height: 24px;        background-color: #0f2a52;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        color: white;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 20px;    }    .column-divider {        width: 2px;        background-color: #e2e8f0;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .step-icon {        width: 24px;        height: 24px;        background-color: #0f2a52;        color: white;        border-radius: 50%;        display: inline-flex;        align-items: center;        justify-content: center;        margin-right: 12px;    }
</style>
