<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="第2章② アクティブリーディング" :current-page="7" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>第2章② アクティブリーディング</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左側：主要コンテンツ --><div class='w-3/4 pr-10'><div class='content-block'><h2 class='section-title'>コア技法:</h2><div class='accent-line'></div><p class='bullet-point text-xl'>質問駆動読み: 読む前に自問（何が主張か？根拠は？反例は？）</p><p class='sub-point'>内容を予測し、確認しながら読む姿勢が理解を深める</p><p class='bullet-point text-xl'>セクションごと1～2行で要約→自分の言葉に変換</p><p class='sub-point'>受動的な読みから能動的な解釈に変わる</p><p class='bullet-point text-xl'>接続を可視化: 因果/対比/具体例を記号でマーキング</p><p class='sub-point'>「→」因果、「↔」対比、「※」具体例など記号で構造化</p><p class='bullet-point text-xl'>メタ認知チェック: '今どこにいる？何が分かっていない？'</p><p class='sub-point'>読書中に立ち止まって自分の理解度を客観視する習慣</p></div></div><!-- 右側：視覚的要素 --><div class='w-1/4 flex flex-col items-center justify-center'><div class='active-icon mb-6'>能動</div><p class='text-center text-lg font-semibold text-red-700'>アクティブに</p><p class='text-center text-lg font-semibold text-red-700'>読む＝理解する</p><p class='text-center text-lg mt-4'>記憶定着率</p><p class='text-center text-xl font-bold text-blue-900'>2.1倍</p></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .section-title {        font-size: 28px;        font-weight: 600;        color: #b83a4b;    }    .bullet-point {        position: relative;        padding-left: 24px;        margin-bottom: 16px;    }    .bullet-point:before {        content: '';        position: absolute;        left: 0;        top: 12px;        width: 10px;        height: 10px;        background-color: #b83a4b;        border-radius: 50%;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 20px;    }    .content-block {        margin-bottom: 30px;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .active-icon {        width: 180px;        height: 180px;        border: 3px solid #0f2a52;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        color: #0f2a52;        font-size: 40px;        font-weight: bold;    }    .sub-point {        margin-left: 30px;        position: relative;        padding-left: 20px;        margin-bottom: 12px;        font-size: 16px;        color: #333;    }    .sub-point:before {        content: '•';        position: absolute;        left: 0;        color: #b83a4b;    }
</style>
