<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="第2章③ 手書きメモとアウトプット設計" :current-page="8" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>第2章③ 手書きメモとアウトプット設計</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左カラム：推奨手法 --><div class='w-1/2 pr-8'><h2 class='column-title mb-2'>推奨:</h2><div class='accent-line'></div><div class='mt-6'><p class='step-item flex items-center text-xl mb-6'><span class='step-icon'>1</span><span><strong>手書きメモ:</strong> キーワード→自作定義→例→疑問→次アクション</span></p><p class='step-item flex items-center text-xl mb-6'><span class='step-icon'>2</span><span><strong>アウトライン化:</strong> 見出し階層で論旨を再構成</span></p><p class='step-item flex items-center text-xl mb-6'><span class='step-icon'>3</span><span><strong>キーワードテスト:</strong> 本を閉じて5語から要旨を再生</span></p><p class='step-item flex items-center text-xl mb-6'><span class='step-icon'>4</span><span><strong>ポモドーロ:</strong> 25分集中＋5分ミニリトリーバルで記憶強化</span></p></div></div><!-- 区切り線 --><div class='column-divider mx-4'></div><!-- 右カラム：効果と科学的根拠 --><div class='w-1/2 pl-8'><h2 class='column-title mb-2'>効果と科学的根拠:</h2><div class='accent-line'></div><div class='mt-6'><div class='mb-6'><h3 class='text-xl font-bold text-blue-800 mb-2'>手書きの優位性</h3><p class='text-lg ml-4'>手書きは脳の運動野と認知領域を同時活性化。デジタル入力より記憶定着率が20〜30%高い。</p></div><div class='mb-6'><h3 class='text-xl font-bold text-blue-800 mb-2'>再構成の効果</h3><p class='text-lg ml-4'>情報を自分の言葉で再構成することで、理解の深さと記憶の持続性が大幅に向上。単なる読み返しより効果的。</p></div><div><h3 class='text-xl font-bold text-blue-800 mb-2'>休憩と反復の最適化</h3><p class='text-lg ml-4'>ポモドーロ法は脳の注意機能疲労を防止。短い休憩中のミニリトリーバルが記憶の「初期固定」を促進する。</p></div></div></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .column-title {        font-size: 28px;        font-weight: 600;        color: #b83a4b;    }    .step-item {        position: relative;        padding-left: 36px;        margin-bottom: 18px;    }    .step-item:before {        content: '';        position: absolute;        left: 0;        top: 8px;        width: 24px;        height: 24px;        background-color: #0f2a52;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        color: white;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 20px;    }    .column-divider {        width: 2px;        background-color: #e2e8f0;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .step-icon {        width: 24px;        height: 24px;        background-color: #0f2a52;        color: white;        border-radius: 50%;        display: inline-flex;        align-items: center;        justify-content: center;        margin-right: 12px;    }
</style>
