<template>
  <SlidePageWrapper slide-id="B0D66FY4D7" page-title="第3章① 読む・聞く・見るの脳科学" :current-page="9" :total-pages="21">
<div class='slide-container flex flex-col'><!-- ヘッダー --><div class='header-bar flex items-center px-16'><h1 class='title text-white'>第3章① 読む・聞く・見るの脳科学</h1></div><!-- メインコンテンツ --><div class='flex flex-1 px-16 py-10'><!-- 左カラム：比較 --><div class='w-1/2 pr-8'><h2 class='column-title mb-2'>比較:</h2><div class='accent-line'></div><div class='mt-6'><div class='mb-8'><div class='media-type'>読む</div><p class='text-xl ml-4 mb-2'><i class='fas fa-brain brain-icon'></i><strong>自己ペース制御</strong>: 難しい部分で立ち止まり、理解度に合わせて速度調整が可能</p><p class='text-xl ml-4 mb-2'><i class='fas fa-brain brain-icon'></i><strong>視覚的処理</strong>: 脳内で言語野とブローカ野が活性化、深い処理</p><p class='text-xl ml-4'><i class='fas fa-brain brain-icon'></i><strong>メリット</strong>: 精読向き、構造把握が容易、負荷調整が自由</p></div><div class='mb-8'><div class='media-type'>聞く</div><p class='text-xl ml-4 mb-2'><i class='fas fa-brain brain-icon'></i><strong>並行作業</strong>: 移動中・作業中に聴取可能、時間効率の面で優位</p><p class='text-xl ml-4 mb-2'><i class='fas fa-brain brain-icon'></i><strong>即時性</strong>: 一時記憶に乗りやすいが、深い処理には追加作業が必要</p><p class='text-xl ml-4'><i class='fas fa-brain brain-icon'></i><strong>メリット</strong>: 音声的刺激で記憶の多経路形成、感情の伝達力</p></div><div class='mb-6'><div class='media-type'>見る</div><p class='text-xl ml-4 mb-2'><i class='fas fa-brain brain-icon'></i><strong>視覚手がかり</strong>: 図表・動きで理解促進、複雑概念の把握に有効</p><p class='text-xl ml-4 mb-2'><i class='fas fa-brain brain-icon'></i><strong>過剰情報リスク</strong>: 視覚・音声・テキストの同時提示で認知負荷↑</p><p class='text-xl ml-4'><i class='fas fa-brain brain-icon'></i><strong>メリット</strong>: デモンストレーションに最適、視覚学習者に効果的</p></div></div></div><!-- 区切り線 --><div class='column-divider mx-4'></div><!-- 右カラム：選び方 --><div class='w-1/2 pl-8'><h2 class='column-title mb-2'>選び方:</h2><div class='accent-line'></div><div class='mt-6'><div class='mb-8'><h3 class='text-xl font-bold text-blue-800 mb-3'>目的による選択</h3><p class='text-lg ml-4 mb-2'><strong>深い理解・分析</strong>: 読む（本・論文・長文記事）</p><p class='text-lg ml-4 mb-2'><strong>概念・プロセス理解</strong>: 見る（動画・図解・アニメーション）</p><p class='text-lg ml-4'><strong>移動中・並行作業時</strong>: 聞く（ポッドキャスト・オーディオブック）</p></div><div class='mb-8'><h3 class='text-xl font-bold text-blue-800 mb-3'>難易度による選択</h3><p class='text-lg ml-4 mb-2'><strong>高難度の新概念</strong>: 読む＋見る（テキスト＋視覚資料）</p><p class='text-lg ml-4 mb-2'><strong>中難度の応用</strong>: 見る＋聞く（解説動画）</p><p class='text-lg ml-4'><strong>低難度の復習</strong>: 聞く（音声要約）または読む（スキミング）</p></div><div><h3 class='text-xl font-bold text-blue-800 mb-3'>最適組み合わせの実践</h3><p class='text-lg ml-4 mb-2'><strong>初学習</strong>: 読む（基本）→見る（応用）→聞く（復習）</p><p class='text-lg ml-4 mb-2'><strong>媒体変更</strong>: 同じ内容を異なる媒体で複数回処理</p><p class='text-lg ml-4'><strong>個人特性</strong>: 自分の学習スタイルに合わせた比重調整</p></div></div></div></div><!-- フッター --><div class='footer'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        background-color: white;        color: #0f2a52;        position: relative;    }    .header-bar {        background-color: #0f2a52;        height: 80px;    }    .title {        font-size: 36px;        font-weight: 700;    }    .column-title {        font-size: 28px;        font-weight: 600;        color: #b83a4b;    }    .media-type {        background-color: #0f2a52;        color: white;        border-radius: 8px;        padding: 8px 16px;        font-weight: 600;        font-size: 20px;        margin-bottom: 12px;        display: inline-block;    }    .accent-line {        width: 40px;        height: 4px;        background-color: #b83a4b;        margin-bottom: 20px;    }    .column-divider {        width: 2px;        background-color: #e2e8f0;    }    .footer {        height: 12px;        background-color: #b83a4b;        position: absolute;        bottom: 0;        left: 0;        width: 100%;    }    .brain-icon {        color: #b83a4b;        margin-right: 10px;    }
</style>
