<template>
  <SlidePageWrapper slide-id="4827212678" page-title="第6章：読者が喜ぶセオリーを絞り出す" :current-page="10" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">第6章：読者が喜ぶセオリーを絞り出す</h1><div class="h-1 w-32 bg-blue-500 mt-2"></div></div><!-- コンテンツ --><div class="flex"><!-- 左側：章番号と大きなアイコン --><div class="flex flex-col items-center mr-10"><div class="chapter-icon bg-blue-500"><i class="fas fa-book-open"></i></div><p class="text-4xl font-bold mt-4 text-blue-500">第6章</p></div><!-- 右側：5つの箇条書きポイント --><div class="flex-1"><!-- ポイント1 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-chalkboard-teacher mr-3 text-blue-500"></i>小6に伝えるつもりで<span class="highlight">わかりやすく</span></p><p class="text-gray-700 ml-8">専門用語を多用せず、小学6年生に説明するような平易な言葉で書くことで、誰にでも伝わる文章に。複雑な概念も身近な例えで具体化する。</p></div><!-- ポイント2 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-gift mr-3 text-blue-500"></i><span class="highlight">読者メリット</span>を明文化→必読理由をつくる</p><p class="text-gray-700 ml-8">「この記事を読むとどんな価値が得られるか」を明確に伝える。タイトルやリード文に「〇〇ができるようになる」「〇〇の悩みが解決する」と具体的に示す。</p></div><!-- ポイント3 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-lightbulb mr-3 text-blue-500"></i>「<span class="highlight">〇〇すると〇〇になる！</span>」のセオリーを10個作成</p><p class="text-gray-700 ml-8">自分の専門分野で「〇〇すると〇〇になる」という法則性・再現性のあるノウハウを最低10個書き出す。これが読者の心を動かす「セオリー」になる。</p></div><!-- ポイント4 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-heading mr-3 text-blue-500"></i>セオリーを<span class="highlight">記事タイトル化</span>する方法</p><p class="text-gray-700 ml-8">作成したセオリーを魅力的な記事タイトルに変換する。数字・具体例・対象読者を明確にし、ベネフィットを前面に。「〇〇する3つの方法」など。</p></div><!-- ポイント5 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-not-equal mr-3 text-blue-500"></i><span class="highlight">アンチテーゼ</span>を書くと"クレバー"に見える</p><p class="text-gray-700 ml-8">一般的な常識や通説に対して異論を唱えることで、知的で鋭い印象を与える。「〇〇と思っていませんか？実は△△なんです」という構成で差別化が図れる。</p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">読者が必要とする「価値ある情報」を届ける</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .chapter-icon {            width: 140px;            height: 140px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            color: white;            font-size: 64px;        }        .point-item {            border-left: 4px solid #3b82f6;            padding-left: 1rem;            margin-bottom: 1.5rem;        }        .highlight {            background-color: #dbeafe;            padding: 0 0.25rem;            font-weight: 500;        }
</style>
