<template>
  <SlidePageWrapper slide-id="4827212678" page-title="第7章（前半）：誰でも書ける'魔法の型'" :current-page="11" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">第7章（前半）：誰でも書ける"魔法の型"</h1><div class="h-1 w-32 bg-blue-500 mt-2"></div></div><!-- コンテンツ --><div class="flex"><!-- 左側：章番号と大きなアイコン --><div class="flex flex-col items-center mr-10"><div class="chapter-icon bg-blue-500"><i class="fas fa-pen-nib"></i></div><p class="text-4xl font-bold mt-4 text-blue-500">第7章</p></div><!-- 右側：3つの箇条書きポイント --><div class="flex-1"><!-- ポイント1 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-heart mr-3 text-blue-500"></i>たった<span class="highlight">1人の悩みを解決</span>すると→<span class="highlight">1000人の共感</span></p><p class="text-gray-700 ml-8">目の前の誰かの悩みを解決する気持ちで書けば、読者の心を動かせる。最初は「いいね」や「コメント」が1件でも、その背後に同じ思いを持つ100人、1000人がいる。相手を思う気持ち200％で文章を書けば、その思いは必ず読者に届く。</p></div><!-- ポイント2 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-file-alt mr-3 text-blue-500"></i><span class="highlight">事実伝達法</span>なら迷わず書ける</p><p class="text-gray-700 ml-8">「事実→解説→独自のコメント」という流れで書く方法。まず世の中の事実や出来事、データを紹介し、その解説を行い、最後に専門家としての視点を加える。小論文や卒論のような「仮説・検証」型の書き方で、時事ネタから始めることで執筆の敷居を下げられる。</p></div><!-- ポイント3 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-puzzle-piece mr-3 text-blue-500"></i><span class="highlight">型</span>で書けば迷わない。まずは<span class="highlight">短文から着手</span></p><p class="text-gray-700 ml-8">「ブロック法」「サンドウィッチ法」など、決まった「型」に当てはめることで、誰でも説得力のある文章が書ける。文章構造を明確にし、各パーツに分けて考えれば、書く際の心理的障壁が下がる。短い文章からスタートし、徐々に長文にチャレンジすると効果的。</p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">誰でも「書けない」を「書けた」に変えられる</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .chapter-icon {            width: 140px;            height: 140px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            color: white;            font-size: 64px;        }        .point-item {            border-left: 4px solid #3b82f6;            padding-left: 1rem;            margin-bottom: 1.5rem;        }        .highlight {            background-color: #dbeafe;            padding: 0 0.25rem;            font-weight: 500;        }
</style>
