<template>
  <SlidePageWrapper slide-id="4827212678" page-title="第7章（後半）：ブロック法とサンドウィッチ法" :current-page="12" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">第7章（後半）：ブロック法とサンドウィッチ法</h1><div class="h-1 w-32 bg-purple-600 mt-2"></div></div><!-- コンテンツ --><div class="flex"><!-- 左側：章番号と大きなアイコン --><div class="flex flex-col items-center mr-10"><div class="chapter-icon bg-purple-600"><i class="fas fa-pen-nib"></i></div><p class="text-4xl font-bold mt-4 text-purple-600">第7章</p></div><!-- 右側：箇条書きポイント --><div class="flex-1"><!-- ポイント1 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-cubes mr-3 text-purple-600"></i>                        ブロック法の<span class="highlight">7ステップ構造</span></p><p class="text-gray-700 ml-8"><span class="step-number">1</span>状況提示：「〇〇な時がありますね」                        <span class="step-number">2</span>アドバイス：「そんな時は●●しましょう」                        <span class="step-number">3</span>結果：「そうすると□□になれます」                        <span class="step-number">4</span>理由：「なぜなら■■だからです」                        <span class="step-number">5</span>禁止事項：「✕✕すると◆◆になるので注意」                        <span class="step-number">6</span>事例：「Bさんは●●して成功しました」                        <span class="step-number">7</span>結論再提示：「〇〇の時は●●しましょう」                    </p></div><!-- ポイント2 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-pencil-alt mr-3 text-purple-600"></i>                        応用：<span class="highlight">各ブロックを加筆</span>し長文化する                    </p><p class="text-gray-700 ml-8">                        ブロックごとに内容を肉付けし、より説得力のある文章に発展させる。執筆後に「型のフォーマット」を消去し、前後のつながりを整えることでプロの文章に仕上がる。                    </p></div><!-- ポイント3 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-layer-group mr-3 text-purple-600"></i><span class="highlight">サンドウィッチ法</span>：WEB連載の鉄板                    </p><p class="text-gray-700 ml-8">                        イントロ（上パン）とエンディング（下パン）で、ノウハウ（具材）を挟む3層構造。具材部分は3〜4つの見出し付きセクションで構成。メリハリがあり読者の理解を深める。                    </p></div><!-- ポイント4 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-magic mr-3 text-purple-600"></i><span class="highlight">レゴブロックのように</span>組み立てる執筆感覚                    </p><p class="text-gray-700 ml-8">                        文章の型を活用することで、初心者でも迷わずに専門家レベルの文章が書ける。頭の中で悩むより、テンプレートに沿って埋めていくだけで、読みやすい文章が完成する。                    </p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">型を活用すれば、文章の質と執筆速度が飛躍的に向上する</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .chapter-icon {            width: 140px;            height: 140px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            color: white;            font-size: 64px;        }        .point-item {            border-left: 4px solid #9333ea;            padding-left: 1rem;            margin-bottom: 1.5rem;        }        .highlight {            background-color: #f3e8ff;            padding: 0 0.25rem;            font-weight: 500;        }        .step-number {            display: inline-flex;            width: 24px;            height: 24px;            border-radius: 50%;            background-color: #9333ea;            color: white;            align-items: center;            justify-content: center;            font-size: 14px;            margin-right: 6px;            font-weight: bold;        }
</style>
