<template>
  <SlidePageWrapper slide-id="4827212678" page-title="第8章（前半）：ブログからWEBメディアへ" :current-page="13" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">第8章（前半）：ブログからWEBメディアへ</h1><div class="h-1 w-32 bg-blue-500 mt-2"></div></div><!-- コンテンツ --><div class="flex"><!-- 左側：章番号と大きなアイコン --><div class="flex flex-col items-center mr-10"><div class="chapter-icon bg-blue-500"><i class="fas fa-rocket"></i></div><p class="text-4xl font-bold mt-4 text-blue-500">第8章</p></div><!-- 右側：4つの箇条書きポイント --><div class="flex-1"><!-- ポイント1 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-blog mr-3 text-blue-500"></i>                        まずは<span class="highlight">ブログ</span>で資産化し、実績を可視化                    </p><p class="text-gray-700 ml-8">                        自分の専門知識を体系的に書き残し、セルフメディアとしての基礎を作る。記事は資産であり、自分の専門性を証明する素材にもなる。                    </p></div><!-- ポイント2 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-globe mr-3 text-blue-500"></i>                        WEBメディア連載は<span class="highlight">ブログの1000倍の読者</span>を獲得できる                    </p><p class="text-gray-700 ml-8">                        大手WEBメディア連載により、自前のブログでは届かない莫大な読者層にリーチできる。1記事で30万人が読むケースも。自ブログへの流入も飛躍的に増加する。                    </p></div><!-- ポイント3 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-search mr-3 text-blue-500"></i><span class="highlight">読者の心理と行動</span>を研究→離脱要因を最小化                    </p><p class="text-gray-700 ml-8">                        読者がどのように記事を読むか、何に反応するかを理解し、冒頭で興味を引き、適度な改行や見出しで読みやすくする。長文離れを防ぐ工夫で最後まで読まれる文章に。                    </p></div><!-- ポイント4 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-bullhorn mr-3 text-blue-500"></i><span class="highlight">媒体サーチ→応募</span>（オーディション）で門戸を開く                    </p><p class="text-gray-700 ml-8">                        自分の専門分野に合ったWEBメディアを探し、ライター募集（オーディション）に積極的に応募する。実績がなくてもチャンスはある。採用されれば一気に影響力が拡大。                    </p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">WEBメディアは読者と信頼を一気に拡大する最短ルート</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .chapter-icon {            width: 140px;            height: 140px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            color: white;            font-size: 64px;        }        .point-item {            border-left: 4px solid #3b82f6;            padding-left: 1rem;            margin-bottom: 1.5rem;        }        .highlight {            background-color: #dbeafe;            padding: 0 0.25rem;            font-weight: 500;        }
</style>
