<template>
  <SlidePageWrapper slide-id="4827212678" page-title="第8章後半：継続・PV・セルフメディア" :current-page="14" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">第8章後半：継続・PV・セルフメディア</h1><div class="h-1 w-32 bg-blue-500 mt-2"></div></div><!-- コンテンツ --><div class="flex"><!-- 左側：章番号と大きなアイコン --><div class="flex flex-col items-center mr-10"><div class="chapter-icon bg-blue-500"><i class="fas fa-chart-line"></i></div><p class="text-4xl font-bold mt-4 text-blue-500">第8章</p></div><!-- 右側：4つの箇条書きポイント --><div class="flex-1"><!-- ポイント1 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-sync-alt mr-3 text-blue-500"></i>                        継続の<span class="highlight">3秘訣</span>：型活用／執筆ルーティン／ネタ帳運用                    </p><p class="text-gray-700 ml-8">                        執筆を継続するには「型」を活用して文章を量産し、決まった曜日・時間の執筆ルーティンを確立、日常のあらゆるシーンからネタを収集してストックしておくことが効果的。                    </p></div><!-- ポイント2 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-heading mr-3 text-blue-500"></i>                        PVが伸びる<span class="highlight">タイトル作法</span>：具体・数値・対象・ベネフィット                    </p><p class="text-gray-700 ml-8">                        読者が思わず開きたくなるタイトルには「具体的な数値」「明確な対象者」「得られるベネフィット」が含まれている。例:「40代主婦が1ヶ月で5kg痩せた簡単レシピ3選」                    </p></div><!-- ポイント3 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-microphone-alt mr-3 text-blue-500"></i>                        素人が<span class="highlight">メディアになる時代</span>：発信インフラを自前で                    </p><p class="text-gray-700 ml-8">                        個人がYouTube、podcast、メルマガなどの複数チャネルで発信することで、大手メディアと肩を並べる影響力を持てる時代。自分の専門領域で「メディア化」することで信頼と集客力を高められる。                    </p></div><!-- ポイント4 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-bullhorn mr-3 text-blue-500"></i><span class="highlight">セルフメディア充実</span>：ブログ＋SNS＋ニュースレター                    </p><p class="text-gray-700 ml-8">                        ブログは資産型コンテンツ、SNSは拡散型、メルマガやニュースレターは関係構築型。これらを組み合わせて独自のメディアエコシステムを作ることで、読者との接点を最大化できる。                    </p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">継続的な発信と読者接点の最大化がセルフブランディングの鍵</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .chapter-icon {            width: 140px;            height: 140px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            color: white;            font-size: 64px;        }        .point-item {            border-left: 4px solid #3b82f6;            padding-left: 1rem;            margin-bottom: 1.5rem;        }        .highlight {            background-color: #dbeafe;            padding: 0 0.25rem;            font-weight: 500;        }
</style>
