<template>
  <SlidePageWrapper slide-id="4827212678" page-title="第9章（前半）：講座・オンラインサロンで価値提供" :current-page="15" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">第9章（前半）：講座・オンラインサロンで価値提供</h1><div class="h-1 w-32 bg-purple-500 mt-2"></div></div><!-- コンテンツ --><div class="flex"><!-- 左側：章番号と大きなアイコン --><div class="flex flex-col items-center mr-10"><div class="chapter-icon bg-purple-500"><i class="fas fa-users"></i></div><p class="text-4xl font-bold mt-4 text-purple-500">第9章</p></div><!-- 右側：3つの箇条書きポイント --><div class="flex-1"><!-- ポイント1 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-virus-slash mr-3 text-purple-500"></i>Withコロナ時代は<span class="highlight">オンラインサロンが一人勝ち</span></p><p class="text-gray-700 ml-8">コロナ禍をきっかけに、オンラインコミュニケーションが一般化。場所や時間に縛られない学びの場として、オンラインサロン・講座が急成長。あなたの専門性を活かしたコミュニティ運営で収益化が可能に。</p></div><!-- ポイント2 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-chalkboard-teacher mr-3 text-purple-500"></i><span class="highlight">講演依頼サイト</span>への登録で実績を創出</p><p class="text-gray-700 ml-8">「講演依頼ドットコム」などの講師登録サイトに、あなたの専門プロフィールと提供できる講座を登録。執筆実績と組み合わせることで講演依頼を獲得し、さらなる信頼と実績を積み上げる好循環を生み出す。</p></div><!-- ポイント3 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-money-bill-wave mr-3 text-purple-500"></i>集客プラットフォーム活用で<span class="highlight">即時マネタイズ</span></p><p class="text-gray-700 ml-8">「ストアカ」「Peatix」「note」などのプラットフォームを利用して、自分の知見やノウハウをオンライン・オフライン講座として提供。既存の集客基盤を活用して素早く収益化できる実践的な方法。</p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">書いて発信した先にある、知の共有と収益化</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .chapter-icon {            width: 140px;            height: 140px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            color: white;            font-size: 64px;        }        .point-item {            border-left: 4px solid #8b5cf6;            padding-left: 1rem;            margin-bottom: 1.5rem;        }        .highlight {            background-color: #ede9fe;            padding: 0 0.25rem;            font-weight: 500;        }
</style>
