<template>
  <SlidePageWrapper slide-id="4827212678" page-title="第9章後半：出版と'著者文化人'への道" :current-page="16" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">第9章後半：出版と"著者文化人"への道</h1><div class="h-1 w-32 bg-blue-500 mt-2"></div></div><!-- コンテンツ --><div class="flex"><!-- 左側：章番号と大きなアイコン --><div class="flex flex-col items-center mr-10"><div class="chapter-icon bg-blue-500"><i class="fas fa-book"></i></div><p class="text-4xl font-bold mt-4 text-blue-500">第9章</p></div><!-- 右側：4つの箇条書きポイント --><div class="flex-1"><!-- ポイント1 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-camera mr-3 text-blue-500"></i><span class="highlight">メディアが取材したくなる</span>活動設計                    </p><p class="text-gray-700 ml-8">                        メディアは「新しさ」「専門性」「ストーリー性」がある人物を求める。独自の視点と実績を組み合わせたニュース価値の高い活動を設計することで、取材依頼が舞い込むようになる。                    </p></div><!-- ポイント2 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-hourglass-half mr-3 text-blue-500"></i>                        人生<span class="highlight">100年時代</span>のセカンドキャリアを"書く"で設計                    </p><p class="text-gray-700 ml-8">                        老後2000万円問題も「書く×好き×得意」で解決できる。長寿社会では複数のキャリアを持つことが常識に。書く習慣は生涯の資産となり、年齢を重ねるほど価値が高まる知的労働になる。                    </p></div><!-- ポイント3 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-laptop-code mr-3 text-blue-500"></i><span class="highlight">WEB連載→紙の出版</span>は十分に可能                    </p><p class="text-gray-700 ml-8">                        WEBメディアでの連載実績を積み、読者の反応データを集めることで、出版社への企画持込みの説得力が高まる。WEBでの成功事例を持って出版社に企画を持ち込むことで、商業出版への道が開かれる。                    </p></div><!-- ポイント4 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-award mr-3 text-blue-500"></i>                        出版の<span class="highlight">効用：信用・案件・協業・コミュニティ</span>形成                    </p><p class="text-gray-700 ml-8">                        本を出すことで社会的信用が格段に向上し、講演依頼や取材、協業の申し込みが増加。本業にも好影響をもたらし、読者コミュニティが形成される。「著者文化人」としての新たなアイデンティティが生まれる。                    </p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">書くことで専門家から著者文化人へのステップアップを実現</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .chapter-icon {            width: 140px;            height: 140px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            color: white;            font-size: 64px;        }        .point-item {            border-left: 4px solid #3b82f6;            padding-left: 1rem;            margin-bottom: 1.5rem;        }        .highlight {            background-color: #dbeafe;            padding: 0 0.25rem;            font-weight: 500;        }
</style>
