<template>
  <SlidePageWrapper slide-id="4827212678" page-title="用語集＋実践チェックリスト" :current-page="19" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">用語集＋実践チェックリスト</h1><div class="h-1 w-32 bg-gray-400 mt-2"></div></div><!-- コンテンツ --><div class="grid grid-cols-2 gap-x-8"><!-- 左カラム：用語集 --><div><div class="section-header bg-blue-500"><i class="fas fa-book-open mr-2"></i>用語集                </div><div class="term-item"><p><span class="term-title">・執筆テーマ：</span>発信の中核となる課題・領域</p></div><div class="term-item"><p><span class="term-title">・リード文：</span>本文前の要約・導入</p></div><div class="term-item"><p><span class="term-title">・セオリー：</span>再現性ある"◯◯すると◯◯になる"の法則</p></div><div class="term-item"><p><span class="term-title">・事実伝達法：</span>事実→解説→自分の見解で構成</p></div><div class="term-item"><p><span class="term-title">・ブロック法：</span>7ブロックで組み立てる型</p></div><div class="term-item"><p><span class="term-title">・サンドウィッチ法：</span>導入／見出し群／結びの三層構造</p></div><div class="term-item"><p><span class="term-title">・セルフメディア：</span>自前の発信基盤（ブログ・メルマガ等）</p></div><div class="term-item"><p><span class="term-title">・PV：</span>ページビュー（閲覧数）</p></div><div class="term-item"><p><span class="term-title">・オーディション：</span>媒体の寄稿者募集</p></div></div><!-- 右カラム：チェックリスト --><div><div class="section-header bg-green-500"><i class="fas fa-tasks mr-2"></i>実践チェックリスト                </div><div class="checklist-item"><p><span class="checkbox"></span>テーマ・肩書・読者像を1文で言える</p></div><div class="checklist-item"><p><span class="checkbox"></span>セオリー10個と記事タイトル10本を作成</p></div><div class="checklist-item"><p><span class="checkbox"></span>週2本の執筆ルーティンを設定</p></div><div class="checklist-item"><p><span class="checkbox"></span>ブロック法で1本サンプル記事を作成</p></div><div class="checklist-item"><p><span class="checkbox"></span>自分年表とプロフィールを更新</p></div><div class="checklist-item"><p><span class="checkbox"></span>媒体3社へ寄稿応募</p></div><div class="checklist-item"><p><span class="checkbox"></span>読者リスト運用を開始（ニュースレター）</p></div><div class="checklist-item"><p><span class="checkbox"></span>自メディア（ブログ・SNS）の連携設定</p></div><div class="checklist-item"><p><span class="checkbox"></span>講演依頼サイトへのプロフィール登録</p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">用語を理解し、実践のステップを着実に進めよう</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .section-header {            font-weight: 700;            padding: 0.5rem 1rem;            margin-bottom: 1rem;            color: white;            border-radius: 4px;        }        .term-item {            border-left: 4px solid #3b82f6;            padding-left: 1rem;            margin-bottom: 1rem;        }        .checklist-item {            border-left: 4px solid #10b981;            padding-left: 1rem;            margin-bottom: 1rem;        }        .term-title {            font-weight: 700;            color: #3b82f6;        }        .checkbox {            display: inline-block;            width: 20px;            height: 20px;            border: 2px solid #10b981;            border-radius: 4px;            margin-right: 0.75rem;            position: relative;            top: 4px;        }
</style>
