<template>
  <SlidePageWrapper slide-id="4827212678" page-title="本書の概要・背景・対象読者" :current-page="2" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-8"><h1 class="text-3xl font-bold text-gray-800">本書の概要・背景・対象読者</h1><div class="h-1 w-32 bg-gray-400 mt-2"></div></div><!-- コンテンツ --><div class="grid grid-cols-1 gap-6"><!-- セクション1：概要 --><div class="flex items-start"><div class="mr-6"><div class="icon-container bg-section-1"><i class="fas fa-book-open fa-lg"></i></div></div><div class="flex-1"><h2 class="text-2xl section-title section-1 mb-3">概要</h2><p class="text-lg text-gray-700 ml-2">書く力で「専門家」として指名される存在になる方法を解説。「好き」で「得意」なことを発信し、セルフブランディングを実現するための実践的な執筆・発信の技術書。</p></div></div><!-- セクション2：時代背景 --><div class="flex items-start"><div class="mr-6"><div class="icon-container bg-section-2"><i class="fas fa-chart-line fa-lg"></i></div></div><div class="flex-1"><h2 class="text-2xl section-title section-2 mb-3">時代背景</h2><p class="text-lg text-gray-700 ml-2">副業解禁・コロナ禍・終身雇用の崩壊により、「個」の時代が到来。大手企業でさえ副業を推奨し、自分の専門性で価値を発揮することが求められる時代に。「書いて発信」が新たなキャリア構築の鍵に。</p></div></div><!-- セクション3：対象読者 --><div class="flex items-start"><div class="mr-6"><div class="icon-container bg-section-3"><i class="fas fa-users fa-lg"></i></div></div><div class="flex-1"><h2 class="text-2xl section-title section-3 mb-3">対象読者</h2><p class="text-lg text-gray-700 ml-2">「書くことが必ずしも得意ではないけれど、伝えたいこと、教えたいこと、叫びたいことがある人」。専門能力を持ちながらも、それをうまく発信できていない人。会社員、フリーランス、事業主など、自分の価値を高めたい全ての人。</p></div></div><!-- セクション4：期待される変化 --><div class="flex items-start"><div class="mr-6"><div class="icon-container bg-section-4"><i class="fas fa-rocket fa-lg"></i></div></div><div class="flex-1"><h2 class="text-2xl section-title section-4 mb-3">得られる変化</h2><p class="text-lg text-gray-700 ml-2">ブログ→WEBメディア連載→取材依頼→講演依頼→出版という流れで、「専門家」「著者文化人」として活動の幅が広がる。本業の売上拡大、副業収入、新たな人脈、セカンドキャリア構築など、人生が書くだけで動き出す。</p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">書くことは幸せになる近道 ―潮凪洋介</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .section-title {            font-weight: 700;            padding-left: 0.5rem;            border-left: 5px solid;        }        .section-1 { border-color: #3b82f6; }        .section-2 { border-color: #10b981; }        .section-3 { border-color: #f97316; }        .section-4 { border-color: #8b5cf6; }        .icon-container {            display: flex;            align-items: center;            justify-content: center;            width: 60px;            height: 60px;            border-radius: 50%;            color: white;        }        .bg-section-1 { background-color: #3b82f6; }        .bg-section-2 { background-color: #10b981; }        .bg-section-3 { background-color: #f97316; }        .bg-section-4 { background-color: #8b5cf6; }
</style>
