<template>
  <SlidePageWrapper slide-id="4827212678" page-title="まとめ・締め：今日から動く3ステップ" :current-page="20" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">まとめ・締め：今日から動く3ステップ</h1><div class="h-1 w-32 bg-gray-400 mt-2"></div></div><!-- コンテンツ --><div class="grid grid-cols-2 gap-x-8"><!-- 左カラム：3ステップ --><div><div class="section-header bg-blue-500"><i class="fas fa-walking mr-2"></i>今日からのアクションプラン</div><div class="step-item pt-1 pb-3"><div class="step-number">1</div><p class="font-bold text-lg mb-2 pl-3">テーマ×肩書×読者像を定義</p><p class="pl-3">あなたの強み、経験を整理し、専門領域を明確に。肩書きを考案し、プロフィールを更新しましょう。読者はどんな人か、何を求めているかを具体的にイメージします。</p></div><div class="step-item pt-1 pb-3"><div class="step-number">2</div><p class="font-bold text-lg mb-2 pl-3">ブロック法で1本執筆→公開</p><p class="pl-3">学んだブロック法を使い、最初の記事を書いてみましょう。完璧を目指さず、まずは完成させることが大切です。ブログに公開し、SNSで導線を作ります。</p></div><div class="step-item pt-1 pb-3"><div class="step-number">3</div><p class="font-bold text-lg mb-2 pl-3">寄稿応募＆定期配信開始</p><p class="pl-3">興味のあるWEBメディアを3つ選び、オーディションに応募。同時に自メディア（ブログ、ニュースレター）の定期更新を始めましょう。週2本のルーティンをつくります。</p></div></div><!-- 右カラム：メッセージ --><div><div class="section-header bg-green-500"><i class="fas fa-heart mr-2"></i>最終メッセージ</div><div class="message-box mb-6"><p class="text-xl font-bold mb-3">人生は<span class="highlight">書くだけ</span>で動き出す</p><p class="mb-3">あなたの経験、知識、専門性は誰かの悩みを解決し、人生を変える力を持っています。</p><p class="mb-3">書くことは幸せへの近道。あなたの価値を社会に届け、多くの人を助けながら、自分自身も成長していきましょう。</p></div><div class="bg-blue-50 p-4 rounded-lg"><p class="font-bold mb-2"><i class="fas fa-quote-left text-blue-400 mr-2"></i>重要なリマインダー<i class="fas fa-quote-right text-blue-400 ml-2"></i></p><p class="mb-2">・完璧を目指さず、<span class="highlight">最初の1フレーズ</span>から始めよう</p><p class="mb-2">・困っている<span class="highlight">たった1人</span>のために書けば1000人に届く</p><p>・書き続けることで<span class="highlight">著者文化人</span>として、新たな人生が開ける</p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">さあ、あなたの物語を書き始めよう！</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .section-header {            font-weight: 700;            padding: 0.5rem 1rem;            margin-bottom: 1rem;            color: white;            border-radius: 4px;        }        .step-item {            border-left: 4px solid #3b82f6;            padding-left: 1rem;            margin-bottom: 1.5rem;            position: relative;        }        .step-number {            position: absolute;            left: -12px;            top: 0;            background-color: #3b82f6;            color: white;            width: 24px;            height: 24px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            font-weight: bold;        }        .message-box {            border-left: 4px solid #10b981;            padding: 1rem;            background-color: #f0fdf4;            border-radius: 0 8px 8px 0;        }        .highlight {            color: #3b82f6;            font-weight: 700;        }
</style>
