<template>
  <SlidePageWrapper slide-id="4827212678" page-title="序章：先駆者たちの背中" :current-page="4" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-8"><h1 class="text-3xl font-bold text-gray-800">序章：先駆者たちの背中</h1><div class="h-1 w-32 bg-gray-400 mt-2"></div></div><!-- コンテンツ --><div class="grid grid-cols-1 gap-6"><!-- セクション1：ポイント --><div class="flex items-start"><div class="mr-6"><div class="icon-container bg-section-1"><i class="fas fa-rocket fa-lg"></i></div></div><div class="flex-1"><h2 class="text-2xl section-title section-1 mb-3">ポイント</h2><p class="text-lg text-gray-700 ml-2">書いて発信することでセルフブランディングが確立し、仕事や人生が加速する。先駆者たちは副業からスタートし、本業以上の収入や影響力を得た人も多数。「好き×得意」を発信することで、新たなキャリアと人脈を獲得し、人生が大きく好転している。</p></div></div><!-- セクション2：事例の共通点 --><div class="flex items-start"><div class="mr-6"><div class="icon-container bg-section-2"><i class="fas fa-hands-helping fa-lg"></i></div></div><div class="flex-1"><h2 class="text-2xl section-title section-2 mb-3">事例の共通点</h2><p class="text-lg text-gray-700 ml-2">多くの先駆者が自身の「挫折体験」「克服プロセス」「専門知識」を言語化し、困っている人に役立つ形で提供している。失恋カウンセラーは自身の失恋経験から、キャリアコンサルタントは転職経験から、美容家は肌トラブル克服から着想を得ている。「弱み」を「強み」に転換する発想が共通している。</p></div></div><!-- セクション3：学び --><div class="flex items-start"><div class="mr-6"><div class="icon-container bg-section-3"><i class="fas fa-lightbulb fa-lg"></i></div></div><div class="flex-1"><h2 class="text-2xl section-title section-3 mb-3">学び</h2><p class="text-lg text-gray-700 ml-2">「最初の1フレーズ」が人生を動かす原動力になる。著者自身も産婦人科の病室で最初の記事を書いたことが、73冊の著書と事業展開につながった。完璧を目指すより「とりあえず書いてみる」着手と継続が重要。誰もが最初は初心者だが、継続的な発信が専門家としての地位を確立させる。</p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">「書くことは人生を変える魔法」―先駆者たちの共通認識</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .section-title {            font-weight: 700;            padding-left: 0.5rem;            border-left: 5px solid;        }        .section-1 { border-color: #3b82f6; }        .section-2 { border-color: #10b981; }        .section-3 { border-color: #f97316; }        .icon-container {            display: flex;            align-items: center;            justify-content: center;            width: 60px;            height: 60px;            border-radius: 50%;            color: white;        }        .bg-section-1 { background-color: #3b82f6; }        .bg-section-2 { background-color: #10b981; }        .bg-section-3 { background-color: #f97316; }
</style>
