<template>
  <SlidePageWrapper slide-id="4827212678" page-title="第1章：個の時代に生き残る条件" :current-page="5" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">第1章：個の時代に生き残る条件</h1><div class="h-1 w-32 bg-blue-500 mt-2"></div></div><!-- コンテンツ --><div class="flex"><!-- 左側：章番号と大きなアイコン --><div class="flex flex-col items-center mr-10"><div class="chapter-icon bg-blue-500"><i class="fas fa-user-tie"></i></div><p class="text-4xl font-bold mt-4 text-blue-500">第1章</p></div><!-- 右側：4つの箇条書きポイント --><div class="flex-1"><!-- ポイント1 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-building mr-3 text-blue-500"></i>                        会社の看板ではなく<span class="highlight">「自分の専門性」</span>で勝負する                    </p><p class="text-gray-700 ml-8">                        終身雇用崩壊、副業解禁の時代。会社だけに頼らず、自分の専門性を磨いて「個」として評価される人材になることが生存戦略に。                    </p></div><!-- ポイント2 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-pen-fancy mr-3 text-blue-500"></i><span class="highlight">頭を下げる営業</span>から、<span class="highlight">書いて発信</span>し尊敬される存在へ                    </p><p class="text-gray-700 ml-8">                        ゴリ押し営業は嫌われる時代。専門家として文章を発信することで信頼を獲得し、「先生」と慕われながら選ばれるようになる道がある。                    </p></div><!-- ポイント3 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-search mr-3 text-blue-500"></i>                        専門家の<span class="highlight">8割が埋もれている</span>→強みを文章化し発信                    </p><p class="text-gray-700 ml-8">                        優れた専門性を持ちながら世間に埋もれている人が多い。SNSや名刺交換だけでは差別化できず、「書いて発信」することで専門性を可視化し、認知を高める必要がある。                    </p></div><!-- ポイント4 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-blog mr-3 text-blue-500"></i>                        ブログが伸びない<span class="highlight">理由を見直す</span></p><p class="text-gray-700 ml-8">                        ブログで集客できない原因は「読者メリットが不明確」「テーマが絞られていない」「継続性がない」「文章が読みにくい」。読者目線の価値提供が必要。                    </p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">「個で生きる時代」に必要なのは、専門性の発信力</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .chapter-icon {            width: 140px;            height: 140px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            color: white;            font-size: 64px;        }        .point-item {            border-left: 4px solid #3b82f6;            padding-left: 1rem;            margin-bottom: 1.5rem;        }        .highlight {            background-color: #dbeafe;            padding: 0 0.25rem;            font-weight: 500;        }
</style>
