<template>
  <SlidePageWrapper slide-id="4827212678" page-title="第2章：0円で始める自分ブランディング" :current-page="6" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">第2章：0円で始める自分ブランディング</h1><div class="h-1 w-32 bg-blue-500 mt-2"></div></div><!-- コンテンツ --><div class="flex"><!-- 左側：章番号と大きなアイコン --><div class="flex flex-col items-center mr-10"><div class="chapter-icon bg-blue-500"><i class="fas fa-pen-nib"></i></div><p class="text-4xl font-bold mt-4 text-blue-500">第2章</p></div><!-- 右側：4つの箇条書きポイント --><div class="flex-1"><!-- ポイント1 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-feather-alt mr-3 text-blue-500"></i>                        得意分野は<span class="highlight">「書く」</span>ことで専門分野へ昇格                    </p><p class="text-gray-700 ml-8">                        あなたの知識や経験を文章化することで、「何となく得意」から「専門家」へと格上げできる。執筆は専門性を証明する最も効果的な手段。                    </p></div><!-- ポイント2 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-trophy mr-3 text-blue-500"></i><span class="highlight">オンリーワン</span>の地位は文章と実績の積み上げで築く                    </p><p class="text-gray-700 ml-8">                        誰もがSNSで発信できる時代だからこそ、質の高い文章と実績を積み重ねることで、あなただけの「オンリーワンの地位」を確立できる。                    </p></div><!-- ポイント3 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-book mr-3 text-blue-500"></i>                        経営者が<span class="highlight">著書を求める理由</span>：信用・採用・販路拡大                    </p><p class="text-gray-700 ml-8">                        書籍は最強の名刺。一冊の著書が信頼性を高め、人材採用、講演依頼、新規顧客獲得など、ビジネスの多方面で大きな効果を発揮する。                    </p></div><!-- ポイント4 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-laptop mr-3 text-blue-500"></i>                        PC一つで<span class="highlight">どこでも働ける</span>"書く×ワーケーション"                    </p><p class="text-gray-700 ml-8">                        文章力は場所を選ばない武器になる。コーヒーショップ、旅先、リゾート地など、好きな環境で執筆しながら収入を得る自由なライフスタイルが実現可能に。                    </p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">0円から始められる最強のセルフブランディング術</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .chapter-icon {            width: 140px;            height: 140px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            color: white;            font-size: 64px;        }        .point-item {            border-left: 4px solid #3b82f6;            padding-left: 1rem;            margin-bottom: 1.5rem;        }        .highlight {            background-color: #dbeafe;            padding: 0 0.25rem;            font-weight: 500;        }
</style>
