<template>
  <SlidePageWrapper slide-id="4827212678" page-title="第3章：書く目的とゴール設定" :current-page="7" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">第3章：書く目的とゴール設定</h1><div class="h-1 w-32 bg-blue-500 mt-2"></div></div><!-- コンテンツ --><div class="flex"><!-- 左側：章番号と大きなアイコン --><div class="flex flex-col items-center mr-10"><div class="chapter-icon bg-blue-500"><i class="fas fa-bullseye"></i></div><p class="text-4xl font-bold mt-4 text-blue-500">第3章</p></div><!-- 右側：4つの箇条書きポイント --><div class="flex-1"><!-- ポイント1 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-handshake mr-3 text-blue-500"></i>会う前から<span class="highlight">「事前信頼」</span>を文章でつくる</p><p class="text-gray-700 ml-8">対面前に記事やコラムを読んでもらうことで、会う前から「この人に会ってみたい」「相談したい」と思われる状態を構築できる。記事が営業マンとして24時間働く。</p></div><!-- ポイント2 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-broadcast-tower mr-3 text-blue-500"></i><span class="highlight">スカイツリー理論</span>：発信の"高さ"が信頼と機会を呼ぶ</p><p class="text-gray-700 ml-8">東京スカイツリーは高さゆえに遠くからも見える。同様に、発信の「高さ」（質・量・継続性）が高いほど、多くの人に見つけてもらえ、信頼と機会につながる。</p></div><!-- ポイント3 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-microphone mr-3 text-blue-500"></i>講演・取材・案件獲得は<span class="highlight">「書いて発言」</span>で叶える</p><p class="text-gray-700 ml-8">講演や取材依頼は偶然ではなく、文章による専門性の可視化から生まれる。書いて発信し続けることで、メディアや講演依頼者の目に留まり、機会が舞い込む。</p></div><!-- ポイント4 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-piggy-bank mr-3 text-blue-500"></i>老後2000万円も<span class="highlight">「好き×得意」</span>の発信で稼ぐ</p><p class="text-gray-700 ml-8">老後資金は会社だけでなく、自分の「好き」と「得意」を掛け合わせた発信を収益化することで確保できる。年金以外の収入源を「書いて発信」することで構築する戦略。</p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">なぜ書くのか？ ゴール設定が書く力を引き出す</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .chapter-icon {            width: 140px;            height: 140px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            color: white;            font-size: 64px;        }        .point-item {            border-left: 4px solid #3b82f6;            padding-left: 1rem;            margin-bottom: 1.5rem;        }        .highlight {            background-color: #dbeafe;            padding: 0 0.25rem;            font-weight: 500;        }
</style>
