<template>
  <SlidePageWrapper slide-id="4827212678" page-title="第4章：執筆テーマの決め方（執筆はテーマが10割）" :current-page="8" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">第4章：執筆テーマの決め方（執筆はテーマが10割）</h1><div class="h-1 w-32 bg-blue-500 mt-2"></div></div><!-- コンテンツ --><div class="flex"><!-- 左側：章番号と大きなアイコン --><div class="flex flex-col items-center mr-10"><div class="chapter-icon bg-blue-500"><i class="fas fa-pen-to-square"></i></div><p class="text-4xl font-bold mt-4 text-blue-500">第4章</p></div><!-- 右側：5つの箇条書きポイント --><div class="flex-1"><!-- ポイント1 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-bullseye mr-3 text-blue-500"></i>                        テーマの精度が文章成果の<span class="highlight">9割を決める</span></p><p class="text-gray-700 ml-8">                        優れた文章の基盤は鋭いテーマ設定にある。テーマ選びの精度が最終的な成果の9割を決定づける。まずはテーマに時間をかけることが重要。                    </p></div><!-- ポイント2 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-heading mr-3 text-blue-500"></i>                        ライティングは<span class="highlight">「タイトルが9割」</span></p><p class="text-gray-700 ml-8">                        一目で価値と対象が伝わるタイトルが読者を引き付ける。タイトルだけで読むか読まないかを判断されるため、インパクトと価値提案を含めた表現を工夫する。                    </p></div><!-- ポイント3 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-exchange-alt mr-3 text-blue-500"></i><span class="highlight">「書きたいこと」</span>より<span class="highlight">「求められること」</span>を優先                    </p><p class="text-gray-700 ml-8">                        自分の書きたいことよりも、読者が求めている情報を優先的に提供することで共感と信頼を得られる。市場ニーズを理解して書くことがファンを増やす鍵となる。                    </p></div><!-- ポイント4 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-chart-pie mr-3 text-blue-500"></i>                        市場規模を見極める／<span class="highlight">弱みに原石が眠る</span></p><p class="text-gray-700 ml-8">                        テーマ選びでは市場規模（読者数）を意識する。また意外にも自分の弱点や苦労した経験には価値ある原石が埋まっており、それを掘り起こすことで独自性のあるテーマとなる。                    </p></div><!-- ポイント5 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-layer-group mr-3 text-blue-500"></i><span class="highlight">テーマ＋サブタイトル＋リード文</span>を設計                    </p><p class="text-gray-700 ml-8">                        魅力的な執筆には3つの要素が必要。メインテーマを補完するサブタイトルと、読者の興味を引くリード文の組み合わせで、読者を惹きつける入口を作る。                    </p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">テーマ選びが文章の成否を左右する</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .chapter-icon {            width: 140px;            height: 140px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            color: white;            font-size: 64px;        }        .point-item {            border-left: 4px solid #3b82f6;            padding-left: 1rem;            margin-bottom: 1.5rem;        }        .highlight {            background-color: #dbeafe;            padding: 0 0.25rem;            font-weight: 500;        }
</style>
