<template>
  <SlidePageWrapper slide-id="4827212678" page-title="第5章：世界に1つの最強プロフィール" :current-page="9" :total-pages="20">
<div class="slide-container flex flex-col"><div class="flex-1 p-10"><!-- ヘッダー --><div class="mb-6"><h1 class="text-3xl font-bold text-gray-800">第5章：世界に1つの最強プロフィール</h1><div class="h-1 w-32 bg-purple-600 mt-2"></div></div><!-- コンテンツ --><div class="flex"><!-- 左側：章番号と大きなアイコン --><div class="flex flex-col items-center mr-10"><div class="chapter-icon bg-purple-600"><i class="fas fa-id-card"></i></div><p class="text-4xl font-bold mt-4 text-purple-600">第5章</p></div><!-- 右側：4つの箇条書きポイント --><div class="flex-1"><!-- ポイント1 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-history mr-3 text-purple-600"></i><span class="highlight">自分年表</span>で強み・転機・成果を見える化</p><p class="text-gray-700 ml-8">人生の転機やキャリア、挫折と成功を時系列で整理することで、自分の強みと専門性がクリアになる。プロフィールに厚みと説得力が生まれる。</p></div><!-- ポイント2 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-tags mr-3 text-purple-600"></i><span class="highlight">ブランド属性</span>を洗い出し、肩書を磨く</p><p class="text-gray-700 ml-8">「得意なこと」「経験分野」「実績」「資格」など、自分を表す要素を総ざらいし、世界で唯一の肩書きを作成。「〇〇専門」「〇〇のプロ」など、記憶に残る肩書が重要。</p></div><!-- ポイント3 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-lightbulb mr-3 text-purple-600"></i>自分の<span class="highlight">法則に名前を付ける</span>→独自性と記憶定着</p><p class="text-gray-700 ml-8">自分オリジナルの方法論やコツに名前を付けることで、読者の記憶に残りやすくなる。「〇〇の法則」「〇〇メソッド」など、あなただけの理論を作る。</p></div><!-- ポイント4 --><div class="point-item"><p class="text-xl font-bold mb-2"><i class="fas fa-mask mr-3 text-purple-600"></i><span class="highlight">"黒歴史"の開示</span>が共感を生む。物語化して資産化</p><p class="text-gray-700 ml-8">失敗や挫折の経験こそが、読者との最大の共感ポイントになる。どん底から立ち上がった経験は強力な武器に。恥ずかしい過去も「物語」として価値がある。</p></div></div></div></div><!-- フッター --><div class="px-10 pb-4 text-right"><p class="text-sm text-gray-500">あなたの人生の物語が、最強のプロフィールを作る</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #ffffff;            overflow: hidden;            position: relative;        }        .chapter-icon {            width: 140px;            height: 140px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            color: white;            font-size: 64px;        }        .point-item {            border-left: 4px solid #9333ea;            padding-left: 1rem;            margin-bottom: 1.5rem;        }        .highlight {            background-color: #f3e8ff;            padding: 0 0.25rem;            font-weight: 500;        }
</style>
