<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="第5章①: 家事のコツ（掃除・片付け）" :current-page="10" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">05</div><h2 class="title text-4xl relative z-10">第5章①: 家事のコツ（掃除・片付け）</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側カラム - 掃除 --><div class="w-1/2 pr-4"><div class="column column-left flex flex-col h-full"><h3 class="column-title text-2xl">掃除</h3><div class="flex items-center mb-4"><div class="icon mr-3"><i class="fas fa-clock text-2xl"></i></div><p class="text-lg"><span class="content-highlight">10分だけ、時間で切る</span></p></div><div class="flex items-center mb-4"><div class="icon mr-3"><i class="fas fa-route text-2xl"></i></div><p class="text-lg"><span class="content-highlight">エリア固定より経路清掃</span></p></div><div class="mt-6"><p class="bullet-point text-base">アラーム設定で10分だけ集中して掃除する</p><p class="bullet-point text-base">玄関から寝室までなど、移動ルートを掃除</p><p class="bullet-point text-base">掃除自体を目的にしない（別の用事の合間に）</p></div><div class="mt-6 p-3 bg-blue-50 rounded"><p class="text-base"><span class="font-bold">Point:</span> 長時間やろうとしないことが鍵。短く区切り、経路を意識すると習慣化しやすくなります。</p></div></div></div><!-- 右側カラム - 片付け --><div class="w-1/2 pl-4"><div class="column column-right"><h3 class="column-title text-2xl">片付け・環境設計</h3><div class="mb-6"><p class="bullet-point text-lg">カテゴリごとに一気に裁く（本・服・書類など）</p><p class="bullet-point text-lg">収納は"戻しやすさ"最優先で設計する</p><p class="bullet-point text-lg">修理や補修は道具を出しっぱなしにする</p><p class="bullet-point text-lg">ストックはテーマ別で可視化する</p></div><div class="flex items-center mt-6"><div class="icon mr-3"><i class="fas fa-lightbulb text-2xl"></i></div><p class="text-lg"><span class="content-highlight">障壁を下げる</span> - 着手のハードルを極力減らす</p></div><div class="flex items-center mt-4"><div class="icon mr-3"><i class="fas fa-eye text-2xl"></i></div><p class="text-lg"><span class="content-highlight">可視化する</span> - 目に入る位置に配置する</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .column-title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        font-weight: 700;        padding-bottom: 8px;        border-bottom: 3px solid #3182ce;        margin-bottom: 16px;    }    .bullet-point {        position: relative;        padding-left: 1.75rem;        margin-bottom: 12px;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 8px;        height: 8px;        background-color: #3182ce;        border-radius: 50%;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .column {        padding: 20px;        background-color: #ffffff;        border-radius: 8px;        box-shadow: 0 2px 5px rgba(0,0,0,0.05);        height: 100%;    }    .column-left {        margin-right: 10px;    }    .column-right {        margin-left: 10px;    }    .icon {        color: #3182ce;    }
</style>
