<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="第5章②: 料理・洗濯・スケジュール管理" :current-page="11" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">05</div><h2 class="title text-4xl relative z-10">第5章②: 料理・洗濯・スケジュール管理</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側カラム - 料理/献立 --><div class="w-1/2 pr-4"><div class="column column-left flex flex-col h-full"><h3 class="column-title text-2xl">料理/献立のコツ</h3><div class="flex items-start mb-4"><div class="icon mr-3 mt-1"><i class="fas fa-utensils text-2xl"></i></div><div><p class="text-lg mb-1"><span class="content-highlight">段取り練習として少量で反復</span></p><p class="text-base text-gray-600">複雑な献立は細かく分解し、少量ずつ試すことで脳の負担を軽減</p></div></div><div class="flex items-start mb-4"><div class="icon mr-3 mt-1"><i class="fas fa-tasks text-2xl"></i></div><div><p class="text-lg mb-1"><span class="content-highlight">同時進行は"順序を決めた並行"で</span></p><p class="text-base text-gray-600">複数の調理を同時にするのではなく、明確な切り替えポイントを設定</p></div></div><div class="flex items-start mb-4"><div class="icon mr-3 mt-1"><i class="fas fa-list-alt text-2xl"></i></div><div><p class="text-lg mb-1"><span class="content-highlight">献立決めは3品の型から</span></p><p class="text-base text-gray-600">主菜・副菜・汁物の基本セットを決めておき、アレンジする</p></div></div><div class="tip-box"><p class="text-base"><span class="font-bold">Point:</span> 「切る→焼く→盛る」の3工程で練習すると脳にパターンが定着し、めんどくさい感が減ります。</p></div></div></div><!-- 右側カラム - 洗濯/スケジュール --><div class="w-1/2 pl-4"><div class="column column-right h-full"><h3 class="column-title text-2xl">洗濯・スケジュール管理</h3><div class="mb-5"><p class="text-lg font-semibold text-blue-700 mb-2">洗濯のコツ:</p><p class="bullet-point text-lg">天気を主役にして日程を決める</p><p class="bullet-point text-lg">前夜にカゴ分けで朝の判断を削減</p><p class="bullet-point text-lg">たたむ作業は習慣化の練習に活用</p></div><div class="mb-5"><p class="text-lg font-semibold text-blue-700 mb-2">スケジュール管理:</p><p class="bullet-point text-lg">情報を空間/視覚/言語に変換</p><p class="bullet-point text-lg">締切は"期限前倒しの擬似期日"を設定</p><p class="bullet-point text-lg">家族スケジュールは一覧化して視認性アップ</p></div><div class="tip-box"><p class="text-base"><span class="font-bold">実践例:</span> 食品の賞味期限管理で「期限切れ防止」ができると、締切タスクの練習にもなります。「見える化」で脳の認知負荷を下げましょう。</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .column-title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        font-weight: 700;        padding-bottom: 8px;        border-bottom: 3px solid #3182ce;        margin-bottom: 16px;    }    .bullet-point {        position: relative;        padding-left: 1.75rem;        margin-bottom: 12px;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 8px;        height: 8px;        background-color: #3182ce;        border-radius: 50%;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .column {        padding: 20px;        background-color: #ffffff;        border-radius: 8px;        box-shadow: 0 2px 5px rgba(0,0,0,0.05);        height: 100%;    }    .column-left {        margin-right: 10px;    }    .column-right {        margin-left: 10px;    }    .icon {        color: #3182ce;    }    .tip-box {        background-color: #ebf8ff;        border-left: 4px solid #3182ce;        padding: 8px 12px;        margin-top: 12px;        border-radius: 4px;    }
</style>
