<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="第6章①: 脳タイプ別の理解（同時系/継次系）" :current-page="12" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">06</div><h2 class="title text-4xl relative z-10">第6章①: 脳タイプ別の理解（同時系/継次系）</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側のコンテンツ --><div class="w-2/3 pr-10"><div class="mb-6"><p class="text-xl font-bold mb-4">脳の情報処理には<span class="content-highlight">2つのタイプ</span>があります</p></div><div class="mb-8"><p class="bullet-point text-lg mb-3"><span class="content-highlight">同時系：</span> 全体像や映像で理解、テーマ駆動が得意</p><p class="sub-bullet text-md mb-2 ml-6">複数の情報を一度に処理できる</p><p class="sub-bullet text-md mb-2 ml-6">ビジュアル・空間的情報に強い</p></div><div class="mb-8"><p class="bullet-point text-lg mb-3"><span class="content-highlight">継次系：</span> 手順で理解、順番と細分化が得意</p><p class="sub-bullet text-md mb-2 ml-6">情報を順序立てて処理する</p><p class="sub-bullet text-md mb-2 ml-6">言語・論理的情報に強い</p></div><div class="mb-4"><p class="text-lg font-bold mb-3">適合の原則：</p><p class="bullet-point text-lg mb-2">同時系には "<span class="content-highlight">まとめ→例→結論</span>"</p><p class="bullet-point text-lg mb-2">継次系には "<span class="content-highlight">結論→手順→確認</span>"</p></div><div class="mt-4"><p class="text-lg font-italic text-gray-600">自己理解で"わかりやすさ"を設計する</p></div></div><!-- 右側の図表 --><div class="w-1/3 flex flex-col justify-center items-center"><div class="flex justify-center mb-4"><i class="fas fa-brain brain-type-icon text-8xl"></i></div><table class="comparison-table w-full mt-4"><tr><td class="header simultaneous-bg rounded-tl-lg">同時系</td><td class="header sequential-bg rounded-tr-lg">継次系</td></tr><tr class="comparison-row"><td>全体像を把握</td><td>詳細から理解</td></tr><tr class="comparison-row"><td>映像・直感的</td><td>手順・論理的</td></tr><tr class="comparison-row"><td>まとめから例示</td><td>順番を重視</td></tr><tr class="comparison-row"><td>並列処理得意</td><td>直列処理得意</td></tr></table></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .bullet-point {        position: relative;        padding-left: 2rem;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 10px;        height: 10px;        background-color: #3182ce;        border-radius: 50%;    }    .sub-bullet {        position: relative;        padding-left: 1.5rem;    }    .sub-bullet::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 6px;        height: 6px;        background-color: #63b3ed;        border-radius: 50%;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .brain-type-icon {        color: #3182ce;        opacity: 0.1;    }    .comparison-table {        border-collapse: separate;        border-spacing: 0 10px;    }    .comparison-table td {        padding: 12px 16px;    }    .comparison-table .header {        text-align: center;        font-weight: 700;        color: white;    }    .simultaneous-bg {        background-color: #3182ce;    }    .sequential-bg {        background-color: #4299e1;    }    .comparison-row {        background-color: #f0f6ff;    }
</style>
