<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="第6章②: 伝え方の4タイプ活用" :current-page="13" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">06</div><h2 class="title text-4xl relative z-10">第6章②: 伝え方の4タイプ活用</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側カラム - タイプと相性 --><div class="w-1/2 pr-4"><div class="column column-left flex flex-col h-full"><h3 class="column-title text-2xl">タイプと相性</h3><div class="type-card"><p class="text-lg font-bold text-blue-800"><i class="fas fa-bolt mr-2"></i>直感型</p><p class="text-base"><span class="ok-text">OK:</span> 先に結論、ポイントのみ</p><p class="text-base"><span class="ng-text">NG:</span> 冗長な経緯説明</p></div><div class="type-card"><p class="text-lg font-bold text-blue-800"><i class="fas fa-exchange-alt mr-2"></i>置き換え型</p><p class="text-base"><span class="ok-text">OK:</span> 例え話・比喩表現</p><p class="text-base"><span class="ng-text">NG:</span> 専門用語のみの説明</p></div><div class="type-card"><p class="text-lg font-bold text-blue-800"><i class="fas fa-list-ol mr-2"></i>まとめ型</p><p class="text-base"><span class="ok-text">OK:</span> 順番通りの手順説明</p><p class="text-base"><span class="ng-text">NG:</span> 要点だけの断片的情報</p></div><div class="type-card"><p class="text-lg font-bold text-blue-800"><i class="fas fa-sitemap mr-2"></i>法則型</p><p class="text-base"><span class="ok-text">OK:</span> 因果関係・原理の説明</p><p class="text-base"><span class="ng-text">NG:</span> 本筋から外れる余談</p></div></div></div><!-- 右側カラム - 実践ポイント --><div class="w-1/2 pl-4"><div class="column column-right"><h3 class="column-title text-2xl">実践ポイント</h3><div class="mb-4"><p class="bullet-point text-lg">相手のタイプを見極めて伝え方を調整する</p><p class="bullet-point text-lg">同じ内容でも伝え方を変えることで理解度が変わる</p><p class="bullet-point text-lg">説明に対する反応から相手のタイプを推測できる</p><p class="bullet-point text-lg">複数人への説明は複数のタイプを混ぜると効果的</p></div><div class="mt-4 p-4 bg-blue-50 rounded"><p class="text-base mb-2"><span class="font-bold">実践例:</span></p><p class="text-base">同時系の人（直感・置き換え）: 「結論から言うと〇〇です。たとえば△△のようなものです」</p><p class="text-base mt-2">継次系の人（まとめ・法則）: 「まず①があり、次に②となり、結果③になります。これは〇〇の法則によるものです」</p></div><div class="mt-4"><p class="text-base text-gray-600">コミュニケーションのストレスを減らし、伝わりやすさを向上させるために、相手のタイプに応じた伝え方を意識しましょう。</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .column-title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        font-weight: 700;        padding-bottom: 8px;        border-bottom: 3px solid #3182ce;        margin-bottom: 16px;    }    .bullet-point {        position: relative;        padding-left: 1.75rem;        margin-bottom: 12px;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 8px;        height: 8px;        background-color: #3182ce;        border-radius: 50%;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .column {        padding: 20px;        background-color: #ffffff;        border-radius: 8px;        box-shadow: 0 2px 5px rgba(0,0,0,0.05);        height: 100%;    }    .column-left {        margin-right: 10px;    }    .column-right {        margin-left: 10px;    }    .icon {        color: #3182ce;    }    .type-card {        border-left: 4px solid #3182ce;        padding: 8px 12px;        margin-bottom: 14px;        background-color: #f0f7ff;    }    .ok-text {        color: #2c7a7b;        font-weight: 600;    }    .ng-text {        color: #c53030;        font-weight: 600;    }
</style>
