<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="第6章③: 会議・後輩指導・大量資料の攻略" :current-page="14" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">06</div><h2 class="title text-4xl relative z-10">第6章③: 会議・後輩指導・大量資料の攻略</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側のコンテンツ --><div class="w-2/3 pr-10"><div class="mb-8"><p class="bullet-point text-xl font-bold mb-3"><span class="content-highlight">会議:</span> 決定事項と次アクションをその場で1行化</p><p class="sub-bullet text-lg ml-4 mb-2">会議終了時に1行の議事録を書き、決定事項を明確化</p><p class="sub-bullet text-lg ml-4 mb-5">録音より自分の言葉でまとめることで記憶に定着</p></div><div class="mb-8"><p class="bullet-point text-xl font-bold mb-3"><span class="content-highlight">後輩指導:</span> 質問後"10秒待つ"で思考を引き出す</p><p class="sub-bullet text-lg ml-4 mb-2">質問してすぐ答えを言わず、10秒のルールで待つ</p><p class="sub-bullet text-lg ml-4 mb-5">自分で考える習慣づけと思考の余白をつくる</p></div><div class="mb-8"><p class="bullet-point text-xl font-bold mb-3"><span class="content-highlight">大量資料:</span> チャンクを先に作り、塊で読む</p><p class="sub-bullet text-lg ml-4 mb-2">まず全体を見渡し、見出しでチャンク(塊)を作る</p><p class="sub-bullet text-lg ml-4 mb-5">「何について書かれているか」の予測を立ててから読む</p></div><div><p class="bullet-point text-xl font-bold mb-3"><span class="content-highlight">依頼業務:</span> 期限・期待値・最初の一歩をセットで共有</p><p class="sub-bullet text-lg ml-4 mb-2">「いつまでに」「どのレベルで」「何から始めるか」を明示</p><p class="sub-bullet text-lg ml-4">相手の脳に「わからない」を残さない伝え方を徹底</p></div></div><!-- 右側のイラスト/図 --><div class="w-1/3 flex justify-center items-center"><div class="comm-icon flex flex-col items-center"><i class="fas fa-comments text-8xl mb-4"></i><i class="fas fa-file-alt text-7xl"></i></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .bullet-point {        position: relative;        padding-left: 2rem;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 10px;        height: 10px;        background-color: #3182ce;        border-radius: 50%;    }    .sub-bullet {        position: relative;        padding-left: 1.5rem;    }    .sub-bullet::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 6px;        height: 6px;        background-color: #63b3ed;        border-radius: 50%;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .comm-icon {        color: #3182ce;        opacity: 0.1;    }
</style>
