<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="終章: 再発防止の設計図" :current-page="15" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">終</div><h2 class="title text-4xl relative z-10">終章: 再発防止の設計図</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側のコンテンツ --><div class="w-2/3 pr-10"><div class="mb-8"><p class="text-xl font-bold mb-4"><span class="content-highlight">サイン:</span> 「めんどくさい」再発のシグナル</p><div class="pl-2"><p class="bullet-point text-lg mb-3">後回しにする頻度が増える</p><p class="bullet-point text-lg mb-3">多動・スマホ回避が増える</p><p class="bullet-point text-lg mb-3">「あとで」と言い訳が増える</p></div></div><div class="mb-8"><p class="text-xl font-bold mb-4"><span class="content-highlight">対処:</span> 3段階のリセット法</p><div class="pl-2"><p class="bullet-point text-lg mb-3">最小一歩に戻す → より小さな行動に分解</p><p class="bullet-point text-lg mb-3">環境を再調整 → 道具の位置・手順を見直す</p><p class="bullet-point text-lg mb-3">命令を言い換える → 脳に通じる別の表現を試す</p></div></div><div class="mb-8"><p class="text-xl font-bold mb-4"><span class="content-highlight">メンテ:</span> 習慣の維持方法</p><div class="pl-2"><p class="bullet-point text-lg mb-3">週1回の振り返り時間を設定</p><p class="bullet-point text-lg mb-3">成果・進捗の可視化を更新</p></div></div><div class="mb-6"><p class="text-xl font-bold mb-4"><span class="content-highlight">支え:</span> 継続の原動力</p><div class="pl-2"><p class="bullet-point text-lg mb-3">"つながりの可視化"で報酬系を再起動</p><p class="bullet-point text-lg mb-3">自分の行動が誰かの役に立つ実感を得る</p></div></div></div><!-- 右側のイラスト/図 --><div class="w-1/3 flex justify-center items-center"><div class="recycle-icon"><i class="fas fa-sync-alt text-9xl"></i></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .bullet-point {        position: relative;        padding-left: 2rem;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 10px;        height: 10px;        background-color: #3182ce;        border-radius: 50%;    }    .sub-bullet {        position: relative;        padding-left: 1.5rem;    }    .sub-bullet::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 6px;        height: 6px;        background-color: #63b3ed;        border-radius: 50%;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .recycle-icon {        color: #3182ce;        opacity: 0.1;    }
</style>
