<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="実践Tips集①（朝・仕事）" :current-page="16" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">16</div><h2 class="title text-4xl relative z-10">実践Tips集①（朝・仕事）</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側のコンテンツ --><div class="w-2/3 pr-10"><div class="mb-8"><p class="category-title text-lg font-bold py-2 px-4 mb-4">朝の実践コツ</p><div class="pl-2"><p class="bullet-point text-lg mb-3">就寝前に起床時刻を<span class="content-highlight">3回唱える</span>で脳に予告</p><p class="bullet-point text-lg mb-3">起床後は<span class="content-highlight">カーテン→水→日光</span>の固定ループ化</p><p class="bullet-point text-lg mb-3">「めんどくさい」と思う前に体を動かす（起き上がる）</p></div></div><div class="mb-8"><p class="category-title text-lg font-bold py-2 px-4 mb-4">仕事の効率化</p><div class="pl-2"><p class="bullet-point text-lg mb-3">ネット接続前に<span class="content-highlight">オフラインタスクを1つ</span>終える</p><p class="bullet-point text-lg mb-3">メールは<span class="content-highlight">時間枠</span>を決めてまとめ読み（通知オフ）</p><p class="bullet-point text-lg mb-3">雑談に反応せず姿勢を低くして集中シグナル</p></div></div><div class="mb-8"><p class="category-title text-lg font-bold py-2 px-4 mb-4">会議・中断対策</p><div class="pl-2"><p class="bullet-point text-lg mb-3">会議終了後すぐに<span class="content-highlight">1行だけ</span>議事録を書く</p><p class="bullet-point text-lg mb-3">次の作業の<span class="content-highlight">最初の工程だけ</span>着手して中断</p><p class="bullet-point text-lg mb-3">集中が切れたら<span class="content-highlight">立って10秒歩く</span>でリセット</p></div></div></div><!-- 右側のイラスト/図 --><div class="w-1/3 flex flex-col justify-center items-center"><div class="tips-icon mb-8"><i class="fas fa-lightbulb text-9xl"></i></div><div class="tips-icon mb-8"><i class="fas fa-laptop text-9xl"></i></div><div class="tips-icon"><i class="fas fa-users text-9xl"></i></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .bullet-point {        position: relative;        padding-left: 2rem;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 10px;        height: 10px;        background-color: #3182ce;        border-radius: 50%;    }    .sub-bullet {        position: relative;        padding-left: 1.5rem;    }    .sub-bullet::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 6px;        height: 6px;        background-color: #63b3ed;        border-radius: 50%;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .tips-icon {        color: #3182ce;        opacity: 0.1;    }    .category-title {        font-family: 'M PLUS Rounded 1c', sans-serif;        background-color: #ebf5ff;        border-left: 4px solid #3182ce;    }
</style>
