<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="実践Tips集②（家事・健康）" :current-page="17" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">17</div><h2 class="title text-4xl relative z-10">実践Tips集②（家事・健康）</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側のコンテンツ --><div class="w-2/3 pr-10"><div class="mb-8"><p class="category-title text-xl mb-4">家事の「めんどくさい」解消法</p><div class="pl-2"><p class="bullet-point text-lg mb-3">掃除は<span class="content-highlight">10分だけ</span>、時間で切る習慣をつくる</p><p class="bullet-point text-lg mb-3">片付けは<span class="content-highlight">カテゴリごと</span>に一気に判断し処理</p><p class="bullet-point text-lg mb-3">修理道具は<span class="content-highlight">出しっぱなし</span>で着手障壁を下げる</p><p class="bullet-point text-lg mb-3">洗濯は<span class="content-highlight">天気主導</span>で計画、前夜に仕分け準備</p><p class="bullet-point text-lg mb-3">料理は<span class="content-highlight">切る→焼く→盛る</span>の3工程で段取り練習</p></div></div><div class="mb-4"><p class="category-title text-xl mb-4">健康習慣のコツ</p><div class="pl-2"><p class="bullet-point text-lg mb-3">アイロンがけを<span class="content-highlight">整える時間</span>として活用</p><p class="bullet-point text-lg mb-3">筋トレは<span class="content-highlight">2分だけ</span>を目標に毎日反復</p><p class="bullet-point text-lg mb-3">家事の合間に<span class="content-highlight">簡易ストレッチ</span>を組み込む</p><p class="bullet-point text-lg mb-3">健康データは<span class="content-highlight">毎日同じ時間</span>に確認する習慣化</p></div></div></div><!-- 右側のアイコン --><div class="w-1/3 flex flex-col justify-center items-center"><div class="icon-container mb-8"><i class="fas fa-home text-9xl"></i></div><div class="icon-container"><i class="fas fa-heartbeat text-9xl"></i></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .bullet-point {        position: relative;        padding-left: 2rem;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 10px;        height: 10px;        background-color: #3182ce;        border-radius: 50%;    }    .sub-bullet {        position: relative;        padding-left: 1.5rem;    }    .sub-bullet::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 6px;        height: 6px;        background-color: #63b3ed;        border-radius: 50%;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .icon-container {        color: #3182ce;        opacity: 0.1;    }    .category-title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2b6cb0;        font-weight: 700;        background-color: #ebf4ff;        display: inline-block;        padding: 2px 10px;        border-radius: 4px;    }
</style>
