<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="重要用語集" :current-page="18" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6 z-10"><h2 class="title text-4xl">重要用語集</h2><div class="accent-line mt-3"></div></div><!-- メインコンテンツ部分 - 用語グリッド --><div class="flex-1 px-16 pb-12 z-10"><div class="grid grid-cols-2 gap-6"><!-- チャンク --><div class="term-card p-5"><div class="flex mb-3"><div class="term-icon mr-3"><i class="fas fa-layer-group"></i></div><h3 class="term-title text-xl">チャンク</h3></div><p class="text-gray-700">情報を"塊"で扱い容量効率を上げる。脳には一度に覚えられることが4つという容量の限界があるが、複数の情報をひとまとめにすることで記憶効率が向上する。</p></div><!-- トップダウン注意 --><div class="term-card p-5"><div class="flex mb-3"><div class="term-icon mr-3"><i class="fas fa-bullseye"></i></div><h3 class="term-title text-xl">トップダウン注意</h3></div><p class="text-gray-700">狙いを定めて注目する注意のタイプ。目的を持って意図的に特定の情報に注目することで、効率的に行動や思考を進められる。</p></div><!-- ボトムアップ注意 --><div class="term-card p-5"><div class="flex mb-3"><div class="term-icon mr-3"><i class="fas fa-exclamation-circle"></i></div><h3 class="term-title text-xl">ボトムアップ注意</h3></div><p class="text-gray-700">変化に自動で反応する注意のタイプ。周囲の環境変化に対して無意識的に反応する注意の働き。突然の音や動きに反応するなど、生存に必要な機能。</p></div><!-- ワーキングメモリ --><div class="term-card p-5"><div class="flex mb-3"><div class="term-icon mr-3"><i class="fas fa-memory"></i></div><h3 class="term-title text-xl">ワーキングメモリ</h3></div><p class="text-gray-700">作業中の情報保持と操作を担う脳の機能。一時的に情報を保持しながら処理する能力で、複雑な思考や問題解決に必要。容量に限りがあるため効率的な使用が重要。</p></div><!-- 同時系/継次系 --><div class="term-card p-5"><div class="flex mb-3"><div class="term-icon mr-3"><i class="fas fa-random"></i></div><h3 class="term-title text-xl">同時系/継次系</h3></div><p class="text-gray-700">情報処理スタイルの2類型。同時系は全体像や映像で理解し、継次系は順序立てて理解する。コミュニケーションでは相手のタイプに合わせることが効果的。</p></div><!-- ボトルネック --><div class="term-card p-5"><div class="flex mb-3"><div class="term-icon mr-3"><i class="fas fa-filter"></i></div><h3 class="term-title text-xl">ボトルネック</h3></div><p class="text-gray-700">並行処理で資源が奪い合う現象。マルチタスクを行うと脳内でリソースの競合が発生し、処理速度低下や疲労感につながる。一度に一つのタスクに集中することで回避可能。</p></div><!-- 最近接領域 --><div class="term-card p-5"><div class="flex mb-3"><div class="term-icon mr-3"><i class="fas fa-arrows-alt"></i></div><h3 class="term-title text-xl">最近接領域</h3></div><p class="text-gray-700">少し背伸び課題が学習を促進する考え方。現在のレベルからちょっと難しい課題に取り組むことで、脳が活性化し効率的に成長できる。ヴィゴツキーの発達理論に基づく。</p></div><!-- 報酬系 --><div class="term-card p-5"><div class="flex mb-3"><div class="term-icon mr-3"><i class="fas fa-star"></i></div><h3 class="term-title text-xl">報酬系</h3></div><p class="text-gray-700">行動に価値づけし継続を促す脳内回路。ドーパミンなどの神経伝達物質が関与し、達成感や満足感を得ることで行動継続の動機付けとなる。</p></div></div></div><!-- 背景の脳アイコン --><div class="brain-bg"><i class="fas fa-brain"></i></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .term-card {        background-color: #ffffff;        border-radius: 8px;        box-shadow: 0 2px 5px rgba(0,0,0,0.05);        transition: transform 0.2s;        height: 100%;    }    .term-title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        font-weight: 700;    }    .term-icon {        color: #3182ce;        background-color: #ebf8ff;        border-radius: 50%;        width: 40px;        height: 40px;        display: flex;        justify-content: center;        align-items: center;    }    .brain-bg {        position: absolute;        right: 30px;        bottom: 30px;        font-size: 15rem;        color: #ebf8ff;        z-index: 0;        opacity: 0.2;    }
</style>
