<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="キーセンテンス・要点のまとめ" :current-page="19" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6 z-10"><h2 class="title text-4xl">キーセンテンス・要点のまとめ</h2><div class="accent-line mt-3"></div></div><!-- メインコンテンツ部分 - キーメッセージグリッド --><div class="flex-1 px-16 pb-12 z-10"><div class="grid grid-cols-2 gap-6"><!-- キーセンテンス1 --><div class="term-card p-5"><div class="flex mb-3"><div class="term-icon mr-3"><i class="fas fa-brain"></i></div><h3 class="term-title text-xl">面倒の正体は脳の省エネ反応</h3></div><p class="text-gray-700">「めんどくさい」と感じるのは、「わからない/予測できない」状況に直面したときの脳の本能的な省エネ反応。不確実性を避け、エネルギーを温存しようとする仕組み。</p></div><!-- キーセンテンス2 --><div class="term-card p-5"><div class="flex mb-3"><div class="term-icon mr-3"><i class="fas fa-comment-dots"></i></div><h3 class="term-title text-xl">やる気より設計が重要</h3></div><p class="text-gray-700">性格やモチベーションに頼るのではなく、「脳に通じる命令」の言い換えと環境設計で誰でも行動できる。具体的・即時的・低負荷な指示が脳には効果的。</p></div><!-- キーセンテンス3 --><div class="term-card p-5"><div class="flex mb-3"><div class="term-icon mr-3"><i class="fas fa-shoe-prints"></i></div><h3 class="term-title text-xl">最小の一歩と可視化の力</h3></div><p class="text-gray-700">「最初の一工程だけ」という極小ステップから始め、成果や進捗を視覚化して報酬回路を活性化させる。これにより行動の障壁を下げ、継続を促進できる。</p></div><!-- キーセンテンス4 --><div class="term-card p-5"><div class="flex mb-3"><div class="term-icon mr-3"><i class="fas fa-tasks"></i></div><h3 class="term-title text-xl">単一タスクとチャンク化</h3></div><p class="text-gray-700">マルチタスクを避け、一つずつ作業に集中することで認知コストを削減。情報は塊(チャンク)にまとめて脳の処理容量を効率化。「両手に違う物を持たない」原則。</p></div><!-- キーセンテンス5 --><div class="term-card p-5"><div class="flex mb-3"><div class="term-icon mr-3"><i class="fas fa-sync-alt"></i></div><h3 class="term-title text-xl">再発は想定内の自然現象</h3></div><p class="text-gray-700">「めんどくさい」の再発は想定内。後回し/多動/スマホ回避などのサインを察知したら、最小一歩→環境調整→命令言い換えの3ステップで立て直す。</p></div><!-- キーセンテンス6 --><div class="term-card p-5"><div class="flex mb-3"><div class="term-icon mr-3"><i class="fas fa-users"></i></div><h3 class="term-title text-xl">脳タイプに合わせた伝達</h3></div><p class="text-gray-700">人によって情報処理タイプ（同時系/継次系）が異なる。4つの伝え方（直感/置き換え/まとめ/法則）を使い分け、相手の理解しやすさに合わせることで、コミュニケーション効率が向上する。</p></div></div></div><!-- 背景の脳アイコン --><div class="brain-bg"><i class="fas fa-lightbulb"></i></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .term-card {        background-color: #ffffff;        border-radius: 8px;        box-shadow: 0 2px 5px rgba(0,0,0,0.05);        transition: transform 0.2s;        height: 100%;    }    .term-title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        font-weight: 700;    }    .term-icon {        color: #3182ce;        background-color: #ebf8ff;        border-radius: 50%;        width: 40px;        height: 40px;        display: flex;        justify-content: center;        align-items: center;    }    .brain-bg {        position: absolute;        right: 30px;        bottom: 30px;        font-size: 15rem;        color: #ebf8ff;        z-index: 0;        opacity: 0.2;    }
</style>
