<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="締め: 今日からの3アクション" :current-page="20" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">20</div><h2 class="title text-4xl relative z-10">締め: 今日からの3アクション</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側のコンテンツ --><div class="w-2/3 pr-10"><div class="mb-10"><p class="text-xl font-bold mb-6"><span class="content-highlight">今すぐ実践できる3つのアクション</span></p><div class="pl-2"><p class="bullet-point text-xl mb-6">最初の工程だけ着手し、次の最初を残して止める</p><p class="bullet-point text-xl mb-6">ネット接続前にオフライン作業を1つ終える</p><p class="bullet-point text-xl mb-6">成果が他者につながる可視化（掲示/共有）をつくる</p></div></div><div class="mt-10"><p class="text-lg font-bold mb-3">続け方のポイント:</p><div class="pl-2"><p class="text-lg mb-3">週に1度、命令と環境を<span class="content-highlight">微調整</span>し、"わからない"を減らし続ける</p><p class="text-lg">「めんどくさい」の再発は想定内。合図→最小一歩→環境調整の<span class="content-highlight">サイクル</span>で立て直す</p></div></div></div><!-- 右側のイラスト/図 --><div class="w-1/3 flex justify-center items-center"><div class="action-icon"><i class="fas fa-check-circle text-9xl"></i></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .bullet-point {        position: relative;        padding-left: 2rem;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 10px;        height: 10px;        background-color: #3182ce;        border-radius: 50%;    }    .sub-bullet {        position: relative;        padding-left: 1.5rem;    }    .sub-bullet::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 6px;        height: 6px;        background-color: #63b3ed;        border-radius: 50%;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .action-icon {        color: #3182ce;        opacity: 0.1;    }
</style>
