<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="全体構成（目次）" :current-page="3" :total-pages="20">
<div class="slide flex"><!-- 左側セクション --><div class="slide-left w-1/3 flex flex-col justify-center items-center p-10"><div class="section-number text-6xl mb-4">03</div><h2 class="title text-3xl text-center">全体構成（目次）</h2><div class="accent-line mt-6"></div></div><!-- 右側セクション --><div class="w-2/3 flex flex-col justify-center p-10"><ul class="space-y-4 text-gray-800"><li class="flex"><span class="chapter-number">序章</span><p class="chapter-title">はじめに</p></li><li class="flex"><span class="chapter-number">第1章</span><p class="chapter-title">脳への命令を変えれば、自分を変えられる</p></li><li class="flex"><span class="chapter-number">第2章</span><p class="chapter-title">めんどくさいが消える7つのコツ</p></li><li class="flex"><span class="chapter-number">第3章</span><p class="chapter-title">脳に通じる命令の作り方</p></li><li class="flex"><span class="chapter-number">第4章</span><p class="chapter-title">ビジネスと情報処理のコツ</p></li><li class="flex"><span class="chapter-number">第5章</span><p class="chapter-title">家事・日常生活のめんどくさいが消えるコツ</p></li><li class="flex"><span class="chapter-number">第6章</span><p class="chapter-title">人間関係やコミュニケーションのストレス対策</p></li><li class="flex"><span class="chapter-number">終章</span><p class="chapter-title">一度消せたはずの「めんどくさい」が再発したときの対策</p></li></ul><div class="mt-8 pt-4 border-t border-gray-300"><p class="text-sm text-gray-600">本書は「めんどくさい」の正体を脳科学の視点から解き明かし、科学的に実証された具体的な解決法を提案します。やる気や性格に関係なく、誰でも実践できる方法を章ごとに詳しく解説しています。</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .slide-left {        background-color: #edf2f7;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .section-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        font-weight: 800;    }    .content-heading {        font-weight: 700;        color: #3182ce;    }    .accent-line {        width: 60px;        height: 4px;        background-color: #3182ce;    }    .chapter-number {        color: #3182ce;        font-weight: 700;        width: 50px;        display: inline-block;    }    .chapter-title {        font-weight: 600;    }
</style>
