<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="第1章: 「めんどくさい」の正体と脳の仕組み" :current-page="4" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">01</div><h2 class="title text-4xl relative z-10">第1章: 「めんどくさい」の正体と脳の仕組み</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側のコンテンツ --><div class="w-2/3 pr-10"><div class="mb-8"><p class="text-xl font-bold mb-4"><span class="content-highlight">核心:</span> 動けないのは性格ではなく"脳に通じない命令"のせい</p></div><div class="mb-8"><p class="text-lg font-bold mb-3">脳が面倒を感じやすい条件:</p><div class="pl-2"><p class="bullet-point text-lg mb-3">予測できない/わからない</p><p class="bullet-point text-lg mb-3">ルールや正しさに縛られる</p><p class="bullet-point text-lg mb-3">エネルギーを無駄に使う</p></div></div><div class="mb-8"><p class="text-lg font-bold mb-3">解決の方向性:</p><p class="pl-2 text-lg">脳に通じる命令=<span class="content-highlight">具体・即時・低負荷</span></p></div><div><p class="text-lg font-bold mb-3">セルフチェック:</p><p class="pl-2 text-lg">「脳に通じてる？」リストで現在地を把握</p></div></div><!-- 右側のイラスト/図 --><div class="w-1/3 flex justify-center items-center"><div class="brain-icon"><i class="fas fa-brain text-9xl"></i></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .bullet-point {        position: relative;        padding-left: 2rem;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 10px;        height: 10px;        background-color: #3182ce;        border-radius: 50%;    }    .sub-bullet {        position: relative;        padding-left: 1.5rem;    }    .sub-bullet::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 6px;        height: 6px;        background-color: #63b3ed;        border-radius: 50%;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .brain-icon {        color: #3182ce;        opacity: 0.1;    }
</style>
