<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="第2章①: めんどくさい沼から抜け出せない理由" :current-page="5" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">02</div><h2 class="title text-4xl relative z-10">第2章①: めんどくさい沼の2つの理由</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側のコンテンツ --><div class="w-2/3 pr-10"><div class="mb-8"><p class="text-xl font-bold mb-4"><span class="content-highlight">めんどくさい沼</span>から抜け出せない2つの理由:</p><div class="pl-4 mb-6"><div class="reason-box mb-4"><p class="text-lg font-medium mb-1">1) 怒られ回避の不安に支配される</p><p class="text-base text-gray-600">他者からの評価を過度に気にし、失敗を恐れる</p></div><div class="reason-box"><p class="text-lg font-medium mb-1">2) 面倒を感じた瞬間の回避パターンが固定化</p><p class="text-base text-gray-600">同じ状況で常に同じ逃避行動を取ってしまう</p></div></div></div><div class="mb-6"><p class="text-xl font-bold mb-4">つまずきを外す<span class="content-highlight">3つの考え方</span>:</p><div class="pl-4"><div class="solution-box mb-4"><p class="bullet-point text-lg mb-1">出来栄えは問わない</p><p class="pl-2 text-base text-gray-600">完成度より着手を重視する</p></div><div class="solution-box mb-4"><p class="bullet-point text-lg mb-1">新しいことを増やさない</p><p class="pl-2 text-base text-gray-600">負荷を一定に保ち、脳の予測可能性を維持</p></div><div class="solution-box"><p class="bullet-point text-lg mb-1">OK範囲を広げる</p><p class="pl-2 text-base text-gray-600">合格基準を下げて、行動のハードルを下げる</p></div></div></div></div><!-- 右側のイラスト/図 --><div class="w-1/3 flex justify-center items-center"><div class="swamp-icon"><i class="fas fa-water text-9xl"></i><div class="mt-4 flex justify-center"><i class="fas fa-arrow-circle-up text-8xl"></i></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .bullet-point {        position: relative;        padding-left: 2rem;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 10px;        height: 10px;        background-color: #3182ce;        border-radius: 50%;    }    .sub-bullet {        position: relative;        padding-left: 1.5rem;    }    .sub-bullet::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 6px;        height: 6px;        background-color: #63b3ed;        border-radius: 50%;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .swamp-icon {        color: #3182ce;        opacity: 0.1;    }    .reason-box {        border-left: 4px solid #3182ce;        padding-left: 1rem;    }    .solution-box {        border-left: 4px solid #4c51bf;        padding-left: 1rem;    }
</style>
