<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="第2章②: いきなり動ける7つのコツ" :current-page="6" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">02</div><h2 class="title text-4xl relative z-10">第2章②: いきなり動ける7つのコツ</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側のコンテンツ --><div class="w-full pr-10"><div class="mb-4"><p class="text-xl font-bold mb-4">医療現場・企業研修で実証された<span class="content-highlight">「いきなり行動できる」</span>テクニック</p></div><div class="grid grid-cols-2 gap-x-6 gap-y-4"><div class="numbered-point"><div class="number-circle">1</div><p class="text-lg">最初の一工程だけ着手して中断OK<br/><span class="text-gray-600 text-base">（完璧主義を捨て、着手の壁を下げる）</span></p></div><div class="numbered-point"><div class="number-circle">2</div><p class="text-lg">両手に違う物を持たない<br/><span class="text-gray-600 text-base">（動線を単純化して決断回数を減らす）</span></p></div><div class="numbered-point"><div class="number-circle">3</div><p class="text-lg">その日いちばんやりたいことを先にやる<br/><span class="text-gray-600 text-base">（報酬系を活性化して脳のエネルギーを確保）</span></p></div><div class="numbered-point"><div class="number-circle">4</div><p class="text-lg">ネット接続前にオフライン作業を1つ<br/><span class="text-gray-600 text-base">（集中と達成感を先に確保する）</span></p></div><div class="numbered-point"><div class="number-circle">5</div><p class="text-lg">掃除は10分だけ（時間で切る）<br/><span class="text-gray-600 text-base">（終わりが見える安心感が行動を促進）</span></p></div><div class="numbered-point"><div class="number-circle">6</div><p class="text-lg">片付けはカテゴリ単位で狙い撃ち<br/><span class="text-gray-600 text-base">（意思決定の種類を統一して脳の負担軽減）</span></p></div><div class="numbered-point col-span-2"><div class="number-circle">7</div><p class="text-lg">成果が誰かにつながる可視化をつくる<br/><span class="text-gray-600 text-base">（社会的報酬で行動継続の動機づけを強化）</span></p></div></div><div class="mt-8 bg-blue-50 p-4 rounded-lg"><p class="text-base font-bold text-blue-800">ポイント: <span class="font-normal">これらのコツは「努力や根性に頼らない」「今すぐ実践できる」のが特徴です</span></p></div></div><!-- 右側のイラスト/図 --><div class="w-1/4 flex justify-center items-center"><div class="tips-icon"><i class="fas fa-lightbulb text-9xl"></i></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .bullet-point {        position: relative;        padding-left: 2rem;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 10px;        height: 10px;        background-color: #3182ce;        border-radius: 50%;    }    .numbered-point {        position: relative;        padding-left: 2rem;    }    .number-circle {        position: absolute;        left: 0;        top: 0.2rem;        width: 22px;        height: 22px;        background-color: #3182ce;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        color: white;        font-weight: bold;        font-size: 0.8rem;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .tips-icon {        color: #3182ce;        opacity: 0.15;    }
</style>
