<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="第3章①: 脳に通じる命令の3要素" :current-page="7" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">03</div><h2 class="title text-4xl relative z-10">第3章①: 脳に通じる命令の3要素</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側のコンテンツ --><div class="w-full"><div class="grid grid-cols-3 gap-6 mb-10"><div class="bg-white p-6 rounded-lg shadow-md"><div class="flex justify-center mb-4"><i class="fas fa-sync-alt element-icon text-5xl"></i></div><p class="text-xl font-bold text-center mb-3"><span class="content-highlight">要素1</span> リズムに合わせる</p><p class="text-base">体内時計/日内リズムに同期させることで、脳が自然に行動を起こせるようにする。朝型/夜型など、自分のリズムを知り活用する。</p></div><div class="bg-white p-6 rounded-lg shadow-md"><div class="flex justify-center mb-4"><i class="fas fa-network-wired element-icon text-5xl"></i></div><p class="text-xl font-bold text-center mb-3"><span class="content-highlight">要素2</span> 神経をつなぎ変える</p><p class="text-base">小さな反復で脳内の配線を強化する。新しい習慣は最小単位で始め、少しずつ繰り返すことで定着させる。</p></div><div class="bg-white p-6 rounded-lg shadow-md"><div class="flex justify-center mb-4"><i class="fas fa-hands-helping element-icon text-5xl"></i></div><p class="text-xl font-bold text-center mb-3"><span class="content-highlight">要素3</span> 感覚データを増やす</p><p class="text-base">視覚・触覚・音など複数の感覚を活用して手がかりを増やす。多感覚の情報で脳が行動を自動化しやすくなる。</p></div></div><div class="principle-box p-6 rounded-md"><p class="text-xl font-bold mb-2">脳への命令設計原則:</p><div class="flex space-x-8"><p class="text-lg bullet-point"><span class="content-highlight">具体的</span>な指示（抽象的な指示は脳が混乱する）</p><p class="text-lg bullet-point"><span class="content-highlight">即時</span>の小さなステップ（遠い目標よりも今日の小さな一歩）</p><p class="text-lg bullet-point"><span class="content-highlight">単一タスク</span>（マルチタスクは脳の処理能力を超える）</p></div><p class="text-lg mt-4 italic text-center">これらを組み合わせて"<span class="content-highlight">わからない</span>"状態を消し、行動を自動化する</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .bullet-point {        position: relative;        padding-left: 2rem;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 10px;        height: 10px;        background-color: #3182ce;        border-radius: 50%;    }    .sub-bullet {        position: relative;        padding-left: 1.5rem;    }    .sub-bullet::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 6px;        height: 6px;        background-color: #63b3ed;        border-radius: 50%;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .element-icon {        color: #3182ce;        opacity: 0.8;    }    .principle-box {        background-color: #ebf8ff;        border-left: 4px solid #3182ce;    }
</style>
