<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="第3章②: 習慣化のコツ" :current-page="8" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">03</div><h2 class="title text-4xl relative z-10">第3章②: 習慣化のコツ</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側のコンテンツ --><div class="w-2/3 pr-10"><div class="mb-8"><p class="text-xl font-bold mb-4"><span class="content-highlight">低ハードル戦略</span> - 始めやすく続けやすい習慣設計</p></div><div class="mb-6"><p class="bullet-point text-lg mb-3"><span class="content-highlight">手をつけただけで合格</span>（達成判定を極小化）</p><p class="sub-bullet text-md mb-2 ml-4">完璧を目指さず、開始だけを評価する</p></div><div class="mb-6"><p class="bullet-point text-lg mb-3"><span class="content-highlight">2週間以内にもう一度だけやる</span></p><p class="sub-bullet text-md mb-2 ml-4">「毎日」ではなく「もう一度だけ」と設定し心理的負担を軽減</p></div><div class="mb-6"><p class="bullet-point text-lg mb-3"><span class="content-highlight">作業連結</span>（終わりに次の最初を用意）</p><p class="sub-bullet text-md mb-2 ml-4">片付けを完了せず、次回の開始ポイントを残す工夫</p></div><div class="mb-6"><p class="bullet-point text-lg mb-3"><span class="content-highlight">環境設計</span>（道具をそばに、目に入る位置）</p><p class="sub-bullet text-md mb-2 ml-4">着手障壁を物理的に下げる空間づくり</p></div><div><p class="bullet-point text-lg mb-3"><span class="content-highlight">トリガー選定</span>（時間/場所/行動の合図）</p><p class="sub-bullet text-md mb-2 ml-4">「〇〇の後に必ず」などの行動連鎖をつくる</p></div></div><!-- 右側のイラスト/図 --><div class="w-1/3 flex flex-col justify-center items-center"><div class="habit-icon mb-8"><i class="fas fa-chart-line text-8xl"></i></div><div class="bg-blue-50 p-4 rounded-lg border border-blue-200"><p class="text-lg font-bold mb-2 text-blue-700">実践例</p><p class="text-md mb-2">・朝の1分だけストレッチ</p><p class="text-md mb-2">・メールは1通だけ返信</p><p class="text-md">・書類は1枚だけ整理</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .bullet-point {        position: relative;        padding-left: 2rem;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 10px;        height: 10px;        background-color: #3182ce;        border-radius: 50%;    }    .sub-bullet {        position: relative;        padding-left: 1.5rem;    }    .sub-bullet::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 6px;        height: 6px;        background-color: #63b3ed;        border-radius: 50%;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .habit-icon {        color: #3182ce;        opacity: 0.1;    }
</style>
