<template>
  <SlidePageWrapper slide-id="B0B28R21WJ" page-title="第4章: ビジネスと情報処理のコツ" :current-page="9" :total-pages="20">
<div class="slide flex flex-col"><!-- ヘッダー部分 --><div class="w-full px-16 pt-12 pb-6"><div class="title-container"><div class="chapter-number text-8xl">04</div><h2 class="title text-4xl relative z-10">第4章: ビジネスと情報処理のコツ</h2><div class="accent-line mt-3"></div></div></div><!-- メインコンテンツ部分 --><div class="flex flex-1 px-16 pb-12"><!-- 左側カラム - 原理 --><div class="w-1/2 pr-4"><div class="column column-left flex flex-col h-full"><h3 class="column-title text-2xl">原理</h3><div class="flex items-center mb-4"><div class="icon mr-3"><i class="fas fa-brain text-2xl"></i></div><p class="text-lg"><span class="content-highlight">マルチタスク回避</span> - 脳は並行処理が苦手</p></div><div class="flex items-center mb-4"><div class="icon mr-3"><i class="fas fa-bullseye text-2xl"></i></div><p class="text-lg"><span class="content-highlight">注意の配分</span> - 狙いを定め、変化を検出</p></div><div class="flex items-center mb-4"><div class="icon mr-3"><i class="fas fa-layer-group text-2xl"></i></div><p class="text-lg"><span class="content-highlight">チャンク化</span> - 情報を塊にして処理効率化</p></div><div class="mt-4"><p class="text-base text-gray-600">脳の情報処理は資源を奪い合い、ボトルネックが生じます。一度に扱える情報量には限界があるため、効率化が必要です。</p></div></div></div><!-- 右側カラム - 具体策 --><div class="w-1/2 pl-4"><div class="column column-right"><h3 class="column-title text-2xl">具体策</h3><div><p class="bullet-point text-lg">会議後に1行だけ議事録を作成</p><p class="bullet-point text-lg">依頼・相談は"塊"でまとめて提示</p><p class="bullet-point text-lg">作業は1つずつ進める設定に固定</p><p class="bullet-point text-lg">注意の三段構え（狙い→変化→選択）</p><p class="bullet-point text-lg">チャンクを作ってから資料を読む</p></div><div class="mt-6 p-3 bg-blue-50 rounded"><p class="text-base"><span class="font-bold">Key Point:</span> 「脳が処理できる量を超えない」ことを常に意識し、情報や作業を適切な大きさに区切って扱いましょう。</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;    }    .title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #2c5282;        font-weight: 700;    }    .title-container {        position: relative;    }    .chapter-number {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        opacity: 0.3;        font-weight: 800;        position: absolute;        top: -20px;        left: -10px;        z-index: 0;    }    .content-highlight {        color: #2b6cb0;        font-weight: 700;    }    .column-title {        font-family: 'M PLUS Rounded 1c', sans-serif;        color: #3182ce;        font-weight: 700;        padding-bottom: 8px;        border-bottom: 3px solid #3182ce;        margin-bottom: 16px;    }    .bullet-point {        position: relative;        padding-left: 1.75rem;        margin-bottom: 12px;    }    .bullet-point::before {        content: '';        position: absolute;        left: 0;        top: 0.5rem;        width: 8px;        height: 8px;        background-color: #3182ce;        border-radius: 50%;    }    .accent-line {        width: 100px;        height: 4px;        background-color: #3182ce;    }    .column {        padding: 20px;        background-color: #ffffff;        border-radius: 8px;        box-shadow: 0 2px 5px rgba(0,0,0,0.05);        height: 100%;    }    .column-left {        margin-right: 10px;    }    .column-right {        margin-left: 10px;    }    .icon {        color: #3182ce;    }
</style>
