<template>
  <SlidePageWrapper slide-id="B09QG8RT8B" page-title="" :current-page="1" :total-pages="21">
<div id='slide'><div class='bg-overlay'></div><div class='decoration-element decoration-1'></div><div class='decoration-element decoration-2'></div><div class='decoration-element decoration-3'></div><div class='gradient-overlay'></div><div class='content-container'><h1 class='main-title'>コンセプチュアル思考</h1><p class='subtitle'>物事の本質を見極め、解釈し、獲得する</p><p class='text-gradient subtitle'>知・情・意を統合し、概念を起こし、世界観をつくる</p><p class='author'>村山 昇 著</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      min-height: 720px;      font-family: 'Noto Serif JP', serif;    }    #slide {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background: linear-gradient(135deg, #1e3a8a 0%, #1e40af 50%, #3b82f6 100%);      position: relative;      overflow: hidden;      color: white;    }    .bg-overlay {      position: absolute;      top: 0;      left: 0;      right: 0;      bottom: 0;      background: radial-gradient(circle at 30% 70%, rgba(59, 130, 246, 0.3) 0%, transparent 50%);    }    .content-container {      position: relative;      z-index: 10;      flex: 1;      display: flex;      flex-direction: column;      justify-content: center;      align-items: center;      padding: 60px 40px;    }    .main-title {      font-size: 64px;      font-weight: 700;      margin-bottom: 20px;      text-align: center;      letter-spacing: 0.05em;      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);      line-height: 1.2;    }    .subtitle {      font-size: 24px;      font-weight: 400;      margin-bottom: 40px;      text-align: center;      opacity: 0.9;      letter-spacing: 0.1em;    }    .author {      font-size: 20px;      font-weight: 500;      text-align: center;      opacity: 0.8;      margin-top: 40px;      letter-spacing: 0.1em;    }    .decoration-element {      position: absolute;      border: 2px solid rgba(255, 255, 255, 0.2);      border-radius: 50%;    }    .decoration-1 {      width: 200px;      height: 200px;      top: -100px;      right: -100px;      animation: float 6s ease-in-out infinite;    }    .decoration-2 {      width: 150px;      height: 150px;      bottom: -75px;      left: -75px;      animation: float 8s ease-in-out infinite reverse;    }    .decoration-3 {      width: 100px;      height: 100px;      top: 50%;      left: 50px;      transform: translateY(-50%);      animation: float 10s ease-in-out infinite;    }    @keyframes float {      0%, 100% { transform: translateY(0px) rotate(0deg); }      50% { transform: translateY(-20px) rotate(180deg); }    }    .gradient-overlay {      position: absolute;      bottom: 0;      left: 0;      right: 0;      height: 200px;      background: linear-gradient(to top, rgba(30, 58, 138, 0.8) 0%, transparent 100%);    }    .text-gradient {      background: linear-gradient(45deg, #fbbf24, #fef3c7);      -webkit-background-clip: text;      -webkit-text-fill-color: transparent;      background-clip: text;    }
</style>
