<template>
  <SlidePageWrapper slide-id="B09QG8RT8B" page-title="" :current-page="18" :total-pages="21">
<div id='slide'><div class='header'><h1 class='title'>キーセンテンス（まとめの抜粋）</h1></div><div class='content-wrapper'><div class='grid-container'><div class='key-box concept-box'><div class='highlight-number'>1</div><h3 class='key-title'><i class='fas fa-lightbulb icon'></i>コンセプチュアル思考の本質</h3><p class='key-content'><strong>コンセプチュアル思考は'在り方'を定め、手段を選ばせる</strong> - 目的と手段を逆転させず、本質から問う</p></div><div class='key-box concept-box'><div class='highlight-number'>2</div><h3 class='key-title'><i class='fas fa-eye icon'></i>主観の重要性</h3><p class='key-content'><strong>客観を超える主観が、独自の世界観を生む</strong> - ニーチェ：「事実はなく、解釈があるのみ」</p></div><div class='key-box abstraction-box'><div class='highlight-number'>3</div><h3 class='key-title'><i class='fas fa-arrows-alt-h icon'></i>抽象と具体の関係</h3><p class='key-content'><strong>抽象と具体の往復幅が、認知を深める</strong> - ハンモック・モデルで思考を深化させる</p></div><div class='key-box abstraction-box'><div class='highlight-number'>4</div><h3 class='key-title'><i class='fas fa-level-up-alt icon'></i>概念の深化</h3><p class='key-content'><strong>概念・観念・信念・理念へと芯を高める</strong> - 共通理解から個人の強い軸へ</p></div><div class='key-box business-box'><div class='highlight-number'>5</div><h3 class='key-title'><i class='fas fa-rocket icon'></i>事業における応用</h3><p class='key-content'><strong>改良ではなく'概念の転換'が市場を動かす</strong> - 郵便馬車をつらねても鉄道は生まれない</p></div><div class='key-box business-box'><div class='highlight-number'>6</div><h3 class='key-title'><i class='fas fa-target icon'></i>目的の定義</h3><p class='key-content'><strong>目標は数値、目的は意味。利益は条件、価値創出が目的</strong> - ドラッカー：「利益は条件であって目的ではない」</p></div><div class='key-box business-box'><div class='highlight-number'>7</div><h3 class='key-title'><i class='fas fa-sync-alt icon'></i>事業の再定義</h3><p class='key-content'><strong>事業は'何を売るか'ではなく'何として売るか'で再定義</strong> - アズ・ア・モデルで価値の枠組みを変える</p></div><div class='key-box integration-box'><div class='highlight-number'>8</div><h3 class='key-title'><i class='fas fa-puzzle-piece icon'></i>知・情・意の融合</h3><p class='key-content'><strong>知×情×意＝分厚い思考。直観→論理で構築する</strong> - 福井謙一：「まず直観が働き、そこから論理が構築されていく」</p></div><div class='key-box integration-box'><div class='highlight-number'>9</div><h3 class='key-title'><i class='fas fa-balance-scale icon'></i>調和の重要性</h3><p class='key-content'><strong>夏目漱石：「智に働けば角が立つ。情に棹させば流される。意地を通せば窮屈だ。」</strong> - 三つを調和させてこそ</p></div></div></div><div class='footer'>コンセプチュアル思考 - 村山昇 著</div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html { margin: 0; padding: 0; }    #slide {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;      color: #2d3748;    }    .header {      background: linear-gradient(135deg, #1a365d 0%, #2c5282 100%);      padding: 24px 40px;      color: white;    }    .title {      font-family: 'Noto Serif JP', serif;      font-size: 32px;      font-weight: 700;    }    .content-wrapper {      flex: 1;      padding: 24px 40px;    }    .grid-container {      display: grid;      grid-template-columns: repeat(4, 1fr);      gap: 16px;      height: 100%;    }    .key-box {      border-radius: 12px;      padding: 20px;      position: relative;      overflow: hidden;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);    }    .key-box::before {      content: '';      position: absolute;      top: 0;      left: 0;      width: 6px;      height: 100%;    }    .concept-box {      background-color: #ebf8ff;      border-left: 6px solid #3182ce;    }    .abstraction-box {      background-color: #fefcbf;      border-left: 6px solid #d69e2e;    }    .business-box {      background-color: #e9f5e9;      border-left: 6px solid #38a169;    }    .integration-box {      background-color: #fee2e2;      border-left: 6px solid #e53e3e;    }    .key-title {      font-size: 16px;      font-weight: 700;      color: #1a365d;      margin-bottom: 10px;      display: flex;      align-items: center;      font-family: 'Noto Serif JP', serif;    }    .key-content {      font-size: 15px;      line-height: 1.5;      font-weight: 500;    }    .key-content strong {      color: #1a365d;      font-weight: 700;    }    .icon {      margin-right: 8px;      font-size: 18px;    }    .highlight-number {      position: absolute;      top: 10px;      right: 10px;      background-color: white;      color: #1a365d;      width: 24px;      height: 24px;      border-radius: 50%;      display: flex;      align-items: center;      justify-content: center;      font-size: 12px;      font-weight: 700;    }    .footer {      padding: 15px 40px;      font-size: 14px;      color: #718096;      text-align: right;      background-color: #f8f9fa;    }
</style>
