<template>
  <SlidePageWrapper slide-id="B09QG8RT8B" page-title="" :current-page="2" :total-pages="21">
<div id='slide'><div class='header'><h1 class='title'>この本は何か / 対象読者 / 得られる変化</h1><p class='subtitle'>コンセプチュアル思考 - 物事の本質を見極め、解釈し、獲得する</p></div><div class='content-wrapper'><div class='section-container'><div class='section'><div class='section-title'><div class='section-icon'><i class='fas fa-compass'></i></div><div class='section-title-text'>位置づけ</div></div><div class='section-content'><ul><li>VUCA時代に必要な<span class='accent-color'>「意の思考」</span>を体系化</li><li>ロジカル思考（知）やデザイン思考（情）を超える第三の思考法</li><li><span class='accent-color'>本質・意味・価値</span>を捉え、創造する力を鍛える</li><li>直観→論理の順で考える思考プロセスの提案</li></ul></div></div><div class='section'><div class='section-title'><div class='section-icon'><i class='fas fa-users'></i></div><div class='section-title-text'>対象読者</div></div><div class='section-content'><ul><li>業界・職種・年次不問のビジネスパーソン</li><li>企画・新規事業・プロダクト開発・経営・人事担当者</li><li>キャリア自律を求める個人</li><li>「自分らしさ」と「組織での存在意義」を模索する人</li></ul></div></div><div class='section'><div class='section-title'><div class='section-icon'><i class='fas fa-exclamation-triangle'></i></div><div class='section-title-text'>背景</div></div><div class='section-content'><ul><li>製品・サービスのコモディティ化が進行</li><li>消費者データへの過度な依存</li><li>他社事例の過剰模倣による均質化</li><li>「<span class='accent-color'>知・情</span>」への偏重と「<span class='accent-color'>意</span>」の軽視</li></ul></div></div><div class='section'><div class='section-title'><div class='section-icon'><i class='fas fa-chart-line'></i></div><div class='section-title-text'>読後の変化</div></div><div class='section-content'><ul><li>自分の言葉で本質を定義し直せる</li><li>独自の概念で世界観を提示できる</li><li>目的から手段を選ぶ思考ができる</li><li><span class='accent-color'>知・情・意</span>の分厚い思考ができる</li></ul></div></div></div></div><div class='decoration-circle'></div><div class='decoration-dots'></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html { margin: 0; padding: 0; }    #slide {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;      color: white;    }    .header {      padding: 30px 40px;      text-align: center;      position: relative;      z-index: 10;    }    .title {      font-family: 'Noto Serif JP', serif;      font-size: 40px;      font-weight: 700;      margin-bottom: 8px;      text-shadow: 2px 2px 4px rgba(0,0,0,0.3);    }    .subtitle {      font-size: 18px;      opacity: 0.9;      font-weight: 300;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 0 40px 30px;      position: relative;      z-index: 10;    }    .section-container {      display: flex;      gap: 20px;      flex: 1;    }    .section {      flex: 1;      background: rgba(255, 255, 255, 0.1);      backdrop-filter: blur(10px);      border-radius: 16px;      padding: 24px;      border: 1px solid rgba(255, 255, 255, 0.2);      transition: transform 0.3s ease;    }    .section:hover {      transform: translateY(-5px);    }    .section-title {      display: flex;      align-items: center;      margin-bottom: 16px;    }    .section-icon {      width: 48px;      height: 48px;      display: flex;      align-items: center;      justify-content: center;      border-radius: 12px;      background: rgba(255, 255, 255, 0.2);      margin-right: 16px;      font-size: 20px;    }    .section-title-text {      font-family: 'Noto Serif JP', serif;      font-size: 20px;      font-weight: 700;    }    .section-content {      font-size: 15px;      line-height: 1.7;      opacity: 0.95;    }    .section-content ul {      padding-left: 0;      margin: 0;      list-style: none;    }    .section-content li {      margin-bottom: 8px;      padding-left: 20px;      position: relative;    }    .section-content li::before {      content: '▸';      position: absolute;      left: 0;      color: #fbbf24;      font-weight: bold;    }    .section-content li:last-child {      margin-bottom: 0;    }    .accent-color {      color: #fbbf24;      font-weight: 500;    }    .decoration {      position: absolute;      z-index: 1;    }    .decoration-circle {      width: 300px;      height: 300px;      border: 3px solid rgba(255, 255, 255, 0.1);      border-radius: 50%;      position: absolute;      top: -150px;      right: -150px;    }    .decoration-dots {      width: 100px;      height: 100px;      background: radial-gradient(circle, rgba(255, 255, 255, 0.1) 1px, transparent 1px);      background-size: 20px 20px;      position: absolute;      bottom: 20px;      left: 20px;      opacity: 0.5;    }
</style>
