<template>
  <SlidePageWrapper slide-id="B09QG8RT8B" page-title="" :current-page="5" :total-pages="21">
<div id='slide'><div class='header'><h1 class='title'>第1章(2) コンセプチュアル思考とは</h1></div><div class='decoration-line'></div><div class='content-wrapper'><div class='highlight-box'><h2 class='highlight-title'>コンセプチュアル思考の定義</h2><p class='highlight-text'>  ものごとの本質を引き抜き、概念・原理・価値の枠組みをつかみ、意味を構築する力。「つかむ・内に取り込む」という語源から、物事の奥にひそむ本質を見出し、独自の世界観をつくり出す思考。</p></div><div class='card-grid'><div class='card'><h3 class='card-title'><i class='fas fa-lightbulb'></i>客観を超える主観</h3><p class='card-content'>分析や他社事例だけでなく、自分なりの解釈や意味づけを重視。独自の視点から物事を捉え直す。</p></div><div class='card'><h3 class='card-title'><i class='fas fa-brain'></i>直観→論理の順</h3><p class='card-content'>福井謙一が指摘したように「まず直観が働き、そこから論理が構築される」思考プロセス。</p></div><div class='card'><h3 class='card-title'><i class='fas fa-compass'></i>「在り方」次元での定義</h3><p class='card-content'>自分や事業の本質的存在意義を問い直し、そこから手段を選ぶ。目的から手段を決める。</p></div><div class='card'><h3 class='card-title'><i class='fas fa-globe'></i>独自の概念や世界観</h3><p class='card-content'>強い意志や哲学、世界観を伴った視点で事業や製品を捉え直す。独自の価値軸を構築する。</p></div></div><div class='bullet-section'><h2 class='section-title'>現代における必要性</h2><div class='grid grid-cols-2 gap-4'><div class='icon-feature'><i class='fas fa-chart-line'></i><span>コモディティ化の打破：分析と改良だけでは「早晩、コモディティ化による持久戦」に陥る</span></div><div class='icon-feature'><i class='fas fa-cogs'></i><span>均質化からの脱却：消費者テストや競合分析だけでは、個性を失った同質的な製品・サービスが生まれる</span></div><div class='icon-feature'><i class='fas fa-shield-alt'></i><span>VUCA時代の羅針盤：不安定で不確実な時代だからこそ、主観的な軸が必要になる</span></div><div class='icon-feature'><i class='fas fa-user'></i><span>人間中心のイノベーション：技術中心ではなく、人間の本質的欲求や価値に根ざした革新を生み出す</span></div></div></div><div class='quote'><p>「結局、突拍子もないようなところから生まれた新しい学問というのは、結論をある事柄から論理的に導けるという性質のものではないのです。では、何をもって新しい理論が生まれてくるのか。それは直観です。まず、直観が働き、そこから論理が構築されていく。」</p><p class='quote-author'>— 福井謙一（ノーベル化学賞受賞者）</p></div></div><div class='footer'>コンセプチュアル思考 - 村山昇 著</div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;    }    #slide {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: #f8f9fa;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;      color: #2d3748;    }    .header {      background-color: #1a365d;      padding: 20px 40px;      color: white;    }    .title {      font-family: 'Noto Serif JP', serif;      font-size: 32px;      font-weight: 700;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 30px 40px;      justify-content: center;    }    .card-grid {      display: grid;      grid-template-columns: 1fr 1fr;      gap: 20px;      margin-bottom: 20px;    }    .card {      background: white;      border-radius: 8px;      padding: 20px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);      border-left: 4px solid #e2725b;    }    .card-title {      font-size: 18px;      font-weight: 700;      color: #1a365d;      margin-bottom: 12px;      display: flex;      align-items: center;    }    .card-title i {      margin-right: 8px;      color: #e2725b;    }    .card-content {      font-size: 14px;      line-height: 1.6;      color: #4a5568;    }    .highlight-box {      background: linear-gradient(135deg, #f0f5ff 0%, #e0e7ff 100%);      border: 2px solid #3182ce;      border-radius: 12px;      padding: 24px;      margin-bottom: 20px;      text-align: center;    }    .highlight-title {      font-size: 24px;      font-weight: 700;      color: #2c5282;      margin-bottom: 12px;      font-family: 'Noto Serif JP', serif;    }    .highlight-text {      font-size: 16px;      color: #2d3748;      line-height: 1.7;    }    .footer {      padding: 15px 40px;      font-size: 14px;      color: #718096;      text-align: right;      background-color: #f8f9fa;    }    .decoration-line {      width: 100%;      height: 4px;      background-color: #e2725b;      position: absolute;      top: 80px;      z-index: 5;    }    .highlight {      font-weight: 500;      color: #1a365d;    }    .icon-feature {      display: flex;      align-items: center;      margin-bottom: 12px;    }    .icon-feature i {      color: #3182ce;      margin-right: 8px;      font-size: 16px;    }    .icon-feature span {      font-size: 14px;      color: #4a5568;    }
</style>
