<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="第4章：ワンルームで作る10プレイス例" :current-page="11" :total-pages="20">
<div class="slide-container"><div class="left-panel"><h1 class="text-3xl font-bold mb-6">第4章：ワンルームで作る10プレイス例</h1><p class="text-lg opacity-80 mt-4">場所法の実践的活用法</p><div class="brain-pattern"><i class="fas fa-home"></i></div></div><div class="right-panel"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-map-marker-alt"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">例（順路）</p><div class="room-map"><p class="text-lg mt-1">①玄関 → ②靴箱 → ③キッチン → ④冷蔵庫 → ⑤流し → ⑥テーブル → ⑦ソファ → ⑧テレビ → ⑨本棚 → ⑩ベッド</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-walking"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">使い方</p><p class="text-lg mt-1">各プレイスに強いイメージで配置 → 頭の中で見取り図を「歩く」ように順番にたどる → 各場所に置いたイメージを回収</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-expand-arrows-alt"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">拡張</p><p class="text-lg mt-1">10→20→100プレイスへ段階的に増やす / 自宅・会社・通学路など複数ルートを用意して使い分ける / 1つのプレイスを細分化して容量を増やす</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-exclamation-triangle"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">注意</p><p class="text-lg mt-1">同じルートに別内容を連続で置くと"ゴースト"（過去のイメージが残る現象）が発生 → 時間間隔を空ける（一晩程度）/ 別ルートを使い分けるなどの対策を</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .left-panel {      width: 30%;      background-color: #1a365d;      color: white;      padding: 40px;      display: flex;      flex-direction: column;      justify-content: center;      position: relative;    }    .right-panel {      width: 70%;      padding: 60px 50px;      display: flex;      flex-direction: column;      justify-content: center;    }    .bullet-item {      display: flex;      align-items: flex-start;      margin-bottom: 25px;    }    .bullet-icon {      font-size: 24px;      margin-right: 15px;      color: #2b6cb0;      flex-shrink: 0;      margin-top: 2px;    }    .bullet-text {      flex: 1;    }    .brain-pattern {      position: absolute;      bottom: 20px;      right: 20px;      font-size: 100px;      opacity: 0.1;    }    .room-map {      border: 2px dashed #2b6cb0;      padding: 15px;      margin-top: 10px;      border-radius: 5px;    }
</style>
