<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="第5章：数字記憶の実践（16桁など）" :current-page="13" :total-pages="20">
<div class="slide-container"><div class="left-panel"><h1 class="text-3xl font-bold mb-6">第5章：数字記憶の実践（16桁など）</h1><p class="text-lg opacity-80 mt-4">数字を効率的に覚えるための実践手順</p><div class="brain-pattern"><i class="fas fa-calculator"></i></div></div><div class="right-panel"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-tasks"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">記憶の基本手順</p><p class="text-lg mt-1">数字→イメージ変換→プレイス配置→ストーリー化→想起の流れで確実に記憶</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-th-large"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">クレジットカード番号の実例</p><p class="text-lg mt-1">16桁は4ブロック（4桁×4）に分割→各プレイスに配置／チェック桁は色や動作で強調</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-exclamation-triangle"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">エラー対策</p><p class="text-lg mt-1">似たイメージの衝突を避ける（2と7など）／ブロック境界を明確化（動作や色で区切る）</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-sync-alt"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">復習サイクル</p><p class="text-lg mt-1">直後→翌日→1週間の間隔で再生速度と正確さを計測／7回の反復で長期記憶へ</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .left-panel {      width: 30%;      background-color: #1a365d;      color: white;      padding: 40px;      display: flex;      flex-direction: column;      justify-content: center;      position: relative;    }    .right-panel {      width: 70%;      padding: 60px 50px;      display: flex;      flex-direction: column;      justify-content: center;    }    .bullet-item {      display: flex;      align-items: flex-start;      margin-bottom: 25px;    }    .bullet-icon {      font-size: 24px;      margin-right: 15px;      color: #2b6cb0;      flex-shrink: 0;      margin-top: 2px;    }    .bullet-text {      flex: 1;    }    .brain-pattern {      position: absolute;      bottom: 20px;      right: 20px;      font-size: 100px;      opacity: 0.1;    }
</style>
