<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="第6章：タグ付け法（顔と名前）—基本" :current-page="14" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">第6章：タグ付け法（顔と名前）—基本</h1></div><div class="content"><div class="steps-container"><div class="step-box"><div class="step-number">STEP 1</div><div class="step-title">観察</div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>顔・髪・服装・声などから<strong>強い特徴</strong>を一言タグ化</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>印象的な部分に注目し、記憶に残りやすい要素を選ぶ</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>例：「眼鏡の人」「赤いネクタイの人」「笑顔が素敵な人」</p></div></div></div><div class="arrow-container"><div class="arrow-icon"><i class="fas fa-long-arrow-alt-right"></i></div></div><div class="step-box"><div class="step-number">STEP 2</div><div class="step-title">連結</div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>タグと氏名/肩書/会社名を<strong>ストーリー</strong>で結ぶ</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>名前の音韻や意味からイメージを作る</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>例：「高橋さん（タグ：髭）→髭が高い橋にかかっている」</p></div></div></div><div class="arrow-container"><div class="arrow-icon"><i class="fas fa-long-arrow-alt-right"></i></div></div><div class="step-box"><div class="step-number">STEP 3</div><div class="step-title">想起</div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>再会時に<strong>タグ→ストーリー→氏名</strong>の順で取り出す</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>ストーリーを頭の中で再生して名前を思い出す</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>例：「あの髭の人→髭と橋のストーリー→高橋さん！」</p></div></div></div></div><div class="mt-8 bg-blue-50 p-4 rounded-lg border border-blue-200"><p class="font-bold text-lg text-blue-800 mb-2">タグ付け法のコツと応用</p><div class="flex"><div class="w-1/2 pr-4"><p class="mb-2"><i class="fas fa-lightbulb text-amber-600 mr-2"></i><strong>複数タグ：</strong>一人に複数のタグを付けて記憶を強化</p><p class="mb-2"><i class="fas fa-lightbulb text-amber-600 mr-2"></i><strong>逆算ストーリー：</strong>名前からタグに向かって連想</p></div><div class="w-1/2 pl-4 border-l border-blue-200"><p class="mb-2"><i class="fas fa-lightbulb text-amber-600 mr-2"></i><strong>相手に興味：</strong>会話で確認しながら記憶を定着</p><p class="mb-2"><i class="fas fa-lightbulb text-amber-600 mr-2"></i><strong>外国名：</strong>音の連想・語感や発音の特徴を利用</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .header {      padding: 30px 50px 10px;      background-color: #1a365d;      color: white;    }    .content {      flex: 1;      display: flex;      flex-direction: column;      padding: 30px 50px;    }    .steps-container {      display: flex;      justify-content: space-between;      margin-top: 20px;      flex-wrap: wrap;    }    .step-box {      width: 30%;      border: 2px solid #2b6cb0;      border-radius: 15px;      padding: 20px;      position: relative;      background-color: white;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);      margin-bottom: 20px;    }    .step-number {      position: absolute;      top: -20px;      left: 30px;      background-color: #2b6cb0;      color: white;      font-weight: bold;      padding: 5px 20px;      border-radius: 20px;      font-size: 18px;    }    .step-title {      margin-top: 10px;      font-size: 22px;      font-weight: bold;      color: #2b6cb0;      margin-bottom: 15px;    }    .arrow-container {      display: flex;      align-items: center;      justify-content: center;      width: 5%;    }    .arrow-icon {      font-size: 24px;      color: #2b6cb0;    }    .tips-box {      margin-top: 30px;      background-color: rgba(43, 108, 176, 0.1);      border-left: 5px solid #2b6cb0;      padding: 15px 20px;      width: 100%;    }    .point-item {      display: flex;      align-items: flex-start;      margin-bottom: 12px;    }    .point-icon {      color: #2b6cb0;      margin-right: 10px;      margin-top: 5px;      flex-shrink: 0;    }
</style>
