<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="第6章：顔と名前の記憶—実践のコツ" :current-page="15" :total-pages="20">
<div class="slide-container"><div class="left-panel"><h1 class="text-3xl font-bold mb-6">第6章：顔と名前の記憶—実践のコツ</h1><p class="text-lg opacity-80 mt-4">タグ付け法の実践応用</p><div class="brain-pattern"><i class="fas fa-id-card"></i></div></div><div class="right-panel"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-handshake"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">初対面フロー</p><p class="text-lg mt-1">観察→タグ化→名前を復唱→ストーリー連結→会話中に再想起</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-building"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">併せて覚える</p><p class="text-lg mt-1">会社名・部署・肩書は場所法の小ルートで管理</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-language"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">外国名/難読名</p><p class="text-lg mt-1">音の連想・語感（ダジャレ）・スペルの形でタグ化</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-sync-alt"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">忘れた時</p><p class="text-lg mt-1">正直に確認しつつ、タグを増やして再連結</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .left-panel {      width: 30%;      background-color: #1a365d;      color: white;      padding: 40px;      display: flex;      flex-direction: column;      justify-content: center;      position: relative;    }    .right-panel {      width: 70%;      padding: 60px 50px;      display: flex;      flex-direction: column;      justify-content: center;    }    .bullet-item {      display: flex;      align-items: flex-start;      margin-bottom: 25px;    }    .bullet-icon {      font-size: 24px;      margin-right: 15px;      color: #2b6cb0;      flex-shrink: 0;      margin-top: 2px;    }    .bullet-text {      flex: 1;    }    .brain-pattern {      position: absolute;      bottom: 20px;      right: 20px;      font-size: 100px;      opacity: 0.1;    }
</style>
