<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="第7章：日常応用①（生活・仕事）" :current-page="16" :total-pages="20">
<div class="slide-container"><div class="left-panel"><h1 class="text-3xl font-bold mb-6">第7章：日常応用①（生活・仕事）</h1><p class="text-lg opacity-80 mt-4">記憶術を身近に活かす</p><div class="brain-pattern"><i class="fas fa-brain"></i></div></div><div class="right-panel"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-shopping-basket"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">買い物リスト</p><p class="text-lg mt-1">キッチンのルートに食材を配置：冷蔵庫→シンク→調理台→オーブンなど、各場所に商品をイメージで置いていく</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-tasks"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">ToDo/手順</p><p class="text-lg mt-1">机周りのルートで開始→終了の流れを固定：デスク→本棚→プリンター→窓など、作業順に配置すると忘れにくい</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-utensils"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">冷蔵庫の中身/昨日の夕飯</p><p class="text-lg mt-1">場所法で時系列を再構成：冷蔵庫の棚を上から順にプレイスとして、食材や料理を配置して記憶</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-microphone"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">スピーチ/プレゼン</p><p class="text-lg mt-1">各章トピックを部屋ごとに割振り：自宅の各部屋に発表内容を配置し、頭の中で「家の中の散歩」をしながら想起</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .left-panel {      width: 30%;      background-color: #1a365d;      color: white;      padding: 40px;      display: flex;      flex-direction: column;      justify-content: center;      position: relative;    }    .right-panel {      width: 70%;      padding: 60px 50px;      display: flex;      flex-direction: column;      justify-content: center;    }    .bullet-item {      display: flex;      align-items: flex-start;      margin-bottom: 25px;    }    .bullet-icon {      font-size: 24px;      margin-right: 15px;      color: #2b6cb0;      flex-shrink: 0;      margin-top: 2px;    }    .bullet-text {      flex: 1;    }    .brain-pattern {      position: absolute;      bottom: 20px;      right: 20px;      font-size: 100px;      opacity: 0.1;    }
</style>
