<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="第7章：日常応用②（学習・資格・語彙）" :current-page="17" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">第7章：日常応用②（学習・資格・語彙）</h1></div><div class="content"><div class="steps-container"><div class="step-box"><div class="step-number">STEP 1</div><div class="step-title">用語/英単語の意味をイメージ化</div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>言葉を具体的な<strong>視覚イメージ</strong>に変換</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>抽象的な概念も関連する物や動作で具体化</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>例：「inflation（インフレ）」→「膨らむ風船」</p></div></div></div><div class="step-box"><div class="step-number">STEP 2</div><div class="step-title">タグや連想で意味の勘どころを付与</div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>単語の<strong>音や形</strong>から連想される日本語を結びつける</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>単語の特徴を捉えたタグを設定（接頭語・語源など）</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>例：「catastrophe」→「猫（cat）が座る（sit）大惨事」</p></div></div></div><div class="step-box"><div class="step-number">STEP 3</div><div class="step-title">場所法で章・単元ごとにルート管理</div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>教科書や参考書の<strong>章ごとに別ルート</strong>を設定</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>各単元をプレイスに順番に配置（目次構造に対応）</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>例：英単語集の各カテゴリに自宅の各部屋を割り当て</p></div></div></div><div class="step-box"><div class="step-number">STEP 4</div><div class="step-title">復習スケジュール</div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>間隔反復法に基づく<strong>計画的な復習</strong></p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>翌日→3日後→7日後→28日後の4段階で復習</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>各復習時は「ルートを歩き、自分でイメージを想起」</p></div></div></div></div><div class="application-box"><p class="font-bold text-lg text-blue-800 mb-2"><i class="fas fa-lightbulb mr-2"></i>応用例：多様な学習分野への展開</p><div class="flex"><div class="w-1/2 pr-4"><p class="mb-2"><i class="fas fa-check-circle text-blue-700 mr-2"></i>歴史年号：場所法+ストーリー（出来事→年号）</p><p class="mb-2"><i class="fas fa-check-circle text-blue-700 mr-2"></i>数学・物理の公式：イメージ→場所法で公式を視覚化</p></div><div class="w-1/2 pl-4 border-l border-blue-200"><p class="mb-2"><i class="fas fa-check-circle text-blue-700 mr-2"></i>医学：症状→所見→対応のチェーン記憶</p><p class="mb-2"><i class="fas fa-check-circle text-blue-700 mr-2"></i>資格試験：法律条文や専門用語をストーリー化</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .header {      padding: 30px 50px 10px;      background-color: #1a365d;      color: white;    }    .content {      flex: 1;      display: flex;      flex-direction: column;      padding: 20px 50px;    }    .steps-container {      display: grid;      grid-template-columns: 1fr 1fr;      grid-gap: 20px;      margin-top: 10px;    }    .step-box {      border: 2px solid #2b6cb0;      border-radius: 15px;      padding: 15px;      position: relative;      background-color: white;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);    }    .step-number {      position: absolute;      top: -15px;      left: 30px;      background-color: #2b6cb0;      color: white;      font-weight: bold;      padding: 4px 15px;      border-radius: 20px;      font-size: 16px;    }    .step-title {      margin-top: 10px;      font-size: 20px;      font-weight: bold;      color: #2b6cb0;      margin-bottom: 10px;    }    .point-item {      display: flex;      align-items: flex-start;      margin-bottom: 8px;    }    .point-icon {      color: #2b6cb0;      margin-right: 10px;      margin-top: 5px;      flex-shrink: 0;    }    .tips-box {      margin-top: 20px;      background-color: rgba(43, 108, 176, 0.1);      border-left: 5px solid #2b6cb0;      padding: 10px 15px;    }    .application-box {      margin-top: 20px;      background-color: #ebf4ff;      border: 1px solid #2b6cb0;      border-radius: 15px;      padding: 15px 20px;    }
</style>
