<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="重要用語・キーワード集" :current-page="18" :total-pages="20">
<div class="slide-container"><div class="left-panel"><h1 class="text-3xl font-bold mb-6">重要用語・キーワード集</h1><p class="text-lg opacity-80 mt-4">記憶術の基礎となる専門用語</p><div class="brain-pattern"><i class="fas fa-book-open"></i></div></div><div class="right-panel"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-brain"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">記憶術</p><p class="text-lg mt-1">覚えるための技法群、大量情報を効率的に記憶するワザ</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-map-marker-alt"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">場所法/メモリーパレス</p><p class="text-lg mt-1">ルートとプレイスに配置して想起する2500年前からの最強記憶術</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-route"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">ルート/プレイス</p><p class="text-lg mt-1">記憶の順路と配置点、家の間取りなど馴染みの場所を活用</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-book"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">ストーリー法</p><p class="text-lg mt-1">単語や事実を物語で連結して記憶する基本テクニック</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-tag"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">タグ付け法</p><p class="text-lg mt-1">顔の特徴をタグ化し氏名と結びつける記憶術</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-exchange-alt"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">変換表/数字変換</p><p class="text-lg mt-1">抽象的な数字を具体的なイメージに変換する手法</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-compress-arrows-alt"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">PAO</p><p class="text-lg mt-1">人物(Person)・動作(Action)・対象(Object)の圧縮記憶法</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-ghost"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">ゴースト</p><p class="text-lg mt-1">以前のイメージが場所に残る現象、時間間隔で解消</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-redo"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">想起</p><p class="text-lg mt-1">ルートを順に辿って配置した情報を取り出す行為</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .left-panel {      width: 30%;      background-color: #1a365d;      color: white;      padding: 40px;      display: flex;      flex-direction: column;      justify-content: center;      position: relative;    }    .right-panel {      width: 70%;      padding: 60px 50px;      display: flex;      flex-direction: column;      justify-content: center;    }    .bullet-item {      display: flex;      align-items: flex-start;      margin-bottom: 25px;    }    .bullet-icon {      font-size: 24px;      margin-right: 15px;      color: #2b6cb0;      flex-shrink: 0;      margin-top: 2px;    }    .bullet-text {      flex: 1;    }    .brain-pattern {      position: absolute;      bottom: 20px;      right: 20px;      font-size: 100px;      opacity: 0.1;    }
</style>
