<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="記憶術の原則・ベストプラクティス" :current-page="19" :total-pages="20">
<div class="slide-container"><div class="left-panel"><h1 class="text-3xl font-bold mb-6">記憶術の原則・ベストプラクティス</h1><p class="text-lg opacity-80 mt-4">『世界最強記憶術 場所法』</p><div class="brain-pattern"><i class="fas fa-brain"></i></div></div><div class="right-panel"><div class="principles-grid"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-route"></i></div><div class="bullet-text"><p class="text-lg font-bold text-blue-800">原則1: 順序づけが王道</p><p class="text-base mt-1">ルートを固定し、順番通りにイメージを配置する</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-exchange-alt"></i></div><div class="bullet-text"><p class="text-lg font-bold text-blue-800">原則2: 抽象は具体イメージへ</p><p class="text-base mt-1">数字や概念を具体的な物や人に変換する</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-bolt"></i></div><div class="bullet-text"><p class="text-lg font-bold text-blue-800">原則3: 印象を強化する</p><p class="text-base mt-1">奇抜・動作・感情を加えて記憶に残りやすくする</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-cube"></i></div><div class="bullet-text"><p class="text-lg font-bold text-blue-800">原則4: 1プレイス1イメージ</p><p class="text-base mt-1">混乱を避けるため、各場所には一つの情報だけを配置</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-ghost"></i></div><div class="bullet-text"><p class="text-lg font-bold text-blue-800">原則5: ゴースト対策</p><p class="text-base mt-1">時間間隔を空ける、または別のルートを使用する</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-user-tag"></i></div><div class="bullet-text"><p class="text-lg font-bold text-blue-800">原則6: 顔と名前はタグ付け</p><p class="text-base mt-1">顔の特徴をタグ化し、名前と結びつける最短ルート</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-sync"></i></div><div class="bullet-text"><p class="text-lg font-bold text-blue-800">原則7: 間隔反復で定着</p><p class="text-base mt-1">効果的な復習スケジュールで長期記憶に転送する</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-running"></i></div><div class="bullet-text"><p class="text-lg font-bold text-blue-800">原則8: 取り出す練習を重ねる</p><p class="text-base mt-1">実際に使う場面を想定して繰り返し思い出す訓練をする</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .left-panel {      width: 30%;      background-color: #1a365d;      color: white;      padding: 40px;      display: flex;      flex-direction: column;      justify-content: center;      position: relative;    }    .right-panel {      width: 70%;      padding: 40px 50px;      display: flex;      flex-direction: column;      justify-content: center;    }    .bullet-item {      display: flex;      align-items: flex-start;      margin-bottom: 20px;    }    .bullet-icon {      font-size: 22px;      margin-right: 15px;      color: #2b6cb0;      flex-shrink: 0;      margin-top: 2px;    }    .bullet-text {      flex: 1;    }    .brain-pattern {      position: absolute;      bottom: 20px;      right: 20px;      font-size: 100px;      opacity: 0.1;    }    .principles-grid {      display: grid;      grid-template-columns: 1fr 1fr;      grid-gap: 20px;    }
</style>
