<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="本書の概要・対象読者・期待される変化" :current-page="2" :total-pages="20">
<div class="slide-container"><div class="left-panel"><h1 class="text-3xl font-bold mb-6">本書の概要・対象読者・期待される変化</h1><p class="text-lg opacity-80 mt-4">『世界最強記憶術 場所法』</p><div class="brain-pattern"><i class="fas fa-brain"></i></div></div><div class="right-panel"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-book"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">テーマ</p><p class="text-lg mt-1">場所法（メモリーパレス）を軸に、誰でも大量・正確・高速に覚える技術を解説</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-question-circle"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">背景</p><p class="text-lg mt-1">「覚えたいのに覚えられない」「すぐ忘れる」を実践的に解決</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-users"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">対象読者</p><p class="text-lg mt-1">学習・資格・仕事・日常の記憶に悩む人、記憶力競技に関心がある人</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-lightbulb"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">期待される変化</p><p class="text-lg mt-1">覚えるのが楽しくなる / アウトプットの量が増える / 思い出す速さが上がる</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .left-panel {      width: 30%;      background-color: #1a365d;      color: white;      padding: 40px;      display: flex;      flex-direction: column;      justify-content: center;      position: relative;    }    .right-panel {      width: 70%;      padding: 60px 50px;      display: flex;      flex-direction: column;      justify-content: center;    }    .bullet-item {      display: flex;      align-items: flex-start;      margin-bottom: 25px;    }    .bullet-icon {      font-size: 24px;      margin-right: 15px;      color: #2b6cb0;      flex-shrink: 0;      margin-top: 2px;    }    .bullet-text {      flex: 1;    }    .brain-pattern {      position: absolute;      bottom: 20px;      right: 20px;      font-size: 100px;      opacity: 0.1;    }
</style>
