<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="締め：今日から始める7日間トライアル" :current-page="20" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">締め：今日から始める7日間トライアル</h1></div><div class="content"><div class="timeline"><div class="day-card"><div class="day-number">Day1</div><p class="font-bold text-blue-800">ストーリー法</p><p class="text-sm mt-1">10項目×3セットを作成・記憶</p></div><div class="day-card"><div class="day-number">Day2</div><p class="font-bold text-blue-800">記憶力測定</p><p class="text-sm mt-1">記憶力の伸びを確認</p></div><div class="day-card"><div class="day-number">Day3</div><p class="font-bold text-blue-800">ルート作成</p><p class="text-sm mt-1">10プレイスを設定</p></div><div class="day-card"><div class="day-number">Day4</div><p class="font-bold text-blue-800">プレイス拡張</p><p class="text-sm mt-1">20プレイスへ拡張</p></div><div class="day-card"><div class="day-number">Day5</div><p class="font-bold text-blue-800">数字変換表</p><p class="text-sm mt-1">オリジナル変換表作成</p></div><div class="day-card"><div class="day-number">Day6</div><p class="font-bold text-blue-800">タグ付け法</p><p class="text-sm mt-1">5人分の顔と名前を記憶</p></div><div class="day-card"><div class="day-number">Day7</div><p class="font-bold text-blue-800">日常応用</p><p class="text-sm mt-1">買い物リスト・ToDo等</p></div></div><div class="mb-6 mt-8"><h2 class="text-2xl font-bold text-blue-800 mb-3">記憶力向上のための実践ポイント</h2><div class="flex flex-wrap"><div class="w-1/2 pr-4 mb-4"><p class="font-bold flex items-center"><i class="fas fa-check-circle text-blue-700 mr-2"></i>必ず毎日少しずつ練習する</p><p class="ml-7 text-sm text-gray-600">脳に定着させるには反復が重要です</p></div><div class="w-1/2 pr-4 mb-4"><p class="font-bold flex items-center"><i class="fas fa-check-circle text-blue-700 mr-2"></i>具体的な目標を設定する</p><p class="ml-7 text-sm text-gray-600">例：「買い物リスト20品を正確に覚える」</p></div><div class="w-1/2 pr-4 mb-4"><p class="font-bold flex items-center"><i class="fas fa-check-circle text-blue-700 mr-2"></i>進捗を記録する</p><p class="ml-7 text-sm text-gray-600">記憶できた項目数・時間を記録して成長を確認</p></div><div class="w-1/2 pr-4 mb-4"><p class="font-bold flex items-center"><i class="fas fa-check-circle text-blue-700 mr-2"></i>他者に教える</p><p class="ml-7 text-sm text-gray-600">教えることで知識が定着し、新たな気づきも得られます</p></div></div></div><div class="cta-section"><div class="cta-icon"><i class="fas fa-rocket"></i></div><div><h2 class="text-2xl font-bold text-blue-900 mb-2">今すぐ始めよう！</h2><p class="text-lg mb-3">第一メモリーパレス（自宅の10プレイス）を作成し、記憶の旅を始めましょう。</p><p class="text-md"><strong>今日の行動</strong>：自宅の見取り図を書き、10箇所のプレイスを決める。そこに買い物リスト10品を配置する練習をしましょう。</p></div></div><div class="brain-icon"><i class="fas fa-brain"></i></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .header {      padding: 30px 50px 15px;      background-color: #1a365d;      color: white;    }    .content {      flex: 1;      padding: 30px 50px;      position: relative;    }    .timeline {      display: flex;      justify-content: space-between;      position: relative;      margin: 20px 0 40px;      z-index: 1;    }    .timeline::after {      content: "";      position: absolute;      top: 30px;      left: 0;      width: 100%;      height: 4px;      background-color: #2b6cb0;      z-index: -1;    }    .day-card {      width: 13%;      background-color: white;      border: 2px solid #2b6cb0;      border-radius: 10px;      padding: 15px;      text-align: center;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);      z-index: 2;    }    .day-number {      width: 60px;      height: 60px;      background-color: #2b6cb0;      color: white;      border-radius: 50%;      display: flex;      align-items: center;      justify-content: center;      font-weight: bold;      font-size: 18px;      margin: -40px auto 10px;    }    .cta-section {      background-color: #ebf4ff;      border-left: 5px solid #2b6cb0;      padding: 25px;      margin-top: 20px;      border-radius: 0 10px 10px 0;      display: flex;      align-items: center;    }    .cta-icon {      font-size: 50px;      color: #2b6cb0;      margin-right: 25px;    }    .brain-icon {      font-size: 180px;      color: rgba(26, 54, 93, 0.03);      position: absolute;      right: 50px;      bottom: 40px;      z-index: 0;    }
</style>
