<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="目次" :current-page="3" :total-pages="20">
<div class="slide-container"><div class="left-panel"><h1 class="text-3xl font-bold mb-6">目次</h1><p class="text-lg opacity-80 mt-4">『世界最強記憶術 場所法』</p><div class="brain-pattern"><i class="fas fa-brain"></i></div><div class="memory-path" style="transform: rotate(30deg);"></div><div class="memory-path" style="transform: rotate(60deg);"></div><div class="memory-path" style="transform: rotate(120deg);"></div></div><div class="right-panel"><div class="toc-item"><div class="chapter-number">1</div><div class="chapter-title"><p class="text-xl font-bold">記憶術は誰でも伸ばせる</p><p class="text-lg mt-1 text-gray-600">「覚えるワザ」の基礎</p></div></div><div class="toc-item"><div class="chapter-number">2</div><div class="chapter-title"><p class="text-xl font-bold">記憶力競技の世界</p><p class="text-lg mt-1 text-gray-600">競技種目と記録更新の実践</p></div></div><div class="toc-item"><div class="chapter-number">3</div><div class="chapter-title"><p class="text-xl font-bold">基本の記憶術「ストーリー法」</p><p class="text-lg mt-1 text-gray-600">物語化による記憶力強化</p></div></div><div class="toc-item"><div class="chapter-number">4</div><div class="chapter-title"><p class="text-xl font-bold">場所法（メソッド・オブ・ロキ）</p><p class="text-lg mt-1 text-gray-600">2500年前からの最強記憶術</p></div></div><div class="toc-item"><div class="chapter-number">5</div><div class="chapter-title"><p class="text-xl font-bold">変換術と数字記憶</p><p class="text-lg mt-1 text-gray-600">数字を具体的イメージへ</p></div></div><div class="toc-item"><div class="chapter-number">6</div><div class="chapter-title"><p class="text-xl font-bold">顔と名前を一致させる「タグ付け法」</p><p class="text-lg mt-1 text-gray-600">特徴と名前の効果的連結</p></div></div><div class="toc-item"><div class="chapter-number">7</div><div class="chapter-title"><p class="text-xl font-bold">日常への応用</p><p class="text-lg mt-1 text-gray-600">買い物リスト・英単語・資格試験</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .left-panel {      width: 30%;      background-color: #1a365d;      color: white;      padding: 40px;      display: flex;      flex-direction: column;      justify-content: center;      position: relative;    }    .right-panel {      width: 70%;      padding: 60px 50px;      display: flex;      flex-direction: column;      justify-content: center;    }    .toc-item {      display: flex;      align-items: center;      margin-bottom: 28px;    }    .chapter-number {      font-size: 28px;      font-weight: bold;      color: #2b6cb0;      width: 60px;      height: 60px;      border: 3px solid #2b6cb0;      border-radius: 50%;      display: flex;      align-items: center;      justify-content: center;      margin-right: 20px;      flex-shrink: 0;    }    .chapter-title {      flex: 1;    }    .brain-pattern {      position: absolute;      bottom: 20px;      right: 20px;      font-size: 100px;      opacity: 0.1;    }    .memory-path {      position: absolute;      bottom: 40px;      right: 140px;      width: 180px;      height: 2px;      background-color: rgba(255, 255, 255, 0.1);    }
</style>
