<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="第1章：記憶術とは何か" :current-page="4" :total-pages="20">
<div class="slide-container"><div class="left-panel"><div class="chapter-number">1</div><h1 class="text-4xl font-bold mb-2 relative z-10">第1章</h1><h2 class="text-3xl font-bold mb-6 relative z-10">記憶術とは何か</h2><p class="text-xl mt-6 opacity-80 relative z-10">誰でも伸ばせる記憶力の仕組み</p><div class="circles"></div><div class="circles" style="width: 200px; height: 200px; bottom: -50px; left: -50px;"></div><div class="circles" style="width: 100px; height: 100px; bottom: 0; left: 0;"></div></div><div class="right-panel"><div class="concept-item"><div class="concept-icon"><i class="fas fa-tools"></i></div><div class="concept-text"><p class="text-xl font-bold text-blue-800">記憶術＝大量の情報を正確・効率的に覚えるための"ワザ"</p><p class="text-lg mt-1">記憶のメカニズムを利用した、覚えるための具体的な技術</p></div></div><div class="concept-item"><div class="concept-icon"><i class="fas fa-user-graduate"></i></div><div class="concept-text"><p class="text-xl font-bold text-blue-800">天才専用ではない</p><p class="text-lg mt-1">方法を知り、訓練すれば誰でも伸びる普遍的スキル</p></div></div><div class="concept-item"><div class="concept-icon"><i class="fas fa-brain"></i></div><div class="concept-text"><p class="text-xl font-bold text-blue-800">効果の柱: ①順序づけ ②イメージ化 ③想起の仕組み化</p><p class="text-lg mt-1">脳の記憶メカニズムに沿った効率的なインプット・アウトプット</p></div></div><div class="concept-item"><div class="concept-icon"><i class="fas fa-sync-alt"></i></div><div class="concept-text"><p class="text-xl font-bold text-blue-800">抽象→具体、羅列→物語への変換</p><p class="text-lg mt-1">実生活の「覚えにくい形」を「覚えやすい形」へ変える</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .left-panel {      width: 40%;      background-color: #1a365d;      color: white;      padding: 40px;      display: flex;      flex-direction: column;      justify-content: center;      position: relative;      overflow: hidden;    }    .right-panel {      width: 60%;      padding: 60px 50px;      display: flex;      flex-direction: column;      justify-content: center;    }    .chapter-number {      font-size: 180px;      font-weight: bold;      opacity: 0.2;      position: absolute;      right: 30px;      top: 50%;      transform: translateY(-50%);    }    .concept-item {      display: flex;      align-items: flex-start;      margin-bottom: 30px;    }    .concept-icon {      font-size: 32px;      margin-right: 20px;      color: #2b6cb0;      flex-shrink: 0;      width: 70px;      height: 70px;      border-radius: 50%;      background-color: rgba(43, 108, 176, 0.1);      display: flex;      align-items: center;      justify-content: center;    }    .concept-text {      flex: 1;    }    .circles {      position: absolute;      width: 300px;      height: 300px;      border-radius: 50%;      border: 2px solid rgba(255, 255, 255, 0.05);      bottom: -100px;      left: -100px;    }
</style>
