<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="第2章：記憶力競技の世界" :current-page="6" :total-pages="20">
<div class="slide-container"><div class="left-panel"><h1 class="text-3xl font-bold mb-6">第2章：記憶力競技の世界</h1><p class="text-lg opacity-80 mt-4">記憶の量と正確さを競う</p><div class="brain-pattern"><i class="fas fa-trophy"></i></div></div><div class="right-panel"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-medal"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">主な種目</p><p class="text-lg mt-1">スピードナンバー／バイナリー／カード／単語／年号／顔と名前 など</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-globe"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">大会形式</p><p class="text-lg mt-1">国内外の公式戦で記憶の量と正確さを競う</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-lightbulb"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">学べること</p><p class="text-lg mt-1">ルール化・手順化・計測が記憶力を加速させる</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-chart-line"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">インパクト</p><p class="text-lg mt-1">子どもからシニアまで、訓練で着実に記録が伸びる</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .left-panel {      width: 30%;      background-color: #1a365d;      color: white;      padding: 40px;      display: flex;      flex-direction: column;      justify-content: center;      position: relative;    }    .right-panel {      width: 70%;      padding: 60px 50px;      display: flex;      flex-direction: column;      justify-content: center;    }    .bullet-item {      display: flex;      align-items: flex-start;      margin-bottom: 25px;    }    .bullet-icon {      font-size: 24px;      margin-right: 15px;      color: #2b6cb0;      flex-shrink: 0;      margin-top: 2px;    }    .bullet-text {      flex: 1;    }    .brain-pattern {      position: absolute;      bottom: 20px;      right: 20px;      font-size: 100px;      opacity: 0.1;    }
</style>
