<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="第3章：ストーリー法の基本（2ステップ）" :current-page="7" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">第3章：ストーリー法の基本（2ステップ）</h1></div><div class="content"><div class="steps-container"><div class="step-box"><div class="step-number">STEP 1</div><div class="step-title">イメージ化</div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>単語や事実を<strong>具体的に見える形</strong>に変換する</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>抽象的な概念も具体物にする（例：「平和」→「白い鳩」）</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>五感を刺激する鮮明なイメージを作る</p></div></div><div class="tips-box"><p class="font-bold mb-2"><i class="fas fa-lightbulb text-blue-700"></i> イメージ化のコツ</p><p>・大きく誇張する（通常の10倍の大きさ）</p><p>・動きをつける（静止画より動画が記憶に残る）</p><p>・色彩を豊かに（特に原色は記憶に残りやすい）</p></div></div><div class="arrow-container"><div class="arrow-icon"><i class="fas fa-long-arrow-alt-right"></i></div></div><div class="step-box"><div class="step-number">STEP 2</div><div class="step-title">物語化</div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>イメージ同士を<strong>奇抜・動的・感情的</strong>に連結する</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>前後の項目が相互作用する短いストーリーを作る</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-arrow-right"></i></div><div><p>順番に沿ってイメージを思い出せるようにする</p></div></div><div class="tips-box"><p class="font-bold mb-2"><i class="fas fa-lightbulb text-blue-700"></i> 物語化のコツ</p><p>・非現実的/突飛なほうが記憶に残る</p><p>・感情を込める（驚き/喜び/恐怖など）</p><p>・自分が主人公になって体験するように想像する</p></div></div></div><div class="mt-8 bg-blue-50 p-4 rounded-lg border border-blue-200"><p class="font-bold text-lg text-blue-800 mb-2">適用範囲とポイント</p><div class="flex"><div class="w-1/2 pr-4"><p class="mb-2"><i class="fas fa-check-circle text-blue-700 mr-2"></i>10項目前後の順序記憶に強い（買い物/ToDoなど）</p><p><i class="fas fa-check-circle text-blue-700 mr-2"></i>定期的に使うことで、イメージ作成スピードが向上</p></div><div class="w-1/2 pl-4 border-l border-blue-200"><p class="mb-2"><i class="fas fa-exclamation-circle text-amber-600 mr-2"></i>超えどころ：10個を超える長列は場所法と併用</p><p><i class="fas fa-exclamation-circle text-amber-600 mr-2"></i>練習：最初は簡単な5項目からスタート</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      flex-direction: column;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .header {      padding: 30px 50px 10px;      background-color: #1a365d;      color: white;    }    .content {      flex: 1;      display: flex;      flex-direction: column;      padding: 30px 50px;    }    .steps-container {      display: flex;      justify-content: space-between;      margin-top: 20px;    }    .step-box {      width: 48%;      border: 2px solid #2b6cb0;      border-radius: 15px;      padding: 25px;      position: relative;      background-color: white;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);    }    .step-number {      position: absolute;      top: -20px;      left: 30px;      background-color: #2b6cb0;      color: white;      font-weight: bold;      padding: 5px 20px;      border-radius: 20px;      font-size: 18px;    }    .step-title {      margin-top: 10px;      font-size: 24px;      font-weight: bold;      color: #2b6cb0;      margin-bottom: 15px;    }    .arrow-container {      display: flex;      align-items: center;      justify-content: center;      position: relative;      margin: 0 -20px;    }    .arrow-icon {      font-size: 36px;      color: #2b6cb0;    }    .tips-box {      margin-top: 30px;      background-color: rgba(43, 108, 176, 0.1);      border-left: 5px solid #2b6cb0;      padding: 15px 20px;    }    .point-item {      display: flex;      align-items: flex-start;      margin-bottom: 12px;    }    .point-icon {      color: #2b6cb0;      margin-right: 10px;      margin-top: 5px;      flex-shrink: 0;    }
</style>
