<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="第3章：ストーリー法の実践例" :current-page="8" :total-pages="20">
<div class="slide-container"><div class="left-panel"><h1 class="text-3xl font-bold mb-6">第3章：ストーリー法の実践例</h1><p class="text-lg opacity-80 mt-4">具体例から学ぶ効果的な物語化</p><div class="brain-pattern"><i class="fas fa-book-open"></i></div></div><div class="right-panel"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-list-ol"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">単語列の例</p><p class="text-lg mt-1">氷→釘→教科書→ボール→ネックレス を一場面の物語に</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-check-circle"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">OK例</p><p class="text-lg mt-1">凍った教科書を釘で割るとボールが飛び出し、ネックレスに絡む</p><p class="text-md text-gray-600 mt-1">（動的・奇抜・視覚的で記憶に残りやすい）</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-times-circle"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">NG例</p><p class="text-lg mt-1">静的・現実的すぎる連結（印象が弱く想起しづらい）</p><p class="text-md text-gray-600 mt-1">例：教科書の上に氷と釘が置いてあり、横にボールとネックレスがある</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-lightbulb"></i></div><div class="bullet-text"><p class="text-xl font-bold text-blue-800">超えどころ</p><p class="text-lg mt-1">10個を超える長列は場所法と併用するのが効果的</p><p class="text-md text-gray-600 mt-1">ストーリーが複雑になりすぎると記憶の負荷が高くなる</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .left-panel {      width: 30%;      background-color: #1a365d;      color: white;      padding: 40px;      display: flex;      flex-direction: column;      justify-content: center;      position: relative;    }    .right-panel {      width: 70%;      padding: 60px 50px;      display: flex;      flex-direction: column;      justify-content: center;    }    .bullet-item {      display: flex;      align-items: flex-start;      margin-bottom: 25px;    }    .bullet-icon {      font-size: 24px;      margin-right: 15px;      color: #2b6cb0;      flex-shrink: 0;      margin-top: 2px;    }    .bullet-text {      flex: 1;    }    .brain-pattern {      position: absolute;      bottom: 20px;      right: 20px;      font-size: 100px;      opacity: 0.1;    }
</style>
