<template>
  <SlidePageWrapper slide-id="B07NDW68MK" page-title="第4章：場所法とは何か" :current-page="9" :total-pages="20">
<div class="slide-container"><div class="left-panel"><div class="chapter-number">4</div><h1 class="text-4xl font-bold mb-2 relative z-10">第4章</h1><h2 class="text-3xl font-bold mb-6 relative z-10">場所法とは何か</h2><p class="text-xl mt-6 opacity-80 relative z-10">2500年前からの最強記憶術</p><div class="circles"></div><div class="circles" style="width: 200px; height: 200px; bottom: -50px; left: -50px;"></div><div class="circles" style="width: 100px; height: 100px; bottom: 0; left: 0;"></div></div><div class="right-panel"><div class="concept-item"><div class="concept-icon"><i class="fas fa-history"></i></div><div class="concept-text"><p class="text-xl font-bold text-blue-800">2500年前から使われる古典的かつ強力な方法</p><p class="text-lg mt-1">古代ギリシャの弁論家が使った「メモリーパレス」とも呼ばれる</p></div></div><div class="concept-item"><div class="concept-icon"><i class="fas fa-map-marked-alt"></i></div><div class="concept-text"><p class="text-xl font-bold text-blue-800">原理: よく知る"場所（ルート）"に"覚えるイメージ"を配置</p><p class="text-lg mt-1">馴染みのある空間を歩き、各ポイントに情報を「置く」イメージ法</p></div></div><div class="concept-item"><div class="concept-icon"><i class="fas fa-database"></i></div><div class="concept-text"><p class="text-xl font-bold text-blue-800">効能: 長い順序/大量データ/高速想起に強い</p><p class="text-lg mt-1">世界記憶力チャンピオンも使用する実証済みの記憶法</p></div></div><div class="concept-item"><div class="concept-icon"><i class="fas fa-check-square"></i></div><div class="concept-text"><p class="text-xl font-bold text-blue-800">使い所: 数字列・学習項目・スピーチ構成など</p><p class="text-lg mt-1">10個、100個、数千個と拡張できる柔軟なメソッド</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      background-color: white;      color: #1a365d;      overflow: hidden;    }    .left-panel {      width: 40%;      background-color: #1a365d;      color: white;      padding: 40px;      display: flex;      flex-direction: column;      justify-content: center;      position: relative;      overflow: hidden;    }    .right-panel {      width: 60%;      padding: 60px 50px;      display: flex;      flex-direction: column;      justify-content: center;    }    .chapter-number {      font-size: 180px;      font-weight: bold;      opacity: 0.2;      position: absolute;      right: 30px;      top: 50%;      transform: translateY(-50%);    }    .concept-item {      display: flex;      align-items: flex-start;      margin-bottom: 30px;    }    .concept-icon {      font-size: 32px;      margin-right: 20px;      color: #2b6cb0;      flex-shrink: 0;      width: 70px;      height: 70px;      border-radius: 50%;      background-color: rgba(43, 108, 176, 0.1);      display: flex;      align-items: center;      justify-content: center;    }    .concept-text {      flex: 1;    }    .circles {      position: absolute;      width: 300px;      height: 300px;      border-radius: 50%;      border: 2px solid rgba(255, 255, 255, 0.05);      bottom: -100px;      left: -100px;    }
</style>
