<template>
  <SlidePageWrapper slide-id="B0899XW4CQ" page-title="原体験ドリブン - 書籍要約" :current-page="1" :total-pages="20">
<div class="slide-container"><div class="accent-shape shape-1"></div><div class="accent-shape shape-2"></div><div class="content-wrapper"><div class="book-title"><p>原体験ドリブン</p></div><div class="underline"></div><div class="book-subtitle"><p>人生の答えの9割がここにある！</p></div><div class="author"><p>チカイケ秀夫（光文社）</p></div><div class="description"><p>原体験から『自分だけの軸』を見つけ、人生・キャリア・起業に活かす全体像を20枚で掴む</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            background-color: #1a365d;            color: white;            overflow: hidden;            position: relative;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            justify-content: center;            align-items: center;            padding: 60px;            position: relative;            z-index: 10;        }        .book-title {            font-size: 80px;            font-weight: 900;            text-align: center;            line-height: 1.2;            margin-bottom: 20px;        }        .book-subtitle {            font-size: 36px;            font-weight: 700;            text-align: center;            margin-bottom: 40px;            color: #f59e0b;        }        .author {            font-size: 24px;            font-weight: 500;            margin-top: 20px;            text-align: center;        }        .description {            font-size: 18px;            margin-top: 40px;            text-align: center;            max-width: 700px;        }        .accent-shape {            position: absolute;            background-color: #2563eb;            width: 400px;            height: 400px;            border-radius: 50%;            opacity: 0.1;            z-index: 1;        }        .shape-1 {            top: -100px;            left: -100px;        }        .shape-2 {            bottom: -100px;            right: -50px;        }        .underline {            height: 8px;            width: 100px;            background-color: #f59e0b;            margin: 30px auto;        }
</style>
