<template>
  <SlidePageWrapper slide-id="B0899XW4CQ" page-title="第3章① ペアワークとは" :current-page="10" :total-pages="20">
<div class="slide-container"><div class="title-section"><div class="accent-shape shape-1"></div><div class="title-text"><p>第3章① ペアワークとは</p></div><div class="title-accent"></div></div><div class="content-section"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-users"></i></div><div class="bullet-text"><div class="bullet-heading"><p>2人1組で『なぜ?』を重ねて掘る対話式ワーク</p></div><div class="bullet-content"><p>互いに質問し合いながら、相手の原体験を引き出す。1人では気づきにくい無意識の動機や価値観を発見できる。</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-lightbulb"></i></div><div class="bullet-text"><div class="bullet-heading"><p>メリット: 客観視/ブラインドスポットに光/問いの多様性</p></div><div class="bullet-content"><p>自分では気づかない角度からの質問で新たな発見。他者の質問による多角的な視点。共感体験による信頼感と安心感。</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-exchange-alt"></i></div><div class="bullet-text"><div class="bullet-heading"><p>自己ワークとの違い</p></div><div class="bullet-content"><p>他者の質問で新しい言葉・意味づけが生まれやすい。自問自答では出てこない答えや気づきが得られる。客観的な視点を提供。</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-hand-point-right"></i></div><div class="bullet-text"><div class="bullet-heading"><p>推奨: 初心者はペアから始めるとブレークスルーが起きやすい</p></div><div class="bullet-content"><p>1人で深掘りするのが難しい場合、まずペアワークからスタートすると自己理解が加速する。何度か体験すると本質的な気づきが増える。</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        background-color: #f8fafc;        color: #1e293b;        overflow: hidden;        position: relative;    }    .title-section {        width: 340px;        background-color: #1a365d;        color: white;        padding: 50px 40px;        display: flex;        flex-direction: column;        justify-content: center;        position: relative;    }    .title-text {        font-size: 36px;        font-weight: 700;        line-height: 1.3;        position: relative;        z-index: 10;    }    .title-accent {        height: 6px;        width: 60px;        background-color: #f59e0b;        margin-top: 20px;        margin-bottom: 15px;    }    .content-section {        flex: 1;        padding: 50px 60px;        display: flex;        flex-direction: column;        justify-content: center;    }    .bullet-item {        margin-bottom: 24px;        display: flex;        align-items: flex-start;    }    .bullet-icon {        color: #1a365d;        font-size: 24px;        margin-right: 16px;        margin-top: 2px;    }    .bullet-text {        flex: 1;    }    .bullet-heading {        font-weight: 700;        font-size: 20px;        color: #1a365d;        margin-bottom: 6px;    }    .bullet-content {        font-size: 18px;        line-height: 1.5;    }    .accent-shape {        position: absolute;        background-color: #2563eb;        border-radius: 50%;        opacity: 0.1;        z-index: 1;    }    .shape-1 {        width: 180px;        height: 180px;        bottom: -60px;        left: -30px;    }
</style>
