<template>
  <SlidePageWrapper slide-id="B0899XW4CQ" page-title="第3章③ ペアワークの注意点" :current-page="12" :total-pages="20">
<div class="slide-container"><div class="title-section"><div class="accent-shape shape-1"></div><div class="title-text"><p>第3章③ ペアワークの注意点</p></div><div class="title-accent"></div></div><div class="content-section"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-hand-holding-heart"></i></div><div class="bullet-text"><div class="bullet-heading"><p>問いかけの姿勢</p></div><div class="bullet-content"><p>問い詰めず"引き出す"姿勢（優しい『なぜ?』）を心がける</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-ban"></i></div><div class="bullet-text"><div class="bullet-heading"><p>禁止事項</p></div><div class="bullet-content"><p>アドバイス/否定/評価/誘導/結論の押し付けは絶対にNG</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-user-shield"></i></div><div class="bullet-text"><div class="bullet-heading"><p>守秘義務</p></div><div class="bullet-content"><p>許可なく第三者に共有しない（安心して話せる環境を守る）</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-heart"></i></div><div class="bullet-text"><div class="bullet-heading"><p>相手への配慮</p></div><div class="bullet-content"><p>つらそう・嫌そうであれば深掘りをやめる、同意を確認しながら進める</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-check-circle"></i></div><div class="bullet-text"><div class="bullet-heading"><p>正解は不要</p></div><div class="bullet-content"><p>「正しい」「間違い」にこだわらず、"なんとなく"から始めてよい</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-headphones"></i></div><div class="bullet-text"><div class="bullet-heading"><p>共感的傾聴</p></div><div class="bullet-content"><p>境界線を尊重しつつ、相手の言葉に真摯に耳を傾ける</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        background-color: #f8fafc;        color: #1e293b;        overflow: hidden;        position: relative;    }    .title-section {        width: 340px;        background-color: #1a365d;        color: white;        padding: 50px 40px;        display: flex;        flex-direction: column;        justify-content: center;        position: relative;    }    .title-text {        font-size: 36px;        font-weight: 700;        line-height: 1.3;        position: relative;        z-index: 10;    }    .title-accent {        height: 6px;        width: 60px;        background-color: #f59e0b;        margin-top: 20px;        margin-bottom: 15px;    }    .content-section {        flex: 1;        padding: 50px 60px;        display: flex;        flex-direction: column;        justify-content: center;    }    .bullet-item {        margin-bottom: 24px;        display: flex;        align-items: flex-start;    }    .bullet-icon {        color: #1a365d;        font-size: 24px;        margin-right: 16px;        margin-top: 2px;    }    .bullet-text {        flex: 1;    }    .bullet-heading {        font-weight: 700;        font-size: 20px;        color: #1a365d;        margin-bottom: 6px;    }    .bullet-content {        font-size: 18px;        line-height: 1.5;    }    .accent-shape {        position: absolute;        background-color: #2563eb;        border-radius: 50%;        opacity: 0.1;        z-index: 1;    }    .shape-1 {        width: 180px;        height: 180px;        bottom: -60px;        left: -30px;    }
</style>
