<template>
  <SlidePageWrapper slide-id="B0899XW4CQ" page-title="第4章① 原体験の活用" :current-page="13" :total-pages="20">
<div class="slide-container"><div class="title-section"><div class="accent-shape shape-1"></div><div class="title-text"><p>第4章① 原体験の活用（自分の軸→実践へ）</p></div><div class="title-accent"></div></div><div class="content-section"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-briefcase"></i></div><div class="bullet-text"><div class="bullet-heading"><p>就活/転職</p></div><div class="bullet-content"><p>志望動機・自己PR・面接回答の一貫性が生まれ、説得力が高まる</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-rocket"></i></div><div class="bullet-text"><div class="bullet-heading"><p>起業/副業</p></div><div class="bullet-content"><p>事業のWHY/ストーリーが明確になり、共感と信頼を獲得しやすくなる</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-users-cog"></i></div><div class="bullet-text"><div class="bullet-heading"><p>組織/採用/マネジメント</p></div><div class="bullet-content"><p>価値観の共有でチームの結束が強まり、同じ方向を目指しやすくなる</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-mountain"></i></div><div class="bullet-text"><div class="bullet-heading"><p>壁に当たった時</p></div><div class="bullet-content"><p>原体験の軸に立ち返ることで、迷いが減り、再出発の力を得られる</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-route"></i></div><div class="bullet-text"><div class="bullet-heading"><p>実践手順</p></div><div class="bullet-content"><p>複数原体験→価値観抽出→言語化→適用領域へ展開→継続的な振り返り</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        background-color: #f8fafc;        color: #1e293b;        overflow: hidden;        position: relative;    }    .title-section {        width: 340px;        background-color: #1a365d;        color: white;        padding: 50px 40px;        display: flex;        flex-direction: column;        justify-content: center;        position: relative;    }    .title-text {        font-size: 36px;        font-weight: 700;        line-height: 1.3;        position: relative;        z-index: 10;    }    .title-accent {        height: 6px;        width: 60px;        background-color: #f59e0b;        margin-top: 20px;        margin-bottom: 15px;    }    .content-section {        flex: 1;        padding: 50px 60px;        display: flex;        flex-direction: column;        justify-content: center;    }    .bullet-item {        margin-bottom: 24px;        display: flex;        align-items: flex-start;    }    .bullet-icon {        color: #1a365d;        font-size: 24px;        margin-right: 16px;        margin-top: 2px;    }    .bullet-text {        flex: 1;    }    .bullet-heading {        font-weight: 700;        font-size: 20px;        color: #1a365d;        margin-bottom: 6px;    }    .bullet-content {        font-size: 18px;        line-height: 1.5;    }    .accent-shape {        position: absolute;        background-color: #2563eb;        border-radius: 50%;        opacity: 0.1;        z-index: 1;    }    .shape-1 {        width: 180px;        height: 180px;        bottom: -60px;        left: -30px;    }
</style>
