<template>
  <SlidePageWrapper slide-id="B0899XW4CQ" page-title="第4章② Being/Doingで軸を整える" :current-page="14" :total-pages="20">
<div class="slide-container"><div class="title-section"><div class="accent-shape shape-1"></div><div class="title-text"><p>第4章② Being/Doingで軸を整える</p></div><div class="title-accent"></div></div><div class="content-section"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-running"></i></div><div class="bullet-text"><div class="bullet-heading"><p>Doing</p></div><div class="bullet-content"><p>何をするか/どんな行動・領域で価値提供するか</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-heartbeat"></i></div><div class="bullet-text"><div class="bullet-heading"><p>Being</p></div><div class="bullet-content"><p>どうありたいか/大事にしたい在り方・姿勢・存在理由</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-lightbulb"></i></div><div class="bullet-text"><div class="bullet-heading"><p>具体例</p></div><div class="bullet-content"><p>Being『好奇心で人をつなぐ人』× Doing『教育×デザインで学びを設計』</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-check-circle"></i></div><div class="bullet-text"><div class="bullet-heading"><p>整合性チェック</p></div><div class="bullet-content"><p>原体験→価値観→Being→Doing の一貫性を確認する</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        background-color: #f8fafc;        color: #1e293b;        overflow: hidden;        position: relative;    }    .title-section {        width: 340px;        background-color: #1a365d;        color: white;        padding: 50px 40px;        display: flex;        flex-direction: column;        justify-content: center;        position: relative;    }    .title-text {        font-size: 36px;        font-weight: 700;        line-height: 1.3;        position: relative;        z-index: 10;    }    .title-accent {        height: 6px;        width: 60px;        background-color: #f59e0b;        margin-top: 20px;        margin-bottom: 15px;    }    .content-section {        flex: 1;        padding: 50px 60px;        display: flex;        flex-direction: column;        justify-content: center;    }    .bullet-item {        margin-bottom: 24px;        display: flex;        align-items: flex-start;    }    .bullet-icon {        color: #1a365d;        font-size: 24px;        margin-right: 16px;        margin-top: 2px;    }    .bullet-text {        flex: 1;    }    .bullet-heading {        font-weight: 700;        font-size: 20px;        color: #1a365d;        margin-bottom: 6px;    }    .bullet-content {        font-size: 18px;        line-height: 1.5;    }    .accent-shape {        position: absolute;        background-color: #2563eb;        border-radius: 50%;        opacity: 0.1;        z-index: 1;    }    .shape-1 {        width: 180px;        height: 180px;        bottom: -60px;        left: -30px;    }
</style>
