<template>
  <SlidePageWrapper slide-id="B0899XW4CQ" page-title="第5章① ケーススタディ：西川隼矢氏" :current-page="16" :total-pages="20">
<div class="slide-container"><div class="title-section"><div class="accent-shape shape-1"></div><div class="title-text"><p>第5章① ケーススタディ：西川隼矢氏</p></div><div class="title-accent"></div></div><div class="content-section"><div class="case-points"><div class="case-point"><div class="point-number">1</div><div class="point-icon"><i class="fas fa-seedling"></i></div><div class="point-content"><div class="point-title"><p>原体験</p></div><div class="point-text"><p>人を笑顔にする喜び×ものづくりの執着。幼少期から自作の品を大切にし、人の反応や笑顔に喜びを感じる強い体験が価値観の根底に。</p></div></div></div><div class="case-point"><div class="point-number">2</div><div class="point-icon"><i class="fas fa-rocket"></i></div><div class="point-content"><div class="point-title"><p>展開</p></div><div class="point-text"><p>水中VRという革新的技術で「無重力の驚き体験」をデザイン。スーパーマンのように飛ぶ感覚をイベント化し、SNSでの発信を通じて共感の輪が広がる。</p></div></div></div><div class="case-point"><div class="point-number">3</div><div class="point-icon"><i class="fas fa-hand-holding-heart"></i></div><div class="point-content"><div class="point-title"><p>価値創造</p></div><div class="point-text"><p>株式会社ロッキンプールを創業し、企業やテーマパークとのコラボレーションへと発展。原体験から生まれたミッションが社会的インパクトを持つビジネスに成長。</p></div></div></div><div class="case-point"><div class="point-number">4</div><div class="point-icon"><i class="fas fa-lightbulb"></i></div><div class="point-content"><div class="point-title"><p>学び</p></div><div class="point-text"><p>原体験→価値観→技術/表現→事業化という一貫したストーリーラインが、ビジネスの独自性と共感力を高め、持続的な成長を可能にした事例。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        background-color: #f8fafc;        color: #1e293b;        overflow: hidden;        position: relative;    }    .title-section {        width: 340px;        background-color: #1a365d;        color: white;        padding: 50px 40px;        display: flex;        flex-direction: column;        justify-content: center;        position: relative;    }    .title-text {        font-size: 36px;        font-weight: 700;        line-height: 1.3;        position: relative;        z-index: 10;    }    .title-accent {        height: 6px;        width: 60px;        background-color: #f59e0b;        margin-top: 20px;        margin-bottom: 15px;    }    .content-section {        flex: 1;        padding: 40px 50px;        display: flex;        flex-direction: column;        justify-content: center;    }    .case-points {        display: flex;        flex-direction: column;        gap: 20px;    }    .case-point {        display: flex;        align-items: flex-start;        background-color: #f1f5f9;        border-radius: 8px;        padding: 16px;        position: relative;    }    .point-icon {        background-color: #1a365d;        color: white;        width: 50px;        height: 50px;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        font-size: 24px;        margin-right: 20px;        flex-shrink: 0;    }    .point-content {        flex: 1;    }    .point-title {        font-size: 20px;        font-weight: 700;        color: #1a365d;        margin-bottom: 8px;    }    .point-text {        font-size: 16px;        line-height: 1.5;    }    .point-number {        position: absolute;        top: -10px;        left: -10px;        background-color: #f59e0b;        color: white;        width: 28px;        height: 28px;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        font-weight: 700;        font-size: 16px;    }    .accent-shape {        position: absolute;        background-color: #2563eb;        border-radius: 50%;        opacity: 0.1;        z-index: 1;    }    .shape-1 {        width: 180px;        height: 180px;        bottom: -60px;        left: -30px;    }
</style>
