<template>
  <SlidePageWrapper slide-id="B0899XW4CQ" page-title="第5章② ケーススタディ：三浦七海氏" :current-page="17" :total-pages="20">
<div class="slide-container"><div class="title-section"><div class="accent-shape shape-1"></div><div class="title-text"><p>第5章② ケーススタディ：三浦七海氏</p></div><div class="title-accent"></div></div><div class="content-section"><div class="case-points"><div class="case-point"><div class="point-number">1</div><div class="point-icon"><i class="fas fa-exclamation-triangle"></i></div><div class="point-content"><div class="point-title"><p>原体験</p></div><div class="point-text"><p>中学3年生の時、知らない男性に声をかけられ恐怖を感じた体験。安全への切実な問題意識と社会課題としての認識が芽生え、トラウマを抱えながらも行動の原動力となった。</p></div></div></div><div class="case-point"><div class="point-number">2</div><div class="point-icon"><i class="fas fa-lightbulb"></i></div><div class="point-content"><div class="point-title"><p>展開</p></div><div class="point-text"><p>「同じ経験で怖い思いをする人を減らしたい」という強い思いから、自身の技術的好奇心と掛け合わせ、IoT技術を活用した防犯アクセサリーの開発に着手。</p></div></div></div><div class="case-point"><div class="point-number">3</div><div class="point-icon"><i class="fas fa-hands-helping"></i></div><div class="point-content"><div class="point-title"><p>価値創造</p></div><div class="point-text"><p>当事者としての切実な声と技術を融合させた社会課題解決型のプロダクト開発。自らの体験を語ることで共感を生み、プロジェクトへの支援と注目を集めることに成功。</p></div></div></div><div class="case-point"><div class="point-number">4</div><div class="point-icon"><i class="fas fa-sync-alt"></i></div><div class="point-content"><div class="point-title"><p>学び</p></div><div class="point-text"><p>ネガティブな体験や恐怖、トラウマですら、解決への強いエネルギーに変換できる。自らの「痛み」から生まれた原体験は、同じ課題を持つ人々を助ける力になりうる。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        background-color: #f8fafc;        color: #1e293b;        overflow: hidden;        position: relative;    }    .title-section {        width: 340px;        background-color: #1a365d;        color: white;        padding: 50px 40px;        display: flex;        flex-direction: column;        justify-content: center;        position: relative;    }    .title-text {        font-size: 36px;        font-weight: 700;        line-height: 1.3;        position: relative;        z-index: 10;    }    .title-accent {        height: 6px;        width: 60px;        background-color: #f59e0b;        margin-top: 20px;        margin-bottom: 15px;    }    .content-section {        flex: 1;        padding: 40px 50px;        display: flex;        flex-direction: column;        justify-content: center;    }    .case-points {        display: flex;        flex-direction: column;        gap: 20px;    }    .case-point {        display: flex;        align-items: flex-start;        background-color: #f1f5f9;        border-radius: 8px;        padding: 16px;        position: relative;    }    .point-icon {        background-color: #1a365d;        color: white;        width: 50px;        height: 50px;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        font-size: 24px;        margin-right: 20px;        flex-shrink: 0;    }    .point-content {        flex: 1;    }    .point-title {        font-size: 20px;        font-weight: 700;        color: #1a365d;        margin-bottom: 8px;    }    .point-text {        font-size: 16px;        line-height: 1.5;    }    .point-number {        position: absolute;        top: -10px;        left: -10px;        background-color: #f59e0b;        color: white;        width: 28px;        height: 28px;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        font-weight: 700;        font-size: 16px;    }    .accent-shape {        position: absolute;        background-color: #2563eb;        border-radius: 50%;        opacity: 0.1;        z-index: 1;    }    .shape-1 {        width: 180px;        height: 180px;        bottom: -60px;        left: -30px;    }
</style>
