<template>
  <SlidePageWrapper slide-id="B0899XW4CQ" page-title="第5章③ ケーススタディ：古村大和氏" :current-page="18" :total-pages="20">
<div class="slide-container"><div class="title-section"><div class="accent-shape shape-1"></div><div class="title-text"><p>第5章③ ケーススタディ：古村大和氏</p></div><div class="title-accent"></div></div><div class="content-section"><div class="case-points"><div class="case-point"><div class="point-number">1</div><div class="point-icon"><i class="fas fa-globe-asia"></i></div><div class="point-content"><div class="point-title"><p>原体験</p></div><div class="point-text"><p>幼少期をニューヨークで過ごし、帰国後に日本の文化や教育環境に大きなカルチャーショックを受けた経験。二つの文化間で揺れ動いたアイデンティティ形成期の混乱が強烈な印象として残る。</p></div></div></div><div class="case-point"><div class="point-number">2</div><div class="point-icon"><i class="fas fa-route"></i></div><div class="point-content"><div class="point-title"><p>展開</p></div><div class="point-text"><p>この経験を「roots（根）」や「core memory（核となる記憶）」として言語化。自分のアイデンティティの軸として認識することで、その後の人生選択の判断基準として活用するようになる。</p></div></div></div><div class="case-point"><div class="point-number">3</div><div class="point-icon"><i class="fas fa-hands-helping"></i></div><div class="point-content"><div class="point-title"><p>価値創造</p></div><div class="point-text"><p>異文化理解や橋渡しを重視する価値観が形成され、多様なバックグラウンドを持つ人々をつなぐ表現活動や社会活動へと波及。文化的多様性を活かした独自の視点からの貢献。</p></div></div></div><div class="case-point"><div class="point-number">4</div><div class="point-icon"><i class="fas fa-lightbulb"></i></div><div class="point-content"><div class="point-title"><p>学び</p></div><div class="point-text"><p>幼少期のコアメモリー（原体験）が自覚され言語化されることで、長期的な進路選択や人生の方向性を一貫して導く羅針盤となる。混乱した経験が、むしろ強みとなって独自の価値提供に転換した例。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        background-color: #f8fafc;        color: #1e293b;        overflow: hidden;        position: relative;    }    .title-section {        width: 340px;        background-color: #1a365d;        color: white;        padding: 50px 40px;        display: flex;        flex-direction: column;        justify-content: center;        position: relative;    }    .title-text {        font-size: 36px;        font-weight: 700;        line-height: 1.3;        position: relative;        z-index: 10;    }    .title-accent {        height: 6px;        width: 60px;        background-color: #f59e0b;        margin-top: 20px;        margin-bottom: 15px;    }    .content-section {        flex: 1;        padding: 40px 50px;        display: flex;        flex-direction: column;        justify-content: center;    }    .case-points {        display: flex;        flex-direction: column;        gap: 20px;    }    .case-point {        display: flex;        align-items: flex-start;        background-color: #f1f5f9;        border-radius: 8px;        padding: 16px;        position: relative;    }    .point-icon {        background-color: #1a365d;        color: white;        width: 50px;        height: 50px;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        font-size: 24px;        margin-right: 20px;        flex-shrink: 0;    }    .point-content {        flex: 1;    }    .point-title {        font-size: 20px;        font-weight: 700;        color: #1a365d;        margin-bottom: 8px;    }    .point-text {        font-size: 16px;        line-height: 1.5;    }    .point-number {        position: absolute;        top: -10px;        left: -10px;        background-color: #f59e0b;        color: white;        width: 28px;        height: 28px;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        font-weight: 700;        font-size: 16px;    }    .accent-shape {        position: absolute;        background-color: #2563eb;        border-radius: 50%;        opacity: 0.1;        z-index: 1;    }    .shape-1 {        width: 180px;        height: 180px;        bottom: -60px;        left: -30px;    }
</style>
