<template>
  <SlidePageWrapper slide-id="B0899XW4CQ" page-title="キーワード・用語集／キーセンテンス" :current-page="19" :total-pages="20">
<div class="slide-container"><div class="title-section"><div class="accent-shape shape-1"></div><div class="title-text"><p>キーワード・用語集／キーセンテンス</p></div><div class="title-accent"></div></div><div class="content-section"><div class="glossary-section"><div class="section-title"><div class="section-icon"><i class="fas fa-book-open"></i></div><p>キーワード・重要用語</p></div><div class="keyword-grid"><div class="keyword-item"><p><span class="keyword-highlight">原体験ドリブン</span>：人生の答えの9割が原体験にある</p></div><div class="keyword-item"><p><span class="keyword-highlight">原体験ジャーニー</span>：原体験を探る旅</p></div><div class="keyword-item"><p><span class="keyword-highlight">無意識</span>：思考・行動の95%を占める</p></div><div class="keyword-item"><p><span class="keyword-highlight">自分だけの軸</span>：原体験から導かれる価値観</p></div><div class="keyword-item"><p><span class="keyword-highlight">動機の深さ</span>：テンション→モチベ→ミッション→無意識</p></div><div class="keyword-item"><p><span class="keyword-highlight">5項目ワーク</span>：原体験を探るための5つの質問</p></div><div class="keyword-item"><p><span class="keyword-highlight">自己/ペア/ふり返りワーク</span>：3種の実践法</p></div><div class="keyword-item"><p><span class="keyword-highlight">Being/Doing</span>：在り方と行動の概念</p></div><div class="keyword-item"><p><span class="keyword-highlight">原体験バズーカ</span>：説得力・巻き込み力・貫通力</p></div><div class="keyword-item"><p><span class="keyword-highlight">コアメモリー</span>：中心となる記憶・原体験</p></div><div class="keyword-item"><p><span class="keyword-highlight">ブラックヒストリー</span>：否定的だが重要な経験</p></div><div class="keyword-item"><p><span class="keyword-highlight">言語化</span>：原体験を言葉にする作業</p></div></div></div><div class="keysentences"><div class="section-title"><div class="section-icon"><i class="fas fa-quote-right"></i></div><p>キーセンテンス</p></div><div class="sentence-list"><div class="sentence-item"><div class="sentence-icon"><i class="fas fa-map-marker-alt"></i></div><p>「人生の答えの大半は自分の原体験の中にある」</p></div><div class="sentence-item"><div class="sentence-icon"><i class="fas fa-compass"></i></div><p>「原体験はブレない『自分だけの軸』になる」</p></div><div class="sentence-item"><div class="sentence-icon"><i class="fas fa-pen"></i></div><p>「言語化が第一歩」</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        background-color: #f8fafc;        color: #1e293b;        overflow: hidden;        position: relative;    }    .title-section {        width: 340px;        background-color: #1a365d;        color: white;        padding: 50px 40px;        display: flex;        flex-direction: column;        justify-content: center;        position: relative;    }    .title-text {        font-size: 36px;        font-weight: 700;        line-height: 1.3;        position: relative;        z-index: 10;    }    .title-accent {        height: 6px;        width: 60px;        background-color: #f59e0b;        margin-top: 20px;        margin-bottom: 15px;    }    .content-section {        flex: 1;        padding: 40px 50px;        display: flex;        flex-direction: column;        justify-content: space-between;    }    .glossary-section {        margin-bottom: 30px;    }    .section-title {        font-size: 22px;        font-weight: 700;        color: #1a365d;        display: flex;        align-items: center;        margin-bottom: 15px;    }    .section-icon {        color: #f59e0b;        font-size: 24px;        margin-right: 12px;    }    .keyword-grid {        display: grid;        grid-template-columns: repeat(3, 1fr);        gap: 12px;    }    .keyword-item {        background-color: #e2e8f0;        border-radius: 6px;        padding: 8px 12px;        font-size: 15px;    }    .keyword-highlight {        color: #1a365d;        font-weight: 700;    }    .keysentences {        margin-top: 30px;    }    .sentence-list {        display: flex;        flex-direction: column;        gap: 15px;    }    .sentence-item {        background-color: #1a365d;        color: white;        border-radius: 8px;        padding: 15px 20px;        font-size: 18px;        font-weight: 500;        display: flex;        align-items: center;    }    .sentence-icon {        color: #f59e0b;        font-size: 24px;        margin-right: 15px;        flex-shrink: 0;    }    .accent-shape {        position: absolute;        background-color: #2563eb;        border-radius: 50%;        opacity: 0.1;        z-index: 1;    }    .shape-1 {        width: 180px;        height: 180px;        bottom: -60px;        left: -30px;    }
</style>
