<template>
  <SlidePageWrapper slide-id="B0899XW4CQ" page-title="本書の概要と対象読者" :current-page="2" :total-pages="20">
<div class="slide-container"><div class="title-section"><div class="accent-shape shape-1"></div><div class="title-text"><p>本書の概要と対象読者</p></div><div class="title-accent"></div></div><div class="content-section"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-book-open"></i></div><div class="bullet-text"><div class="bullet-heading"><p>主題</p></div><div class="bullet-content"><p>幼少期〜現在の強い体験＝原体験を掘り下げ、ブレない『自分だけの軸』を言語化・活用する方法論</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-brain"></i></div><div class="bullet-text"><div class="bullet-heading"><p>背景</p></div><div class="bullet-content"><p>思考・行動の多くは無意識（約95%）に影響される→外部要因より自分の原体験が羅針盤</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-users"></i></div><div class="bullet-text"><div class="bullet-heading"><p>対象</p></div><div class="bullet-content"><p>学生/就活生, 転職・キャリア迷子, 起業家/個人事業主, マネージャー, クリエイター, 自分探し中の人</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-chart-line"></i></div><div class="bullet-text"><div class="bullet-heading"><p>期待される変化</p></div><div class="bullet-content"><p>迷いが減る/決断が早くなる/自己PRや志望動機・起業のWHYが一貫し、共感と説得力が高まる</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        background-color: #f8fafc;        color: #1e293b;        overflow: hidden;        position: relative;    }    .title-section {        width: 340px;        background-color: #1a365d;        color: white;        padding: 50px 40px;        display: flex;        flex-direction: column;        justify-content: center;        position: relative;    }    .title-text {        font-size: 36px;        font-weight: 700;        line-height: 1.3;        position: relative;        z-index: 10;    }    .title-accent {        height: 6px;        width: 60px;        background-color: #f59e0b;        margin-top: 20px;        margin-bottom: 15px;    }    .content-section {        flex: 1;        padding: 50px 60px;        display: flex;        flex-direction: column;        justify-content: center;    }    .bullet-item {        margin-bottom: 24px;        display: flex;        align-items: flex-start;    }    .bullet-icon {        color: #1a365d;        font-size: 24px;        margin-right: 16px;        margin-top: 2px;    }    .bullet-text {        flex: 1;    }    .bullet-heading {        font-weight: 700;        font-size: 20px;        color: #1a365d;        margin-bottom: 6px;    }    .bullet-content {        font-size: 18px;        line-height: 1.5;    }    .accent-shape {        position: absolute;        background-color: #2563eb;        border-radius: 50%;        opacity: 0.1;        z-index: 1;    }    .shape-1 {        width: 180px;        height: 180px;        bottom: -60px;        left: -30px;    }
</style>
