<template>
  <SlidePageWrapper slide-id="B0899XW4CQ" page-title="第1章① 原体験とは何か" :current-page="4" :total-pages="20">
<div class="slide-container"><div class="title-section"><div class="accent-shape shape-1"></div><div class="title-text"><p>第1章① 原体験とは何か</p></div><div class="title-accent"></div></div><div class="content-section"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-fingerprint"></i></div><div class="bullet-text"><div class="bullet-heading"><p>定義</p></div><div class="bullet-content"><p>強い感情を伴う印象的な出来事の記憶（幼少期〜現在）。無意識下で価値観・意思決定の土台になる『自分のルーツ』</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-brain"></i></div><div class="bullet-text"><div class="bullet-heading"><p>特徴</p></div><div class="bullet-content"><p>個別性が高い/ポジ・ネガ両方/繰り返しパターン化/幼少期（3歳前後）に起点があることが多い</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-lightbulb"></i></div><div class="bullet-text"><div class="bullet-heading"><p>無意識の影響</p></div><div class="bullet-content"><p>思考・行動の95%が無意識に由来→原体験を自覚化すると選択が一貫する</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-layer-group"></i></div><div class="bullet-text"><div class="bullet-heading"><p>動機の4段階</p></div><div class="bullet-content"><p>①テンション（一時的気分）②モチベーション（原体験と連動）③ミッション（原体験から導かれる）④無意識（原体験そのもの）</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        background-color: #f8fafc;        color: #1e293b;        overflow: hidden;        position: relative;    }    .title-section {        width: 340px;        background-color: #1a365d;        color: white;        padding: 50px 40px;        display: flex;        flex-direction: column;        justify-content: center;        position: relative;    }    .title-text {        font-size: 36px;        font-weight: 700;        line-height: 1.3;        position: relative;        z-index: 10;    }    .title-accent {        height: 6px;        width: 60px;        background-color: #f59e0b;        margin-top: 20px;        margin-bottom: 15px;    }    .content-section {        flex: 1;        padding: 50px 60px;        display: flex;        flex-direction: column;        justify-content: center;    }    .bullet-item {        margin-bottom: 24px;        display: flex;        align-items: flex-start;    }    .bullet-icon {        color: #1a365d;        font-size: 24px;        margin-right: 16px;        margin-top: 2px;    }    .bullet-text {        flex: 1;    }    .bullet-heading {        font-weight: 700;        font-size: 20px;        color: #1a365d;        margin-bottom: 6px;    }    .bullet-content {        font-size: 18px;        line-height: 1.5;    }    .accent-shape {        position: absolute;        background-color: #2563eb;        border-radius: 50%;        opacity: 0.1;        z-index: 1;    }    .shape-1 {        width: 180px;        height: 180px;        bottom: -60px;        left: -30px;    }
</style>
