<template>
  <SlidePageWrapper slide-id="B0899XW4CQ" page-title="第1章② 原体験の重要性（なぜ軸になるのか）" :current-page="5" :total-pages="20">
<div class="slide-container"><div class="title-section"><div class="accent-shape shape-1"></div><div class="title-text"><p>第1章② 原体験の重要性（なぜ軸になるのか）</p></div><div class="title-accent"></div></div><div class="content-section"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-compass"></i></div><div class="bullet-text"><div class="bullet-heading"><p>内発的エネルギー源</p></div><div class="bullet-content"><p>外部環境や他者評価に左右されにくい、自分だけの原動力となる</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-balance-scale"></i></div><div class="bullet-text"><div class="bullet-heading"><p>ブレない選択基準</p></div><div class="bullet-content"><p>進学/就職/転職/起業/人間関係など、人生の重要な分岐点での判断軸になる</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-bolt"></i></div><div class="bullet-text"><div class="bullet-heading"><p>共感と継続の源泉</p></div><div class="bullet-content"><p>説得力・共感力・継続力が高まる（あなたにしかないストーリー=WHYがあるから）</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-user-circle"></i></div><div class="bullet-text"><div class="bullet-heading"><p>著者の事例</p></div><div class="bullet-content"><p>熱中体験（音楽・映像）→VJ/デザイン活動→ベンチャー関与→起業志向へと一貫した熱量で展開</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        background-color: #f8fafc;        color: #1e293b;        overflow: hidden;        position: relative;    }    .title-section {        width: 340px;        background-color: #1a365d;        color: white;        padding: 50px 40px;        display: flex;        flex-direction: column;        justify-content: center;        position: relative;    }    .title-text {        font-size: 36px;        font-weight: 700;        line-height: 1.3;        position: relative;        z-index: 10;    }    .title-accent {        height: 6px;        width: 60px;        background-color: #f59e0b;        margin-top: 20px;        margin-bottom: 15px;    }    .content-section {        flex: 1;        padding: 50px 60px;        display: flex;        flex-direction: column;        justify-content: center;    }    .bullet-item {        margin-bottom: 24px;        display: flex;        align-items: flex-start;    }    .bullet-icon {        color: #1a365d;        font-size: 24px;        margin-right: 16px;        margin-top: 2px;    }    .bullet-text {        flex: 1;    }    .bullet-heading {        font-weight: 700;        font-size: 20px;        color: #1a365d;        margin-bottom: 6px;    }    .bullet-content {        font-size: 18px;        line-height: 1.5;    }    .accent-shape {        position: absolute;        background-color: #2563eb;        border-radius: 50%;        opacity: 0.1;        z-index: 1;    }    .shape-1 {        width: 180px;        height: 180px;        bottom: -60px;        left: -30px;    }
</style>
