<template>
  <SlidePageWrapper slide-id="B0899XW4CQ" page-title="第2章① 自己ワークの概要" :current-page="7" :total-pages="20">
<div class="slide-container"><div class="title-section"><div class="accent-shape shape-1"></div><div class="title-text"><p>第2章① 自己ワークの概要</p></div><div class="title-accent"></div></div><div class="content-section"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-bullseye"></i></div><div class="bullet-text"><div class="bullet-heading"><p>目的</p></div><div class="bullet-content"><p>無意識に沈む価値観と行動原理を自覚化する</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-toolbox"></i></div><div class="bullet-text"><div class="bullet-heading"><p>準備</p></div><div class="bullet-content"><p>ノート/ペン/静かな環境/タイマー（推奨）</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-heart"></i></div><div class="bullet-text"><div class="bullet-heading"><p>姿勢</p></div><div class="bullet-content"><p>正解探しより"本音"を拾う。比べない・飾らない</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-gem"></i></div><div class="bullet-text"><div class="bullet-heading"><p>成果物</p></div><div class="bullet-content"><p>原体験メモ、価値観キーワード、暫定ミッション案</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        background-color: #f8fafc;        color: #1e293b;        overflow: hidden;        position: relative;    }    .title-section {        width: 340px;        background-color: #1a365d;        color: white;        padding: 50px 40px;        display: flex;        flex-direction: column;        justify-content: center;        position: relative;    }    .title-text {        font-size: 36px;        font-weight: 700;        line-height: 1.3;        position: relative;        z-index: 10;    }    .title-accent {        height: 6px;        width: 60px;        background-color: #f59e0b;        margin-top: 20px;        margin-bottom: 15px;    }    .content-section {        flex: 1;        padding: 50px 60px;        display: flex;        flex-direction: column;        justify-content: center;    }    .bullet-item {        margin-bottom: 24px;        display: flex;        align-items: flex-start;    }    .bullet-icon {        color: #1a365d;        font-size: 24px;        margin-right: 16px;        margin-top: 2px;    }    .bullet-text {        flex: 1;    }    .bullet-heading {        font-weight: 700;        font-size: 20px;        color: #1a365d;        margin-bottom: 6px;    }    .bullet-content {        font-size: 18px;        line-height: 1.5;    }    .accent-shape {        position: absolute;        background-color: #2563eb;        border-radius: 50%;        opacity: 0.1;        z-index: 1;    }    .shape-1 {        width: 180px;        height: 180px;        bottom: -60px;        left: -30px;    }
</style>
