<template>
  <SlidePageWrapper slide-id="B0899XW4CQ" page-title="第2章③ 深掘りの実践ポイント" :current-page="9" :total-pages="20">
<div class="slide-container"><div class="title-section"><div class="accent-shape shape-1"></div><div class="title-text"><p>第2章③ 深掘りの実践ポイント</p></div><div class="title-accent"></div></div><div class="content-section"><div class="steps-list"><div class="step-item"><div class="step-number">1</div><div class="step-content"><div class="step-text"><p>各項目をまず3〜5分で荒く→後で深掘り</p></div></div></div><div class="step-item"><div class="step-number">2</div><div class="step-content"><div class="step-text"><p>『なぜ?』を最低5回繰り返す</p></div></div></div><div class="step-item"><div class="step-number">3</div><div class="step-content"><div class="step-text"><p>3歳前後〜中学期までの出来事も探索</p></div></div></div><div class="step-item"><div class="step-number">4</div><div class="step-content"><div class="step-text"><p>五感と言葉を具体化（台詞/音/匂い/風景）</p></div></div></div><div class="step-item"><div class="step-number">5</div><div class="step-content"><div class="step-text"><p>反復と熟成（時間を置く→再編集）</p></div></div></div><div class="step-item"><div class="step-number">6</div><div class="step-content"><div class="step-text"><p>ふり返りワークで共通テーマを抽出</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        background-color: #f8fafc;        color: #1e293b;        overflow: hidden;        position: relative;    }    .title-section {        width: 340px;        background-color: #1a365d;        color: white;        padding: 50px 40px;        display: flex;        flex-direction: column;        justify-content: center;        position: relative;    }    .title-text {        font-size: 36px;        font-weight: 700;        line-height: 1.3;        position: relative;        z-index: 10;    }    .title-accent {        height: 6px;        width: 60px;        background-color: #f59e0b;        margin-top: 20px;        margin-bottom: 15px;    }    .content-section {        flex: 1;        padding: 40px 50px;        display: flex;        flex-direction: column;        justify-content: center;    }    .steps-list {        display: flex;        flex-direction: column;        gap: 16px;    }    .step-item {        display: flex;        align-items: flex-start;    }    .step-number {        background-color: #1a365d;        color: white;        width: 36px;        height: 36px;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        font-weight: 700;        font-size: 18px;        margin-right: 16px;        flex-shrink: 0;    }    .step-content {        flex: 1;        padding-top: 5px;    }    .step-text {        font-size: 18px;        line-height: 1.5;    }    .accent-shape {        position: absolute;        background-color: #2563eb;        border-radius: 50%;        opacity: 0.1;        z-index: 1;    }    .shape-1 {        width: 180px;        height: 180px;        bottom: -60px;        left: -30px;    }
</style>
