<template>
  <SlidePageWrapper slide-id="B08CMN4R97" page-title="セルフケアの道具箱 解説スライド" :current-page="1" :total-pages="23">
<div class="slide-container"><img alt="セルフケアの背景画像" class="cover-image" src="https://media-public.canva.com/K2wBI/MAGjYiK2wBI/1/tl.jpg"/><div class="content-wrapper"><h1 class="main-title"><p>セルフケアの道具箱</p></h1><h2 class="subtitle"><p>ストレスと上手につきあう100のワーク</p></h2><div class="divider"></div><div class="author"><p>伊藤絵美・細川貂々</p></div><div class="publisher"><p>晶文社</p></div><div class="divider"></div><div class="presentation-info"><p>書籍解説スライド：全10章・100ワーク</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;            overflow: hidden;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #f9f4ee;            display: flex;            flex-direction: column;            align-items: center;            justify-content: center;            position: relative;        }        .cover-image {            width: 100%;            height: 100%;            position: absolute;            top: 0;            left: 0;            object-fit: cover;            opacity: 0.85;        }        .content-wrapper {            position: relative;            z-index: 10;            width: 80%;            background-color: rgba(255, 255, 255, 0.85);            padding: 3rem;            border-radius: 1rem;            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);        }        .main-title {            color: #4b5563;            font-weight: 700;            font-size: 3rem;            line-height: 1.2;            margin-bottom: 0.5rem;            text-align: center;        }        .subtitle {            color: #6b7280;            font-size: 1.8rem;            margin-bottom: 2rem;            text-align: center;        }        .author {            color: #374151;            font-size: 1.4rem;            margin-bottom: 0.5rem;            text-align: center;        }        .publisher {            color: #6b7280;            font-size: 1.2rem;            margin-bottom: 1rem;            text-align: center;        }        .divider {            width: 50%;            height: 2px;            background-color: #e5e7eb;            margin: 1rem auto;        }        .presentation-info {            color: #6b7280;            font-size: 1rem;            text-align: center;            margin-top: 1.5rem;        }
</style>
