<template>
  <SlidePageWrapper slide-id="B08CMN4R97" page-title="セルフケアの道具箱 解説スライド" :current-page="2" :total-pages="23">
<div class="slide-container"><div class="content-wrapper"><h1 class="main-title"><p>本書の概要・執筆背景・対象読者・得られること</p></h1><div class="bullet-list"><div class="bullet-item"><div class="bullet-icon bg-icon-1"><i class="fas fa-pen"></i></div><div class="bullet-text"><p class="bullet-title">執筆背景</p><p>著者30年の臨床経験から「回復の鍵は継続的セルフケア」にあると痛感。誰もが実践できる100ワークを平易に体系化。</p></div></div><div class="bullet-item"><div class="bullet-icon bg-icon-2"><i class="fas fa-bullseye"></i></div><div class="bullet-text"><p class="bullet-title">目的</p><p>ストレスに気づき、外在化し、対処を増やし、自己回復力を高める。</p></div></div><div class="bullet-item"><div class="bullet-icon bg-icon-3"><i class="fas fa-users"></i></div><div class="bullet-text"><p class="bullet-title">対象読者</p><p>ストレス・生きづらさを感じるすべての人。専門知識なしでOK。</p></div></div><div class="bullet-item"><div class="bullet-icon bg-icon-4"><i class="fas fa-gift"></i></div><div class="bullet-text"><p class="bullet-title">得られるベネフィット</p><p>マインドフルネス／コーピング／ストレス日記／サポート活用／スキーマの理解と修正。</p></div></div><div class="bullet-item"><div class="bullet-icon bg-icon-5"><i class="fas fa-star"></i></div><div class="bullet-text"><p class="bullet-title">セルフケアの重要性</p><p>援助は一時的。日々のセルフケア継続が回復力・耐性を育てる。</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;            overflow: hidden;        }        .slide-container {            width: 1280px;            min-height: 720px;            background-color: #f9f4ee;            display: flex;            flex-direction: column;            align-items: center;            justify-content: center;            position: relative;        }        .content-wrapper {            position: relative;            z-index: 10;            width: 90%;            display: flex;            flex-direction: column;            background-color: rgba(255, 255, 255, 0.85);            padding: 2rem 3rem;            border-radius: 1rem;            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);        }        .main-title {            color: #4b5563;            font-weight: 700;            font-size: 2.2rem;            margin-bottom: 1.5rem;            text-align: center;            border-bottom: 2px solid #e5e7eb;            padding-bottom: 0.75rem;        }        .bullet-list {            display: flex;            flex-direction: column;            gap: 0.75rem;        }        .bullet-item {            display: flex;            align-items: flex-start;            padding: 0.5rem;            border-radius: 0.5rem;        }        .bullet-item:nth-child(odd) {            background-color: rgba(243, 244, 246, 0.6);        }        .bullet-icon {            flex-shrink: 0;            width: 2rem;            height: 2rem;            display: flex;            align-items: center;            justify-content: center;            margin-right: 1rem;            border-radius: 50%;            color: white;        }        .bullet-text {            flex-grow: 1;        }        .bullet-text p {            margin: 0;            line-height: 1.6;        }        .bg-icon-1 { background-color: #3b82f6; }        .bg-icon-2 { background-color: #10b981; }        .bg-icon-3 { background-color: #f59e0b; }        .bg-icon-4 { background-color: #ef4444; }        .bg-icon-5 { background-color: #8b5cf6; }                .bullet-title {            font-weight: 700;            color: #1f2937;            margin-bottom: 0.25rem;        }
</style>
