<template>
  <SlidePageWrapper slide-id="B01LYN9D9S" page-title="「言葉にできる」は武器になる。" :current-page="1" :total-pages="20">
<div class="slide-container"><div class="book-cover"><p class="book-title"><span class="quote-mark">「</span>言葉にできる<span class="quote-mark">」</span>は武器になる。</p><p class="book-subtitle">内なる言葉を磨き、外に向かう言葉を強くする</p><p class="book-author">著者：梅田 悟司</p><p class="book-publisher">日本経済新聞出版</p><p class="book-category">用途：ビジネス・企画・マネジメント・創作・就活・プレゼン</p><p class="book-slide-info">本要約スライド（全20ページ）</p><div class="bottom-border"></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            overflow: hidden;            position: relative;            background-color: #f8f9fa;            display: flex;            flex-direction: column;        }        .book-cover {            flex: 1;            display: flex;            flex-direction: column;            justify-content: center;            align-items: center;            padding: 40px;            text-align: center;            background-color: #f8f9fa;            position: relative;        }        .book-cover::before {            content: "";            position: absolute;            top: 0;            left: 0;            right: 0;            height: 8px;            background-color: #1a365d;        }        .book-title {            font-family: 'Noto Serif JP', serif;            font-weight: 700;            font-size: 64px;            color: #1a365d;            margin-bottom: 24px;            line-height: 1.3;        }        .book-subtitle {            font-family: 'Noto Serif JP', serif;            font-size: 28px;            color: #4a5568;            margin-bottom: 48px;            line-height: 1.5;        }        .book-author {            font-family: 'Noto Sans JP', sans-serif;            font-size: 24px;            color: #2d3748;            margin-bottom: 16px;        }        .book-publisher {            font-family: 'Noto Sans JP', sans-serif;            font-size: 18px;            color: #4a5568;            margin-bottom: 40px;        }        .book-category {            font-family: 'Noto Sans JP', sans-serif;            font-size: 16px;            color: #718096;            max-width: 600px;            line-height: 1.6;            margin-bottom: 24px;        }        .book-slide-info {            font-family: 'Noto Sans JP', sans-serif;            font-size: 16px;            color: #718096;            background-color: #e2e8f0;            padding: 8px 20px;            border-radius: 20px;        }        .quote-mark {            font-family: 'Noto Serif JP', serif;            font-size: 24px;            color: #4299e1;            margin: 0 4px;        }        .bottom-border {            position: absolute;            bottom: 0;            left: 0;            right: 0;            height: 8px;            background-color: #1a365d;        }
</style>
