<template>
  <SlidePageWrapper slide-id="B01LYN9D9S" page-title="「言葉にできる」は武器になる。 - 第2部まとめ：思考サイクルの実践" :current-page="13" :total-pages="20">
<div class="slide-container"><div class="content-area"><div class="header"><p class="title">第2部まとめ：思考サイクルの実践</p></div><div class="main-content"><div class="bullet-list"><p class="bullet-item"><span class="highlight">運用ルール：</span>週2回、午前中に"自分会議"を60分確保。頭が冴えている時間帯で、無理なく継続できる頻度を意識する。</p><p class="bullet-item"><span class="highlight">道具：</span>A4紙/付箋/太ペン。デジタルではなくアナログツールが思考の広がりを促進する。記録を蓄積し再利用することで、思考の積み重ねが可能になる。</p><p class="bullet-item"><span class="highlight">KPI：</span>素材数（内なる言葉の量）／グループ数／アクションの質。量を測ることで、思考の広がりを可視化できる。</p><p class="bullet-item"><span class="highlight">継続のコツ：</span>小さく早く回し、都度アウトプットで検証。完璧主義を手放し、実践と検証の繰り返しで磨く。</p></div><div class="practice-box"><p class="practice-title">実践のためのチェックポイント</p><div class="sub-bullet"><p class="sub-bullet-item">すべての手順を一度に完璧にこなそうとせず、まずは「書き出し→T字型思考法→グルーピング」の3ステップから始める</p><p class="sub-bullet-item">アウトプットしたものを人に見せる機会を意図的に作る</p><p class="sub-bullet-item">内なる言葉の解像度を上げるほど、外に向かう言葉が洗練されていくことを実感する</p><p class="sub-bullet-item">思考サイクルを回すことで、自分特有の思考の癖や強みが見えてくる</p></div></div></div><div class="bottom-border"></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            overflow: hidden;            position: relative;            background-color: #f8f9fa;            display: flex;            flex-direction: column;        }        .content-area {            flex: 1;            display: flex;            flex-direction: column;            padding: 40px 80px;        }        .header {            position: relative;            padding-bottom: 16px;            margin-bottom: 24px;            border-bottom: 2px solid #e2e8f0;        }        .header::before {            content: "";            position: absolute;            top: -40px;            left: -80px;            right: -80px;            height: 8px;            background-color: #1a365d;        }        .title {            font-family: 'Noto Serif JP', serif;            font-weight: 700;            font-size: 36px;            color: #1a365d;            margin-bottom: 8px;        }        .section-title {            font-family: 'Noto Sans JP', sans-serif;            font-weight: 700;            font-size: 22px;            color: #2d3748;            margin-top: 24px;            margin-bottom: 12px;        }        .main-content {            flex: 1;        }        .bullet-list {            padding-left: 0;            margin-top: 8px;            margin-bottom: 24px;        }        .bullet-item {            position: relative;            padding-left: 24px;            margin-bottom: 16px;            font-size: 18px;            line-height: 1.6;            color: #4a5568;        }        .bullet-item::before {            content: "•";            position: absolute;            left: 0;            color: #4299e1;            font-weight: bold;            font-size: 20px;        }        .sub-bullet {            padding-left: 24px;            margin-top: 8px;        }        .sub-bullet-item {            position: relative;            padding-left: 20px;            margin-bottom: 8px;            font-size: 17px;            color: #4a5568;        }        .sub-bullet-item::before {            content: "-";            position: absolute;            left: 0;            color: #63b3ed;        }        .highlight {            color: #2b6cb0;            font-weight: 600;        }        .practice-box {            background-color: #ebf8ff;            border-left: 4px solid #4299e1;            padding: 16px;            margin: 16px 0;            border-radius: 4px;        }        .practice-title {            font-weight: 600;            color: #2b6cb0;            margin-bottom: 8px;            font-size: 18px;        }        .bottom-border {            position: absolute;            bottom: 0;            left: 0;            right: 0;            height: 8px;            background-color: #1a365d;        }
</style>
