<template>
  <SlidePageWrapper slide-id="B01LYN9D9S" page-title="「言葉にできる」は武器になる。 - 戦略2：心構えを持つ（本音をさらけ出す）" :current-page="16" :total-pages="20">
<div class="slide-container"><div class="content-area"><div class="header"></div><div class="main-content"><p class="section-badge">戦略2</p><p class="section-title">心構えを持つ</p><p class="subtitle">本音をさらけ出す</p><div class="icon-box"><i class="fas fa-heart"></i></div><p class="section-desc">技巧や表現テクニックよりも、本音と経験に根ざした言葉こそが人の心に響きます</p><div class="bullet-list"><p class="bullet-item"><span class="highlight">技巧＜本音：</span>等身大の経験・感情・価値観を前面に。</p><p class="bullet-item"><span class="highlight">"たった一人"に届ける：</span>具体的な顔に向けて書く/話す。</p><p class="bullet-item"><span class="highlight">話すように書く：</span>口語のリズムで温度を乗せる。</p><p class="bullet-item"><span class="highlight">推敲でズレ取り：</span>自分の思いから逸れていないか確認。</p></div></div><div class="bottom-border"></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;        display: flex;        flex-direction: column;    }    .content-area {        flex: 1;        display: flex;        flex-direction: column;        padding: 40px 80px;    }    .header {        position: relative;        padding-bottom: 16px;        margin-bottom: 24px;    }    .header::before {        content: "";        position: absolute;        top: -40px;        left: -80px;        right: -80px;        height: 8px;        background-color: #1a365d;    }    .main-content {        flex: 1;        display: flex;        flex-direction: column;        justify-content: center;        align-items: center;        text-align: center;    }    .section-badge {        background-color: #ebf8ff;        color: #2b6cb0;        font-weight: 600;        font-size: 18px;        padding: 6px 16px;        border-radius: 20px;        margin-bottom: 24px;        display: inline-block;    }    .section-title {        font-family: 'Noto Serif JP', serif;        font-weight: 700;        font-size: 48px;        color: #1a365d;        margin-bottom: 36px;        line-height: 1.3;        position: relative;        display: inline-block;    }    .section-title::after {        content: "";        position: absolute;        bottom: -12px;        left: 50%;        transform: translateX(-50%);        width: 80%;        height: 3px;        background-color: #4299e1;    }    .section-desc {        font-size: 22px;        color: #4a5568;        max-width: 800px;        line-height: 1.6;        margin-bottom: 36px;    }    .bullet-list {        max-width: 800px;        text-align: left;        margin-bottom: 40px;    }    .bullet-item {        position: relative;        padding-left: 28px;        margin-bottom: 18px;        font-size: 20px;        color: #4a5568;        line-height: 1.5;    }    .bullet-item::before {        content: "•";        position: absolute;        left: 0;        color: #4299e1;        font-weight: bold;        font-size: 24px;    }    .highlight {        color: #2b6cb0;        font-weight: 500;    }    .icon-box {        font-size: 64px;        color: #4299e1;        margin: 20px 0;    }    .subtitle {        font-size: 24px;        color: #718096;        margin-top: -24px;        margin-bottom: 24px;    }    .bottom-border {        position: absolute;        bottom: 0;        left: 0;        right: 0;        height: 8px;        background-color: #1a365d;    }
</style>
