<template>
  <SlidePageWrapper slide-id="B01LYN9D9S" page-title="「言葉にできる」は武器になる。 - 実践テクニック集" :current-page="17" :total-pages="20">
<div class="slide-container"><div class="content-area"><div class="header"><p class="title">実践テクニック集</p></div><div class="main-content"><div class="technique-columns"><div class="technique-column"><div class="bullet-list"><p class="bullet-item"><span class="highlight">常套句の排除：</span>「ご多忙のところ」「お世話になっております」などのビジネス定型句を、自分の言葉に置き換える。</p><div class="sub-bullet"><p class="sub-bullet-item">例：<span class="example">「この度は弊社製品をお選びいただき」→「あなたの信頼に応えます」</span></p></div><p class="bullet-item"><span class="highlight">先鋭化（推敲）：</span>一文字でも減らし、核心を際立たせる。説明過多より情報密度を重視。</p><div class="sub-bullet"><p class="sub-bullet-item">例：<span class="example">「私が思うに、おそらく〜かもしれません」→「〜だ」</span></p></div><p class="bullet-item"><span class="highlight">リズム重視：</span>音読して引っかかりを発見・除去。耳で聞いて心地よい文章に。</p></div></div><div class="technique-column"><div class="bullet-list"><p class="bullet-item"><span class="highlight">動詞へのこだわり：</span>文に躍動感を与える。一般動詞より具体的な動詞を選ぶ。</p><div class="sub-bullet"><p class="sub-bullet-item">例：<span class="example">「進める」→「やり切る」「育てる」→「開花させる」</span></p></div><p class="bullet-item"><span class="highlight">命名法：</span>「○○って、△△だ」の型で新しい意味づけを与える。</p><div class="sub-bullet"><p class="sub-bullet-item">例：<span class="example">「会議って、意思決定の場だ」「学びって、自分を裏切ることだ」</span></p></div><p class="bullet-item"><span class="highlight">似て非なる語の区別：</span>近い言葉の違いを意識し、使い分けることで解像度を上げる。</p><div class="sub-bullet"><p class="sub-bullet-item">例：<span class="example">「問題」と「課題」、「顧客」と「個客」、「解決」と「消化」</span></p></div></div></div></div></div><div class="bottom-border"></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            overflow: hidden;            position: relative;            background-color: #f8f9fa;            display: flex;            flex-direction: column;        }        .content-area {            flex: 1;            display: flex;            flex-direction: column;            padding: 40px 80px;        }        .header {            position: relative;            padding-bottom: 16px;            margin-bottom: 24px;            border-bottom: 2px solid #e2e8f0;        }        .header::before {            content: "";            position: absolute;            top: -40px;            left: -80px;            right: -80px;            height: 8px;            background-color: #1a365d;        }        .title {            font-family: 'Noto Serif JP', serif;            font-weight: 700;            font-size: 36px;            color: #1a365d;            margin-bottom: 8px;        }        .main-content {            flex: 1;            display: flex;        }        .bullet-list {            padding-left: 0;            margin-top: 8px;            margin-bottom: 24px;            flex: 1;        }        .bullet-item {            position: relative;            padding-left: 24px;            margin-bottom: 16px;            font-size: 18px;            line-height: 1.6;            color: #4a5568;        }        .bullet-item::before {            content: "•";            position: absolute;            left: 0;            color: #4299e1;            font-weight: bold;            font-size: 20px;        }        .sub-bullet {            padding-left: 24px;            margin-top: 8px;        }        .sub-bullet-item {            position: relative;            padding-left: 20px;            margin-bottom: 8px;            font-size: 17px;            color: #4a5568;        }        .sub-bullet-item::before {            content: "-";            position: absolute;            left: 0;            color: #63b3ed;        }        .highlight {            color: #2b6cb0;            font-weight: 600;        }        .example {            font-style: italic;            color: #718096;        }        .technique-columns {            display: flex;            justify-content: space-between;        }        .technique-column {            flex: 1;            margin-right: 30px;        }        .technique-column:last-child {            margin-right: 0;        }        .bottom-border {            position: absolute;            bottom: 0;            left: 0;            right: 0;            height: 8px;            background-color: #1a365d;        }
</style>
