<template>
  <SlidePageWrapper slide-id="B01LYN9D9S" page-title="「言葉にできる」は武器になる。 - キーセンテンス集" :current-page="18" :total-pages="20">
<div class="slide-container"><div class="content-area"><div class="header"><p class="title">キーセンテンス集</p></div><div class="main-content"><div class="quotes-container"><div class="quote-card"><div class="quote-icon"><i class="fas fa-quote-right"></i></div><p class="quote-text"><span class="quote-highlight">言葉は思考の上澄み。</span>深さが言葉の深さを決める。</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-quote-right"></i></div><p class="quote-text"><span class="quote-highlight">伝える前に、</span>まず意見を育てる。</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-quote-right"></i></div><p class="quote-text"><span class="quote-highlight">"人を動かす"</span>より<span class="quote-highlight">"人が動きたくなる"</span>言葉を目指す。</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-quote-right"></i></div><p class="quote-text"><span class="quote-highlight">内側の解像度が上がるほど、</span>外側は短く強くなる。</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-quote-right"></i></div><p class="quote-text"><span class="quote-highlight">型は器。</span>本音で満たして初めて機能する。</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-quote-right"></i></div><p class="quote-text"><span class="quote-highlight">たった一人に届けば、</span>やがて多くに広がる。</p></div></div></div><div class="bottom-border"></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;        display: flex;        flex-direction: column;    }    .content-area {        flex: 1;        display: flex;        flex-direction: column;        padding: 40px 80px;    }    .header {        position: relative;        padding-bottom: 16px;        margin-bottom: 24px;        border-bottom: 2px solid #e2e8f0;    }    .header::before {        content: "";        position: absolute;        top: -40px;        left: -80px;        right: -80px;        height: 8px;        background-color: #1a365d;    }    .title {        font-family: 'Noto Serif JP', serif;        font-weight: 700;        font-size: 36px;        color: #1a365d;        margin-bottom: 8px;    }    .main-content {        flex: 1;        display: flex;        flex-direction: column;    }    .quotes-container {        display: flex;        flex-wrap: wrap;        gap: 20px;    }    .quote-card {        flex: 1 1 calc(50% - 20px);        min-width: calc(50% - 20px);        position: relative;        padding: 24px 20px 20px 32px;        background-color: #ffffff;        border-left: 4px solid #4299e1;        border-radius: 4px;        box-shadow: 0 2px 5px rgba(0,0,0,0.1);    }    .quote-icon {        position: absolute;        top: -15px;        left: 12px;        width: 32px;        height: 32px;        border-radius: 50%;        background-color: #4299e1;        color: white;        display: flex;        align-items: center;        justify-content: center;    }    .quote-text {        font-family: 'Noto Serif JP', serif;        font-size: 18px;        line-height: 1.5;        color: #2d3748;        margin-bottom: 8px;    }    .quote-highlight {        color: #2b6cb0;        font-weight: 600;    }    .bottom-border {        position: absolute;        bottom: 0;        left: 0;        right: 0;        height: 8px;        background-color: #1a365d;    }
</style>
