<template>
  <SlidePageWrapper slide-id="B01LYN9D9S" page-title="「言葉にできる」は武器になる。 - 重要な概念・用語集" :current-page="19" :total-pages="20">
<div class="slide-container"><div class="content-area"><div class="header"><p class="title">重要な概念・用語集</p></div><div class="main-content"><div class="quotes-container"><div class="quote-card"><div class="quote-icon"><i class="fas fa-book"></i></div><p class="term-title">内なる言葉</p><p class="quote-text">頭の中で自問自答する際に使われる<span class="quote-highlight">思考のための言語</span>。価値観・感情・違和感など、自己との対話に使われる言葉。</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-comments"></i></div><p class="term-title">外に向かう言葉</p><p class="quote-text">会話・文章・メール・SNSなど、<span class="quote-highlight">相手に伝えるための表現</span>。内なる言葉の質が高まると、外に向かう言葉も強くなる。</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-sitemap"></i></div><p class="term-title">T字型思考法</p><p class="quote-text"><span class="quote-highlight">「なぜ？」「それで？」「本当に？」</span>の3つの問いで思考を縦に深め、横に広げ、本質に戻す手法。思考の幅と深さを拡張する。</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-sync-alt"></i></div><p class="term-title">思考サイクル</p><p class="quote-text">内なる言葉を磨く<span class="quote-highlight">7つのステップ</span>。①書き出す②T字型思考法③グルーピング④視点拡張⑤寝かせる⑥真逆⑦複眼思考の順で回す。</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-object-group"></i></div><p class="term-title">グルーピング</p><p class="quote-text">断片的な思考やキーワードを<span class="quote-highlight">意味の塊に整理</span>する作業。事実/感情/願望/課題など軸で分類し、全体像を可視化する。</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-users"></i></div><p class="term-title">複眼思考</p><p class="quote-text"><span class="quote-highlight">他者の立場になりきって</span>考える視点獲得法。顧客・上司・部下・過去の自分など、具体的な誰かの目線で見直すことで新たな気づきを得る。</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-tag"></i></div><p class="term-title">命名法</p><p class="quote-text">「○○って、△△だ」という型で<span class="quote-highlight">新たな意味づけを与える</span>手法。既存の概念に新しい解釈や価値を付与する言葉の設計術。</p></div><div class="quote-card"><div class="quote-icon"><i class="fas fa-cut"></i></div><p class="term-title">先鋭化</p><p class="quote-text">余計な言葉を削ぎ落とし<span class="quote-highlight">核心を際立たせる</span>編集作業。一語一句を吟味し、不要な説明や修飾を減らすことで言葉の強度を高める。</p></div></div></div><div class="bottom-border"></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #f8f9fa;        display: flex;        flex-direction: column;    }    .content-area {        flex: 1;        display: flex;        flex-direction: column;        padding: 40px 80px;    }    .header {        position: relative;        padding-bottom: 16px;        margin-bottom: 24px;        border-bottom: 2px solid #e2e8f0;    }    .header::before {        content: "";        position: absolute;        top: -40px;        left: -80px;        right: -80px;        height: 8px;        background-color: #1a365d;    }    .title {        font-family: 'Noto Serif JP', serif;        font-weight: 700;        font-size: 36px;        color: #1a365d;        margin-bottom: 8px;    }    .main-content {        flex: 1;        display: flex;        flex-direction: column;    }    .quotes-container {        display: flex;        flex-wrap: wrap;        gap: 20px;    }    .quote-card {        flex: 1 1 calc(50% - 20px);        min-width: calc(50% - 20px);        position: relative;        padding: 24px 20px 20px 32px;        background-color: #ffffff;        border-left: 4px solid #4299e1;        border-radius: 4px;        box-shadow: 0 2px 5px rgba(0,0,0,0.1);    }    .quote-icon {        position: absolute;        top: -15px;        left: 12px;        width: 32px;        height: 32px;        border-radius: 50%;        background-color: #4299e1;        color: white;        display: flex;        align-items: center;        justify-content: center;    }    .quote-text {        font-family: 'Noto Serif JP', serif;        font-size: 18px;        line-height: 1.5;        color: #2d3748;        margin-bottom: 8px;    }    .quote-highlight {        color: #2b6cb0;        font-weight: 600;    }    .term-title {        font-weight: 700;        color: #2b6cb0;        font-size: 20px;        margin-bottom: 4px;    }    .bottom-border {        position: absolute;        bottom: 0;        left: 0;        right: 0;        height: 8px;        background-color: #1a365d;    }
</style>
