<template>
  <SlidePageWrapper slide-id="B01LYN9D9S" page-title="「言葉にできる」は武器になる。 - 本書の概要・背景・対象読者" :current-page="2" :total-pages="20">
<div class="slide-container"><div class="content-area"><div class="header"><p class="title">本書の概要・背景・対象読者</p></div><div class="main-content"><div class="section"><p class="section-title">概要</p><p class="section-content">思考を深めて"内なる言葉"の解像度を上げ、その力を"外に向かう言葉"へ変換する実践書。</p></div><div class="section"><p class="section-title">背景</p><p class="section-content">テクニック偏重では伝わらない時代。言葉の重み・深みが人を動かす。</p></div><div class="section"><p class="section-title">対象読者</p><p class="section-content bullet-list"><span class="bullet-item">企画職/営業/管理職/研究者/学生/クリエイター/就活生。</span></p></div><div class="section"><p class="section-title">得られる気づき</p><p class="section-content bullet-list"><span class="bullet-item"><span class="highlight">思考→内なる言葉→外に向かう言葉</span>の順序</span><span class="bullet-item"><span class="highlight">T字型思考法</span>（なぜ？/それで？/本当に？）</span><span class="bullet-item"><span class="highlight">7つの思考サイクル</span>による内なる言葉の強化</span><span class="bullet-item"><span class="highlight">型×心構え</span>による言葉の力の引き出し方</span></p></div></div><div class="bottom-border"></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            overflow: hidden;            position: relative;            background-color: #f8f9fa;            display: flex;            flex-direction: column;        }        .content-area {            flex: 1;            display: flex;            flex-direction: column;            padding: 40px 80px;        }        .header {            position: relative;            padding-bottom: 16px;            margin-bottom: 24px;            border-bottom: 2px solid #e2e8f0;        }        .header::before {            content: "";            position: absolute;            top: -40px;            left: -80px;            right: -80px;            height: 8px;            background-color: #1a365d;        }        .title {            font-family: 'Noto Serif JP', serif;            font-weight: 700;            font-size: 36px;            color: #1a365d;            margin-bottom: 8px;        }        .section-title {            font-family: 'Noto Sans JP', sans-serif;            font-weight: 700;            font-size: 22px;            color: #2d3748;            margin-top: 24px;            margin-bottom: 12px;        }        .section-content {            font-family: 'Noto Sans JP', sans-serif;            font-size: 18px;            color: #4a5568;            line-height: 1.7;            margin-bottom: 8px;        }        .bullet-list {            padding-left: 24px;        }        .bullet-item {            position: relative;            padding-left: 16px;            margin-bottom: 8px;        }        .bullet-item::before {            content: "•";            position: absolute;            left: 0;            color: #4299e1;            font-weight: bold;        }        .highlight {            color: #1a365d;            font-weight: 500;        }        .bottom-border {            position: absolute;            bottom: 0;            left: 0;            right: 0;            height: 8px;            background-color: #1a365d;        }
</style>
