<template>
  <SlidePageWrapper slide-id="B01LYN9D9S" page-title="「言葉にできる」は武器になる。 - 目次（全体構成の大枠）" :current-page="3" :total-pages="20">
<div class="slide-container"><div class="content-area"><div class="header"><p class="title">目次（全体構成の大枠）</p></div><div class="main-content"><div class="section"><p class="section-title">第1部 内なる言葉と向き合う<span class="section-pages">（p4-6）</span></p><p class="section-content">言葉で評価される時代／「外に向かう言葉」と「内なる言葉」／<span class="highlight">言葉は思考の上澄み</span></p></div><div class="section"><p class="section-title">第2部 内なる言葉を磨く思考サイクル<span class="section-pages">（p7-13）</span></p><p class="section-content">7つのステップ／<span class="highlight">T字型思考法</span>／グルーピング／視点拡張／寝かせる／真逆思考／複眼思考</p></div><div class="section"><p class="section-title">第3部 思いをさらけ出す2つの戦略<span class="section-pages">（p14-17）</span></p><p class="section-content">戦略1：<span class="highlight">日本語の「型」を知る</span>（たとえる・繰り返す・対句・断定・感じる言葉）<br/>戦略2：<span class="highlight">言葉を生み出す「心構え」を持つ</span>（本音・等身大・実践テクニック）</p></div><div class="section"><p class="section-title">まとめ<span class="section-pages">（p18-20）</span></p><p class="section-content">キーセンテンス／重要概念・用語集／「言葉にできる」が武器になる（締め）</p></div></div><div class="bottom-border"></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            overflow: hidden;            position: relative;            background-color: #f8f9fa;            display: flex;            flex-direction: column;        }        .content-area {            flex: 1;            display: flex;            flex-direction: column;            padding: 40px 80px;        }        .header {            position: relative;            padding-bottom: 16px;            margin-bottom: 24px;            border-bottom: 2px solid #e2e8f0;        }        .header::before {            content: "";            position: absolute;            top: -40px;            left: -80px;            right: -80px;            height: 8px;            background-color: #1a365d;        }        .title {            font-family: 'Noto Serif JP', serif;            font-weight: 700;            font-size: 36px;            color: #1a365d;            margin-bottom: 8px;        }        .section-title {            font-family: 'Noto Sans JP', sans-serif;            font-weight: 700;            font-size: 24px;            color: #2d3748;            margin-top: 24px;            margin-bottom: 12px;            display: flex;            justify-content: space-between;            align-items: center;        }        .section-pages {            font-size: 18px;            color: #4a5568;            font-weight: normal;        }        .section-content {            font-family: 'Noto Sans JP', sans-serif;            font-size: 18px;            color: #4a5568;            line-height: 1.7;            margin-left: 24px;            margin-bottom: 16px;        }        .highlight {            color: #1a365d;            font-weight: 500;        }        .bottom-border {            position: absolute;            bottom: 0;            left: 0;            right: 0;            height: 8px;            background-color: #1a365d;        }
</style>
