<template>
  <SlidePageWrapper slide-id="B01LYN9D9S" page-title="「言葉にできる」は武器になる。 - 言葉は思考の上澄み／内なる言葉を磨く重要性" :current-page="6" :total-pages="20">
<div class="slide-container"><div class="content-area"><div class="header"><p class="title">言葉は思考の上澄み／内なる言葉を磨く重要性</p></div><div class="main-content"><div class="quote"><p>「言葉は思考の上澄みに過ぎない」</p></div><div class="bullet-list"><p class="bullet-item"><span class="highlight">思考の質が言葉の質を決める：</span>思考が浅いまま言葉だけを磨こうとしても、表層的で軽い言葉になってしまう。どれだけ言語技術を高めても、中身が伴っていなければ「口先だけ」という印象を与える。</p><p class="bullet-item"><span class="highlight">先に「意見を育てる」ことの重要性：</span>伝える前に、まず自分の考えを深める。内なる言葉の増量と精緻化が、外に向かう言葉の重みと説得力を生み出す源泉となる。</p><p class="bullet-item"><span class="highlight">内なる言葉を磨いた結果：</span></p><div class="sub-bullet"><p class="sub-bullet-item">短くとも強い言葉：無駄な説明が減り、核心を突く表現が生まれる</p><p class="sub-bullet-item">議論での耐久性：反論や質問にも柔軟に対応できる思考の幅と奥行き</p><p class="sub-bullet-item">再現性ある表現力：場面や相手が変わっても一貫して伝わる言葉の強さ</p><p class="sub-bullet-item">内側の解像度が上がるほど、外側の言葉は洗練される</p></div></div></div><div class="bottom-border"></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            overflow: hidden;            position: relative;            background-color: #f8f9fa;            display: flex;            flex-direction: column;        }        .content-area {            flex: 1;            display: flex;            flex-direction: column;            padding: 40px 80px;        }        .header {            position: relative;            padding-bottom: 16px;            margin-bottom: 24px;            border-bottom: 2px solid #e2e8f0;        }        .header::before {            content: "";            position: absolute;            top: -40px;            left: -80px;            right: -80px;            height: 8px;            background-color: #1a365d;        }        .title {            font-family: 'Noto Serif JP', serif;            font-weight: 700;            font-size: 36px;            color: #1a365d;            margin-bottom: 8px;        }        .section-title {            font-family: 'Noto Sans JP', sans-serif;            font-weight: 700;            font-size: 22px;            color: #2d3748;            margin-top: 24px;            margin-bottom: 12px;        }        .main-content {            flex: 1;        }        .bullet-list {            padding-left: 0;            margin-top: 8px;            margin-bottom: 24px;        }        .bullet-item {            position: relative;            padding-left: 24px;            margin-bottom: 16px;            font-size: 18px;            line-height: 1.6;            color: #4a5568;        }        .bullet-item::before {            content: "•";            position: absolute;            left: 0;            color: #4299e1;            font-weight: bold;            font-size: 20px;        }        .sub-bullet {            padding-left: 24px;            margin-top: 8px;        }        .sub-bullet-item {            position: relative;            padding-left: 20px;            margin-bottom: 8px;            font-size: 17px;            color: #4a5568;        }        .sub-bullet-item::before {            content: "-";            position: absolute;            left: 0;            color: #63b3ed;        }        .highlight {            color: #2b6cb0;            font-weight: 600;        }        .quote {            background-color: #edf2f7;            border-left: 4px solid #4299e1;            padding: 16px 24px;            margin: 24px 0;            font-family: 'Noto Serif JP', serif;            font-size: 22px;            color: #2d3748;            font-style: italic;            font-weight: 500;        }        .bottom-border {            position: absolute;            bottom: 0;            left: 0;            right: 0;            height: 8px;            background-color: #1a365d;        }
</style>
