<template>
  <SlidePageWrapper slide-id="B018PGI6JM" page-title="" :current-page="1" :total-pages="20">
<div class='slide-container'><div class='shape shape-1'></div><div class='shape shape-2'></div><div class='content-wrapper'><div class='accent-line'></div><h1 class='title'><p>非言語を言語化せよ</p></h1><h2 class='subtitle'><p>「情報発信」時代の非常識な成功法則</p></h2><div class='author'><p>長倉顕太 著</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            flex-direction: column;            justify-content: center;            align-items: center;            text-align: center;            background-color: #f8f9fa;            position: relative;            overflow: hidden;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            justify-content: center;            align-items: center;            padding: 0 80px;            z-index: 10;        }        .title {            font-size: 72px;            font-weight: 900;            line-height: 1.2;            margin-bottom: 24px;            color: #1a202c;        }        .subtitle {            font-size: 32px;            font-weight: 700;            line-height: 1.4;            margin-bottom: 48px;            color: #4a5568;        }        .author {            font-size: 24px;            color: #718096;            margin-top: 40px;        }        .accent-line {            width: 100px;            height: 8px;            background-color: #3182ce;            margin-bottom: 32px;        }        .shape {            position: absolute;            z-index: 1;        }        .shape-1 {            width: 300px;            height: 300px;            background-color: rgba(66, 153, 225, 0.1);            top: -100px;            right: -100px;            border-radius: 50%;        }        .shape-2 {            width: 200px;            height: 200px;            background-color: rgba(49, 130, 206, 0.1);            bottom: -50px;            left: -50px;            border-radius: 50%;        }
</style>
