<template>
  <SlidePageWrapper slide-id="B018PGI6JM" page-title="" :current-page="13" :total-pages="20">
<div class='slide-container'><div class='shape shape-1'></div><div class='shape shape-2'></div><div class='content-wrapper'><div class='title-section'><h1 class='title'><p>「誰が言うか？」の時代</p></h1><div class='accent-line'></div></div><div class='content-section'><div class='item'><div class='item-title'><p>評価軸</p></div><div class='item-content'><p>内容×発信者＝信頼。文脈・履歴・一貫性が重視される</p></div></div><div class='item'><div class='item-title'><p>強化法</p></div><div class='item-content'><p>実績の見せ方（事例/プロセス/失敗）、推薦/共同プロジェクト</p></div></div><div class='item'><div class='item-title'><p>避けるべき罠</p></div><div class='item-content'><p>権威借りの空洞化。自分の足で実績を積み上げる</p></div></div><div class='item'><div class='item-title'><p>SNS時代の信頼構築</p></div><div class='item-content'><p>「何を言うか」より「誰が言うか」が価値の源泉に</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            flex-direction: column;            background-color: #ffffff;            position: relative;            overflow: hidden;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title-section {            margin-bottom: 40px;        }        .title {            font-size: 48px;            font-weight: 700;            color: #1a202c;            margin-bottom: 16px;            line-height: 1.2;        }        .accent-line {            width: 80px;            height: 6px;            background-color: #3182ce;        }        .content-section {            display: flex;            flex-direction: column;            gap: 30px;        }        .item {            display: flex;            flex-direction: column;            gap: 10px;        }        .item-title {            font-size: 20px;            font-weight: 700;            color: #2d3748;        }        .item-content {            font-size: 18px;            color: #4a5568;            line-height: 1.6;        }        .shape {            position: absolute;            z-index: 1;        }        .shape-1 {            width: 300px;            height: 300px;            background-color: rgba(66, 153, 225, 0.05);            top: -150px;            right: -150px;            border-radius: 50%;        }        .shape-2 {            width: 200px;            height: 200px;            background-color: rgba(49, 130, 206, 0.05);            bottom: -80px;            left: -80px;            border-radius: 50%;        }
</style>
