<template>
  <SlidePageWrapper slide-id="B018PGI6JM" page-title="" :current-page="16" :total-pages="20">
<div class='slide-container'><div class='shape shape-1'></div><div class='shape shape-2'></div><div class='content-wrapper'><div class='title-section'><h1 class='title'><p>TRACK 8：拘束されろ！</p></h1><div class='accent-line'></div></div><div class='content-section'><div class='item'><div class='item-title'><p>意味</p></div><div class='item-content'><p>あえて制約を受け入れ、規律で実力を底上げする</p></div></div><div class='item'><div class='item-title'><p>例</p></div><div class='item-content'><p>公開締切・毎日発信・伴走者・コミュニティ規約</p></div></div><div class='item'><div class='item-title'><p>狙い</p></div><div class='item-content'><p>習慣化→資産化→信用化（ルーティンが人格を作る）</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            flex-direction: column;            background-color: #ffffff;            position: relative;            overflow: hidden;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title-section {            margin-bottom: 40px;        }        .title {            font-size: 48px;            font-weight: 700;            color: #1a202c;            margin-bottom: 16px;            line-height: 1.2;        }        .accent-line {            width: 80px;            height: 6px;            background-color: #3182ce;        }        .content-section {            display: flex;            flex-direction: column;            gap: 30px;        }        .item {            display: flex;            flex-direction: column;            gap: 10px;        }        .item-title {            font-size: 24px;            font-weight: 700;            color: #2d3748;        }        .item-content {            font-size: 20px;            color: #4a5568;            line-height: 1.6;        }        .shape {            position: absolute;            z-index: 1;        }        .shape-1 {            width: 300px;            height: 300px;            background-color: rgba(66, 153, 225, 0.05);            top: -150px;            right: -150px;            border-radius: 50%;        }        .shape-2 {            width: 200px;            height: 200px;            background-color: rgba(49, 130, 206, 0.05);            bottom: -80px;            left: -80px;            border-radius: 50%;        }
</style>
