<template>
  <SlidePageWrapper slide-id="B018PGI6JM" page-title="" :current-page="18" :total-pages="20">
<div class='slide-container'><div class='shape shape-1'></div><div class='shape shape-2'></div><div class='content-wrapper'><div class='title-section'><h1 class='title'><p>キーセンテンス集</p></h1><div class='accent-line'></div></div><div class='quotes-container'><div class='quote-item'><div class='quote-text'><p>成功者は言語を現実化できる人だ</p></div></div><div class='quote-item'><div class='quote-text'><p>言葉の目盛りを狂わせろ！</p></div></div><div class='quote-item'><div class='quote-text'><p>情報発信によって'会い'が決まる</p></div></div><div class='quote-item'><div class='quote-text'><p>出会いを制すれば人生を制す</p></div></div><div class='quote-item'><div class='quote-text'><p>ギブギブギブが世界を変える！</p></div></div><div class='quote-item'><div class='quote-text'><p>誰が言うか、が価値になる</p></div></div><div class='quote-item'><div class='quote-text'><p>情報空間と物理空間を一致させろ</p></div></div><div class='quote-item'><div class='quote-text'><p>良い奴しか残らない</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #ffffff;        position: relative;        overflow: hidden;    }    .content-wrapper {        flex: 1;        display: flex;        flex-direction: column;        padding: 50px 80px;        z-index: 10;    }    .title-section {        margin-bottom: 30px;    }    .title {        font-size: 40px;        font-weight: 700;        color: #1a202c;        margin-bottom: 16px;        line-height: 1.2;    }    .accent-line {        width: 80px;        height: 6px;        background-color: #3182ce;        margin-bottom: 30px;    }    .quotes-container {        display: grid;        grid-template-columns: repeat(2, 1fr);        grid-gap: 25px;    }    .quote-item {        background-color: #f7fafc;        border-radius: 8px;        padding: 25px;        position: relative;        border-left: 5px solid #3182ce;    }    .quote-text {        font-size: 18px;        line-height: 1.5;        color: #2d3748;        font-weight: 500;    }    .quote-text::before {        content: ''';        font-size: 48px;        font-weight: 900;        color: #3182ce;        opacity: 0.3;        position: absolute;        top: 5px;        left: 15px;    }    .quote-text::after {        content: ''';        font-size: 48px;        font-weight: 900;        color: #3182ce;        opacity: 0.3;        position: absolute;        bottom: -20px;        right: 15px;    }    .shape {        position: absolute;        z-index: 1;    }    .shape-1 {        width: 300px;        height: 300px;        background-color: rgba(66, 153, 225, 0.05);        top: -150px;        right: -150px;        border-radius: 50%;    }    .shape-2 {        width: 200px;        height: 200px;        background-color: rgba(49, 130, 206, 0.05);        bottom: -80px;        left: -80px;        border-radius: 50%;    }
</style>
