<template>
  <SlidePageWrapper slide-id="B018PGI6JM" page-title="" :current-page="19" :total-pages="20">
<div class='slide-container'><div class='shape shape-1'></div><div class='shape shape-2'></div><div class='content-wrapper'><div class='title-section'><h1 class='title'><p>用語集</p></h1><div class='accent-line'></div></div><div class='glossary-grid'><div class='glossary-item'><div class='term'><i class='fas fa-circle'></i><p>非言語</p></div><div class='definition'><p>言葉になる前の感覚/経験/空気感/体験など、言語化される前の直感的な理解や認識</p></div></div><div class='glossary-item'><div class='term'><i class='fas fa-circle'></i><p>言葉の目盛り</p></div><div class='definition'><p>現実を切り取る自分独自の基準/解像度。細かいほど現実の認識精度が上がる</p></div></div><div class='glossary-item'><div class='term'><i class='fas fa-circle'></i><p>情報空間</p></div><div class='definition'><p>ネット/言葉/抽象領域。物理空間（現実の行為/出会い）と一致させることが重要</p></div></div><div class='glossary-item'><div class='term'><i class='fas fa-circle'></i><p>ギブギブギブ</p></div><div class='definition'><p>見返りを前提にしない連続的な価値提供。世界を変える根本原理</p></div></div><div class='glossary-item'><div class='term'><i class='fas fa-circle'></i><p>リアル良い奴</p></div><div class='definition'><p>誠実・約束厳守・利他・学習継続の人。SNS時代に最終的に残る人物像</p></div></div><div class='glossary-item'><div class='term'><i class='fas fa-circle'></i><p>ケツガサキ</p></div><div class='definition'><p>縁や案件の'終わり方'設計。始め方だけでなく終え方まで考慮した関係構築</p></div></div><div class='glossary-item'><div class='term'><i class='fas fa-circle'></i><p>地雷で出会い</p></div><div class='definition'><p>リスクな出会いを学びに変える姿勢。トラブルも成長材料として捉える考え方</p></div></div><div class='glossary-item'><div class='term'><i class='fas fa-circle'></i><p>自己承認型発信</p></div><div class='definition'><p>承認依存の自慢型アウトプット。真の価値を生まない罠</p></div></div><div class='glossary-item'><div class='term'><i class='fas fa-circle'></i><p>タイトルの非言語化</p></div><div class='definition'><p>空気を凝縮し刺さる言葉にする技法。ベストセラーを生む条件</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #ffffff;        position: relative;        overflow: hidden;    }    .content-wrapper {        flex: 1;        display: flex;        flex-direction: column;        padding: 50px 80px;        z-index: 10;    }    .title-section {        margin-bottom: 30px;    }    .title {        font-size: 40px;        font-weight: 700;        color: #1a202c;        margin-bottom: 16px;        line-height: 1.2;    }    .accent-line {        width: 80px;        height: 6px;        background-color: #3182ce;        margin-bottom: 30px;    }    .glossary-grid {        display: grid;        grid-template-columns: repeat(3, 1fr);        grid-gap: 20px;    }    .glossary-item {        background-color: #f7fafc;        border-radius: 8px;        padding: 15px;        border-left: 4px solid #3182ce;    }    .term {        font-size: 18px;        font-weight: 700;        color: #2d3748;        margin-bottom: 8px;        display: flex;        align-items: center;    }    .term i {        margin-right: 8px;        color: #3182ce;        font-size: 14px;    }    .definition {        font-size: 14px;        color: #4a5568;        line-height: 1.5;    }    .shape {        position: absolute;        z-index: 1;    }    .shape-1 {        width: 300px;        height: 300px;        background-color: rgba(66, 153, 225, 0.05);        top: -150px;        right: -150px;        border-radius: 50%;    }    .shape-2 {        width: 200px;        height: 200px;        background-color: rgba(49, 130, 206, 0.05);        bottom: -80px;        left: -80px;        border-radius: 50%;    }
</style>
