<template>
  <SlidePageWrapper slide-id="B018PGI6JM" page-title="" :current-page="2" :total-pages="20">
<div class='slide-container'><div class='shape shape-1'></div><div class='shape shape-2'></div><div class='content-wrapper'><div class='title-section'><h1 class='title'><p>本書の概要・背景・対象読者</p></h1><div class='accent-line'></div></div><div class='content-section'><div class='item'><div class='item-title'><p>概要</p></div><div class='item-content'><p>非言語（体験・感覚・空気）を言語化し発信して現実を変える方法論</p></div></div><div class='item'><div class='item-title'><p>背景</p></div><div class='item-content'><p>SNSとコンテンツの時代—「誰が言うか」と'素の生き様'が価値に</p></div></div><div class='item'><div class='item-title'><p>対象読者</p></div><div class='item-content'><p>情報発信者/個人起業家/リーダー/採用・広報/著者志望</p></div></div><div class='item'><div class='item-title'><p>読後の変化</p></div><div class='item-content'><p>自分の'非言語'を言葉にし、出会い・信用・機会を設計できる</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            flex-direction: column;            background-color: #ffffff;            position: relative;            overflow: hidden;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title-section {            margin-bottom: 40px;        }        .title {            font-size: 48px;            font-weight: 700;            color: #1a202c;            margin-bottom: 16px;            line-height: 1.2;        }        .accent-line {            width: 80px;            height: 6px;            background-color: #3182ce;        }        .content-section {            display: flex;            flex-direction: column;            gap: 30px;        }        .item {            display: flex;            flex-direction: column;            gap: 10px;        }        .item-title {            font-size: 20px;            font-weight: 700;            color: #2d3748;        }        .item-content {            font-size: 18px;            color: #4a5568;            line-height: 1.6;        }        .shape {            position: absolute;            z-index: 1;        }        .shape-1 {            width: 300px;            height: 300px;            background-color: rgba(66, 153, 225, 0.05);            top: -150px;            right: -150px;            border-radius: 50%;        }        .shape-2 {            width: 200px;            height: 200px;            background-color: rgba(49, 130, 206, 0.05);            bottom: -80px;            left: -80px;            border-radius: 50%;        }
</style>
