<template>
  <SlidePageWrapper slide-id="B018PGI6JM" page-title="" :current-page="20" :total-pages="20">
<div class='slide-container'><div class='shape shape-1'></div><div class='shape shape-2'></div><div class='content-wrapper'><div class='title-section'><h1 class='title'><p>まとめ（締め）—7日間実装プラン</p></h1><div class='accent-line'></div></div><div class='summary-box'><div class='summary-title'><i class='fas fa-lightbulb'></i><p>書籍の要点</p></div><div class='summary-content'><p>非言語→言語→発信→一致→出会い→信用→成果</p></div></div><div class='action-plan'><div class='action-title'><i class='fas fa-tasks'></i><p>7日間実践プログラム</p></div><div class='days-container'><div class='day-card'><div class='day-title'><p>Day 1</p></div><div class='day-content'><p>体験棚卸し10件<br/>今までの体験から非言語的なものをリストアップ</p></div></div><div class='day-card'><div class='day-title'><p>Day 2</p></div><div class='day-content'><p>3つ再定義（目盛りを狂わせる）<br/>常識と異なる視点で言語化する</p></div></div><div class='day-card'><div class='day-title'><p>Day 3</p></div><div class='day-content'><p>タイトル10本<br/>魅力的な非言語→言語のタイトルを作る</p></div></div><div class='day-card'><div class='day-title'><p>Day 4</p></div><div class='day-content'><p>発信導線設計<br/>ブログ/Note/動画などの発信経路を整える</p></div></div><div class='day-card'><div class='day-title'><p>Day 5</p></div><div class='day-content'><p>ギブ企画1本公開<br/>見返りを求めない価値提供を始める</p></div></div><div class='day-card'><div class='day-title'><p>Day 6</p></div><div class='day-content'><p>出会い場の設計（3アポ）<br/>情報発信から実際の出会いへ接続する</p></div></div></div><div class='day-card' style='width: 100%'><div class='day-title'><p>Day 7</p></div><div class='day-content'><p>振り返り→改善→次週計画<br/>1週間の成果を確認し、PDCAサイクルを回す</p></div></div></div><div class='conclusion'><div class='conclusion-text'><p>'素の生き様'を言葉に。小さく始めて反復する。<br/>非言語を言語化する習慣が、あなたの現実を変える。</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #ffffff;        position: relative;        overflow: hidden;    }    .content-wrapper {        flex: 1;        display: flex;        flex-direction: column;        padding: 50px 80px;        z-index: 10;    }    .title-section {        margin-bottom: 30px;    }    .title {        font-size: 40px;        font-weight: 700;        color: #1a202c;        margin-bottom: 16px;        line-height: 1.2;    }    .accent-line {        width: 80px;        height: 6px;        background-color: #3182ce;        margin-bottom: 20px;    }    .summary-box {        background-color: #ebf8ff;        border-left: 4px solid #3182ce;        padding: 20px;        border-radius: 8px;        margin-bottom: 25px;    }    .summary-title {        font-size: 20px;        font-weight: 700;        color: #2c5282;        margin-bottom: 10px;        display: flex;        align-items: center;    }    .summary-title i {        margin-right: 10px;    }    .summary-content {        font-size: 16px;        color: #2d3748;        line-height: 1.5;    }    .action-plan {        flex: 1;    }    .action-title {        font-size: 22px;        font-weight: 700;        color: #2d3748;        margin-bottom: 20px;        display: flex;        align-items: center;    }    .action-title i {        margin-right: 10px;        color: #3182ce;    }    .days-container {        display: flex;        gap: 15px;        flex-wrap: wrap;    }    .day-card {        width: calc(33.333% - 10px);        background-color: #f7fafc;        border-radius: 8px;        padding: 15px;        margin-bottom: 15px;        border-top: 3px solid #3182ce;    }    .day-title {        font-size: 18px;        font-weight: 700;        color: #2d3748;        margin-bottom: 8px;    }    .day-content {        font-size: 15px;        color: #4a5568;        line-height: 1.5;    }    .conclusion {        margin-top: 20px;        padding: 15px;        background-color: #f7fafc;        border-radius: 8px;        text-align: center;    }    .conclusion-text {        font-size: 18px;        color: #2d3748;        font-weight: 500;        line-height: 1.5;    }    .shape {        position: absolute;        z-index: 1;    }    .shape-1 {        width: 300px;        height: 300px;        background-color: rgba(66, 153, 225, 0.05);        top: -150px;        right: -150px;        border-radius: 50%;    }    .shape-2 {        width: 200px;        height: 200px;        background-color: rgba(49, 130, 206, 0.05);        bottom: -80px;        left: -80px;        border-radius: 50%;    }
</style>
