<template>
  <SlidePageWrapper slide-id="B018PGI6JM" page-title="" :current-page="3" :total-pages="20">
<div class='slide-container'><div class='shape shape-1'></div><div class='shape shape-2'></div><div class='content-wrapper'><div class='title-section'><h1 class='title'><p>目次（全体構成）</p></h1><div class='accent-line'></div></div><div class='toc-grid'><div class='toc-item'><div class='page-number'><p>1</p></div><div class='page-title'><p>表紙</p></div></div><div class='toc-item'><div class='page-number'><p>2</p></div><div class='page-title'><p>概要・背景・対象</p></div></div><div class='toc-item'><div class='page-number'><p>3</p></div><div class='page-title'><p>目次</p></div></div><div class='toc-item'><div class='page-number'><p>4</p></div><div class='page-title'><p>核心コンセプト</p></div></div><div class='toc-item'><div class='page-number'><p>5</p></div><div class='page-title'><p>Track 1</p></div></div><div class='toc-item'><div class='page-number'><p>6</p></div><div class='page-title'><p>Track 2</p></div></div><div class='toc-item'><div class='page-number'><p>7</p></div><div class='page-title'><p>情報×物理の一致</p></div></div><div class='toc-item'><div class='page-number'><p>8</p></div><div class='page-title'><p>Track 3</p></div></div><div class='toc-item'><div class='page-number'><p>9</p></div><div class='page-title'><p>Track 4</p></div></div><div class='toc-item'><div class='page-number'><p>10</p></div><div class='page-title'><p>出会いのコントロール</p></div></div><div class='toc-item'><div class='page-number'><p>11</p></div><div class='page-title'><p>Track 5</p></div></div><div class='toc-item'><div class='page-number'><p>12</p></div><div class='page-title'><p>Track 6</p></div></div><div class='toc-item'><div class='page-number'><p>13</p></div><div class='page-title'><p>誰が言うか</p></div></div><div class='toc-item'><div class='page-number'><p>14</p></div><div class='page-title'><p>Track 7</p></div></div><div class='toc-item'><div class='page-number'><p>15</p></div><div class='page-title'><p>ギブが世界を変える</p></div></div><div class='toc-item'><div class='page-number'><p>16</p></div><div class='page-title'><p>Track 8</p></div></div><div class='toc-item'><div class='page-number'><p>17</p></div><div class='page-title'><p>実践方法</p></div></div><div class='toc-item'><div class='page-number'><p>18</p></div><div class='page-title'><p>キーセンテンス</p></div></div><div class='toc-item'><div class='page-number'><p>19</p></div><div class='page-title'><p>用語集</p></div></div><div class='toc-item'><div class='page-number'><p>20</p></div><div class='page-title'><p>まとめ</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #ffffff;        position: relative;        overflow: hidden;    }    .content-wrapper {        flex: 1;        display: flex;        flex-direction: column;        padding: 50px 80px;        z-index: 10;    }    .title-section {        margin-bottom: 40px;    }    .title {        font-size: 48px;        font-weight: 700;        color: #1a202c;        margin-bottom: 16px;        line-height: 1.2;    }    .accent-line {        width: 80px;        height: 6px;        background-color: #3182ce;        margin-bottom: 30px;    }    .toc-grid {        display: grid;        grid-template-columns: repeat(3, 1fr);        grid-gap: 20px 40px;        width: 100%;    }    .toc-item {        display: flex;        align-items: center;        padding: 8px 0;    }    .page-number {        font-size: 18px;        font-weight: 700;        color: #3182ce;        margin-right: 12px;        min-width: 24px;        text-align: center;    }    .page-title {        font-size: 18px;        color: #4a5568;        line-height: 1.6;    }    .shape {        position: absolute;        z-index: 1;    }    .shape-1 {        width: 300px;        height: 300px;        background-color: rgba(66, 153, 225, 0.05);        top: -150px;        right: -150px;        border-radius: 50%;    }    .shape-2 {        width: 200px;        height: 200px;        background-color: rgba(49, 130, 206, 0.05);        bottom: -80px;        left: -80px;        border-radius: 50%;    }
</style>
