<template>
  <SlidePageWrapper slide-id="B018PGI6JM" page-title="" :current-page="6" :total-pages="20">
<div class='slide-container'><div class='shape shape-1'></div><div class='shape shape-2'></div><div class='content-wrapper'><div class='title-section'><h1 class='title'><p>TRACK 2：「言葉の目盛り」を狂わせろ</p></h1><div class='accent-line'></div></div><div class='content-section'><div class='item'><div class='item-title'><p>言葉の目盛りとは</p></div><div class='item-content'><p>物事を見る自分独自の基準/解像度。既存の言語体系や認識フレーム</p></div></div><div class='item'><div class='item-title'><p>狙い</p></div><div class='item-content'><p>既成概念をズラす表現で'新しい見え方'を提供し、差別化された価値を生む</p></div></div><div class='item'><div class='item-title'><p>実践</p></div><div class='item-content'><p>①再定義（常識を覆す） ②新ラベリング（名付け直し） ③逆説/比喩（意外な組み合わせ） ④タイトル化（凝縮・記号化）</p></div></div><div class='item'><div class='item-title'><p>効果</p></div><div class='item-content'><p>目盛りが細かいほど現実の理解と影響力が増す。非言語から受け取れる情報量も増加</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            flex-direction: column;            background-color: #ffffff;            position: relative;            overflow: hidden;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title-section {            margin-bottom: 40px;        }        .title {            font-size: 48px;            font-weight: 700;            color: #1a202c;            margin-bottom: 16px;            line-height: 1.2;        }        .accent-line {            width: 80px;            height: 6px;            background-color: #3182ce;        }        .content-section {            display: flex;            flex-direction: column;            gap: 30px;        }        .item {            display: flex;            flex-direction: column;            gap: 10px;        }        .item-title {            font-size: 20px;            font-weight: 700;            color: #2d3748;        }        .item-content {            font-size: 18px;            color: #4a5568;            line-height: 1.6;        }        .shape {            position: absolute;            z-index: 1;        }        .shape-1 {            width: 300px;            height: 300px;            background-color: rgba(66, 153, 225, 0.05);            top: -150px;            right: -150px;            border-radius: 50%;        }        .shape-2 {            width: 200px;            height: 200px;            background-color: rgba(49, 130, 206, 0.05);            bottom: -80px;            left: -80px;            border-radius: 50%;        }
</style>
