<template>
  <SlidePageWrapper slide-id="B018PGI6JM" page-title="" :current-page="8" :total-pages="20">
<div class='slide-container'><div class='shape shape-1'></div><div class='shape shape-2'></div><div class='content-wrapper'><div class='title-section'><h1 class='title'><p>TRACK 3：自分に酔うバカ（自己承認欲求の罠）</p></h1><div class='accent-line'></div></div><div class='content-section'><div class='item'><div class='item-title'><div class='flex-row'><i class='fas fa-exclamation-triangle warning-icon'></i><p>問題</p></div></div><div class='item-content'><p>'自分スゴイ'の承認獲得型は共感も信用も生まない</p></div></div><div class='item'><div class='item-title'><div class='flex-row'><i class='fas fa-lightbulb solution-icon'></i><p>代替案</p></div></div><div class='item-content'><p>素の生き様・反省・学び・再挑戦の記録を出す</p></div></div><div class='item'><div class='item-title'><div class='flex-row'><i class='fas fa-balance-scale principle-icon'></i><p>原則</p></div></div><div class='item-content'><p>利他的視点（相手の役立ち）×検証可能性（実験ログ）</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            flex-direction: column;            background-color: #ffffff;            position: relative;            overflow: hidden;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title-section {            margin-bottom: 40px;        }        .title {            font-size: 48px;            font-weight: 700;            color: #1a202c;            margin-bottom: 16px;            line-height: 1.2;        }        .accent-line {            width: 80px;            height: 6px;            background-color: #3182ce;        }        .content-section {            display: flex;            flex-direction: column;            gap: 30px;        }        .item {            display: flex;            flex-direction: column;            gap: 10px;        }        .item-title {            font-size: 28px;            font-weight: 700;            color: #2d3748;        }        .item-content {            font-size: 24px;            color: #4a5568;            line-height: 1.6;        }        .shape {            position: absolute;            z-index: 1;        }        .shape-1 {            width: 300px;            height: 300px;            background-color: rgba(66, 153, 225, 0.05);            top: -150px;            right: -150px;            border-radius: 50%;        }        .shape-2 {            width: 200px;            height: 200px;            background-color: rgba(49, 130, 206, 0.05);            bottom: -80px;            left: -80px;            border-radius: 50%;        }        .warning-icon {            color: #e53e3e;            margin-right: 10px;        }        .solution-icon {            color: #38a169;            margin-right: 10px;        }        .principle-icon {            color: #3182ce;            margin-right: 10px;        }        .flex-row {            display: flex;            align-items: center;        }
</style>
