<template>
  <SlidePageWrapper slide-id="B0FYLJTC59" page-title="ホメホメ革命 書籍要約" :current-page="1" :total-pages="20">
<div class="slide-container flex flex-col items-center justify-center px-20"><!-- Background decoration - "Thank you" bubbles --><div class="thank-you-bubble" style="width: 120px; height: 120px; top: 100px; left: 200px; font-size: 18px;">ありがとう</div><div class="thank-you-bubble" style="width: 180px; height: 180px; bottom: 120px; right: 180px; font-size: 24px;">ありがとう</div><div class="thank-you-bubble" style="width: 90px; height: 90px; top: 200px; right: 300px; font-size: 14px;">ありがとう</div><div class="thank-you-bubble" style="width: 150px; height: 150px; bottom: 180px; left: 150px; font-size: 20px;">ありがとう</div><!-- Main content --><div class="flex flex-col items-center justify-center text-center z-10 pt-12"><p class="mb-3 text-gray-500 text-2xl">書籍要約プレゼンテーション</p><div class="my-8"><p class="text-6xl font-bold color-accent mb-3">ホメホメ<span class="text-gray-700">革命</span></p><p class="text-3xl text-gray-700 mt-4">日本の日常に<span class="color-accent font-bold">"ありがとう"</span>を取り戻す</p></div><div class="my-8 bg-white bg-opacity-70 px-10 py-6 rounded-lg shadow-lg"><p class="text-xl text-gray-700">著者: 中島克也／WD-LAB!出版</p><p class="mt-5 text-2xl text-gray-700">減点文化から承認文化へ。<br/>言葉を変え、関係を変え、社会を変える。</p></div><div class="mt-6 mb-12"><p class="text-lg text-gray-600 border-t border-b border-orange-300 py-3 px-8">          本書の要点を20枚で凝縮し、今すぐ実践できる方法を提示。        </p></div><div class="flex justify-center items-center mt-2"><i class="fas fa-heart text-2xl mr-3 color-accent"></i><p class="text-xl text-gray-600">承認・共感・信頼の文化を創る</p><i class="fas fa-heart text-2xl ml-3 color-accent"></i></div></div><!-- Footer --><div class="absolute bottom-6 right-10"><p class="text-sm text-gray-500">1 / 20</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      font-family: 'M PLUS Rounded 1c', sans-serif;    }    .slide-container {      width: 1280px;      min-height: 720px;      overflow: hidden;      position: relative;      background-color: #FFF8F0;    }    .color-accent {      color: #FF8A00;    }    .thank-you-bubble {      position: absolute;      border-radius: 50%;      display: flex;      align-items: center;      justify-content: center;      font-weight: bold;      opacity: 0.15;      color: #FF8A00;      background-color: #FFF0E0;    }
</style>
