<template>
  <SlidePageWrapper slide-id="B0FYLJTC59" page-title="第8章: ホメホメ話法「もったいない」" :current-page="14" :total-pages="20">
<div class="slide-container flex flex-col px-16 py-12"><!-- Header --><div class="w-full mb-6"><h1 class="text-4xl font-bold text-center"><span class="color-accent">第8章: ホメホメ話法</span><span class="text-gray-700">「もったいない」</span></h1><div class="w-32 h-1 bg-orange-400 mx-auto mt-4"></div></div><!-- Main Content - Two Column Layout --><div class="flex-1 w-full flex flex-row"><!-- Left Column - Techniques and Concepts --><div class="w-1/2 pr-6 flex flex-col space-y-5"><div class="bg-accent-light rounded-lg p-4 mb-2"><p class="text-2xl font-bold color-accent mb-2 text-center">コツ・考え方</p></div><div class="technique-card pl-4 py-4 bg-white rounded-lg shadow-sm"><div class="flex items-center"><i class="fas fa-hands text-xl color-accent mr-3"></i><p class="text-xl font-bold text-gray-700">褒めが届かない相手には"惜しみ"でくすぐる</p></div><p class="text-md text-gray-600 ml-10 mt-2">直接の褒め言葉が響かない人にも「もったいない」という「惜しみ」の言葉が心に届く</p></div><div class="technique-card pl-4 py-4 bg-white rounded-lg shadow-sm"><div class="flex items-center"><i class="fas fa-star text-xl color-accent mr-3"></i><p class="text-xl font-bold text-gray-700">相手の可能性を信じる未来承認の言葉</p></div><p class="text-md text-gray-600 ml-10 mt-2">「もったいない」は相手の中に眠る可能性への期待と信頼を示す強力な承認</p></div><div class="technique-card pl-4 py-4 bg-white rounded-lg shadow-sm"><div class="flex items-center"><i class="fas fa-fire text-xl color-accent mr-3"></i><p class="text-xl font-bold text-gray-700">提案前に自己効力感を点火</p></div><p class="text-md text-gray-600 ml-10 mt-2">相手の内発的動機を呼び起こし、自ら行動したいという気持ちを引き出す</p></div></div><!-- Right Column - Practical Phrases --><div class="w-1/2 pl-6 flex flex-col space-y-5"><div class="bg-green-50 rounded-lg p-4 mb-2"><p class="text-2xl font-bold text-green-700 mb-2 text-center">使える言い回し</p></div><div class="phrase-card pl-4 py-4 bg-white rounded-lg shadow-sm"><div class="flex items-center"><i class="fas fa-comment-alt text-xl text-green-600 mr-3"></i><p class="text-xl text-gray-700">「あなたほどの人がここで止まるのはもったいない」</p></div><p class="text-md text-gray-600 ml-10 mt-2">相手の能力を認めつつ、次の一歩を踏み出す勇気を引き出す</p></div><div class="phrase-card pl-4 py-4 bg-white rounded-lg shadow-sm"><div class="flex items-center"><i class="fas fa-comment-alt text-xl text-green-600 mr-3"></i><p class="text-xl text-gray-700">「この視点、次はもっと活きる」</p></div><p class="text-md text-gray-600 ml-10 mt-2">現在の挑戦が将来に繋がることを示し、長期的な成長を促す</p></div><div class="phrase-card pl-4 py-4 bg-white rounded-lg shadow-sm"><div class="flex items-center"><i class="fas fa-comment-alt text-xl text-green-600 mr-3"></i><p class="text-xl text-gray-700">「ここまでの積み重ね、次の挑戦に効く」</p></div><p class="text-md text-gray-600 ml-10 mt-2">これまでの努力を認め、次のステップへの意欲を高める</p></div></div></div><!-- Footer --><div class="w-full flex justify-between items-center mt-8"><div class="flex items-center"><i class="fas fa-quote-left text-sm color-accent mr-2"></i><p class="text-sm text-gray-500">ホメホメ革命</p></div><p class="text-sm text-gray-500">14 / 20</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'M PLUS Rounded 1c', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            position: relative;            background-color: #FFF8F0;        }        .color-accent {            color: #FF8A00;        }        .bg-accent-light {            background-color: rgba(255, 138, 0, 0.08);        }        .technique-card {            border-left: 4px solid #FF8A00;            transition: all 0.2s ease;        }        .technique-card:hover {            background-color: rgba(255, 138, 0, 0.15);        }        .phrase-card {            border-left: 4px solid #4CAF50;            transition: all 0.2s ease;        }        .phrase-card:hover {            background-color: rgba(76, 175, 80, 0.15);        }
</style>
