<template>
  <SlidePageWrapper slide-id="B0FYLJTC59" page-title="家庭・教育現場での応用" :current-page="15" :total-pages="20">
<div class="slide-container flex flex-col items-center px-16 py-12"><!-- Header --><div class="w-full mb-8"><h1 class="text-4xl font-bold text-center"><span class="color-accent">家庭・教育現場</span>での応用</h1><div class="w-32 h-1 bg-orange-400 mx-auto mt-4"></div></div><!-- Main Content --><div class="flex-1 w-full flex flex-col justify-center"><div class="grid grid-cols-1 gap-8"><!-- 家庭 --><div class="content-box pl-6 py-2"><div class="flex items-center"><i class="fas fa-home text-2xl color-accent mr-4"></i><p class="text-2xl font-bold text-gray-700">家庭:</p></div><p class="ml-12 text-xl text-gray-700">「おかえり」「ありがとう」を再設計、日常の承認習慣化。</p></div><!-- 思春期 --><div class="content-box pl-6 py-2"><div class="flex items-center"><i class="fas fa-child text-2xl color-accent mr-4"></i><p class="text-2xl font-bold text-gray-700">思春期:</p></div><p class="ml-12 text-xl text-gray-700">直接より"間接承認"（第三者経由/背中で示す/空間で認める）。</p></div><!-- 学校 --><div class="content-box pl-6 py-2"><div class="flex items-center"><i class="fas fa-school text-2xl color-accent mr-4"></i><p class="text-2xl font-bold text-gray-700">学校:</p></div><p class="ml-12 text-xl text-gray-700">教師の負担集中ではなく、子ども同士のホメホメ循環を設計。</p></div><!-- ポイント --><div class="content-box pl-6 py-2"><div class="flex items-center"><i class="fas fa-star text-2xl color-accent mr-4"></i><p class="text-2xl font-bold text-gray-700">ポイント:</p></div><p class="ml-12 text-xl text-gray-700">「できた/できない」よりも、取り組み・過程を言語化して承認。</p></div></div></div><!-- Footer --><div class="w-full flex justify-between items-center mt-8"><div class="flex items-center"><i class="fas fa-heart text-sm color-accent mr-2"></i><p class="text-sm text-gray-500">ホメホメ革命</p></div><p class="text-sm text-gray-500">15 / 20</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'M PLUS Rounded 1c', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            overflow: hidden;            position: relative;            background-color: #FFF8F0;        }        .color-accent {            color: #FF8A00;        }        .bg-accent-light {            background-color: rgba(255, 138, 0, 0.1);        }        .content-box {            border-left: 4px solid #FF8A00;        }
</style>
