<template>
  <SlidePageWrapper slide-id="B0FYLJTC59" page-title="キーセンテンス集" :current-page="18" :total-pages="20">
<div class="slide-container flex flex-col px-16 py-12"><!-- Header --><div class="w-full mb-6"><h1 class="text-4xl font-bold text-center"><span class="color-accent">キーセンテンス</span><span class="text-gray-700">集</span></h1><div class="w-32 h-1 bg-orange-400 mx-auto mt-4"></div></div><!-- Main Content --><div class="flex-1 w-full flex flex-col justify-center"><div class="grid grid-cols-2 gap-4"><!-- Left Column --><div class="flex flex-col space-y-4"><!-- Quote 1 --><div class="quote-card bg-white rounded-lg shadow-sm p-4"><div class="flex"><i class="fas fa-quote-left text-3xl color-accent mr-3 mt-1"></i><p class="text-xl text-gray-700">言葉が変われば、国が変わる。</p></div></div><!-- Quote 2 --><div class="quote-card bg-white rounded-lg shadow-sm p-4"><div class="flex"><i class="fas fa-quote-left text-3xl color-accent mr-3 mt-1"></i><p class="text-xl text-gray-700">分断より共感、批判より信頼、減点より承認。</p></div></div><!-- Quote 3 --><div class="quote-card bg-white rounded-lg shadow-sm p-4"><div class="flex"><i class="fas fa-quote-left text-3xl color-accent mr-3 mt-1"></i><p class="text-xl text-gray-700">最もチームを弱らせるのは"無関心"。</p></div></div></div><!-- Right Column --><div class="flex flex-col space-y-4"><!-- Quote 4 --><div class="quote-card bg-white rounded-lg shadow-sm p-4"><div class="flex"><i class="fas fa-quote-left text-3xl color-accent mr-3 mt-1"></i><p class="text-xl text-gray-700">評価ではなく、尊重から始める。</p></div></div><!-- Quote 5 --><div class="quote-card bg-white rounded-lg shadow-sm p-4"><div class="flex"><i class="fas fa-quote-left text-3xl color-accent mr-3 mt-1"></i><p class="text-xl text-gray-700">「もったいない」は未来への承認。</p></div></div><!-- Quote 6 --><div class="quote-card bg-white rounded-lg shadow-sm p-4"><div class="flex"><i class="fas fa-quote-left text-3xl color-accent mr-3 mt-1"></i><p class="text-xl text-gray-700">ありがとうを可視化すると、関係は強くなる。</p></div></div></div></div></div><!-- Footer --><div class="w-full flex justify-between items-center mt-8"><div class="flex items-center"><i class="fas fa-quote-right text-sm color-accent mr-2"></i><p class="text-sm text-gray-500">ホメホメ革命</p></div><p class="text-sm text-gray-500">18 / 20</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'M PLUS Rounded 1c', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            position: relative;            background-color: #FFF8F0;        }        .color-accent {            color: #FF8A00;        }        .quote-card {            border-left: 4px solid #FF8A00;            transition: all 0.2s ease;        }        .quote-card:hover {            background-color: rgba(255, 138, 0, 0.08);        }
</style>
