<template>
  <SlidePageWrapper slide-id="B0FYLJTC59" page-title="締め: 世界で一番「ありがとう」が響く国へ" :current-page="20" :total-pages="20">
<div class="slide-container flex flex-col px-16 py-12"><!-- Header --><div class="w-full mb-6"><h1 class="text-4xl font-bold text-center"><span class="color-accent">締め:</span><span class="text-gray-700">世界で一番「ありがとう」が響く国へ</span></h1><div class="w-32 h-1 bg-orange-400 mx-auto mt-4"></div></div><!-- Main Content --><div class="flex-1 w-full flex flex-col justify-center"><!-- Action Title --><div class="mb-6"><p class="text-2xl font-bold text-center text-gray-700"><i class="fas fa-play-circle color-accent mr-3"></i>今日からの3アクション            </p></div><!-- Action Items --><div class="space-y-5"><!-- Action 1 --><div class="action-card bg-white rounded-lg shadow-sm p-4 flex items-center"><div class="action-circle mr-4">1</div><div><p class="text-xl font-bold text-gray-700">日に3回、具体的な感謝を言葉にする</p><p class="text-md text-gray-600 mt-1">「いつもありがとう」ではなく、「〇〇してくれて助かった」と具体的に</p></div></div><!-- Action 2 --><div class="action-card bg-white rounded-lg shadow-sm p-4 flex items-center"><div class="action-circle mr-4">2</div><div><p class="text-xl font-bold text-gray-700">P→Iで対話を設計する</p><p class="text-md text-gray-600 mt-1">まず称賛(Praise)、その上で改善(Improve)の提案を</p></div></div><!-- Action 3 --><div class="action-card bg-white rounded-lg shadow-sm p-4 flex items-center"><div class="action-circle mr-4">3</div><div><p class="text-xl font-bold text-gray-700">承認の痕跡（カード/掲示/SNS）を残す</p><p class="text-md text-gray-600 mt-1">言葉は消えても、形に残した承認は何度も効果を発揮する</p></div></div></div><!-- Call to Action --><div class="highlight-box p-6 mt-8"><p class="text-xl text-gray-700 text-center"><span class="font-bold color-accent">あなたの一言が、</span>関係と未来を変える<span class="font-bold color-accent">"革命"</span>の一歩になる。            </p></div></div><!-- Footer --><div class="w-full flex justify-between items-center mt-8"><div class="flex items-center"><i class="fas fa-heart text-sm color-accent mr-2"></i><p class="text-sm text-gray-500">ホメホメ革命</p></div><p class="text-sm text-gray-500">20 / 20</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'M PLUS Rounded 1c', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            position: relative;            background-color: #FFF8F0;        }        .color-accent {            color: #FF8A00;        }        .action-card {            border-left: 4px solid #FF8A00;            transition: all 0.2s ease;        }        .action-card:hover {            background-color: rgba(255, 138, 0, 0.08);        }        .action-circle {            width: 40px;            height: 40px;            border-radius: 50%;            background-color: #FF8A00;            color: white;            display: flex;            align-items: center;            justify-content: center;            font-weight: bold;            font-size: 1.25rem;        }        .highlight-box {            background-color: rgba(255, 138, 0, 0.08);            border-radius: 12px;        }
</style>
