<template>
  <SlidePageWrapper slide-id="B0FYLJTC59" page-title="目次・全体構造（書籍ベース）" :current-page="3" :total-pages="20">
<div class="slide-container flex flex-col px-16 py-12"><!-- Header --><div class="w-full mb-8"><h1 class="text-4xl font-bold text-center"><span class="color-accent">目次・全体構造</span><span class="text-gray-700">（書籍ベース）</span></h1><div class="w-32 h-1 bg-orange-400 mx-auto mt-4"></div></div><!-- Main Content - Two Column Layout --><div class="flex-1 w-full"><div class="grid grid-cols-2 gap-4"><!-- Left Column --><div class="flex flex-col space-y-3"><div class="chapter-item pl-4 py-2"><p class="text-lg font-bold color-accent">序章:</p><p class="text-xl text-gray-700">ホメホメ国家構想</p><p class="text-md text-gray-600">— 言葉が変われば、国が変わる</p></div><div class="chapter-item pl-4 py-2"><p class="text-lg font-bold color-accent">第1章:</p><p class="text-xl text-gray-700">「ホメホメ」が国の空気を変える日</p><p class="text-md text-gray-600">（＝ホメホメマインド）</p></div><div class="chapter-item pl-4 py-2"><p class="text-lg font-bold color-accent">第2章:</p><p class="text-xl text-gray-700">ホメホメの科学</p><p class="text-md text-gray-600">— 心理と脳のメカニズム</p></div><div class="chapter-item pl-4 py-2"><p class="text-lg font-bold color-accent">第3章:</p><p class="text-xl text-gray-700">（実践編・章題未特定）</p></div><div class="chapter-item pl-4 py-2"><p class="text-lg font-bold color-accent">第4章:</p><p class="text-xl text-gray-700">ホメホメ職場</p><p class="text-md text-gray-600">— 承認のデザイン</p></div></div><!-- Right Column --><div class="flex flex-col space-y-3"><div class="chapter-item pl-4 py-2"><p class="text-lg font-bold color-accent">第5章:</p><p class="text-xl text-gray-700">（実践編・章題未特定）</p></div><div class="chapter-item pl-4 py-2"><p class="text-lg font-bold color-accent">第6章:</p><p class="text-xl text-gray-700">ホメホメ地域</p><p class="text-md text-gray-600">— 承認がめぐるまち</p></div><div class="chapter-item pl-4 py-2"><p class="text-lg font-bold color-accent">第7章:</p><p class="text-xl text-gray-700">（実践編・章題未特定）</p></div><div class="chapter-item pl-4 py-2"><p class="text-lg font-bold color-accent">第8章:</p><p class="text-xl text-gray-700">ホメホメ話法</p><p class="text-md text-gray-600">— 「もったいない」でくすぐる</p></div><div class="chapter-item pl-4 py-2"><p class="text-lg font-bold color-accent">第9章:</p><p class="text-xl text-gray-700">（実践編・章題未特定）</p></div><div class="chapter-item pl-4 py-2"><p class="text-lg font-bold color-accent">第10章:</p><p class="text-xl text-gray-700">ホメホメ社会宣言</p><p class="text-md text-gray-600">— 言葉を変えれば未来が変わる</p></div></div></div></div><!-- Footer --><div class="w-full flex justify-between items-center mt-8"><div class="flex items-center"><i class="fas fa-book-open text-sm color-accent mr-2"></i><p class="text-sm text-gray-500">ホメホメ革命</p></div><p class="text-sm text-gray-500">3 / 20</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'M PLUS Rounded 1c', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        overflow: hidden;        position: relative;        background-color: #FFF8F0;    }    .color-accent {        color: #FF8A00;    }    .color-secondary {        color: #4CAF50;    }    .chapter-item {        border-left: 4px solid #FF8A00;        transition: all 0.3s ease;    }    .chapter-item:hover {        background-color: rgba(255, 138, 0, 0.1);    }
</style>
