<template>
  <SlidePageWrapper slide-id="B0FYLJTC59" page-title="第2章: ホメホメの科学的根拠" :current-page="8" :total-pages="20">
<div class="slide-container flex flex-col items-center px-16 py-12"><!-- Header --><div class="w-full mb-8"><h1 class="text-4xl font-bold text-center"><span class="color-accent">第2章:</span> ホメホメの科学的根拠            </h1><div class="w-32 h-1 bg-orange-400 mx-auto mt-4"></div></div><!-- Main Content --><div class="flex-1 w-full flex flex-col justify-center"><div class="grid grid-cols-1 gap-8"><!-- 心理学 --><div class="content-box pl-6 py-2"><div class="flex items-center"><i class="fas fa-brain text-2xl color-accent mr-4"></i><p class="text-2xl font-bold text-gray-700">心理学:</p></div><p class="ml-12 text-xl text-gray-700">プロセス称賛は成長志向と持続を高める（ドウェック研究など）。</p></div><!-- 脳科学 --><div class="content-box pl-6 py-2"><div class="flex items-center"><i class="fas fa-dna text-2xl color-accent mr-4"></i><p class="text-2xl font-bold text-gray-700">脳科学:</p></div><p class="ml-12 text-xl text-gray-700">褒め言葉でドーパミン/オキシトシン活性化→つながりの快感→やる気と回復力。</p></div><!-- 回復力 --><div class="content-box pl-6 py-2"><div class="flex items-center"><i class="fas fa-heartbeat text-2xl color-accent mr-4"></i><p class="text-2xl font-bold text-gray-700">回復力:</p></div><p class="ml-12 text-xl text-gray-700">感情を肯定されると自己回復力（レジリエンス）が高まる。</p></div><!-- 結論 --><div class="content-box pl-6 py-2 bg-accent-light"><div class="flex items-center"><i class="fas fa-check-circle text-2xl color-accent mr-4"></i><p class="text-2xl font-bold text-gray-700">結論:</p></div><p class="ml-12 text-xl text-gray-700">叱責より承認が、学習/成績/協働を促進。科学的に実証されている。</p></div></div></div><!-- Footer --><div class="w-full flex justify-between items-center mt-8"><div class="flex items-center"><i class="fas fa-heart text-sm color-accent mr-2"></i><p class="text-sm text-gray-500">ホメホメ革命</p></div><p class="text-sm text-gray-500">8 / 20</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'M PLUS Rounded 1c', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            overflow: hidden;            position: relative;            background-color: #FFF8F0;        }        .color-accent {            color: #FF8A00;        }        .bg-accent-light {            background-color: rgba(255, 138, 0, 0.1);        }        .content-box {            border-left: 4px solid #FF8A00;        }
</style>
