<template>
  <SlidePageWrapper slide-id="B0FPPSR9ZW" page-title="第9章：リカバリー（回復）とセルフケア" :current-page="14" :total-pages="20">
<div class='slide-container'><div class='decoration decoration-top-right'></div><div class='decoration decoration-bottom-left'></div><div class='content-wrapper'><div class='header'><p class='title'>第9章：リカバリー（回復）とセルフケア</p><p class='subtitle'>回復こそがトレーニングの一部</p></div><div class='content-section'><div class='bullet-item'><div class='bullet-icon accent-color-1'><i class='fas fa-moon'></i></div><div class='bullet-text'><p class='bullet-title'>睡眠</p><p class='bullet-desc'>就寝・起床時刻の固定で体内リズムを安定させる／寝る90分前の入浴でスムーズな入眠を促進</p></div></div><div class='bullet-item'><div class='bullet-icon accent-color-2'><i class='fas fa-hot-tub'></i></div><div class='bullet-text'><p class='bullet-title'>入浴</p><p class='bullet-desc'>40℃前後の湯に10～15分浸かることで副交感神経優位に→リラックス効果と深い睡眠</p></div></div><div class='bullet-item'><div class='bullet-icon accent-color-3'><i class='fas fa-wind'></i></div><div class='bullet-text'><p class='bullet-title'>呼吸・昼寝</p><p class='bullet-desc'>腹式呼吸でリラックス効果／15～20分のパワーナップで午後の集中力回復</p></div></div><div class='bullet-item'><div class='bullet-icon accent-color-4'><i class='fas fa-apple-alt'></i></div><div class='bullet-text'><p class='bullet-title'>栄養</p><p class='bullet-desc'>運動後30分以内のたんぱく質摂取／適切な水分と電解質補給で回復を促進</p></div></div><div class='bullet-item'><div class='bullet-icon accent-color-5'><i class='fas fa-calendar-alt'></i></div><div class='bullet-text'><p class='bullet-title'>週内設計</p><p class='bullet-desc'>軽・中・強度の運動と休息日を適切に配置／回復をデザインすることで体力向上と怪我防止</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;            color: #333;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            background-color: #f5f9fc;            overflow: hidden;            position: relative;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px;            z-index: 2;        }        .header {            margin-bottom: 40px;        }        .title {            font-size: 42px;            font-weight: 700;            color: #1e88e5;            margin-bottom: 10px;        }        .subtitle {            font-size: 24px;            font-weight: 500;            color: #546e7a;        }        .content-section {            display: flex;            flex-direction: column;            gap: 24px;        }        .bullet-item {            display: flex;            align-items: flex-start;            gap: 16px;        }        .bullet-icon {            flex-shrink: 0;            width: 46px;            height: 46px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            font-size: 20px;            color: white;        }        .bullet-text {            flex: 1;        }        .bullet-title {            font-size: 22px;            font-weight: 700;            margin-bottom: 6px;        }        .bullet-desc {            font-size: 18px;            font-weight: 400;            line-height: 1.5;        }        .accent-color-1 { background-color: #4caf50; }        .accent-color-2 { background-color: #2196f3; }        .accent-color-3 { background-color: #ff9800; }        .accent-color-4 { background-color: #9c27b0; }        .accent-color-5 { background-color: #e91e63; }        .decoration {            position: absolute;            z-index: 1;        }        .decoration-top-right {            top: -80px;            right: -80px;            width: 200px;            height: 200px;            border-radius: 50%;            background-color: rgba(33, 150, 243, 0.1);        }        .decoration-bottom-left {            bottom: -100px;            left: -100px;            width: 300px;            height: 300px;            border-radius: 50%;            background-color: rgba(76, 175, 80, 0.1);        }
</style>
