<template>
  <SlidePageWrapper slide-id="B0FPPSR9ZW" page-title="習慣化のコツとつまずき対策" :current-page="17" :total-pages="20">
<div class='slide-container'><div class='decoration decoration-top-right'></div><div class='decoration decoration-bottom-left'></div><div class='content-wrapper'><div class='header'><p class='title'>習慣化のコツとつまずき対策</p><p class='subtitle'>継続するための具体的テクニックと再開のヒント</p></div><div class='content-section'><div class='bullet-item'><div class='bullet-icon accent-color-1'><i class='fas fa-calendar-check'></i></div><div class='bullet-text'><p class='bullet-title'>If-Thenプランニング</p><p class='bullet-desc'>「もし○○したら、△△する」と具体的に計画。例：「朝歯を磨いたら、10秒スクワット」</p></div></div><div class='bullet-item'><div class='bullet-icon accent-color-2'><i class='fas fa-clock'></i></div><div class='bullet-text'><p class='bullet-title'>2分ルール</p><p class='bullet-desc'>最小行動から着手する。たった2分間だけと決めて始める。ハードルを極限まで下げる</p></div></div><div class='bullet-item'><div class='bullet-icon accent-color-3'><i class='fas fa-home'></i></div><div class='bullet-text'><p class='bullet-title'>環境デザイン</p><p class='bullet-desc'>邪魔なものを減らし、サポート要素を増やす。運動着を目立つ場所に、ながら運動の仕掛けを設置</p></div></div><div class='bullet-item'><div class='bullet-icon accent-color-4'><i class='fas fa-users'></i></div><div class='bullet-text'><p class='bullet-title'>ソーシャルサポート</p><p class='bullet-desc'>家族・友人に宣言し記録を共有。アプリでコミュニティに参加し励まし合う</p></div></div><div class='bullet-item'><div class='bullet-icon accent-color-5'><i class='fas fa-redo'></i></div><div class='bullet-text'><p class='bullet-title'>挫折時の再起</p><p class='bullet-desc'>完璧主義を捨て、原因を1つだけ特定して修正。「明日から再開」と決めて罪悪感を手放す</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;            color: #333;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            background-color: #f5f9fc;            overflow: hidden;            position: relative;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px;            z-index: 2;        }        .header {            margin-bottom: 40px;        }        .title {            font-size: 42px;            font-weight: 700;            color: #1e88e5;            margin-bottom: 10px;        }        .subtitle {            font-size: 24px;            font-weight: 500;            color: #546e7a;        }        .content-section {            display: flex;            flex-direction: column;            gap: 24px;        }        .bullet-item {            display: flex;            align-items: flex-start;            gap: 16px;        }        .bullet-icon {            flex-shrink: 0;            width: 46px;            height: 46px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            font-size: 20px;            color: white;        }        .bullet-text {            flex: 1;        }        .bullet-title {            font-size: 22px;            font-weight: 700;            margin-bottom: 6px;        }        .bullet-desc {            font-size: 18px;            font-weight: 400;            line-height: 1.5;        }        .accent-color-1 { background-color: #4caf50; }        .accent-color-2 { background-color: #2196f3; }        .accent-color-3 { background-color: #ff9800; }        .accent-color-4 { background-color: #9c27b0; }        .accent-color-5 { background-color: #e91e63; }        .decoration {            position: absolute;            z-index: 1;        }        .decoration-top-right {            top: -80px;            right: -80px;            width: 200px;            height: 200px;            border-radius: 50%;            background-color: rgba(33, 150, 243, 0.1);        }        .decoration-bottom-left {            bottom: -100px;            left: -100px;            width: 300px;            height: 300px;            border-radius: 50%;            background-color: rgba(76, 175, 80, 0.1);        }
</style>
