<template>
  <SlidePageWrapper slide-id="B0FPPSR9ZW" page-title="第2–3章：運動が苦手を変える・モチベ不要" :current-page="6" :total-pages="20">
<div class='slide-container'><div class='decoration decoration-top-right'></div><div class='decoration decoration-bottom-left'></div><div class='content-wrapper'><div class='header'><p class='title'>第2–3章：運動が苦手を変える・モチベ不要</p><p class='subtitle'>無理なく続けるための仕組みづくり</p></div><div class='content-section'><div class='bullet-item'><div class='bullet-icon accent-color-1'><i class='fas fa-arrow-alt-circle-up'></i></div><div class='bullet-text'><p class='bullet-title'>小さな目標を設計</p><p class='bullet-desc'>「あと1回」「あと1秒」の小さな積み重ねで成功体験を増やす</p></div></div><div class='bullet-item'><div class='bullet-icon accent-color-2'><i class='fas fa-cogs'></i></div><div class='bullet-text'><p class='bullet-title'>仕組み化</p><p class='bullet-desc'>トリガー習慣（歯磨き前に10秒運動など）と前日のセットアップ</p></div></div><div class='bullet-item'><div class='bullet-icon accent-color-3'><i class='fas fa-chart-bar'></i></div><div class='bullet-text'><p class='bullet-title'>記録とごほうび</p><p class='bullet-desc'>見える形で達成を記録し、脳の報酬系を活用して継続力を高める</p></div></div><div class='bullet-item'><div class='bullet-icon accent-color-4'><i class='fas fa-clipboard-list'></i></div><div class='bullet-text'><p class='bullet-title'>ルール化</p><p class='bullet-desc'>時間・種目・強度の上限と下限を事前に決めておき迷いを減らす</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;            color: #333;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            background-color: #f5f9fc;            overflow: hidden;            position: relative;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px;            z-index: 2;        }        .header {            margin-bottom: 40px;        }        .title {            font-size: 42px;            font-weight: 700;            color: #1e88e5;            margin-bottom: 10px;        }        .subtitle {            font-size: 24px;            font-weight: 500;            color: #546e7a;        }        .content-section {            display: flex;            flex-direction: column;            gap: 24px;        }        .bullet-item {            display: flex;            align-items: flex-start;            gap: 16px;        }        .bullet-icon {            flex-shrink: 0;            width: 46px;            height: 46px;            border-radius: 50%;            display: flex;            align-items: center;            justify-content: center;            font-size: 20px;            color: white;        }        .bullet-text {            flex: 1;        }        .bullet-title {            font-size: 22px;            font-weight: 700;            margin-bottom: 6px;        }        .bullet-desc {            font-size: 18px;            font-weight: 400;            line-height: 1.5;        }        .accent-color-1 { background-color: #4caf50; }        .accent-color-2 { background-color: #2196f3; }        .accent-color-3 { background-color: #ff9800; }        .accent-color-4 { background-color: #9c27b0; }        .decoration {            position: absolute;            z-index: 1;        }        .decoration-top-right {            top: -80px;            right: -80px;            width: 200px;            height: 200px;            border-radius: 50%;            background-color: rgba(33, 150, 243, 0.1);        }        .decoration-bottom-left {            bottom: -100px;            left: -100px;            width: 300px;            height: 300px;            border-radius: 50%;            background-color: rgba(76, 175, 80, 0.1);        }
</style>
