<template>
  <SlidePageWrapper slide-id="B086KQK72S" page-title="パッと書けてすぐに売れる稼ぐ人の「超速」文章術" :current-page="1" :total-pages="20">
<div class='slide-container'><div class='pattern-overlay'></div><div class='corner-accent top-right'></div><div class='corner-accent bottom-left'></div><div class='slide-content'><div class='title-box'><p class='text-5xl font-black tracking-tight text-center mb-2'>パッと書けてすぐに売れる</p><p class='text-6xl font-black tracking-tight text-center'>稼ぐ人の「超速」文章術</p></div><div class='accent-box'><p class='text-xl font-medium text-center'>速く×上手く×売れるを同時に叶える 実践ライティング</p></div><div class='usage-box'><p class='text-lg'>SNS／ブログ／メルマガ／LP／企画書／社内文書</p></div><div class='author-box'><p class='text-3xl font-bold'>著者：中野 巧</p><p class='text-xl'>NAKANO KOU</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            position: relative;            background-color: #f8f9fa;            display: flex;            flex-direction: column;            overflow: hidden;        }        .slide-content {            flex: 1;            display: flex;            flex-direction: column;            justify-content: center;            align-items: center;            padding: 40px;            position: relative;            z-index: 10;        }        .title-box {            background-color: #ffffff;            border-left: 10px solid #ff7e36;            padding: 30px 40px;            margin-bottom: 30px;            width: 85%;            box-shadow: 0 4px 12px rgba(0,0,0,0.08);        }        .accent-box {            background-color: #3498db;            color: white;            padding: 20px;            width: 75%;            box-shadow: 0 4px 12px rgba(0,0,0,0.08);        }        .usage-box {            background-color: #ffffff;            padding: 15px 25px;            margin-top: 25px;            width: 70%;            border: 2px solid #ff7e36;            text-align: center;        }        .author-box {            text-align: right;            width: 85%;            margin-top: 20px;        }        .pattern-overlay {            position: absolute;            top: 0;            left: 0;            width: 100%;            height: 100%;            opacity: 0.05;            z-index: 1;            background-color: #333;            background-image: url('data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='0.4'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E');        }        .corner-accent {            position: absolute;            width: 200px;            height: 200px;            background-color: #ff7e36;            opacity: 0.1;            z-index: 2;        }        .top-right {            top: -100px;            right: -100px;            transform: rotate(45deg);        }        .bottom-left {            bottom: -100px;            left: -100px;            transform: rotate(45deg);        }
</style>
