<template>
  <SlidePageWrapper slide-id="B086KQK72S" page-title="第7章②：LPを強くする11の売れる要素" :current-page="14" :total-pages="20">
<div class='slide-container'><div class='pattern-overlay'></div><div class='slide-header'><div class='title-bar'><h2 class='text-4xl font-bold'>第7章②：LPを強くする11の売れる要素</h2></div><p class='subtitle'>ランディングページを確実に成約へ導く11の構成パーツ</p></div><div class='slide-content'><div class='element-box'><div class='number'>1</div><h3>メインコピー</h3><p>顧客を一瞬で惹きつける<span class='highlight'>キャッチコピー</span>。ベネフィットを直感的に伝え、興味を引く第一関門。</p></div><div class='element-box'><div class='number'>2</div><h3>サブコピー</h3><p>メインを補足する<span class='highlight'>リード文</span>。より具体的に価値を伝え、続きを読ませる橋渡し役。</p></div><div class='element-box'><div class='number'>3</div><h3>70%の現実</h3><p>顧客が直面している<span class='highlight'>満たされない現実</span>や問題点を共感的に描写し、痛みに寄り添う。</p></div><div class='element-box'><div class='number'>4</div><h3>100〜120%の未来</h3><p>商品導入後の<span class='highlight'>理想的な未来像</span>。短期的な変化から長期的な人生の変化まで提示。</p></div><div class='element-box'><div class='number'>5</div><h3>一般的な解決策</h3><p>既存の解決方法と<span class='highlight'>その限界</span>を示し、新しいソリューションの必要性を暗示。</p></div><div class='element-box'><div class='number'>6</div><h3>商品による解決策</h3><p>あなたの商品・サービスが提供する<span class='highlight'>独自の解決法</span>と、なぜ他と違うのかを明確に。</p></div><div class='element-box'><div class='number'>7</div><h3>証拠（エビデンス）</h3><p>実績・数字・事例・お客様の声など、<span class='highlight'>信頼性を裏付ける</span>客観的な証拠の提示。</p></div><div class='element-box'><div class='number'>8</div><h3>商品概要・スペック</h3><p>具体的な<span class='highlight'>内容・仕様・詳細</span>を明示し、検討材料を提供。比較検討を可能に。</p></div><div class='element-box'><div class='number'>9</div><h3>行動喚起（オファー）</h3><p>具体的な<span class='highlight'>申込方法・期間限定・特典</span>など、今行動する理由と方法を明確に。</p></div><div class='element-box'><div class='number'>10</div><h3>感動ストーリー</h3><p>顧客が<span class='highlight'>共感できる物語</span>。ビジョンや自己開示を通じて感情的な結びつきを作る。</p></div><div class='element-box'><div class='number'>11</div><h3>付加要素</h3><p><span class='highlight'>FAQ・プロフィール・体験談・PS</span>など、不安を払拭し背中を押す補足的要素。</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        position: relative;        background-color: #f8f9fa;        display: flex;        flex-direction: column;        overflow: hidden;    }    .slide-header {        padding: 30px 50px 10px;        z-index: 10;    }    .slide-content {        flex: 1;        display: flex;        flex-wrap: wrap;        padding: 0 50px 40px;        z-index: 10;    }    .title-bar {        position: relative;        border-left: 10px solid #ff7e36;        padding-left: 20px;        margin-bottom: 20px;    }    .element-box {        background-color: white;        border-radius: 8px;        box-shadow: 0 4px 12px rgba(0,0,0,0.05);        padding: 15px;        margin: 8px;        width: calc(33.333% - 16px);        position: relative;        overflow: hidden;    }    .element-box .number {        position: absolute;        top: 10px;        left: 10px;        background-color: #ff7e36;        color: white;        width: 28px;        height: 28px;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        font-weight: bold;        font-size: 14px;    }    .element-box h3 {        margin-left: 35px;        font-size: 18px;        font-weight: 700;        color: #3498db;        margin-bottom: 10px;    }    .element-box p {        font-size: 14px;        line-height: 1.4;        color: #444;    }    .highlight {        color: #ff7e36;        font-weight: 700;    }    .pattern-overlay {        position: absolute;        top: 0;        left: 0;        width: 100%;        height: 100%;        opacity: 0.03;        z-index: 1;        background-image: url('data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='0.4'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E');    }    .subtitle {        font-size: 18px;        color: #666;        margin-top: -10px;        margin-left: 30px;        margin-bottom: 20px;    }
</style>
