<template>
  <SlidePageWrapper slide-id="B086KQK72S" page-title="重要コラムで身につく'考え方'" :current-page="16" :total-pages="20">
<div class='slide-container'><div class='pattern-overlay'></div><div class='slide-header'><div class='title-bar'><h2 class='text-4xl font-bold'>重要コラムで身につく'考え方'</h2></div></div><div class='slide-content'><div class='content-column'><div class='content-box'><h3 class='text-xl font-bold'><i class='fas fa-lightbulb'></i> 実践マインドセット</h3><ul class='bullet-list'><li><i class='fas fa-quote-left'></i><div><p><span class='highlight'>100点は不要：</span>30%の完成度でOK！文章に完璧はなく、「出す→改善」の循環が大切</p></div></li><li><i class='fas fa-quote-left'></i><div><p><span class='highlight'>2割で8割の成果：</span>「内容→構成→表現」の順に優先。テクニックよりも'何を・どう伝えるか'が重要</p></div></li><li><i class='fas fa-quote-left'></i><div><p><span class='highlight'>SNS投稿と集客：</span>無料だけでなく広告テストもショートカットに。アルゴリズムに左右されず確実性を高める</p></div></li></ul></div></div><div class='content-column'><div class='content-box'><h3 class='text-xl font-bold'><i class='fas fa-book-open'></i> 実例から学ぶ</h3><ul class='bullet-list'><li><i class='fas fa-quote-left'></i><div><p><span class='highlight'>そごう・西武広告：</span>「さ、ひっくり返そう。」というコピーは上から読むと「逆転」、下から読むと「現状維持」を意味する。<span class='highlight'>読む順で意味が反転＝構成の力</span>を示す究極事例</p></div></li><li><i class='fas fa-quote-left'></i><div><p><span class='highlight'>メリットvsベネフィット：</span>メリット＝商品の特徴・機能、ベネフィット＝顧客が得る体験・変化・利益。<span class='highlight'>顧客が本当に欲しいのは'得'</span>であり、「だから何？」と問いながらベネフィットへ変換する</p></div></li></ul></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        position: relative;        background-color: #f8f9fa;        display: flex;        flex-direction: column;        overflow: hidden;    }    .slide-header {        padding: 30px 50px 10px;        z-index: 10;    }    .slide-content {        flex: 1;        display: flex;        padding: 0 50px 40px;        z-index: 10;    }    .title-bar {        position: relative;        border-left: 10px solid #ff7e36;        padding-left: 20px;        margin-bottom: 20px;    }    .content-column {        flex: 1;        display: flex;        flex-direction: column;        padding: 0 15px;    }    .content-box {        background-color: white;        border-radius: 8px;        box-shadow: 0 4px 12px rgba(0,0,0,0.05);        padding: 20px 25px;        margin-bottom: 20px;        flex: 1;        overflow: hidden;    }    .content-box h3 {        display: flex;        align-items: center;        margin-bottom: 15px;        color: #3498db;    }    .content-box h3 i {        margin-right: 10px;    }    .bullet-list {        list-style: none;        padding-left: 5px;    }    .bullet-list li {        display: flex;        align-items: flex-start;        margin-bottom: 15px;        line-height: 1.5;    }    .bullet-list i {        color: #ff7e36;        margin-right: 10px;        margin-top: 5px;        flex-shrink: 0;    }    .highlight {        color: #ff7e36;        font-weight: 700;    }    .pattern-overlay {        position: absolute;        top: 0;        left: 0;        width: 100%;        height: 100%;        opacity: 0.03;        z-index: 1;        background-image: url('data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='0.4'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E');    }
</style>
