<template>
  <SlidePageWrapper slide-id="B086KQK72S" page-title="キーメッセージ集（Key Sentences）" :current-page="18" :total-pages="20">
<div class='slide-container'><div class='pattern-overlay'></div><div class='slide-header'><div class='title-bar'><h2 class='text-4xl font-bold'>キーメッセージ集（Key Sentences）</h2></div></div><div class='slide-content'><div class='content-column w-full'><div class='content-box'><h3 class='text-xl font-bold'><i class='fas fa-quote-left'></i> 書籍の核となるメッセージ</h3><ul class='bullet-list'><li><i class='fas fa-lightbulb'></i><div><p class='message-text'>上手い文章を<span class='highlight'>「速く書ける」</span>ことが時代の必須スキル</p></div></li><li><i class='fas fa-lightbulb'></i><div><p class='message-text'>文章は、<span class='highlight'>誰でも、確実に、上手くなる</span></p></div></li><li><i class='fas fa-lightbulb'></i><div><p class='message-text'><span class='highlight'>あなたの当たり前</span>は、相手の当たり前とは限らない</p></div></li><li><i class='fas fa-lightbulb'></i><div><p class='message-text'>完璧主義をやめ、<span class='highlight'>30%の完成度でOK</span>。まず出す→改善する</p></div></li><li><i class='fas fa-lightbulb'></i><div><p class='message-text'><span class='highlight'>読み手中心</span>（あなた主語）で設計する</p></div></li></ul></div><div class='content-box'><h3 class='text-xl font-bold'><i class='fas fa-star'></i> 成功の要素</h3><ul class='bullet-list'><li><i class='fas fa-check-circle'></i><div><p class='message-text'><span class='highlight'>型×心理効果×仕組み</span>の3要素で質と速度を両立</p></div></li><li><i class='fas fa-check-circle'></i><div><p class='message-text'>内容と構成で<span class='highlight'>2割の努力で8割の成果</span>を出す</p></div></li><li><i class='fas fa-check-circle'></i><div><p class='message-text'><span class='highlight'>メリット</span>（商品特徴）より<span class='highlight'>ベネフィット</span>（得られる体験・変化）を伝える</p></div></li><li><i class='fas fa-check-circle'></i><div><p class='message-text'><span class='highlight'>共感の仕組み</span>で読み手の行動を促す</p></div></li><li><i class='fas fa-check-circle'></i><div><p class='message-text'>文章構成こそが<span class='highlight'>「伝わる力」</span>の要</p></div></li></ul></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        position: relative;        background-color: #f8f9fa;        display: flex;        flex-direction: column;        overflow: hidden;    }    .slide-header {        padding: 30px 50px 10px;        z-index: 10;    }    .slide-content {        flex: 1;        display: flex;        padding: 0 50px 40px;        z-index: 10;    }    .title-bar {        position: relative;        border-left: 10px solid #ff7e36;        padding-left: 20px;        margin-bottom: 20px;    }    .content-column {        flex: 1;        display: flex;        flex-direction: column;        padding: 0 15px;    }    .content-box {        background-color: white;        border-radius: 8px;        box-shadow: 0 4px 12px rgba(0,0,0,0.05);        padding: 20px 25px;        margin-bottom: 20px;        flex: 1;        overflow: hidden;    }    .content-box h3 {        display: flex;        align-items: center;        margin-bottom: 15px;        color: #3498db;    }    .content-box h3 i {        margin-right: 10px;    }    .bullet-list {        list-style: none;        padding-left: 5px;    }    .bullet-list li {        display: flex;        align-items: flex-start;        margin-bottom: 18px;        line-height: 1.5;    }    .bullet-list i {        color: #ff7e36;        margin-right: 10px;        margin-top: 5px;        font-size: 18px;    }    .highlight {        color: #ff7e36;        font-weight: 700;    }    .quote-icon {        font-size: 24px;        color: rgba(52, 152, 219, 0.2);        margin-right: 10px;    }    .message-text {        font-size: 18px;    }    .pattern-overlay {        position: absolute;        top: 0;        left: 0;        width: 100%;        height: 100%;        opacity: 0.03;        z-index: 1;        background-image: url('data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='0.4'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E');    }
</style>
