<template>
  <SlidePageWrapper slide-id="B086KQK72S" page-title="実践ワーク一覧（すぐ使える演習）" :current-page="19" :total-pages="20">
<div class='slide-container'><div class='pattern-overlay'></div><div class='slide-header'><div class='title-bar'><h2 class='text-4xl font-bold'>実践ワーク一覧（すぐ使える演習）</h2></div></div><div class='slide-content'><div class='work-container'><div class='work-item'><div class='work-icon'><i class='fas fa-sync-alt fa-2x'></i></div><div class='work-content'><h3 class='work-title'>第1章：アップデート法でフィードバック</h3><p class='work-description'>10のアップデート法を使って、自分や他者の文章に具体的な改善点を見つけ、赤ペンで修正。発表とフィードバックで実践力を高める。</p></div></div><div class='work-item'><div class='work-icon'><i class='fas fa-comment-dots fa-2x'></i></div><div class='work-content'><h3 class='work-title'>第2章：SNS文章作成ゲーム</h3><p class='work-description'>5つの質問に答えるだけで5パターンの投稿文が自動で完成。結論展開型、感情巻き込み型など、状況に応じて最適な形を選べる。</p></div></div><div class='work-item'><div class='work-icon'><i class='fas fa-users fa-2x'></i></div><div class='work-content'><h3 class='work-title'>第3章：よってたかって文章改善</h3><p class='work-description'>キャッチコピー・接続詞・ターゲット設定などを活用して、グループでアイデアを出し合いながら文章の魅力と読みやすさを高める。</p></div></div><div class='work-item'><div class='work-icon'><i class='fas fa-pencil-alt fa-2x'></i></div><div class='work-content'><h3 class='work-title'>第4章：勝負！文章作成ゲーム</h3><p class='work-description'>穴埋めテンプレート2.0を使って、短時間で構造化された高品質な記事を作成。テンプレートの各要素をつなぎ言葉で自然につなげる。</p></div></div><div class='work-item'><div class='work-icon'><i class='fas fa-heart fa-2x'></i></div><div class='work-content'><h3 class='work-title'>第5章：エンパシーチャートで社内文書</h3><p class='work-description'>10の質問で感情と論理の両面から社内文書を設計。ポジティブ・ネガティブ両方の視点を入れることで、共感度の高い文章に変換する。</p></div></div><div class='work-item'><div class='work-icon'><i class='fas fa-lightbulb fa-2x'></i></div><div class='work-content'><h3 class='work-title'>第6章：寄り添いマップで配信ネタ出し</h3><p class='work-description'>1つの題材から複数の配信ネタを生み出す。価値の源泉・現実・メリット・未来といった視点から付箋でアイデアを拡散→収束させる。</p></div></div><div class='work-item'><div class='work-icon'><i class='fas fa-trophy fa-2x'></i></div><div class='work-content'><h3 class='work-title'>第7章：LP作成バトル</h3><p class='work-description'>5ブロック×11要素の構成で、グループ対抗で売れるランディングページを設計。HEAD・ROOT'S・Technique・Evidence・Pointの流れで構築。</p></div></div><div class='work-item'><div class='work-icon'><i class='fas fa-check-double fa-2x'></i></div><div class='work-content'><h3 class='work-title'>すぐに実践！ワークの活用法</h3><p class='work-description'>全てのワークは10〜30分で実施可能。個人・グループどちらでも効果的。実際の業務課題に応用することで効果を最大化できる。</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        position: relative;        background-color: #f8f9fa;        display: flex;        flex-direction: column;        overflow: hidden;    }    .slide-header {        padding: 30px 50px 10px;        z-index: 10;    }    .slide-content {        flex: 1;        display: flex;        padding: 0 50px 40px;        z-index: 10;    }    .title-bar {        position: relative;        border-left: 10px solid #ff7e36;        padding-left: 20px;        margin-bottom: 20px;    }    .work-container {        display: flex;        flex-wrap: wrap;        width: 100%;        gap: 20px;    }    .work-item {        background-color: white;        border-radius: 8px;        box-shadow: 0 4px 12px rgba(0,0,0,0.05);        padding: 20px;        width: calc(50% - 10px);        display: flex;        align-items: flex-start;    }    .work-icon {        background-color: #f0f9ff;        color: #3498db;        width: 60px;        height: 60px;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        margin-right: 15px;        flex-shrink: 0;    }    .work-content {        flex: 1;    }    .work-title {        color: #ff7e36;        font-weight: 700;        margin-bottom: 5px;        font-size: 1.1rem;    }    .work-description {        color: #505050;        font-size: 0.95rem;        line-height: 1.4;    }    .pattern-overlay {        position: absolute;        top: 0;        left: 0;        width: 100%;        height: 100%;        opacity: 0.03;        z-index: 1;        background-image: url('data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='0.4'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E');    }
</style>
