<template>
  <SlidePageWrapper slide-id="B086KQK72S" page-title="この本の概要・対象読者・得られる変化" :current-page="2" :total-pages="20">
<div class='slide-container'><div class='pattern-overlay'></div><div class='slide-header'><div class='title-bar'><h2 class='text-4xl font-bold'>この本の概要・対象読者・得られる変化</h2></div></div><div class='slide-content'><div class='content-column'><div class='content-box'><h3 class='text-xl font-bold'><i class='fas fa-book'></i> 概要</h3><ul class='bullet-list'><li><i class='fas fa-check-circle'></i><p>誰でも短時間で成果の出る文章が書ける<span class='highlight'>「型×心理×仕組み」</span>を体系化</p></li><li><i class='fas fa-check-circle'></i><p>SNSからランディングページまで、幅広いライティングに対応</p></li><li><i class='fas fa-check-circle'></i><p>「速く書く」と「上手く書く」を両立させる実践的テンプレート</p></li></ul></div><div class='content-box'><h3 class='text-xl font-bold'><i class='fas fa-history'></i> 背景</h3><ul class='bullet-list'><li><i class='fas fa-check-circle'></i><p>誰もがメディア化する時代、文章は<span class='highlight'>全員の必須スキル</span>に</p></li><li><i class='fas fa-check-circle'></i><p>「速く書けて上手い」が現代の即戦力条件</p></li><li><i class='fas fa-check-circle'></i><p>SNS・ブログ・LP等の多様なプラットフォーム対応が必要</p></li></ul></div></div><div class='content-column'><div class='content-box'><h3 class='text-xl font-bold'><i class='fas fa-users'></i> 対象読者</h3><ul class='bullet-list'><li><i class='fas fa-check-circle'></i><p>新入社員・若手ビジネスパーソン</p></li><li><i class='fas fa-check-circle'></i><p>自営業・フリーランス</p></li><li><i class='fas fa-check-circle'></i><p>広報・営業・マーケティング担当者</p></li><li><i class='fas fa-check-circle'></i><p>SNSやブログで情報発信をしたい方</p></li></ul></div><div class='content-box'><h3 class='text-xl font-bold'><i class='fas fa-chart-line'></i> 得られる変化</h3><ul class='bullet-list'><li><i class='fas fa-check-circle'></i><p><span class='highlight'>伝わる文章</span>→売上・反応率向上</p></li><li><i class='fas fa-check-circle'></i><p><span class='highlight'>速く書ける</span>→業務効率化・継続配信</p></li><li><i class='fas fa-check-circle'></i><p><span class='highlight'>共感が生まれる</span>→関係性・信頼構築</p></li><li><i class='fas fa-check-circle'></i><p><span class='highlight'>ストレス軽減</span>→文章作成の心理的負担減</p></li></ul></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        position: relative;        background-color: #f8f9fa;        display: flex;        flex-direction: column;        overflow: hidden;    }    .slide-header {        padding: 30px 50px 10px;        z-index: 10;    }    .slide-content {        flex: 1;        display: flex;        padding: 0 50px 40px;        z-index: 10;    }    .title-bar {        position: relative;        border-left: 10px solid #ff7e36;        padding-left: 20px;        margin-bottom: 20px;    }    .content-column {        flex: 1;        display: flex;        flex-direction: column;        padding: 0 15px;    }    .content-box {        background-color: white;        border-radius: 8px;        box-shadow: 0 4px 12px rgba(0,0,0,0.05);        padding: 20px 25px;        margin-bottom: 20px;        height: calc(50% - 10px);        overflow: hidden;    }    .content-box h3 {        display: flex;        align-items: center;        margin-bottom: 15px;        color: #3498db;    }    .content-box h3 i {        margin-right: 10px;    }    .bullet-list {        list-style: none;        padding-left: 5px;    }    .bullet-list li {        display: flex;        align-items: flex-start;        margin-bottom: 12px;        line-height: 1.5;    }    .bullet-list i {        color: #ff7e36;        margin-right: 10px;        margin-top: 5px;    }    .highlight {        color: #ff7e36;        font-weight: 700;    }    .pattern-overlay {        position: absolute;        top: 0;        left: 0;        width: 100%;        height: 100%;        opacity: 0.03;        z-index: 1;        background-image: url('data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='0.4'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E');    }
</style>
