<template>
  <SlidePageWrapper slide-id="B086KQK72S" page-title="全体構成（7章の大枠）" :current-page="3" :total-pages="20">
<div class='slide-container'><div class='pattern-overlay'></div><div class='slide-header'><div class='title-bar'><h2 class='text-4xl font-bold'>全体構成（7章の大枠）</h2></div></div><div class='slide-content'><div class='chapter-grid'><div class='chapter-card'><div class='side-accent'></div><div class='chapter-number'>1</div><div class='chapter-content'><p class='chapter-title'>超速！文章アップデート法</p><p class='chapter-desc'>知るだけで文章が上手くなる5つのコツと心理効果。文章量を半減させつつ伝わる力をアップさせる実践テクニック。</p></div></div><div class='chapter-card'><div class='side-accent'></div><div class='chapter-number'>2</div><div class='chapter-content'><p class='chapter-title'>超速！SNS文章作成ゲーム</p><p class='chapter-desc'>SNS投稿が自動で5パターン出てくる方法。とっておきの5つの質問で継続的な配信が可能に。</p></div></div><div class='chapter-card'><div class='side-accent'></div><div class='chapter-number'>3</div><div class='chapter-content'><p class='chapter-title'>超速！文章テクニック</p><p class='chapter-desc'>キャッチコピー369、刺さるネーミング、ターゲット設定、接続詞活用など即効性のあるテクニック集。</p></div></div><div class='chapter-card'><div class='side-accent'></div><div class='chapter-number'>4</div><div class='chapter-content'><p class='chapter-title'>超速！穴埋めテンプレート</p><p class='chapter-desc'>良質な記事が量産できるCatch Me If You Can構造の穴埋め式テンプレート2.0でブログ・メルマガを効率化。</p></div></div><div class='chapter-card'><div class='side-accent'></div><div class='chapter-number'>5</div><div class='chapter-content'><p class='chapter-title'>超速！共感チャート</p><p class='chapter-desc'>1枚のシートを埋めるだけで共感を結果に繋げるエンパシーチャート。10要素×3ステップで共感文章を生み出す。</p></div></div><div class='chapter-card'><div class='side-accent'></div><div class='chapter-number'>6</div><div class='chapter-content'><p class='chapter-title'>超速！寄り添いマップ</p><p class='chapter-desc'>新しい配信ネタが次々湧いてくる5つの質問法と、コア・トライアングルによる価値の明確化テクニック。</p></div></div><div class='chapter-card'><div class='side-accent'></div><div class='chapter-number'>7</div><div class='chapter-content'><p class='chapter-title'>超速！究極のLPテンプレート</p><p class='chapter-desc'>5ブロック構造と11の売れる要素、22のチェックポイントで完成する高変換率ランディングページの作り方。</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        position: relative;        background-color: #f8f9fa;        display: flex;        flex-direction: column;        overflow: hidden;    }    .slide-header {        padding: 30px 50px 15px;        z-index: 10;    }    .slide-content {        flex: 1;        display: flex;        flex-direction: column;        padding: 0 50px 40px;        z-index: 10;    }    .title-bar {        position: relative;        border-left: 10px solid #ff7e36;        padding-left: 20px;        margin-bottom: 20px;    }    .chapter-grid {        display: grid;        grid-template-columns: repeat(2, 1fr);        gap: 20px;    }    .chapter-card {        background-color: white;        border-radius: 8px;        box-shadow: 0 4px 12px rgba(0,0,0,0.05);        padding: 15px 20px;        display: flex;        align-items: flex-start;        transition: transform 0.2s;        position: relative;        overflow: hidden;    }    .chapter-card:hover {        transform: translateY(-3px);    }    .chapter-number {        background-color: #3498db;        color: white;        border-radius: 50%;        width: 48px;        height: 48px;        display: flex;        justify-content: center;        align-items: center;        font-weight: bold;        font-size: 1.3rem;        margin-right: 15px;        flex-shrink: 0;    }    .chapter-content {        flex: 1;    }    .chapter-title {        color: #ff7e36;        font-weight: bold;        font-size: 1.2rem;        margin-bottom: 8px;        line-height: 1.3;    }    .chapter-desc {        font-size: 0.95rem;        color: #555;        line-height: 1.4;    }    .pattern-overlay {        position: absolute;        top: 0;        left: 0;        width: 100%;        height: 100%;        opacity: 0.03;        z-index: 1;        background-image: url('data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='0.4'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E');    }    .side-accent {        position: absolute;        width: 10px;        height: 60%;        background-color: #ff7e36;        opacity: 0.2;        right: 0;        top: 20%;    }
</style>
