<template>
  <SlidePageWrapper slide-id="B086KQK72S" page-title="第1章①：知るだけで上手くなる5つのコツ" :current-page="4" :total-pages="20">
<div class='slide-container'><div class='pattern-overlay'></div><div class='slide-header'><div class='title-bar'><h2 class='text-4xl font-bold'>第1章①：知るだけで上手くなる5つのコツ</h2></div></div><div class='slide-content'><div class='content-box'><ul class='tip-list'><li class='tip-item'><div class='tip-number'>1</div><div class='tip-content'><p class='tip-title'><i class='fas fa-user tip-icon'></i>主語を「あなた」にする</p><p class='tip-description'>「私は」主語の自己中心文章より、読み手を主役にした「あなたは」主語の文章に。</p><div class='tip-effect'>効果：<span class='highlight'>読み手参加型</span>で共感・関心度UP</div></div></li><li class='tip-item'><div class='tip-number'>2</div><div class='tip-content'><p class='tip-title'><i class='fas fa-question-circle tip-icon'></i>「？」を乱用しない</p><p class='tip-description'>疑問符の連続使用は読み手に精神的圧迫感を与える。必要最小限に。</p><div class='tip-effect'>効果：<span class='highlight'>心理的余裕</span>が生まれ読みやすさ向上</div></div></li><li class='tip-item'><div class='tip-number'>3</div><div class='tip-content'><p class='tip-title'><i class='fas fa-text-width tip-icon'></i>1文50文字以内</p><p class='tip-description'>長文は理解を妨げる。一文を短く区切って「ブロック化」すると伝わる。</p><div class='tip-effect'>効果：<span class='highlight'>可読性向上</span>・内容が頭に残りやすい</div></div></li><li class='tip-item'><div class='tip-number'>4</div><div class='tip-content'><p class='tip-title'><i class='fas fa-feather-alt tip-icon'></i>相手に負担を与えない</p><p class='tip-description'>専門用語や前提知識の押し付けは読者離れの原因に。平易な表現を心がける。</p><div class='tip-effect'>効果：<span class='highlight'>多くの読者</span>に内容が伝わりやすくなる</div></div></li><li class='tip-item'><div class='tip-number'>5</div><div class='tip-content'><p class='tip-title'><i class='fas fa-comment tip-icon'></i>「説教」しない</p><p class='tip-description'>主観的な押し付けや上から目線は不快感を与える。共感から入り提案へ。</p><div class='tip-effect'>効果：<span class='highlight'>心理的抵抗感低下</span>・提案受入れ率向上</div></div></li></ul></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        position: relative;        background-color: #f8f9fa;        display: flex;        flex-direction: column;        overflow: hidden;    }    .slide-header {        padding: 30px 50px 10px;        z-index: 10;    }    .slide-content {        flex: 1;        display: flex;        flex-direction: column;        padding: 0 50px 40px;        z-index: 10;    }    .title-bar {        position: relative;        border-left: 10px solid #ff7e36;        padding-left: 20px;        margin-bottom: 20px;    }    .content-box {        background-color: white;        border-radius: 8px;        box-shadow: 0 4px 12px rgba(0,0,0,0.05);        padding: 25px 30px;        margin-bottom: 20px;        flex: 1;    }    .highlight {        color: #ff7e36;        font-weight: 700;    }    .pattern-overlay {        position: absolute;        top: 0;        left: 0;        width: 100%;        height: 100%;        opacity: 0.03;        z-index: 1;        background-image: url('data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='0.4'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E');    }    .tip-list {        list-style: none;        padding: 0;        counter-reset: tip-counter;    }    .tip-item {        display: flex;        margin-bottom: 20px;        align-items: flex-start;    }    .tip-number {        background-color: #3498db;        color: white;        width: 36px;        height: 36px;        border-radius: 50%;        display: flex;        align-items: center;        justify-content: center;        font-weight: bold;        font-size: 18px;        margin-right: 15px;        flex-shrink: 0;    }    .tip-content {        flex: 1;    }    .tip-title {        font-size: 20px;        font-weight: bold;        margin-bottom: 5px;        color: #333;    }    .tip-description {        color: #555;        line-height: 1.5;    }    .tip-effect {        display: inline-block;        background-color: #e8f4fc;        color: #2980b9;        padding: 4px 10px;        border-radius: 4px;        margin-top: 5px;        font-size: 14px;    }    .tip-icon {        color: #ff7e36;        margin-right: 8px;    }
</style>
