<template>
  <SlidePageWrapper slide-id="B086KQK72S" page-title="第1章②：効く心理効果5＋文章量を半減するコツ" :current-page="5" :total-pages="20">
<div class='slide-container'><div class='pattern-overlay'></div><div class='slide-header'><div class='title-bar'><h2 class='text-4xl font-bold'>第1章②：効く心理効果5＋文章量を半減するコツ</h2></div></div><div class='slide-content'><div class='content-column'><div class='content-box'><h3 class='text-xl font-bold'><i class='fas fa-brain'></i> 文章に効く5つの心理効果</h3><ul class='bullet-list'><li><i class='fas fa-check-circle'></i><p><span class='highlight'>プライマシー効果</span>（冒頭が命）：最初に読んだ情報が強く記憶に残る</p></li><li><i class='fas fa-check-circle'></i><p><span class='highlight'>リーセンシー効果</span>（締めを強く）：最後に読んだ情報も記憶に残りやすい</p></li><li><i class='fas fa-check-circle'></i><p><span class='highlight'>見出し効果</span>：見出しだけで内容の6割が伝わる</p></li><li><i class='fas fa-check-circle'></i><p><span class='highlight'>ツァイガルニック効果</span>：未完成や余白が好奇心を刺激する</p></li><li><i class='fas fa-check-circle'></i><p><span class='highlight'>ハロー効果</span>：権威や実績などがあると全体的に良い印象を与える</p></li></ul></div></div><div class='content-column'><div class='content-box'><h3 class='text-xl font-bold'><i class='fas fa-cut'></i> 文章量を半減する方法</h3><ul class='bullet-list'><li><i class='fas fa-check-circle'></i><p><span class='highlight'>第三者に読んでもらい'削って'もらう</span></p><p>自分では気づかない無駄を他者視点で特定できる</p></li><li><i class='fas fa-check-circle'></i><p><span class='highlight'>普段からの小さなトレーニング</span></p><p>・長い文章を3行に要約する練習<br/>・SNSの文字数制限で表現力を鍛える<br/>・「言いたいこと」を1つに絞る</p></li><li><i class='fas fa-check-circle'></i><p><span class='highlight'>100点主義を手放す</span></p><p>「30%の完成度でOK」という許可を自分に出す</p></li><li><i class='fas fa-lightbulb'></i><p>文章は<span class='highlight'>書いてから削る</span>。書きながら削ろうとすると詰まる</p></li></ul></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        position: relative;        background-color: #f8f9fa;        display: flex;        flex-direction: column;        overflow: hidden;    }    .slide-header {        padding: 30px 50px 10px;        z-index: 10;    }    .slide-content {        flex: 1;        display: flex;        padding: 0 50px 40px;        z-index: 10;    }    .title-bar {        position: relative;        border-left: 10px solid #ff7e36;        padding-left: 20px;        margin-bottom: 20px;    }    .content-column {        flex: 1;        display: flex;        flex-direction: column;        padding: 0 15px;    }    .content-box {        background-color: white;        border-radius: 8px;        box-shadow: 0 4px 12px rgba(0,0,0,0.05);        padding: 20px 25px;        margin-bottom: 20px;        height: calc(100% - 10px);        overflow: hidden;    }    .content-box h3 {        display: flex;        align-items: center;        margin-bottom: 15px;        color: #3498db;    }    .content-box h3 i {        margin-right: 10px;    }    .bullet-list {        list-style: none;        padding-left: 5px;    }    .bullet-list li {        display: flex;        align-items: flex-start;        margin-bottom: 12px;        line-height: 1.5;    }    .bullet-list i {        color: #ff7e36;        margin-right: 10px;        margin-top: 5px;    }    .highlight {        color: #ff7e36;        font-weight: 700;    }    .pattern-overlay {        position: absolute;        top: 0;        left: 0;        width: 100%;        height: 100%;        opacity: 0.03;        z-index: 1;        background-image: url('data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='0.4'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E');    }
</style>
