<template>
  <SlidePageWrapper slide-id="KISEKIKA" page-title="第6章 Thursday: 情報公開と信頼" :current-page="10" :total-pages="20">
<div class="flex flex-col w-[1280px] min-h-[720px] bg-gradient-to-br from-blue-50 to-white" style="font-family: 'Noto Sans JP', sans-serif;"><header class="bg-blue-700 py-4 px-8"><h1 class="text-3xl font-bold text-white">第6章 Thursday: 情報公開と信頼</h1></header><div class="flex flex-1 p-8"><div class="w-full"><div class="bg-blue-50 rounded-lg p-6 mb-8"><div class="flex items-center mb-4"><i class="fas fa-shield-alt text-orange-500 text-3xl mr-4"></i><p class="text-xl text-gray-700">木曜日 - 情報の共有と信頼関係を基盤とした組織文化の構築</p></div></div><div class="grid grid-cols-1 gap-6"><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-green-600 flex items-center justify-center"><i class="fas fa-heart text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">ミッション/クレド掲示より、日々の行動で価値観を醸成</h3><p class="text-lg text-gray-700">「真の価値観は、地に足のついた状態から生まれます。組織においては、コントロールをやめることで、自然に価値観が生まれます。」形式的な理念掲示よりも、実際の経営行動と信頼関係が本質的価値観を育みます。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-red-500 flex items-center justify-center"><i class="fas fa-eye-slash text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">監視・監査の過剰は信頼を破壊→最小限に</h3><p class="text-lg text-gray-700">「監査は、企業が一貫性を保つために行います。…人は悪意を働くことを前提とした行為であり、それは即ち社員を信頼していない証拠です。」過度の監視ではなく、信頼を基盤とした体制を維持します。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center"><i class="fas fa-chart-pie text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">会計含む情報を全社オープン、社員に会計教育</h3><p class="text-lg text-gray-700">「情報の秘匿によって不正な権力が生まれる可能性を排除するには、情報は常に誰にでも開示され共有されなければなりません。」会計報告も全社員に毎月公開し、バランスシートの読み方や会計データの意味も教育しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-purple-600 flex items-center justify-center"><i class="fas fa-comments text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">民主的合意形成: 異論・議論を重視</h3><p class="text-lg text-gray-700">「議論を通して定められた決定事項は、既に説明や代替案の検討、反対意見・疑問点を検討しているのだから、導入が迅速に成される…民主体制では異議を唱え、議論を戦わせることが必要です。」</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-yellow-500 flex items-center justify-center"><i class="fas fa-handshake text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">例外的な不正があっても"信頼ベース"を崩さない</h3><p class="text-lg text-gray-700">社員を信頼することのリスクがあっても、管理体制の強化には進まず、「人を信じ、ありのままでいる」ことを貫いています。例：米国人マネージャーの不正時も信頼ベースの体制を維持し、名誉を守る配慮を行いました。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>

</style>
