<template>
  <SlidePageWrapper slide-id="KISEKIKA" page-title="第7章 Friday: 多様性と自己管理" :current-page="11" :total-pages="20">
<div class="flex flex-col w-[1280px] min-h-[720px] bg-gradient-to-br from-blue-50 to-white" style="font-family: 'Noto Sans JP', sans-serif;"><header class="bg-blue-700 py-4 px-8"><h1 class="text-3xl font-bold text-white">第7章 Friday: 多様性と自己管理</h1></header><div class="flex flex-1 p-8"><div class="w-full"><div class="bg-blue-50 rounded-lg p-6 mb-8"><div class="flex items-center mb-4"><i class="fas fa-compass text-purple-500 text-3xl mr-4"></i><p class="text-xl text-gray-700">金曜日 - 多様性を受容し、自律性と透明性を重視した組織づくり</p></div></div><div class="grid grid-cols-1 gap-6"><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center"><i class="fas fa-users-cog text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">画一性のリスクと多様性の価値</h3><p class="text-lg text-gray-700">「画一性は、会社にとって危険なもの」。同質のMBA取得者ばかりの企業や固定観念に縛られた組織のリスクを指摘し、多様なバックグラウンドを持つ人材を積極的に受け入れます。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-purple-600 flex items-center justify-center"><i class="fas fa-user-check text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">採用は現場主導の多面評価プロセス</h3><p class="text-lg text-gray-700">面接には全部門から集まった約4名の社員が参加し、現場メンバーとの相性を重視。最終決定は現場の面接官の合議に基づき、経営陣の意向を押し付けない透明性の高い採用を実践しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-green-600 flex items-center justify-center"><i class="fas fa-project-diagram text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">6〜10人の小集団による自己管理</h3><p class="text-lg text-gray-700">「セムコ社の部門は、常にメンバーがお互いを理解し、全体を把握できるサイズで構成」。小集団ごとに責任と決定権を持ち、グループ内で議論を完結させる体制を整えています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-orange-500 flex items-center justify-center"><i class="fas fa-vote-yea text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">危機時の全員参加型意思決定</h3><p class="text-lg text-gray-700">ブラジル経済危機の際は、全社員がカフェテリアに集まって議論し、投票で工場閉鎖を決定。労働組合と経営サイド双方の承認を得るプロセスを重視しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-red-500 flex items-center justify-center"><i class="fas fa-shield-alt text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">信頼を基盤とした運営</h3><p class="text-lg text-gray-700">盗難事件などのトラブルでも、監視カメラ設置ではなく社員による投票と信頼を重視。「社員による自己管理を徹底し、必要最小限のコントロールで運営」する文化を大切にしています。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>

</style>
