<template>
  <SlidePageWrapper slide-id="KISEKIKA" page-title="第8章 Saturday: 自主性と給与自己決定" :current-page="12" :total-pages="20">
<div class="flex flex-col w-[1280px] min-h-[720px] bg-gradient-to-br from-blue-50 to-white" style="font-family: 'Noto Sans JP', sans-serif;"><header class="bg-blue-700 py-4 px-8"><h1 class="text-3xl font-bold text-white">第8章 Saturday: 自主性と給与自己決定</h1></header><div class="flex flex-1 p-8"><div class="w-full"><div class="bg-blue-50 rounded-lg p-6 mb-8"><div class="flex items-center mb-4"><i class="fas fa-calendar-day text-yellow-500 text-3xl mr-4"></i><p class="text-xl text-gray-700">土曜日 - 自律的な組織運営と役職や権限の再定義</p></div></div><div class="grid grid-cols-1 gap-6"><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center"><i class="fas fa-users-cog text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">会議は全社招待だが完全自由参加</h3><p class="text-lg text-gray-700">「セムコ社では、誰にもミーティングに出席するよう強制しません」。参加具合がその企画への賛否を示し、無関心な企画やポジションは自然と消滅する仕組みになっています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-purple-600 flex items-center justify-center"><i class="fas fa-user-friends text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">正社員絶対主義を疑問視</h3><p class="text-lg text-gray-700">「会社で働く人全員が、はたして正社員である必要があるのか」と問いかけ、多様な契約形態や雇用関係を採用。事業価値を生み出せる人材であれば、働き方の形式にはこだわらない柔軟な姿勢を示しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-green-600 flex items-center justify-center"><i class="fas fa-money-bill-wave text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">給与自己決定と複線報酬制度</h3><p class="text-lg text-gray-700">「彼らは妥当な給与額を判断することができます」。社員が自ら給与を決定する制度を導入し、固定給のほか、成果連動・利益分配・ストックオプションなど複数の報酬形態から選択できるようにしています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-orange-500 flex items-center justify-center"><i class="fas fa-crown text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">リーダーシップの再定義</h3><p class="text-lg text-gray-700">「真のリーダーシップとは会社の中のすべてのことを一から見直すように促すこと」。カリスマ経営者への過度な依存や"英雄待望"の集団心理を危険視し、促進役・触媒としてのリーダー像を提唱しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-red-500 flex items-center justify-center"><i class="fas fa-id-card text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">肩書きより「何をするか」を重視</h3><p class="text-lg text-gray-700">「セムコ社では、社員に好きなように名刺をつくらせています」。肩書きや特権（専用室、駐車場など）を否定し、実際の貢献や役割こそが価値であると考え、階層や序列より機能を優先しています。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>

</style>
