<template>
  <SlidePageWrapper slide-id="KISEKIKA" page-title="第9章 Everyday: 直観とセレンディピティ" :current-page="13" :total-pages="20">
<div class="flex flex-col w-[1280px] min-h-[720px] bg-gradient-to-br from-blue-50 to-white" style="font-family: 'Noto Sans JP', sans-serif;"><header class="bg-blue-700 py-4 px-8"><h1 class="text-3xl font-bold text-white">第9章 Everyday: 直観とセレンディピティ</h1></header><div class="flex flex-1 p-8"><div class="w-full"><div class="bg-blue-50 rounded-lg p-6 mb-8"><div class="flex items-center mb-4"><i class="fas fa-calendar-alt text-indigo-500 text-3xl mr-4"></i><p class="text-xl text-gray-700">毎日 - 直観と偶然の発見を大切にし、常識に捉われない変革の実践</p></div></div><div class="grid grid-cols-1 gap-6"><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-red-500 flex items-center justify-center"><i class="fas fa-bolt text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">許可を願うより許しを請え</h3><p class="text-lg text-gray-700">現場の即断・即応を奨励し、危機時には判断を待つよりも行動を優先。ウイルス感染時にエンジニアがサーバーを即座に遮断した事例など、結果責任を取る覚悟と合わせた現場判断を重視します。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center"><i class="fas fa-lightbulb text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">直観×データの融合</h3><p class="text-lg text-gray-700">「本章でわたしがお伝えしたいテーマは『常に直観にしたがって行動する』こと」。数字や計画は直観を補強する材料であり、学者・数値予測・中期計画より社員の直観とチームの知恵を重視します。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-green-600 flex items-center justify-center"><i class="fas fa-vote-yea text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">Go/No Goミーティングと全員投票</h3><p class="text-lg text-gray-700">新製品や新規事業提案は社員全員で討議・投票。トップのアイデア（自作の食洗機案など）でも、支持がなければ実施しない。変わり者や奇抜なアイデアも歓迎するが、組織の納得感を最重視します。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-orange-500 flex items-center justify-center"><i class="fas fa-exclamation-circle text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">常識への挑戦と根本からの再設計</h3><p class="text-lg text-gray-700">既存の常識や慣習（車や航空機の例）、見かけだけのイノベーションを批判。数字だけの変更や計画は意味がなく、産業構造自体の変革がなければ真の変化は起きないと指摘しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-purple-600 flex items-center justify-center"><i class="fas fa-sync-alt text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">転がる石のように変わり続ける</h3><p class="text-lg text-gray-700">「転がる石にはコケが生えない」という哲学で、常に変化し続ける組織を目指します。管理・命令型の伝統から脱却し、社員の智恵と自由で自律的な経営により、持続的に進化する組織を構築しています。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>

</style>
