<template>
  <SlidePageWrapper slide-id="KISEKIKA" page-title="経営哲学の核心" :current-page="16" :total-pages="20">
<div class="flex flex-col w-[1280px] min-h-[720px] bg-gradient-to-br from-blue-50 to-white" style="font-family: 'Noto Sans JP', sans-serif;"><header class="bg-blue-700 py-4 px-8"><h1 class="text-3xl font-bold text-white">経営哲学の核心</h1></header><div class="flex flex-1 p-8"><div class="w-full"><div class="bg-blue-50 rounded-lg p-6 mb-8"><div class="flex items-center mb-4"><i class="fas fa-lightbulb text-yellow-500 text-3xl mr-4"></i><p class="text-xl text-gray-700">セムコ社の経営哲学を支える5つの柱</p></div></div><div class="grid grid-cols-1 gap-6"><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center"><i class="fas fa-handshake text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">会社は人のためにある。仕事＝幸福の実現装置</h3><p class="text-lg text-gray-700">セムコ社では、会社の目的は「社員が人生の価値と目的に沿って生きている実感を得ること」であり、仕事は幸福と自己実現の場であるという哲学を基盤としています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-purple-600 flex items-center justify-center"><i class="fas fa-user-shield text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">管理より信頼、統制より自律、命令より対話</h3><p class="text-lg text-gray-700">従来の指揮統制型組織から脱し、社員への全幅の信頼と自律性を重んじる組織づくり。情報のオープン化と民主的な意思決定が相互信頼を生み出しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-green-600 flex items-center justify-center"><i class="fas fa-question-circle text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">「なぜ？」を連続で問い、惰性を壊す</h3><p class="text-lg text-gray-700">同じことに対して最低3回は「なぜ？」と問い続けることで、組織の固定観念や惰性を打破。常に問いを持ち、既存のやり方に疑問を投げかける文化が革新を生み出しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-orange-500 flex items-center justify-center"><i class="fas fa-chart-bar text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">数字だけで経営しない。倫理・信頼・直観を重視</h3><p class="text-lg text-gray-700">利益や数値は手段であって目的ではない。企業倫理を貫き、賄賂を拒否し、直観や人間性を大切にした意思決定を行います。データは直観を裏付けるために使用するという哲学です。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-red-500 flex items-center justify-center"><i class="fas fa-arrows-alt text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">変化はボトムアップで起こる。現場の知恵が主役</h3><p class="text-lg text-gray-700">トップダウンの改革は形式的変化に過ぎません。本質的な変革は現場の当事者意識と自律性から生まれるとの考えから、権限を極限まで現場に委譲し、社員の智恵を組織の原動力としています。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>

</style>
