<template>
  <SlidePageWrapper slide-id="KISEKIKA" page-title="実践のポイント（訳者メッセージ）" :current-page="17" :total-pages="20">
<div class="flex flex-col w-[1280px] min-h-[720px] bg-gradient-to-br from-blue-50 to-white" style="font-family: 'Noto Sans JP', sans-serif;"><header class="bg-blue-700 py-4 px-8"><h1 class="text-3xl font-bold text-white">実践のポイント（訳者メッセージ）</h1></header><div class="flex flex-1 p-8"><div class="w-full"><div class="bg-blue-50 rounded-lg p-6 mb-8"><div class="flex items-center mb-4"><i class="fas fa-lightbulb text-yellow-500 text-3xl mr-4"></i><p class="text-xl text-gray-700">奇跡の経営を実践するための訳者からのアドバイス</p></div></div><div class="grid grid-cols-1 gap-6"><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center"><i class="fas fa-building text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">制度より文化。まず"行動"で信頼を示す</h3><p class="text-lg text-gray-700">「お客さまや取引先といった社外の人は、会社の発信する言葉によるメッセージではなく、日々の行動をみて判断する」。制度や規則よりも、実際の行動で信頼を示すことが最も重要です。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-green-600 flex items-center justify-center"><i class="fas fa-walking text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">他人を変えようとせず、自分から始める</h3><p class="text-lg text-gray-700">「決して自分以外の人の考えを変えようとしないこと」。変革は自分自身から始めるべきであり、他者が変わることを期待するのではなく、まず自分が行動を起こすことが大切です。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-red-500 flex items-center justify-center"><i class="fas fa-heart text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">同僚・上司・部下を信頼する/自分も信じる</h3><p class="text-lg text-gray-700">「必ず同僚や上司を信頼する」「必ず自分を信じる」。相互の信頼関係がなければ、どんな制度も形骸化します。信頼は一方的なものではなく、自分自身への信頼も含めた双方向の関係です。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-purple-600 flex items-center justify-center"><i class="fas fa-clock text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">フレックスはツール。本質は相互の信頼</h3><p class="text-lg text-gray-700">「フレックスタイム制は、単なる制度でしかないのです。重要なのは、一週間毎日が週末発想の根底にある相互の信頼です」。制度は手段であり、目的ではありません。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-orange-500 flex items-center justify-center"><i class="fas fa-book-reader text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">組織で読む/議論する/小さく試す</h3><p class="text-lg text-gray-700">「会社で一週間毎日が週末発想を導入するのであれば、ぜひ、会社の同僚や上司、部下と一緒になって読むことをお薦めします」。共に学び、議論し、小さな変化から始めることで、組織全体の変革へとつなげていきましょう。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>

</style>
