<template>
  <SlidePageWrapper slide-id="KISEKIKA" page-title="キーセンテンス集" :current-page="18" :total-pages="20">
<div class="flex flex-col w-[1280px] min-h-[720px] bg-gradient-to-br from-blue-50 to-white" style="font-family: 'Noto Sans JP', sans-serif;"><header class="bg-blue-700 py-4 px-8"><h1 class="text-3xl font-bold text-white">キーセンテンス集</h1></header><div class="flex-1 p-8"><div class="grid grid-cols-2 gap-6 h-full"><!-- 引用1 --><div class="bg-blue-50 rounded-lg p-6 flex items-start shadow-sm"><i class="fas fa-quote-left text-blue-400 text-4xl mr-4 mt-2"></i><div><p class="text-xl text-gray-700 font-medium">コントロールをやめることで、真の価値観が自然に生まれる</p><p class="text-sm text-gray-500 mt-3">- 第六章より</p></div></div><!-- 引用2 --><div class="bg-green-50 rounded-lg p-6 flex items-start shadow-sm"><i class="fas fa-quote-left text-green-400 text-4xl mr-4 mt-2"></i><div><p class="text-xl text-gray-700 font-medium">一週間毎日が週末発想は、仕事を自由・幸福・自律の場にするための方法</p><p class="text-sm text-gray-500 mt-3">- 第一章より</p></div></div><!-- 引用3 --><div class="bg-red-50 rounded-lg p-6 flex items-start shadow-sm"><i class="fas fa-quote-left text-red-400 text-4xl mr-4 mt-2"></i><div><p class="text-xl text-gray-700 font-medium">無限成長を前提にするのはがん細胞と同じ発想だ</p><p class="text-sm text-gray-500 mt-3">- 第五章より</p></div></div><!-- 引用4 --><div class="bg-purple-50 rounded-lg p-6 flex items-start shadow-sm"><i class="fas fa-quote-left text-purple-400 text-4xl mr-4 mt-2"></i><div><p class="text-xl text-gray-700 font-medium">情報の独占は不正と権力集中の温床。すべてを開示せよ</p><p class="text-sm text-gray-500 mt-3">- 第六章より</p></div></div><!-- 引用5 --><div class="bg-yellow-50 rounded-lg p-6 flex items-start shadow-sm"><i class="fas fa-quote-left text-yellow-500 text-4xl mr-4 mt-2"></i><div><p class="text-xl text-gray-700 font-medium">許可を願うより、許しを請え</p><p class="text-sm text-gray-500 mt-3">- 第九章より</p></div></div><!-- 引用6 --><div class="bg-orange-50 rounded-lg p-6 flex items-start shadow-sm"><i class="fas fa-quote-left text-orange-400 text-4xl mr-4 mt-2"></i><div><p class="text-xl text-gray-700 font-medium">データは直観を裏打ちするために使え</p><p class="text-sm text-gray-500 mt-3">- 第九章より</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>

</style>
