<template>
  <SlidePageWrapper slide-id="KISEKIKA" page-title="本書の概要と対象読者" :current-page="2" :total-pages="20">
<div class="flex flex-col w-[1280px] min-h-[720px] bg-gradient-to-br from-blue-50 to-white" style="font-family: 'Noto Sans JP', sans-serif;"><header class="bg-blue-700 py-4 px-8"><h1 class="text-3xl font-bold text-white">本書の概要と対象読者</h1></header><div class="flex flex-1 p-8"><!-- 左側：テーマとコアコンセプト --><div class="flex-1 pr-6 border-r border-gray-200"><div class="mb-8"><h2 class="text-2xl font-bold text-blue-700 mb-4 flex items-center"><i class="fas fa-book-open mr-3"></i>テーマ                    </h2><div class="bg-blue-50 rounded-lg p-5"><p class="text-xl text-gray-700 mb-3">「一週間毎日が週末発想」</p><p class="text-lg text-gray-600">週末の自由・幸福・自律性を平日の仕事に持ち込む新しい経営哲学と実践</p></div></div><div><h2 class="text-2xl font-bold text-blue-700 mb-4 flex items-center"><i class="fas fa-lightbulb mr-3"></i>コアコンセプト                    </h2><ul class="space-y-3"><li class="flex items-start"><i class="fas fa-check-circle text-green-500 mt-1 mr-3"></i><p class="text-lg text-gray-700">コントロールの放棄、民主的運営</p></li><li class="flex items-start"><i class="fas fa-check-circle text-green-500 mt-1 mr-3"></i><p class="text-lg text-gray-700">自己管理、主体性の尊重</p></li><li class="flex items-start"><i class="fas fa-check-circle text-green-500 mt-1 mr-3"></i><p class="text-lg text-gray-700">情報のオープン化と透明性</p></li><li class="flex items-start"><i class="fas fa-check-circle text-green-500 mt-1 mr-3"></i><p class="text-lg text-gray-700">「なぜ？」を問い続ける文化</p></li></ul></div></div><!-- 右側：対象読者と期待される変化 --><div class="flex-1 pl-6"><div class="mb-8"><h2 class="text-2xl font-bold text-blue-700 mb-4 flex items-center"><i class="fas fa-users mr-3"></i>対象読者                    </h2><ul class="space-y-3"><li class="flex items-start"><i class="fas fa-user-tie text-blue-500 mt-1 mr-3"></i><p class="text-lg text-gray-700">経営者・役員・事業部長</p></li><li class="flex items-start"><i class="fas fa-user-friends text-blue-500 mt-1 mr-3"></i><p class="text-lg text-gray-700">人事部門・組織開発担当者</p></li><li class="flex items-start"><i class="fas fa-tasks text-blue-500 mt-1 mr-3"></i><p class="text-lg text-gray-700">現場リーダー・マネジャー</p></li><li class="flex items-start"><i class="fas fa-sync-alt text-blue-500 mt-1 mr-3"></i><p class="text-lg text-gray-700">働き方改革に関心のある方</p></li></ul></div><div><h2 class="text-2xl font-bold text-blue-700 mb-4 flex items-center"><i class="fas fa-chart-line mr-3"></i>期待される変化                    </h2><ul class="space-y-3"><li class="flex items-start"><i class="fas fa-arrow-right text-orange-500 mt-1 mr-3"></i><p class="text-lg text-gray-700">管理主義から信頼主義への移行</p></li><li class="flex items-start"><i class="fas fa-arrow-right text-orange-500 mt-1 mr-3"></i><p class="text-lg text-gray-700">制度ではなく文化を設計する視点</p></li><li class="flex items-start"><i class="fas fa-arrow-right text-orange-500 mt-1 mr-3"></i><p class="text-lg text-gray-700">社員の主体性が成果と直結する仕組み</p></li><li class="flex items-start"><i class="fas fa-arrow-right text-orange-500 mt-1 mr-3"></i><p class="text-lg text-gray-700">退職率低下と生産性向上の両立</p></li></ul></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>

</style>
