<template>
  <SlidePageWrapper slide-id="KISEKIKA" page-title="締め: 一週間毎日が週末発想へ" :current-page="20" :total-pages="20">
<div class="flex flex-col w-[1280px] min-h-[720px] bg-gradient-to-br from-blue-50 to-white" style="font-family: 'Noto Sans JP', sans-serif;"><header class="bg-blue-700 py-4 px-8"><h1 class="text-3xl font-bold text-white">締め: 一週間毎日が週末発想へ</h1></header><div class="flex flex-1 p-8"><div class="w-full"><div class="bg-blue-50 rounded-lg p-6 mb-8"><div class="flex items-center mb-4"><i class="fas fa-sun text-yellow-500 text-3xl mr-4"></i><p class="text-xl text-gray-700">働く喜びと組織の成功は両立する - まずは小さな一歩から変革を</p></div></div><div class="grid grid-cols-1 gap-6"><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-green-600 flex items-center justify-center"><i class="fas fa-walking text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">今日からできる一歩</h3><p class="text-lg text-gray-700">1) 会議や情報を開く：すべての情報を隠さず共有する<br/>2) 勤務の自由度を1つ増やす：時間や場所の選択権を与える<br/>3) 『なぜ？』を3回問う：固定観念や慣習を問い直す</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center"><i class="fas fa-balance-scale text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">成果と幸福の両立は可能</h3><p class="text-lg text-gray-700">セムコ社の実績が証明するように、管理や監視ではなく、「信頼・自律・民主性」を基盤とした組織では、社員の幸福と企業の持続的成長が同時に実現します。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-purple-600 flex items-center justify-center"><i class="fas fa-seedling text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">小さく始め、継続的に発展させる</h3><p class="text-lg text-gray-700">すべてを一度に変えようとせず、小さな変化から始めましょう。学びを共有し、実験と検証を繰り返しながら、組織の仕組みを更新し続けることが重要です。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-red-500 flex items-center justify-center"><i class="fas fa-flag text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">目的: 仕事=幸福の実感</h3><p class="text-lg text-gray-700">一週間毎日が週末発想の真の目的は、仕事を単なる収入源から「人生を価値あるものとし、目的にそって生きている実感を得る場」へと変革し、人と組織がともに繁る場をつくることです。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-orange-500 flex items-center justify-center"><i class="fas fa-sync-alt text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">常に変わり続ける勇気を持つ</h3><p class="text-lg text-gray-700">「転がる石にはコケが生えない」ように、常に問い続け、変化し続ける組織であれば、どんな環境変化にも適応できます。変化を恐れず、直観と好奇心を大切にしましょう。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>

</style>
