<template>
  <SlidePageWrapper slide-id="KISEKIKA" page-title="第1章 Anyday: コントロールの放棄" :current-page="5" :total-pages="20">
<div class="flex flex-col w-[1280px] min-h-[720px] bg-gradient-to-br from-blue-50 to-white" style="font-family: 'Noto Sans JP', sans-serif;"><header class="bg-blue-700 py-4 px-8"><h1 class="text-3xl font-bold text-white">第1章 Anyday: コントロールの放棄</h1></header><div class="flex flex-1 p-8"><div class="w-full"><div class="bg-blue-50 rounded-lg p-6 mb-8"><div class="flex items-center mb-4"><i class="fas fa-sun text-yellow-500 text-3xl mr-4"></i><p class="text-xl text-gray-700">どんな日でも - 従来の経営の枠組みを手放し、民主制経営へ</p></div></div><div class="grid grid-cols-1 gap-6"><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center"><i class="fas fa-handshake text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">指揮統制をやめ、社員の自主管理へ</h3><p class="text-lg text-gray-700">「コントロールをやめることが絶対的に重要」であり、階層的な管理や指示命令型のマネジメントを否定。代わりに社員が自らの興味と直感で仕事を選び、自主管理するシステムを採用しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-purple-600 flex items-center justify-center"><i class="fas fa-sitemap text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">組織図や固定役職に依存しない</h3><p class="text-lg text-gray-700">組織階層も公式の組織図も存在せず、CEO・COO・CIOが不在の時期もあります。人事部がなく、長期予算・ビジネスプラン・戦略計画も極小化されています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-green-600 flex items-center justify-center"><i class="fas fa-question-circle text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">「なぜ？」を問い続ける文化が惰性を破る</h3><p class="text-lg text-gray-700">「われわれの成功の秘訣は、理由を問うこと」。特定のことについて連続して3回は「なぜ？」と質問し、固定観念や惰性からの脱却を戦略的に実践しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-orange-500 flex items-center justify-center"><i class="fas fa-users text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">民主的意思決定: 全員参加の文化</h3><p class="text-lg text-gray-700">リーダー選定や新規事業案決定にも全社員が参加。経営の根底にはデモクラシー（民主主義）とオープンコミュニケーション、活発な発言・質問の文化があります。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-red-500 flex items-center justify-center"><i class="fas fa-chart-line text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">成果: 高成長と高満足を両立</h3><p class="text-lg text-gray-700">人数・売上ともに大きく成長（初期90人 年間400万ドル→3000人、2億1200万ドル）し、年40%成長も実現。77大学で事例研究対象となり、世界的に高い評価を得ています。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>

</style>
