<template>
  <SlidePageWrapper slide-id="KISEKIKA" page-title="第2章 Sunday: 自由な時間と週末発想" :current-page="6" :total-pages="20">
<div class="flex flex-col w-[1280px] min-h-[720px] bg-gradient-to-br from-blue-50 to-white" style="font-family: 'Noto Sans JP', sans-serif;"><header class="bg-blue-700 py-4 px-8"><h1 class="text-3xl font-bold text-white">第2章 Sunday: 自由な時間と週末発想</h1></header><div class="flex flex-1 p-8"><div class="w-full"><div class="bg-blue-50 rounded-lg p-6 mb-8"><div class="flex items-center mb-4"><i class="fas fa-umbrella-beach text-yellow-500 text-3xl mr-4"></i><p class="text-xl text-gray-700">日曜日 - 自由な時間の希少性と仕事・生活のバランス再考</p></div></div><div class="grid grid-cols-1 gap-6"><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center"><i class="fas fa-hourglass-half text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">自由な時間の希少性を直視</h3><p class="text-lg text-gray-700">現代社会では「雑用や義務から解放され、自分の思い通りに過ごせる時間」が希少になっています。テクノロジーの発展により仕事が私生活を侵食する構造を認識し是正する必要があります。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-purple-600 flex items-center justify-center"><i class="fas fa-clock text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">フレックス/サテライト/在宅の標準化</h3><p class="text-lg text-gray-700">セムコ社では、柔軟な勤務体系（フレックスタイム・サテライトオフィス・在宅勤務）を全社で導入。社員自身が勤務場所・時間を自己決定し、管理職は本質的成果のみを評価する体制に移行しました。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-green-600 flex items-center justify-center"><i class="fas fa-balance-scale text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">成果のみを評価する "寄宿学校型管理" の否定</h3><p class="text-lg text-gray-700">社員が「仕事・個人・精神」のバランスをとれると、生産性も向上し会社にもメリットが生まれます。週末/平日の従来の時間配分や勤務スタイルを根本的に見直し、より柔軟な働き方を推奨しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-orange-500 flex items-center justify-center"><i class="fas fa-industry text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">製造ラインにも柔軟勤務を導入</h3><p class="text-lg text-gray-700">一般的に不可能と思われるアセンブリーラインへのフレックスタイム導入にも成功。批判や実務的課題があっても、現場の自主的な調整力で問題なく運用されています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-red-500 flex items-center justify-center"><i class="fas fa-chart-pie text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">結果: 生産性と満足度が同時向上</h3><p class="text-lg text-gray-700">社員は自由な時間配分により、家族や趣味、自己成長を両立しながら高い生産性と満足感を実現。「自由にさせるとサボる」という従来型管理発想に反し、社員の成熟性と責任感によって成果が向上しています。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>

</style>
