<template>
  <SlidePageWrapper slide-id="KISEKIKA" page-title="第3章 Monday: モチベーションと天職" :current-page="7" :total-pages="20">
<div class="flex flex-col w-[1280px] min-h-[720px] bg-gradient-to-br from-blue-50 to-white" style="font-family: 'Noto Sans JP', sans-serif;"><header class="bg-blue-700 py-4 px-8"><h1 class="text-3xl font-bold text-white">第3章 Monday: モチベーションと天職</h1></header><div class="flex flex-1 p-8"><div class="w-full"><div class="bg-blue-50 rounded-lg p-6 mb-8"><div class="flex items-center mb-4"><i class="fas fa-moon text-indigo-500 text-3xl mr-4"></i><p class="text-xl text-gray-700">月曜日 - 心からウキウキして働く、社員の自律性とやりがいの両立</p></div></div><div class="grid grid-cols-1 gap-6"><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-indigo-600 flex items-center justify-center"><i class="fas fa-star text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">人は誰も「眠っている才能」を持つ</h3><p class="text-lg text-gray-700">潜在能力、興味、スキルを活用し、天職（人生の目的に合致した職業）に就くことで真の仕事への満足感が得られます。社員それぞれの「天職」への接続を支援する仕組みを整えています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-green-600 flex items-center justify-center"><i class="fas fa-lightbulb text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">モチベーションは強制でなく仕組みで生む</h3><p class="text-lg text-gray-700">強制的トレーニングや集会でなく、自律性を重視。「人は理由があるから働く」という観点から、お金以外の動機づけを大切にし、仕組み自体にモチベーションが生まれるよう設計しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-teal-600 flex items-center justify-center"><i class="fas fa-user-clock text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">仕事/場所/時間/給与の自己決定制</h3><p class="text-lg text-gray-700">社員は自分で仕事や働く場所・時間・給与も決める自己管理制を実施。縦割り組織や事細かな職務規定から脱却し、自由な挑戦やジョブローテーションを後押ししています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-orange-500 flex items-center justify-center"><i class="fas fa-balance-scale text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">人生サイクルに合わせた制度設計</h3><p class="text-lg text-gray-700">「変動型給与」「ちょっとだけリタイア・プログラム」「ワーク・アンド・ストップ・プログラム」など、健康・家族・年齢などに合わせてフレキシブルに働ける制度を導入しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-red-500 flex items-center justify-center"><i class="fas fa-user-friends text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">事例: クロヴィスの越境的貢献</h3><p class="text-lg text-gray-700">人事部出身のクロヴィスは職種や役割に縛られず、工場労働者向けのハンモック付き庭園やフレックスタイム制導入を実現。高給オファーを断った理由は「会社の価値観への共感」「人々への貢献」というお金以上の価値でした。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>

</style>
