<template>
  <SlidePageWrapper slide-id="KISEKIKA" page-title="第4章 Tuesday: 仕事＝幸福の実現" :current-page="8" :total-pages="20">
<div class="flex flex-col w-[1280px] min-h-[720px] bg-gradient-to-br from-blue-50 to-white" style="font-family: 'Noto Sans JP', sans-serif;"><header class="bg-blue-700 py-4 px-8"><h1 class="text-3xl font-bold text-white">第4章 Tuesday: 仕事＝幸福の実現</h1></header><div class="flex flex-1 p-8"><div class="w-full"><div class="bg-blue-50 rounded-lg p-6 mb-8"><div class="flex items-center mb-4"><i class="fas fa-smile-beam text-yellow-500 text-3xl mr-4"></i><p class="text-xl text-gray-700">火曜日 - 全社員の才能を引き出し、仕事と幸福を一致させる</p></div></div><div class="grid grid-cols-1 gap-6"><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center"><i class="fas fa-heart text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">仕事の究極目的は「価値と目的に沿って生きている実感」</h3><p class="text-lg text-gray-700">仕事が意義あるものとなるには、それぞれの人の才能に合わせてカスタマイズされたものであるべき。単に職務記述書通りの仕事や給料のためだけの仕事では充実感や成長は得られません。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-green-600 flex items-center justify-center"><i class="fas fa-sync-alt text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">ジョブローテーション/リバース評価/自己管理で才能を開花</h3><p class="text-lg text-gray-700">職場の自由な選択、部下が上司を評価する制度、自己管理といった一連のプログラムを通じて、社員一人ひとりの眠っている才能を引き出し、天職を見つける環境を実現しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-purple-600 flex items-center justify-center"><i class="fas fa-balance-scale text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">評議員制度: 社員代表が価値観逸脱を監視</h3><p class="text-lg text-gray-700">117人の評議員を社員が選出し、各事業単位や地域、現場ごとにセムコ社の社員を代表。月に一度委員会を開き、経営陣がセムコ社の原則・価値観に反していないか確認します。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-orange-500 flex items-center justify-center"><i class="fas fa-user-check text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">離職率1%以下の背景は"自発性と尊重"</h3><p class="text-lg text-gray-700">2001年に自主的にセムコ社を辞めた人は約3000人中わずか3人だけ。社員の自発性重視、「思い通りに仕向ける教育は一切しない」という姿勢が、高い定着率と満足度を生み出しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-red-500 flex items-center justify-center"><i class="fas fa-chart-bar text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">数字主義/恐怖政治/ベルカーブ淘汰を批判</h3><p class="text-lg text-gray-700">「パフォーマンスが悪いからといって社員を解雇すると、必ず別の問題が生まれる」と、ジャック・ウェルチ式の下位10%切り捨てやベルカーブ評価、数値一辺倒の経営手法を明確に否定しています。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>

</style>
