<template>
  <SlidePageWrapper slide-id="KISEKIKA" page-title="第5章 Wednesday: 成長神話への挑戦" :current-page="9" :total-pages="20">
<div class="flex flex-col w-[1280px] min-h-[720px] bg-gradient-to-br from-blue-50 to-white" style="font-family: 'Noto Sans JP', sans-serif;"><header class="bg-blue-700 py-4 px-8"><h1 class="text-3xl font-bold text-white">第5章 Wednesday: 成長神話への挑戦</h1></header><div class="flex flex-1 p-8"><div class="w-full"><div class="bg-blue-50 rounded-lg p-6 mb-8"><div class="flex items-center mb-4"><i class="fas fa-balance-scale text-blue-500 text-3xl mr-4"></i><p class="text-xl text-gray-700">水曜日 - 企業成長や利益追求の価値観を問い直し、新しい評価軸を模索する</p></div></div><div class="grid grid-cols-1 gap-6"><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-red-600 flex items-center justify-center"><i class="fas fa-chart-line text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">成長=善の神話を疑う</h3><p class="text-lg text-gray-700">「永久に成長し続けるのはがん細胞だけ」と永久的成長の概念を否定。成長は一時的なものであり、規模拡大や数字を自己目的化することへの危険性を指摘しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-yellow-500 flex items-center justify-center"><i class="fas fa-exclamation-triangle text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">規模拡大の副作用</h3><p class="text-lg text-gray-700">過度な成長による弊害として、統制回帰、過剰な設備投資や買収、企業文化の崩壊、競争力の喪失などを挙げ、拡大至上主義への警告を発しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-green-600 flex items-center justify-center"><i class="fas fa-search-dollar text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">新評価軸: 多面的な信頼指標</h3><p class="text-lg text-gray-700">会社の善し悪しを測る新しい指標として、株主・社員・顧客・供給者・社会の信頼度を重視。社員や外部関係者への匿名アンケートを実施し、その結果を公開しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center"><i class="fas fa-handshake text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">倫理: 賄賂・リベート断固拒否</h3><p class="text-lg text-gray-700">ブラジル石油業界での賄賂要求に対し、毅然とした態度で拒否。契約を失っても倫理的行動を貫き、必要に応じて証拠も提供するという姿勢を示しています。</p></div></div><div class="flex items-start"><div class="mr-6 mt-1"><div class="w-12 h-12 rounded-full bg-purple-600 flex items-center justify-center"><i class="fas fa-store text-white text-xl"></i></div></div><div><h3 class="text-xl font-bold text-blue-700 mb-2">適正規模・長期安定という選択肢</h3><p class="text-lg text-gray-700">老舗企業の例を挙げ、必ずしも規模を拡大せず事業領域を絞ることで長期存続が可能であり、これも正当な選択肢であることを主張しています。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>

</style>
