<template>
  <SlidePageWrapper slide-id="B0FJQNNQSR" page-title="回復の4段階ステップ" :current-page="11" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="title">回復の4段階ステップ</h1></div><div class="content-wrapper"><div class="introduction"><p>半うつからの回復は一気に進むものではなく、段階的なプロセスを経ていきます。<span class="emphasis">食事と睡眠を整えることが土台</span>となり、徐々に心と体の調子が上向いていきます。</p></div><div class="steps-container"><div class="step step-1"><div class="step-number">1</div><div class="step-box"><h2 class="step-title">土台</h2><p class="step-desc">食べる・寝るを整える<br/>セロトニン増加の基礎固め</p></div></div><div class="step step-2"><div class="step-number">2</div><div class="step-box"><h2 class="step-title">安定</h2><p class="step-desc">イライラが減る<br/>不安が和らぐ<br/>憂鬱感が軽減する</p></div></div><div class="step step-3"><div class="step-number">3</div><div class="step-box"><h2 class="step-title">活性</h2><p class="step-desc">根気が戻ってくる<br/>興味・好奇心が芽生える<br/>集中力が向上する<br/>人との交流が楽しく感じる</p></div></div><div class="step step-4"><div class="step-number">4</div><div class="step-box"><h2 class="step-title">充足</h2><p class="step-desc">喜びを感じられるようになる<br/>生きがいの実感が戻る<br/>新しい目標が見つかる<br/>自分らしさを取り戻す<br/>未来に希望が持てる</p></div></div></div><div class="introduction" style="margin-top: 30px;"><p>回復には個人差がありますが、<span class="emphasis">小さな変化を感じ取り、焦らずに一歩一歩進むこと</span>が大切です。</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        height: 100%;        width: 100%;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f5f9fa;    }    .header {        padding: 30px 60px 10px;        border-bottom: 2px solid #2a6b7a;    }    .title {        font-size: 40px;        font-weight: 700;        color: #2a6b7a;    }    .content-wrapper {        display: flex;        flex: 1;        flex-direction: column;        padding: 20px 60px;    }    .introduction {        text-align: center;        margin-bottom: 20px;        font-size: 20px;        color: #457986;        padding: 0 100px;        line-height: 1.5;    }    .emphasis {        background-color: rgba(42, 107, 122, 0.1);        padding: 2px 6px;        border-radius: 4px;        font-weight: 500;    }    .steps-container {        display: flex;        justify-content: center;        align-items: flex-end;        margin-top: 20px;        height: 450px;    }    .step {        position: relative;        width: 220px;        margin: 0 15px;        display: flex;        flex-direction: column;        align-items: center;        justify-content: flex-end;    }    .step-box {        width: 100%;        border-radius: 10px 10px 0 0;        padding: 20px 10px;        display: flex;        flex-direction: column;        align-items: center;        color: white;        box-shadow: 0 4px 8px rgba(0,0,0,0.1);    }    .step-number {        position: absolute;        top: -25px;        left: 10px;        width: 40px;        height: 40px;        border-radius: 50%;        background-color: #2a6b7a;        color: white;        display: flex;        justify-content: center;        align-items: center;        font-size: 20px;        font-weight: bold;        z-index: 2;    }    .step-title {        font-size: 24px;        font-weight: 600;        margin-bottom: 15px;        text-align: center;    }    .step-desc {        font-size: 16px;        text-align: center;        line-height: 1.4;    }    .step-1 .step-box {        background-color: #4CAF50;        height: 150px;    }    .step-2 .step-box {        background-color: #2196F3;        height: 220px;    }    .step-3 .step-box {        background-color: #FF9800;        height: 300px;    }    .step-4 .step-box {        background-color: #9C27B0;        height: 380px;    }    .step-icon {        font-size: 36px;        margin-bottom: 10px;    }
</style>
