<template>
  <SlidePageWrapper slide-id="B0FJQNNQSR" page-title="キーセンテンスと用語集" :current-page="18" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="title">キーセンテンスと用語集</h1></div><div class="content-wrapper"><div class="left-column"><h2 class="section-title">キーセンテンス</h2><div class="key-sentence"><div class="key-sentence-title"><i class="fas fa-quote-left"></i><p>半うつは怠けではない</p></div><p class="key-sentence-text">半うつは脳の神経伝達物質の減少が原因であり、気合や根性、意志の弱さの問題ではありません。科学的根拠に基づいた理解と対処が必要です。</p></div><div class="key-sentence"><div class="key-sentence-title"><i class="fas fa-quote-left"></i><p>現代人の5人に1人</p></div><p class="key-sentence-text">半うつは特別な人だけがなるものではなく、現代社会を生きる約20％の人が経験する一般的な心の状態です。あなたは一人ではありません。</p></div><div class="key-sentence"><div class="key-sentence-title"><i class="fas fa-quote-left"></i><p>食べる・寝るが土台</p></div><p class="key-sentence-text">回復の第一歩は「食べる」「寝る」という基本的な生理機能の立て直しです。これが整うことで、脳の機能が回復し始めます。</p></div><div class="key-sentence"><div class="key-sentence-title"><i class="fas fa-quote-left"></i><p>60点でいい・小さく始める</p></div><p class="key-sentence-text">完璧主義から脱却し、「まずは60点でいい」という考え方で小さな一歩から始めることが、持続可能な回復への道です。</p></div></div><div class="right-column"><h2 class="section-title">用語集</h2><div class="glossary-container"><div class="glossary-item"><h3 class="glossary-term">セロトニン / ドーパミン / ノルアドレナリン</h3><p class="glossary-desc"><span class="highlight">セロトニン</span>：心の安全装置。気分の安定、不安の調整、食欲コントロールなどを担う</p><p class="glossary-desc"><span class="highlight">ドーパミン</span>：「ワクワク」の源。快楽や積極性、意欲を生み出す</p><p class="glossary-desc"><span class="highlight">ノルアドレナリン</span>：「やる気」のアクセル。集中力や気力、実行力を支える</p></div><div class="glossary-item"><h3 class="glossary-term">偽休息 / 本当の休息</h3><p class="glossary-desc"><span class="highlight">偽休息</span>：アルコール、無目的スクロール、過集中の逃避など、一時的な気分転換にはなるが脳の回復にはならない行動</p><p class="glossary-desc"><span class="highlight">本当の休息</span>：何もしない時間、自然や散歩、短時間の昼寝など、脳と心身が本当に回復できる状態</p></div><div class="glossary-item"><h3 class="glossary-term">デジタルサンセット / CBT-I</h3><p class="glossary-desc"><span class="highlight">デジタルサンセット</span>：就寝90分前からスマホやPCの画面を見ない習慣。ブルーライトを避け睡眠の質を向上させる</p><p class="glossary-desc"><span class="highlight">CBT-I</span>：睡眠認知行動療法。睡眠に関する考え方や行動パターンを変えることで不眠を改善する手法</p></div><div class="glossary-item"><h3 class="glossary-term">報酬予測エラー</h3><p class="glossary-desc">期待と実際に得られる報酬のズレから学びを得る脳の機能。期待値を適切に調整し、小さな成功体験を積み重ねることで、自己肯定感を高める考え方</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        height: 100%;        width: 100%;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f5f9fa;    }    .header {        padding: 30px 60px 10px;        border-bottom: 2px solid #2a6b7a;    }    .title {        font-size: 40px;        font-weight: 700;        color: #2a6b7a;    }    .content-wrapper {        display: flex;        flex: 1;        padding: 20px 60px;    }    .left-column {        width: 50%;        padding-right: 30px;    }    .right-column {        width: 50%;        padding-left: 30px;        border-left: 1px solid #ccdce0;    }    .section-title {        font-size: 28px;        font-weight: 600;        color: #2a6b7a;        margin-bottom: 20px;        display: flex;        align-items: center;    }    .section-title:before {        content: "";        display: inline-block;        width: 6px;        height: 28px;        background-color: #2a6b7a;        margin-right: 12px;        border-radius: 3px;    }    .key-sentence {        margin-bottom: 25px;        padding: 15px;        border-radius: 8px;        background-color: rgba(42, 107, 122, 0.08);    }    .key-sentence-title {        font-size: 22px;        font-weight: 600;        color: #2a6b7a;        margin-bottom: 10px;        display: flex;        align-items: center;    }    .key-sentence-title i {        margin-right: 10px;        color: #2a6b7a;    }    .key-sentence-text {        font-size: 18px;        line-height: 1.6;        color: #457986;    }    .glossary-container {        display: grid;        grid-template-columns: 1fr;        gap: 20px;    }    .glossary-item {        margin-bottom: 5px;    }    .glossary-term {        font-size: 20px;        font-weight: 600;        color: #2a6b7a;        margin-bottom: 8px;        padding-bottom: 4px;        border-bottom: 1px dashed #ccdce0;    }    .glossary-desc {        font-size: 16px;        line-height: 1.5;        color: #457986;        padding-left: 10px;    }    .highlight {        background-color: rgba(42, 107, 122, 0.15);        padding: 2px 6px;        border-radius: 4px;        font-weight: 500;    }
</style>
