<template>
  <SlidePageWrapper slide-id="B0FJQNNQSR" page-title="本書の概要" :current-page="2" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="title">本書の概要</h1></div><div class="content-wrapper"><div class="left-column"><p class="sidebar-text">「なんとなく不調」と「うつ病」の間に存在する<span class="emphasis">「半うつ」</span>の正体と回復への道筋を解明します</p><p class="sidebar-text">精神科医として<span class="emphasis">25年の診療経験</span>から見えてきた現代人の心の不調を科学的に解説</p></div><div class="right-column"><div class="section"><h2 class="section-title">目的</h2><ul class="item-list"><li class="item"><p>「半うつ」に名前を与え、見えづらい心の不調を可視化する</p></li><li class="item"><p>脳科学的な原因と具体的な回復法を提示する</p></li><li class="item"><p>「怠け」ではない科学的な理解を広める</p></li></ul></div><div class="section"><h2 class="section-title">対象読者</h2><ul class="item-list"><li class="item"><p>なんとなく不調を感じる現代人</p></li><li class="item"><p>頑張れない自分を責めてしまう人</p></li><li class="item"><p>家族・同僚の不調に気づき支えたい人</p></li></ul></div><div class="section"><h2 class="section-title">得られる変化</h2><ul class="item-list"><li class="item"><p>自己否定から距離を置ける安心感</p></li><li class="item"><p>食事・睡眠・休息など具体的な改善策</p></li><li class="item"><p>うつ病への進行予防と早期対応</p></li></ul></div><div class="section"><h2 class="section-title">メッセージ</h2><ul class="item-list"><li class="item"><p>半うつは<span class="emphasis">怠け</span>ではなく、<span class="emphasis">誰にでも起こりうる</span>心の不調</p></li><li class="item"><p>小さな生活改善から必ず良くなる道がある</p></li></ul></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        height: 100%;        width: 100%;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f5f9fa;        color: #2a6b7a;    }    .header {        padding: 30px 60px 20px;        border-bottom: 2px solid #2a6b7a;    }    .title {        font-size: 40px;        font-weight: 700;        color: #2a6b7a;    }    .content-wrapper {        display: flex;        flex: 1;        padding: 0 60px;    }    .left-column {        width: 30%;        padding: 30px 20px 30px 0;        display: flex;        flex-direction: column;        justify-content: center;    }    .right-column {        width: 70%;        padding: 30px 0 30px 30px;        border-left: 1px solid #ccdce0;    }    .section {        margin-bottom: 30px;    }    .section-title {        font-size: 24px;        font-weight: 500;        margin-bottom: 14px;        color: #2a6b7a;        display: flex;        align-items: center;    }    .section-title:before {        content: "";        display: inline-block;        width: 8px;        height: 28px;        background-color: #2a6b7a;        margin-right: 12px;        border-radius: 4px;    }    .item-list {        list-style-type: none;        padding-left: 20px;    }    .item {        position: relative;        margin-bottom: 12px;        font-size: 20px;        line-height: 1.5;        padding-left: 16px;    }    .item:before {        content: "";        position: absolute;        left: 0;        top: 10px;        width: 8px;        height: 8px;        border-radius: 50%;        background-color: #5ba8bc;    }    .emphasis {        background-color: rgba(42, 107, 122, 0.1);        padding: 2px 6px;        border-radius: 4px;    }    .sidebar-text {        font-size: 22px;        line-height: 1.6;        color: #457986;        margin-bottom: 20px;    }
</style>
