<template>
  <SlidePageWrapper slide-id="B0FJQNNQSR" page-title="目次・全体構造" :current-page="3" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="title">目次・全体構造</h1></div><div class="content-wrapper"><div class="left-column"><p class="sidebar-text">本書は<span class="emphasis">「半うつ」</span>の理解から、原因究明、具体的な回復法、そして新しい生き方の発見まで段階的に進んでいきます</p><p class="sidebar-text">各章は<span class="emphasis">科学的知見</span>と<span class="emphasis">実践的なヒント</span>を兼ね備え、回復への道筋を示しています</p></div><div class="right-column"><div class="section"><h2 class="section-title">全6章の構成</h2><ul class="item-list"><li class="item"><div class="chapter-number">1</div><p>現代人の5人に1人を襲う「半分うつ」<span class="chapter-subtitle">半うつの定義と社会的背景</span></p></li><li class="item"><div class="chapter-number">2</div><p>「半うつ」どう治す？<span class="chapter-subtitle">現代社会要因と対策の基本方針</span></p></li><li class="item"><div class="chapter-number">3</div><p>「セロトニン」を増やす3つの方法<span class="chapter-subtitle">食事・睡眠・運動による神経伝達物質の活性化</span></p></li><li class="item"><div class="chapter-number">4</div><p>回復ステップ／安全運転の前に知っておきたい危険信号<span class="chapter-subtitle">回復過程と本当の休息の取り方</span></p></li><li class="item"><div class="chapter-number">5</div><p>アクセル（ノルアドレナリン）の適切な踏み方<span class="chapter-subtitle">やる気と集中力のバランス調整</span></p></li><li class="item"><div class="chapter-number">6</div><p>回復のステップ／新しい走り方を覚える<span class="chapter-subtitle">人生の再設計と自分らしい生き方の発見</span></p></li></ul></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        height: 100%;        width: 100%;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f5f9fa;        color: #2a6b7a;    }    .header {        padding: 30px 60px 20px;        border-bottom: 2px solid #2a6b7a;    }    .title {        font-size: 40px;        font-weight: 700;        color: #2a6b7a;    }    .content-wrapper {        display: flex;        flex: 1;        padding: 0 60px;    }    .left-column {        width: 30%;        padding: 30px 20px 30px 0;        display: flex;        flex-direction: column;        justify-content: center;    }    .right-column {        width: 70%;        padding: 30px 0 30px 30px;        border-left: 1px solid #ccdce0;    }    .section {        margin-bottom: 30px;    }    .section-title {        font-size: 24px;        font-weight: 500;        margin-bottom: 14px;        color: #2a6b7a;        display: flex;        align-items: center;    }    .section-title:before {        content: "";        display: inline-block;        width: 8px;        height: 28px;        background-color: #2a6b7a;        margin-right: 12px;        border-radius: 4px;    }    .item-list {        list-style-type: none;        padding-left: 20px;    }    .item {        position: relative;        margin-bottom: 16px;        font-size: 20px;        line-height: 1.4;        padding-left: 45px;    }    .chapter-number {        position: absolute;        left: 0;        top: 0;        width: 36px;        height: 36px;        display: flex;        align-items: center;        justify-content: center;        border-radius: 50%;        background-color: #2a6b7a;        color: white;        font-weight: 500;        font-size: 18px;    }    .emphasis {        background-color: rgba(42, 107, 122, 0.1);        padding: 2px 6px;        border-radius: 4px;    }    .sidebar-text {        font-size: 22px;        line-height: 1.6;        color: #457986;        margin-bottom: 20px;    }    .chapter-subtitle {        font-size: 16px;        color: #5ba8bc;        display: block;        margin-top: 4px;    }
</style>
