<template>
  <SlidePageWrapper slide-id="B0BL6YPTQV" page-title="第4章：東南アジア・ASEANの地政学" :current-page="11" :total-pages="20">
<div class="slide-container"><div class="slide-sidebar"></div><div class="background-element"><svg viewbox="0 0 800 720" xmlns="http://www.w3.org/2000/svg"><path d="M0,0 L800,0 L800,720 L0,720 Z" fill="#1a365d"></path><path d="M100,100 C200,50 300,150 400,100 C500,50 600,150 700,100 M50,200 C150,150 250,250 350,200 C450,150 550,250 650,200 M0,300 C100,250 200,350 300,300 C400,250 500,350 600,300 M-50,400 C50,350 150,450 250,400 C350,350 450,450 550,400 M-100,500 C0,450 100,550 200,500 C300,450 400,550 500,500 M-150,600 C-50,550 50,650 150,600 C250,550 350,650 450,600" fill="none" stroke="#3182ce" stroke-width="2"></path></svg></div><div class="slide-content"><div class="title-container"><p class="chapter">第4章</p><p class="title">東南アジア・ASEANの地政学</p></div><div class="content-section"><div class="list-container"><div class="list-item"><div class="list-icon"><i class="fas fa-dharmachakra"></i></div><div class="list-text"><p><span class="highlight">マンダラ論</span>：中心と周縁が緩やかに重層共存する東南アジア固有の国家形成</p></div></div><div class="list-item"><div class="list-icon"><i class="fas fa-users"></i></div><div class="list-text"><p><span class="highlight">多民族・多宗教・起業家精神</span>、豊かな港湾と漁業資源</p></div></div><div class="list-item"><div class="list-icon"><i class="fas fa-chart-line"></i></div><div class="list-text"><p>経済圏の要点：<span class="highlight">人口規模の大きさ</span>、製造業・デジタルの伸長</p></div></div><div class="list-item"><div class="list-icon"><i class="fas fa-city"></i></div><div class="list-text"><p><span class="highlight">シンガポール＝情報・金融・物流のハブ</span></p></div></div><div class="list-item"><div class="list-icon"><i class="fas fa-road"></i></div><div class="list-text"><p>中国の<span class="highlight">一帯一路にとっても要衝</span>、親日国が多い</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            overflow: hidden;            display: flex;            position: relative;            background-color: #f8f9fa;        }        .slide-sidebar {            width: 80px;            background-color: #1a365d;            height: 100%;            position: absolute;            left: 0;            top: 0;            z-index: 5;        }        .slide-content {            width: 100%;            padding: 40px 40px 40px 120px;            z-index: 10;            display: flex;            flex-direction: column;        }        .background-element {            position: absolute;            top: 0;            right: 0;            height: 100%;            width: 35%;            opacity: 0.05;            z-index: 1;        }        .title-container {            margin-bottom: 30px;            position: relative;        }        .chapter {            font-size: 18px;            font-weight: 500;            color: #3182ce;            margin-bottom: 5px;        }        .title {            font-size: 40px;            font-weight: 700;            color: #1a365d;            position: relative;            padding-bottom: 12px;        }        .title:after {            content: "";            position: absolute;            bottom: 0;            left: 0;            width: 100px;            height: 4px;            background-color: #3182ce;        }        .content-section {            margin-top: 30px;        }        .list-container {            display: flex;            flex-direction: column;            gap: 20px;        }        .list-item {            display: flex;            align-items: flex-start;            background-color: rgba(255, 255, 255, 0.7);            padding: 15px 20px;            border-radius: 8px;            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05);        }        .list-icon {            color: #3182ce;            font-size: 18px;            margin-right: 15px;            padding-top: 3px;        }        .list-text p {            margin: 0;            line-height: 1.6;            color: #4a5568;            font-size: 20px;        }        .highlight {            color: #2c5282;            font-weight: 500;        }
</style>
