<template>
  <SlidePageWrapper slide-id="B0BL6YPTQV" page-title="キーセンテンス集" :current-page="18" :total-pages="20">
<div class="slide-container"><div class="slide-sidebar"></div><div class="background-element"><svg viewbox="0 0 512 720" xmlns="http://www.w3.org/2000/svg"><path d="M150,100 Q250,80 350,150" fill="none" stroke="#1a365d" stroke-width="8"></path><path d="M100,200 Q200,180 300,250" fill="none" stroke="#1a365d" stroke-width="8"></path><path d="M50,300 Q150,280 250,350" fill="none" stroke="#1a365d" stroke-width="8"></path><path d="M0,400 Q100,380 200,450" fill="none" stroke="#1a365d" stroke-width="8"></path><path d="M-50,500 Q50,480 150,550" fill="none" stroke="#1a365d" stroke-width="8"></path><path d="M-100,600 Q0,580 100,650" fill="none" stroke="#1a365d" stroke-width="8"></path><text fill="#1a365d" font-size="120" opacity="0.1" x="380" y="150">"</text><text fill="#1a365d" font-size="120" opacity="0.1" x="380" y="400">"</text><text fill="#1a365d" font-size="120" opacity="0.1" x="380" y="650">"</text></svg></div><div class="slide-content"><div class="title-container"><p class="title">キーセンテンス集</p></div><div class="quotes-container"><div class="quote-box"><div class="quote-icon"><i class="fas fa-quote-left"></i></div><div class="quote-text"><p>「<span class="quote-highlight">あなたがその国のトップだったらどう考えるか？</span>」</p></div></div><div class="quote-box"><div class="quote-icon"><i class="fas fa-quote-left"></i></div><div class="quote-text"><p>「<span class="quote-highlight">平和とは力の均衡状態である</span>」</p></div></div><div class="quote-box"><div class="quote-icon"><i class="fas fa-quote-left"></i></div><div class="quote-text"><p>「<span class="quote-highlight">重大リスクはインパクト×確率で判断する</span>」</p></div></div><div class="quote-box"><div class="quote-icon"><i class="fas fa-quote-left"></i></div><div class="quote-text"><p>「<span class="quote-highlight">地理が行動原理を規定する</span>」</p></div></div><div class="quote-box"><div class="quote-icon"><i class="fas fa-quote-left"></i></div><div class="quote-text"><p>「<span class="quote-highlight">地政学は未来予測のための実践的フレームだ</span>」</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            overflow: hidden;            display: flex;            position: relative;            background-color: #f8f9fa;        }        .slide-sidebar {            width: 80px;            background-color: #1a365d;            height: 100%;            position: absolute;            left: 0;            top: 0;            z-index: 5;        }        .slide-content {            width: 100%;            padding: 40px 40px 40px 120px;            z-index: 10;            display: flex;            flex-direction: column;        }        .title-container {            margin-bottom: 30px;            position: relative;        }        .title {            font-size: 40px;            font-weight: 700;            color: #1a365d;            position: relative;            padding-bottom: 12px;        }        .title:after {            content: "";            position: absolute;            bottom: 0;            left: 0;            width: 100px;            height: 4px;            background-color: #3182ce;        }        .quotes-container {            display: flex;            flex-direction: column;            gap: 20px;            flex: 1;        }        .quote-box {            background-color: rgba(255, 255, 255, 0.85);            border-left: 5px solid #3182ce;            border-radius: 4px;            padding: 18px 25px;            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.08);            position: relative;            transition: transform 0.2s ease;            display: flex;            align-items: center;        }        .quote-box:hover {            transform: translateX(5px);        }        .quote-icon {            position: absolute;            top: 10px;            left: 15px;            color: #3182ce;            opacity: 0.3;            font-size: 20px;        }        .quote-text {            font-size: 22px;            line-height: 1.5;            color: #2d3748;            margin-left: 10px;        }        .quote-text p {            margin: 0;            padding: 0;        }        .quote-highlight {            font-weight: 600;            color: #2c5282;        }        .background-element {            position: absolute;            top: 0;            right: 0;            width: 40%;            height: 100%;            z-index: 1;            opacity: 0.04;        }
</style>
