<template>
  <SlidePageWrapper slide-id="B0BL6YPTQV" page-title="第1章：最強である4つの理由" :current-page="5" :total-pages="20">
<div class="slide-container"><div class="slide-sidebar"></div><div class="background-element"><svg viewbox="0 0 800 720" xmlns="http://www.w3.org/2000/svg"><path d="M0,0 L800,0 L800,720 L0,720 Z" fill="#1a365d"></path><path d="M100,100 C200,50 300,150 400,100 C500,50 600,150 700,100 M50,200 C150,150 250,250 350,200 C450,150 550,250 650,200 M0,300 C100,250 200,350 300,300 C400,250 500,350 600,300 M-50,400 C50,350 150,450 250,400 C350,350 450,450 550,400 M-100,500 C0,450 100,550 200,500 C300,450 400,550 500,500 M-150,600 C-50,550 50,650 150,600 C250,550 350,650 450,600" fill="none" stroke="#3182ce" stroke-width="2"></path></svg></div><div class="slide-content"><div class="title-container"><p class="chapter">第1章</p><p class="title">第1章：最強である4つの理由</p></div><div class="content-section"><div class="list-container"><div class="list-item"><div class="list-icon"><i class="fas fa-search-plus"></i></div><div class="list-text"><p><span class="highlight">世界情勢の解像度が上がる：</span>国際ニュースの奥にある地理・歴史的制約を読み解き、表面的な報道だけでは見えない本質的な構造が理解できるようになる</p></div></div><div class="list-item"><div class="list-icon"><i class="fas fa-chart-line"></i></div><div class="list-text"><p><span class="highlight">長期未来予測のツール：</span>構造変化の方向性を掴み、投資家（例：レイ・ダリオ氏）も重視する産業・安全保障の長期トレンドを読める</p></div></div><div class="list-item"><div class="list-icon"><i class="fas fa-balance-scale"></i></div><div class="list-text"><p><span class="highlight">リスク評価＝インパクト×確率：</span>台湾有事などの重大国際リスクを「発生確率」と「影響度」の両面から合理的に評価・優先順位付けできる</p></div></div><div class="list-item"><div class="list-icon"><i class="fas fa-chess-king"></i></div><div class="list-text"><p><span class="highlight">トップのロールプレイ訓練：</span>「自分がその国の元首ならどう考え、決断するか」を反復することで複眼的思考と現実主義が身につく</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            overflow: hidden;            display: flex;            position: relative;            background-color: #f8f9fa;        }        .slide-sidebar {            width: 80px;            background-color: #1a365d;            height: 100%;            position: absolute;            left: 0;            top: 0;            z-index: 5;        }        .slide-content {            width: 100%;            padding: 40px 40px 40px 120px;            z-index: 10;            display: flex;            flex-direction: column;        }        .background-element {            position: absolute;            top: 0;            right: 0;            height: 100%;            width: 35%;            opacity: 0.05;            z-index: 1;        }        .title-container {            margin-bottom: 30px;            position: relative;        }        .chapter {            font-size: 18px;            font-weight: 500;            color: #3182ce;            margin-bottom: 5px;        }        .title {            font-size: 40px;            font-weight: 700;            color: #1a365d;            position: relative;            padding-bottom: 12px;        }        .title:after {            content: "";            position: absolute;            bottom: 0;            left: 0;            width: 100px;            height: 4px;            background-color: #3182ce;        }        .content-section {            margin-top: 30px;        }        .list-container {            display: flex;            flex-direction: column;            gap: 20px;        }        .list-item {            display: flex;            align-items: flex-start;            background-color: rgba(255, 255, 255, 0.7);            padding: 15px 20px;            border-radius: 8px;            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05);        }        .list-icon {            color: #3182ce;            font-size: 18px;            margin-right: 15px;            padding-top: 3px;        }        .list-text p {            margin: 0;            line-height: 1.6;            color: #4a5568;            font-size: 20px;        }        .highlight {            color: #2c5282;            font-weight: 500;        }
</style>
