<template>
  <SlidePageWrapper slide-id="486594458303" page-title="AIエージェント 人類と協働する機械 - 第3部要約" :current-page="1" :total-pages="23">
<div class="slide-container"><!-- Background Pattern (SVG Grid to avoid CSS gradients) --><svg class="svg-grid" height="100%" width="100%" xmlns="http://www.w3.org/2000/svg"><defs><pattern height="40" id="grid" patternunits="userSpaceOnUse" width="40"><path d="M 40 0 L 0 0 0 40" fill="none" stroke="white" stroke-width="0.5"></path></pattern></defs><rect fill="url(#grid)" height="100%" width="100%"></rect></svg><!-- Geometric Decorations --><div class="decoration-circle-top"></div><div class="decoration-circle-top-inner"></div><div class="decoration-line-bottom"></div><div class="decoration-line-accent"></div><!-- Content --><div class="content-wrapper"><div class="flex justify-center items-center mb-6"><span class="bg-blue-900 text-blue-200 px-4 py-1 rounded-sm text-sm font-bold tracking-wider uppercase border border-blue-700">        Book Summary Slides      </span></div><h1 class="text-6xl font-black text-white leading-tight tracking-tight mb-2 drop-shadow-lg">      AIエージェント<br/><span class="text-5xl font-bold text-gray-200">人類と協働する機械</span></h1><div class="title-divider"></div><h2 class="text-4xl font-bold text-blue-400 mb-4">      第3部    </h2><p class="text-3xl text-gray-100 font-bold mb-12">      知識創造というソフトウェアの新大陸    </p><div class="flex flex-col items-center justify-center mt-8 space-y-2"><p class="text-gray-400 text-lg font-medium">著者</p><p class="text-3xl font-bold text-white">広木 大地</p></div><div class="absolute bottom-12 left-0 w-full text-center"><p class="text-gray-500 text-sm font-light tracking-widest">        © 2025 Genspark AI Slides. All rights reserved.      </p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      background-color: #000000;      color: #f8fafc;      overflow: hidden;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      height: 720px;      min-height: 720px;      position: relative;      display: flex;      flex-direction: column;      justify-content: center;      align-items: center;      background-color: #050505;      overflow: hidden;    }    /* Decorative Elements */    .decoration-circle-top {      position: absolute;      top: -200px;      right: -100px;      width: 600px;      height: 600px;      border: 2px solid rgba(59, 130, 246, 0.15);      border-radius: 50%;      z-index: 0;    }    .decoration-circle-top-inner {      position: absolute;      top: -150px;      right: -50px;      width: 500px;      height: 500px;      border: 1px solid rgba(59, 130, 246, 0.1);      border-radius: 50%;      z-index: 0;    }    .decoration-line-bottom {      position: absolute;      bottom: 0;      left: 0;      width: 100%;      height: 8px;      background-color: #1e3a8a; /* Dark Blue */      z-index: 10;    }    .decoration-line-accent {      position: absolute;      bottom: 0;      left: 0;      width: 30%;      height: 8px;      background-color: #3b82f6; /* Bright Blue */      z-index: 11;    }    .content-wrapper {      z-index: 10;      text-align: center;      max-width: 1000px;      width: 100%;      padding: 0 40px;    }    .title-divider {      width: 80px;      height: 4px;      background-color: #3b82f6;      margin: 2rem auto;    }    .grid-bg {      position: absolute;      top: 0;      left: 0;      width: 100%;      height: 100%;      background-image:         linear-gradient(rgba(255, 255, 255, 0.03) 1px, transparent 1px),        linear-gradient(90deg, rgba(255, 255, 255, 0.03) 1px, transparent 1px);      background-size: 40px 40px;      opacity: 0.5;      z-index: 0;      pointer-events: none; /* Ensure no interaction issues, though pure CSS visual */    }    /* Note: Using background-image for grid lines is standard and not considered a gradient fill in the sense of "gradient background".        It creates a pattern. If strict no-gradient policy applies to patterns too, I can remove it.        However, based on "CSS gradients... as they cause export rendering issues", simple repeating patterns are usually safer or can be omitted.       Let's keep it simple and use SVG pattern or just omit for safety if strict.        I will use SVG background for grid to be safe and compliant with "Do not use any CSS gradients".    */    .svg-grid {      position: absolute;      top: 0;      left: 0;      width: 100%;      height: 100%;      z-index: 0;      opacity: 0.1;    }
</style>
