<template>
  <SlidePageWrapper slide-id="486594458303" page-title="" :current-page="15" :total-pages="23">
<div class="slide-container"><!-- Background Pattern --><svg class="bg-pattern" xmlns="http://www.w3.org/2000/svg"><defs><pattern height="40" id="dots" patternunits="userSpaceOnUse" width="40"><circle cx="2" cy="2" fill="#1e3a8a" r="1.5"></circle></pattern></defs><rect fill="url(#dots)" height="100%" width="100%"></rect><!-- Accent Shape --><circle cx="1200" cy="100" fill="none" r="300" stroke="#1e3a8a" stroke-opacity="0.2" stroke-width="2"></circle><circle cx="100" cy="600" fill="none" r="200" stroke="#1e3a8a" stroke-opacity="0.2" stroke-width="2"></circle></svg><!-- Decorative Quotes --><div class="quote-mark quote-mark-left">“</div><div class="quote-mark quote-mark-right">”</div><!-- Main Content --><div class="content-wrapper"><!-- Quote 1: Main Message --><div class="quote-card"><div class="topic-tag">知識創造の本質</div><p class="quote-text">          「AIエージェントは人間の知識創造を<span class="text-gray-400">置き換える</span>のではなく、<br/><span class="highlight-phrase" style="font-size: 1.2em;">拡張する</span>ものです。」        </p></div><!-- Quote 2: Collaboration --><div class="quote-card" style="border-left-color: #22d3ee;"><div class="topic-tag" style="background-color: #0e7490; border-color: #22d3ee; color: #cffafe;">協働による相乗効果</div><p class="quote-text">          「<span class="text-cyan-200">人間の創造性と直感力</span>を活かし、<br/><span class="text-blue-300">AIの情報処理能力と分析力</span>を組み合わせることで、<br/>          これまで不可能だった<span class="highlight-phrase text-cyan-400" style="background-color: rgba(34, 211, 238, 0.1); color: #22d3ee;">規模とスピードで知識創造を実現</span>できる。」        </p><div class="flex justify-end items-center mt-4 pt-3 border-t border-gray-700"><div class="flex items-center text-cyan-500 mr-4"><i class="fas fa-rocket mr-2"></i><span class="text-sm font-bold">Expansion &amp; Acceleration</span></div><p class="quote-author" style="float: none; border: none; margin: 0; padding: 0;">第3部 第11章『SECIモデルとAIエージェントの統合』 p.27-28</p></div></div></div><!-- Footer --><div class="footer-bar"><p>Copyright © 2025 Genspark AI Slides. All rights reserved.</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      background-color: #050505;      color: #f8fafc;      margin: 0;      padding: 0;      overflow: hidden;    }    .slide-container {      width: 1280px;      min-height: 720px;      position: relative;      display: flex;      flex-direction: column;      background-color: #050505;      overflow: hidden;      justify-content: center;      align-items: center;    }    /* Background Pattern */    .bg-pattern {      position: absolute;      top: 0;      left: 0;      width: 100%;      height: 100%;      z-index: 0;    }    /* Large Quotes - Decorative */    .quote-mark {      font-family: 'Times New Roman', serif;      font-size: 200px;      line-height: 1;      color: #1e3a8a; /* Dark Blue */      opacity: 0.3;      position: absolute;      z-index: 1;    }    .quote-mark-left {      top: 40px;      left: 60px;    }    .quote-mark-right {      bottom: 40px;      right: 60px;      transform: rotate(180deg);    }    /* Content Wrapper */    .content-wrapper {      width: 1000px;      z-index: 10;      display: flex;      flex-direction: column;      gap: 50px;    }    /* Quote Card */    .quote-card {      background-color: rgba(17, 24, 39, 0.8); /* Gray 900 with opacity */      border-left: 6px solid #3b82f6; /* Blue 500 */      padding: 40px;      border-radius: 0 12px 12px 0;      box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.5);      position: relative;      backdrop-filter: blur(5px);    }    .quote-text {      font-size: 28px;      font-weight: 500;      line-height: 1.8;      color: #f3f4f6;      margin-bottom: 10px;    }    .highlight-phrase {      color: #60a5fa; /* Blue 400 */      font-weight: 700;      background-color: rgba(59, 130, 246, 0.1);      padding: 2px 6px;      border-radius: 4px;    }    .quote-author {      text-align: right;      color: #9ca3af;      font-size: 16px;      margin-top: 15px;      font-style: italic;      border-top: 1px solid #374151;      padding-top: 10px;      display: inline-block;      float: right;    }    /* Badge/Tag */    .topic-tag {      position: absolute;      top: -15px;      left: 30px;      background-color: #1e3a8a;      color: #bfdbfe;      padding: 6px 16px;      border-radius: 20px;      font-size: 14px;      font-weight: 700;      letter-spacing: 0.05em;      border: 1px solid #3b82f6;      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.3);    }    /* Footer */    .footer-bar {      position: absolute;      bottom: 0;      left: 0;      width: 100%;      height: 40px;      display: flex;      justify-content: center;      align-items: center;      font-size: 12px;      color: #4b5563;      background-color: #050505;      z-index: 20;    }
</style>
