<template>
  <SlidePageWrapper slide-id="486594458303" page-title="" :current-page="16" :total-pages="23">
<div class="slide-container"><!-- Left Panel: Title & Theme --><div class="left-panel"><div class="section-number">12</div><!-- Dots Pattern --><svg class="svg-dots" xmlns="http://www.w3.org/2000/svg"><defs><pattern height="20" id="dots" patternunits="userSpaceOnUse" width="20"><circle cx="2" cy="2" fill="#3b82f6" r="1"></circle></pattern></defs><rect fill="url(#dots)" height="100%" width="100%"></rect></svg><div class="title-wrapper"><div class="decoration-line"></div><h2 class="text-blue-400 font-bold text-xl mb-2 tracking-widest uppercase">Chapter 12</h2><h1 class="text-4xl font-bold text-white leading-tight mb-8">          知識創造エージェントの<br/><span class="text-blue-500">企業戦略</span></h1><p class="text-gray-300 text-lg leading-relaxed font-light">          SaaS中心の時代から、<br/><strong class="text-white">AIエージェント中心</strong>の時代へ。<br/><br/>          企業システムは<strong class="text-white">「道具」</strong>から<strong class="text-white">「同僚」</strong>へと進化する。        </p></div></div><!-- Right Panel: Content Structure --><div class="right-panel"><div class="mb-8"><h3 class="text-2xl font-bold text-white mb-6 border-b border-gray-800 pb-4"><i class="fas fa-chess-strategy text-blue-500 mr-3"></i>3つの主要戦略        </h3><div class="space-y-6"><div class="chapter-list-item"><p class="text-blue-300 text-sm font-bold mb-1">Strategy 1</p><p class="text-xl font-bold text-white">コンパウンド戦略（幅）</p><p class="text-gray-400 text-sm mt-1">複数領域を横断し、データ統合とLTV最大化を狙う</p></div><div class="chapter-list-item"><p class="text-blue-300 text-sm font-bold mb-1">Strategy 2</p><p class="text-xl font-bold text-white">BPaaS戦略（深さ）</p><p class="text-gray-400 text-sm mt-1">業務プロセス全体をAIで自動化・請負化する</p></div><div class="chapter-list-item"><p class="text-blue-300 text-sm font-bold mb-1">Strategy 3</p><p class="text-xl font-bold text-white">プラットフォーム＋コンサルテーション</p><p class="text-gray-400 text-sm mt-1">標準基盤と伴走型支援で、組織変革を推進する</p></div></div></div><div class="highlight-box"><div class="flex items-start"><div class="mr-4 mt-1"><i class="fas fa-bullseye text-blue-400 text-2xl"></i></div><div><p class="text-gray-400 text-sm font-bold uppercase tracking-wider mb-1">FINAL GOAL</p><p class="text-xl text-white font-medium leading-snug">              自社の<span class="text-blue-400 font-bold">暗黙知</span>に根ざした<br/><span class="text-blue-400 font-bold">「知識創造エージェント」</span>の内製力を獲得する。            </p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      background-color: #000000;      color: #f8fafc;      margin: 0;      padding: 0;      overflow: hidden;    }    .slide-container {      width: 1280px;      height: 720px;      position: relative;      display: flex;      flex-direction: row;      background-color: #050505;      overflow: hidden;    }    /* Left Accent Panel */    .left-panel {      width: 35%;      height: 100%;      background-color: #111827; /* Gray 900 */      position: relative;      display: flex;      flex-direction: column;      justify-content: center;      padding: 0 60px;      border-right: 4px solid #1e3a8a; /* Dark Blue border */      z-index: 10;    }        /* Right Content Panel */    .right-panel {      flex: 1;      height: 100%;      background-color: #000000;      display: flex;      flex-direction: column;      justify-content: center;      padding: 0 60px;      position: relative;      z-index: 5;    }    /* SVG Patterns */    .svg-dots {      position: absolute;      top: 0;      left: 0;      width: 100%;      height: 100%;      opacity: 0.1;      z-index: 0;    }    .section-number {      font-size: 180px;      font-weight: 900;      color: rgba(30, 58, 138, 0.3); /* Faint blue */      line-height: 1;      position: absolute;      top: -40px;      left: -20px;      z-index: 0;    }        .title-wrapper {      position: relative;      z-index: 10;    }    .chapter-list-item {      position: relative;      padding-left: 24px;      margin-bottom: 20px;      border-left: 3px solid #3b82f6; /* Blue 500 */      transition: all 0.3s ease;    }        .decoration-line {      height: 2px;      width: 100px;      background-color: #3b82f6;      margin-bottom: 2rem;    }    .highlight-box {      background-color: #1e1e1e;      border: 1px solid #333;      border-radius: 8px;      padding: 24px;      margin-top: 30px;    }
</style>
