<template>
  <SlidePageWrapper slide-id="486594458303" page-title="" :current-page="2" :total-pages="23">
<div class="slide-container"><!-- Left Panel: Title & Theme --><div class="left-panel"><div class="section-number">03</div><!-- Dots Pattern --><svg class="svg-dots" xmlns="http://www.w3.org/2000/svg"><defs><pattern height="20" id="dots" patternunits="userSpaceOnUse" width="20"><circle cx="2" cy="2" fill="#3b82f6" r="1"></circle></pattern></defs><rect fill="url(#dots)" height="100%" width="100%"></rect></svg><div class="title-wrapper"><div class="decoration-line"></div><h2 class="text-blue-400 font-bold text-xl mb-2 tracking-widest uppercase">Part 3</h2><h1 class="text-4xl font-bold text-white leading-tight mb-8">          知識創造という<br/><span class="text-blue-500">ソフトウェアの新大陸</span></h1><p class="text-gray-300 text-lg leading-relaxed font-light">          企業システムは効率化の時代を超え、知識創造（SoK）へ。<br/><br/>          AIエージェントは知識創造プロセスを<strong class="text-white font-bold">“拡張”</strong>する。        </p></div></div><!-- Right Panel: Content Structure --><div class="right-panel"><div class="mb-10"><h3 class="text-2xl font-bold text-white mb-6 border-b border-gray-800 pb-4"><i class="fas fa-list-ul text-blue-500 mr-3"></i>本パートの構成        </h3><div class="space-y-6"><div class="chapter-list-item"><p class="text-blue-300 text-sm font-bold mb-1">Chapter 10</p><p class="text-xl font-bold text-white">拡張を続けるシステム領域</p><p class="text-gray-400 text-sm mt-1">SoR → SoE → SoI → SoK への進化</p></div><div class="chapter-list-item"><p class="text-blue-300 text-sm font-bold mb-1">Chapter 11</p><p class="text-xl font-bold text-white">SECIモデルとAIエージェントの統合</p><p class="text-gray-400 text-sm mt-1">知識創造の“螺旋”を加速する仕組み</p></div><div class="chapter-list-item"><p class="text-blue-300 text-sm font-bold mb-1">Chapter 12</p><p class="text-xl font-bold text-white">知識創造エージェントの企業戦略</p><p class="text-gray-400 text-sm mt-1">コンパウンド／BPaaS／プラットフォーム＋コンサル</p></div></div></div><div class="highlight-box"><div class="flex items-start"><div class="mr-4 mt-1"><i class="fas fa-flag-checkered text-blue-400 text-2xl"></i></div><div><p class="text-gray-400 text-sm font-bold uppercase tracking-wider mb-1">GOAL / 到達点</p><p class="text-xl text-white font-medium leading-snug">              価値の基準は<span class="text-blue-400 font-bold">“効率”</span>から<span class="text-blue-400 font-bold">“創造の質”</span>へ。<br/><span class="text-base text-gray-400 font-normal mt-1 block">自律的に知識を創造する企業への転換点を探ります。</span></p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      background-color: #000000;      color: #f8fafc;      margin: 0;      padding: 0;      overflow: hidden;    }    .slide-container {      width: 1280px;      height: 720px;      position: relative;      display: flex;      flex-direction: row;      background-color: #050505;      overflow: hidden;    }    /* Left Accent Panel */    .left-panel {      width: 35%;      height: 100%;      background-color: #111827; /* Gray 900 */      position: relative;      display: flex;      flex-direction: column;      justify-content: center;      padding: 0 60px;      border-right: 4px solid #1e3a8a; /* Dark Blue border */      z-index: 10;    }        /* Right Content Panel */    .right-panel {      flex: 1;      height: 100%;      background-color: #000000;      display: flex;      flex-direction: column;      justify-content: center;      padding: 0 60px;      position: relative;      z-index: 5;    }    /* SVG Patterns */    .svg-dots {      position: absolute;      top: 0;      left: 0;      width: 100%;      height: 100%;      opacity: 0.1;      z-index: 0;    }    .section-number {      font-size: 180px;      font-weight: 900;      color: rgba(30, 58, 138, 0.3); /* Faint blue */      line-height: 1;      position: absolute;      top: -40px;      left: -20px;      z-index: 0;    }        .title-wrapper {      position: relative;      z-index: 10;    }    .chapter-list-item {      position: relative;      padding-left: 24px;      margin-bottom: 20px;      border-left: 3px solid #3b82f6; /* Blue 500 */      transition: all 0.3s ease;    }        .decoration-line {      height: 2px;      width: 100px;      background-color: #3b82f6;      margin-bottom: 2rem;    }    .highlight-box {      background-color: #1e1e1e;      border: 1px solid #333;      border-radius: 8px;      padding: 24px;      margin-top: 30px;    }
</style>
