<template>
  <SlidePageWrapper slide-id="486594458303" page-title="" :current-page="3" :total-pages="23">
<div class="slide-container"><!-- Left Panel: Title & Theme --><div class="left-panel"><div class="section-number">10</div><!-- Dots Pattern --><svg class="svg-dots" xmlns="http://www.w3.org/2000/svg"><defs><pattern height="20" id="dots" patternunits="userSpaceOnUse" width="20"><circle cx="2" cy="2" fill="#3b82f6" r="1"></circle></pattern></defs><rect fill="url(#dots)" height="100%" width="100%"></rect></svg><div class="title-wrapper"><div class="decoration-line"></div><h2 class="text-blue-400 font-bold text-xl mb-2 tracking-widest uppercase">Chapter 10</h2><h1 class="text-4xl font-bold text-white leading-tight mb-8">          拡張を続ける<br/><span class="text-blue-500">システム領域</span></h1><p class="text-gray-300 text-lg leading-relaxed font-light">          ソフトウェアは「記録（SoR）」から「顧客接点（SoE）」、「洞察（SoI）」を経て、ついに<strong class="text-white font-bold">「知識創造（SoK）」</strong>へ。        </p></div></div><!-- Right Panel: Content Structure --><div class="right-panel"><div class="mb-6"><h3 class="text-2xl font-bold text-white mb-6 border-b border-gray-800 pb-4"><i class="fas fa-layer-group text-blue-500 mr-3"></i>章の主題とキーポイント        </h3><div class="space-y-4"><div class="point-box"><div class="flex items-center mb-2"><div class="bg-blue-900 p-2 rounded-full mr-3 text-blue-300"><i class="fas fa-cubes"></i></div><h4 class="text-xl font-bold text-white">レイヤーの積層的進化</h4></div><p class="text-gray-300 ml-12">              SoR（記録）、SoE（体験）、SoI（洞察）は互いに否定するものではなく、<span class="text-blue-400 font-bold">地層のように積み重なり</span>、その上にSoK（知識創造）が成立する。            </p></div><div class="point-box"><div class="flex items-center mb-2"><div class="bg-blue-900 p-2 rounded-full mr-3 text-blue-300"><i class="fas fa-brain"></i></div><h4 class="text-xl font-bold text-white">非構造化データ × 生成AI</h4></div><p class="text-gray-300 ml-12">              従来の分析（構造化データ中心）から、会話・音声・テキストなどの<span class="text-blue-400 font-bold">非構造化データ</span>をAIが処理し、「仮説生成→検証」までを自動化する領域へ。            </p></div><div class="point-box"><div class="flex items-center mb-2"><div class="bg-blue-900 p-2 rounded-full mr-3 text-blue-300"><i class="fas fa-ruler-combined"></i></div><h4 class="text-xl font-bold text-white">価値評価の転換</h4></div><p class="text-gray-300 ml-12">              システムの価値基準は「業務範囲のカバレッジ（効率）」から、<span class="text-blue-400 font-bold">「創造できる価値の質」</span>へと根本的に変化する。            </p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      background-color: #000000;      color: #f8fafc;      margin: 0;      padding: 0;      overflow: hidden;    }    .slide-container {      width: 1280px;      height: 720px;      position: relative;      display: flex;      flex-direction: row;      background-color: #050505;      overflow: hidden;    }    /* Left Accent Panel */    .left-panel {      width: 35%;      height: 100%;      background-color: #111827; /* Gray 900 */      position: relative;      display: flex;      flex-direction: column;      justify-content: center;      padding: 0 60px;      border-right: 4px solid #1e3a8a; /* Dark Blue border */      z-index: 10;    }        /* Right Content Panel */    .right-panel {      flex: 1;      height: 100%;      background-color: #000000;      display: flex;      flex-direction: column;      justify-content: center;      padding: 0 60px;      position: relative;      z-index: 5;    }    /* SVG Patterns */    .svg-dots {      position: absolute;      top: 0;      left: 0;      width: 100%;      height: 100%;      opacity: 0.1;      z-index: 0;    }    .section-number {      font-size: 180px;      font-weight: 900;      color: rgba(30, 58, 138, 0.3); /* Faint blue */      line-height: 1;      position: absolute;      top: -40px;      left: -20px;      z-index: 0;    }        .title-wrapper {      position: relative;      z-index: 10;    }    .chapter-list-item {      position: relative;      padding-left: 24px;      margin-bottom: 20px;      border-left: 3px solid #3b82f6; /* Blue 500 */      transition: all 0.3s ease;    }        .decoration-line {      height: 2px;      width: 100px;      background-color: #3b82f6;      margin-bottom: 2rem;    }    .point-box {        background-color: #111827;        border-left: 4px solid #3b82f6;        padding: 20px;        margin-bottom: 20px;        border-radius: 0 8px 8px 0;    }
</style>
