<template>
  <SlidePageWrapper slide-id="486594458303" page-title="" :current-page="9" :total-pages="23">
<div class="slide-container"><!-- Left Panel: Title & Theme --><div class="left-panel"><div class="section-number">11</div><!-- Dots Pattern --><svg class="svg-dots" xmlns="http://www.w3.org/2000/svg"><defs><pattern height="20" id="dots" patternunits="userSpaceOnUse" width="20"><circle cx="2" cy="2" fill="#3b82f6" r="1"></circle></pattern></defs><rect fill="url(#dots)" height="100%" width="100%"></rect></svg><div class="title-wrapper"><div class="decoration-line"></div><h2 class="text-blue-400 font-bold text-xl mb-2 tracking-widest uppercase">Chapter 11</h2><h1 class="text-4xl font-bold text-white leading-tight mb-8">          SECIモデルと<br/><span class="text-blue-500">AIエージェントの統合</span></h1><p class="text-gray-300 text-lg leading-relaxed font-light">          SECIモデルの4段階にAIエージェントを配置し、<br/>          知識創造の<strong class="text-white font-bold">“螺旋”</strong>を加速する。        </p></div></div><!-- Right Panel: Content Structure --><div class="right-panel"><div class="mb-10"><h3 class="text-2xl font-bold text-white mb-6 border-b border-gray-800 pb-4"><i class="fas fa-cogs text-blue-500 mr-3"></i>本章の主題        </h3><div class="space-y-6"><p class="text-gray-300 text-lg leading-relaxed">            知識創造理論として名高い<span class="text-white font-bold">「SECIモデル」</span>を現代のAI技術で再構築します。<br/>            人間とAIが協働することで、暗黙知と形式知の循環サイクルを高速化し、組織的な知識創造を実現する仕組みを解説します。          </p></div></div><div class="highlight-box"><h3 class="text-xl font-bold text-white mb-4"><i class="fas fa-key text-blue-400 mr-2"></i>Key Concepts / 鍵概念          </h3><div class="grid grid-cols-1 gap-4"><div class="flex items-start"><div class="text-blue-500 mr-3 mt-1"><i class="fas fa-check-circle"></i></div><div><p class="text-white font-bold">暗黙知 / 形式知</p><p class="text-gray-400 text-sm">言葉にならない経験知と、明文化された知識の相互変換。</p></div></div><div class="flex items-start"><div class="text-blue-500 mr-3 mt-1"><i class="fas fa-check-circle"></i></div><div><p class="text-white font-bold">場 (Ba)</p><p class="text-gray-400 text-sm">知識変換を促進するための物理的・仮想的な空間や文脈。</p></div></div><div class="flex items-start"><div class="text-blue-500 mr-3 mt-1"><i class="fas fa-check-circle"></i></div><div><p class="text-white font-bold">継続学習ループ</p><p class="text-gray-400 text-sm">実践とフィードバックを通じて、知識が常に更新され続けるサイクル。</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      background-color: #000000;      color: #f8fafc;      margin: 0;      padding: 0;      overflow: hidden;    }    .slide-container {      width: 1280px;      height: 720px;      position: relative;      display: flex;      flex-direction: row;      background-color: #050505;      overflow: hidden;    }    /* Left Accent Panel */    .left-panel {      width: 35%;      height: 100%;      background-color: #111827; /* Gray 900 */      position: relative;      display: flex;      flex-direction: column;      justify-content: center;      padding: 0 60px;      border-right: 4px solid #1e3a8a; /* Dark Blue border */      z-index: 10;    }        /* Right Content Panel */    .right-panel {      flex: 1;      height: 100%;      background-color: #000000;      display: flex;      flex-direction: column;      justify-content: center;      padding: 0 60px;      position: relative;      z-index: 5;    }    /* SVG Patterns */    .svg-dots {      position: absolute;      top: 0;      left: 0;      width: 100%;      height: 100%;      opacity: 0.1;      z-index: 0;    }    .section-number {      font-size: 180px;      font-weight: 900;      color: rgba(30, 58, 138, 0.3); /* Faint blue */      line-height: 1;      position: absolute;      top: -40px;      left: -20px;      z-index: 0;    }        .title-wrapper {      position: relative;      z-index: 10;    }    .chapter-list-item {      position: relative;      padding-left: 24px;      margin-bottom: 20px;      border-left: 3px solid #3b82f6; /* Blue 500 */      transition: all 0.3s ease;    }        .decoration-line {      height: 2px;      width: 100px;      background-color: #3b82f6;      margin-bottom: 2rem;    }    .highlight-box {      background-color: #1e1e1e;      border: 1px solid #333;      border-radius: 8px;      padding: 24px;      margin-top: 30px;    }
</style>
