<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="8つの方法① 赦しの文化" :current-page="10" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="header"><div class="method-number">1</div><div><h1 class="method-title">赦しの文化</h1><p class="method-subtitle">恐れの文化から、挑戦と学びの文化へ</p></div></div><div class="content-grid"><div class="content-section"><div class="section-title"><i class="fas fa-bullseye"></i><p>ねらい</p></div><div class="section-content"><div class="transform-arrow"><p class="transform-from">恐れの文化</p><p class="arrow"><i class="fas fa-long-arrow-alt-right"></i></p><p class="transform-to">赦しの文化</p></div><p>ミスや失敗を恐れる風土から、挑戦を受け入れ、失敗から学ぶ組織へと転換します。責任追及より再発防止と成長に焦点を当てる文化を醸成します。</p></div></div><div class="content-section"><div class="section-title"><i class="fas fa-hammer"></i><p>実践</p></div><div class="section-content"><ul class="bullet-list"><li><p>失敗体験をオープンに共有するフォーラムの設置</p></li><li><p>「チャレンジ賞」など、挑戦自体を評価する表彰制度</p></li><li><p>失敗事例の学びを全体で共有する仕組みづくり</p></li></ul></div></div><div class="content-section"><div class="section-title"><i class="fas fa-cogs"></i><p>マネジメント</p></div><div class="section-content"><ul class="bullet-list"><li><p>問題発生時、個人追及ではなくチーム全体の課題として捉える</p></li><li><p>リーダー自身が失敗を認め、学びを共有する姿勢を示す</p></li><li><p>「何が悪かったか」より「何を学んだか」を重視する対話</p></li></ul></div></div><div class="content-section"><div class="section-title"><i class="fas fa-chart-line"></i><p>期待効果</p></div><div class="section-content"><ul class="bullet-list"><li><p>心理的安全性の向上と発言しやすい環境の実現</p></li><li><p>挑戦する人材の増加とイノベーションの創出</p></li><li><p>透明性の高い問題解決と組織全体の学習能力向上</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 40px;    }    .header {      display: flex;      align-items: center;      margin-bottom: 40px;    }    .method-number {      width: 80px;      height: 80px;      background-color: #2563eb;      border-radius: 50%;      color: white;      font-size: 36px;      font-weight: 900;      display: flex;      align-items: center;      justify-content: center;      margin-right: 20px;    }    .method-title {      font-size: 36px;      font-weight: 700;      color: #1a365d;    }    .method-subtitle {      font-size: 22px;      color: #4a5568;      margin-top: 4px;    }    .content-grid {      display: grid;      grid-template-columns: repeat(2, 1fr);      grid-template-rows: repeat(2, 1fr);      gap: 30px;      flex: 1;    }    .content-section {      background-color: #f8fafc;      border-radius: 12px;      padding: 24px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);    }    .section-title {      font-size: 20px;      font-weight: 700;      color: #2563eb;      margin-bottom: 16px;      display: flex;      align-items: center;    }    .section-title i {      margin-right: 10px;    }    .section-content {      font-size: 18px;      color: #333;      line-height: 1.6;    }    .bullet-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .bullet-list li {      position: relative;      padding-left: 24px;      margin-bottom: 12px;    }    .bullet-list li:before {      content: "";      position: absolute;      left: 0;      top: 10px;      width: 8px;      height: 8px;      background-color: #2563eb;      border-radius: 50%;    }    .transform-arrow {      display: flex;      align-items: center;      margin: 10px 0;    }    .transform-from {      color: #e53e3e;      font-weight: 500;    }    .transform-to {      color: #2f855a;      font-weight: 500;    }    .arrow {      color: #2563eb;      margin: 0 10px;    }
</style>
