<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="8つの方法② オープン文化" :current-page="11" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="header"><div class="method-number">2</div><div><h1 class="method-title">オープン文化</h1><p class="method-subtitle">クローズ文化から、透明性とつながりの文化へ</p></div></div><div class="content-grid"><div class="content-section"><div class="section-title"><i class="fas fa-bullseye"></i><p>ねらい</p></div><div class="section-content"><div class="transform-arrow"><p class="transform-from">クローズ文化</p><p class="arrow"><i class="fas fa-long-arrow-alt-right"></i></p><p class="transform-to">オープン文化</p></div><p>情報や意思決定プロセスをできる限りオープンにし、組織全体の透明性を高めます。「知らなかった」「聞いていない」という状況をなくし、全員参加型の組織づくりを目指します。</p></div></div><div class="content-section"><div class="section-title"><i class="fas fa-hammer"></i><p>実践</p></div><div class="section-content"><ul class="bullet-list"><li><p>週次経営ミーティングの全職員オブザーブ参加</p></li><li><p>パブリックコメント制度による意思決定の可視化</p></li><li><p>社内SNSやオープンチャットでの情報共有の徹底</p></li></ul></div></div><div class="content-section"><div class="section-title"><i class="fas fa-cogs"></i><p>仕組み</p></div><div class="section-content"><ul class="bullet-list"><li><p>会議体の議題・資料・議事録を全員と共有</p></li><li><p>決定事項の背景・理由も含めた情報開示</p></li><li><p>「ブラックボックス化」を排除し、プロセスを可視化</p></li></ul></div></div><div class="content-section"><div class="section-title"><i class="fas fa-chart-line"></i><p>期待効果</p></div><div class="section-content"><ul class="bullet-list"><li><p>情報格差の縮小と組織の一体感向上</p></li><li><p>意思決定への納得感と当事者意識の醸成</p></li><li><p>信頼関係の構築と協力体制の強化</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 40px;    }    .header {      display: flex;      align-items: center;      margin-bottom: 40px;    }    .method-number {      width: 80px;      height: 80px;      background-color: #2563eb;      border-radius: 50%;      color: white;      font-size: 36px;      font-weight: 900;      display: flex;      align-items: center;      justify-content: center;      margin-right: 20px;    }    .method-title {      font-size: 36px;      font-weight: 700;      color: #1a365d;    }    .method-subtitle {      font-size: 22px;      color: #4a5568;      margin-top: 4px;    }    .content-grid {      display: grid;      grid-template-columns: repeat(2, 1fr);      grid-template-rows: repeat(2, 1fr);      gap: 30px;      flex: 1;    }    .content-section {      background-color: #f8fafc;      border-radius: 12px;      padding: 24px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);    }    .section-title {      font-size: 20px;      font-weight: 700;      color: #2563eb;      margin-bottom: 16px;      display: flex;      align-items: center;    }    .section-title i {      margin-right: 10px;    }    .section-content {      font-size: 18px;      color: #333;      line-height: 1.6;    }    .bullet-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .bullet-list li {      position: relative;      padding-left: 24px;      margin-bottom: 12px;    }    .bullet-list li:before {      content: "";      position: absolute;      left: 0;      top: 10px;      width: 8px;      height: 8px;      background-color: #2563eb;      border-radius: 50%;    }    .transform-arrow {      display: flex;      align-items: center;      margin: 10px 0;    }    .transform-from {      color: #e53e3e;      font-weight: 500;    }    .transform-to {      color: #2f855a;      font-weight: 500;    }    .arrow {      color: #2563eb;      margin: 0 10px;    }
</style>
