<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="8つの方法③ 現場が主役" :current-page="12" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="header"><div class="method-number">3</div><div><h1 class="method-title">現場が主役</h1><p class="method-subtitle">本社主導から、現場重視の組織へ</p></div></div><div class="content-grid"><div class="content-section"><div class="section-title"><i class="fas fa-bullseye"></i><p>ねらい</p></div><div class="section-content"><div class="transform-arrow"><p class="transform-from">本社が主役</p><p class="arrow"><i class="fas fa-long-arrow-alt-right"></i></p><p class="transform-to">現場が主役</p></div><p>本社や上層部が主導権を持つ構造から、現場に必要な権限と裁量を持たせ、顧客に最も近い現場の声や判断を重視する組織へと転換します。</p></div></div><div class="content-section"><div class="section-title"><i class="fas fa-hammer"></i><p>実践</p></div><div class="section-content"><ul class="bullet-list"><li><p>現場主導のプロジェクトチーム（PT）組成と企画権限付与</p></li><li><p>各種会議体への現場メンバー参画拡大</p></li><li><p>未来開発PTなど現場発の制度改革推進</p></li></ul></div></div><div class="content-section"><div class="section-title"><i class="fas fa-cogs"></i><p>仕組み</p></div><div class="section-content"><ul class="bullet-list"><li><p>現場への意思決定権限の委譲と業務裁量拡大</p></li><li><p>現場KPIの再定義（顧客価値・現場満足度指標の重視）</p></li><li><p>経営会議のオブザーバー枠拡大と現場の声の採用</p></li></ul></div></div><div class="content-section"><div class="section-title"><i class="fas fa-chart-line"></i><p>期待効果</p></div><div class="section-content"><ul class="bullet-list"><li><p>顧客ニーズへの迅速な対応と価値創出の加速</p></li><li><p>現場の当事者意識と責任感の向上</p></li><li><p>多様な視点と知恵を活かした組織力の強化</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 40px;    }    .header {      display: flex;      align-items: center;      margin-bottom: 40px;    }    .method-number {      width: 80px;      height: 80px;      background-color: #2563eb;      border-radius: 50%;      color: white;      font-size: 36px;      font-weight: 900;      display: flex;      align-items: center;      justify-content: center;      margin-right: 20px;    }    .method-title {      font-size: 36px;      font-weight: 700;      color: #1a365d;    }    .method-subtitle {      font-size: 22px;      color: #4a5568;      margin-top: 4px;    }    .content-grid {      display: grid;      grid-template-columns: repeat(2, 1fr);      grid-template-rows: repeat(2, 1fr);      gap: 30px;      flex: 1;    }    .content-section {      background-color: #f8fafc;      border-radius: 12px;      padding: 24px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);    }    .section-title {      font-size: 20px;      font-weight: 700;      color: #2563eb;      margin-bottom: 16px;      display: flex;      align-items: center;    }    .section-title i {      margin-right: 10px;    }    .section-content {      font-size: 18px;      color: #333;      line-height: 1.6;    }    .bullet-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .bullet-list li {      position: relative;      padding-left: 24px;      margin-bottom: 12px;    }    .bullet-list li:before {      content: "";      position: absolute;      left: 0;      top: 10px;      width: 8px;      height: 8px;      background-color: #2563eb;      border-radius: 50%;    }    .transform-arrow {      display: flex;      align-items: center;      margin: 10px 0;    }    .transform-from {      color: #e53e3e;      font-weight: 500;    }    .transform-to {      color: #2f855a;      font-weight: 500;    }    .arrow {      color: #2563eb;      margin: 0 10px;    }
</style>
