<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="8つの方法④ ボトムアップ" :current-page="13" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="header"><div class="method-number">4</div><div><h1 class="method-title">ボトムアップ</h1><p class="method-subtitle">トップダウン文化から、全員参加の意思決定文化へ</p></div></div><div class="content-grid"><div class="content-section"><div class="section-title"><i class="fas fa-bullseye"></i><p>ねらい</p></div><div class="section-content"><div class="transform-arrow"><p class="transform-from">トップダウン</p><p class="arrow"><i class="fas fa-long-arrow-alt-right"></i></p><p class="transform-to">ボトムアップ</p></div><p>方針や制度を上位から押しつけるのではなく、現場や社員の意見・提案を起点に意思決定を行う仕組みを構築します。全員が当事者となる組織文化を醸成します。</p></div></div><div class="content-section"><div class="section-title"><i class="fas fa-hammer"></i><p>実践</p></div><div class="section-content"><ul class="bullet-list"><li><p>「パブリックコメント」による全員参加・自由参加型の制度改革</p></li><li><p>公募制プロジェクトチーム（PT）の組織化と権限付与</p></li><li><p>社内SNSでの意見募集→議論→ルール化のサイクル確立</p></li></ul></div></div><div class="content-section"><div class="section-title"><i class="fas fa-cogs"></i><p>マネジメント</p></div><div class="section-content"><ul class="bullet-list"><li><p>アンケートと討議結果を意思決定に確実に反映する仕組み</p></li><li><p>現場からの提案や改善案を積極的に支援・承認する姿勢</p></li><li><p>意見集約プロセスを透明化し、フィードバック循環を作る</p></li></ul></div></div><div class="content-section"><div class="section-title"><i class="fas fa-chart-line"></i><p>期待効果</p></div><div class="section-content"><ul class="bullet-list"><li><p>「自分たちで作った」という当事者意識とオーナーシップの向上</p></li><li><p>現場の知恵を活かした実効性の高い制度・施策の実現</p></li><li><p>納得感の向上によるモチベーションアップと実行力強化</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 40px;    }    .header {      display: flex;      align-items: center;      margin-bottom: 40px;    }    .method-number {      width: 80px;      height: 80px;      background-color: #2563eb;      border-radius: 50%;      color: white;      font-size: 36px;      font-weight: 900;      display: flex;      align-items: center;      justify-content: center;      margin-right: 20px;    }    .method-title {      font-size: 36px;      font-weight: 700;      color: #1a365d;    }    .method-subtitle {      font-size: 22px;      color: #4a5568;      margin-top: 4px;    }    .content-grid {      display: grid;      grid-template-columns: repeat(2, 1fr);      grid-template-rows: repeat(2, 1fr);      gap: 30px;      flex: 1;    }    .content-section {      background-color: #f8fafc;      border-radius: 12px;      padding: 24px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);    }    .section-title {      font-size: 20px;      font-weight: 700;      color: #2563eb;      margin-bottom: 16px;      display: flex;      align-items: center;    }    .section-title i {      margin-right: 10px;    }    .section-content {      font-size: 18px;      color: #333;      line-height: 1.6;    }    .bullet-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .bullet-list li {      position: relative;      padding-left: 24px;      margin-bottom: 12px;    }    .bullet-list li:before {      content: "";      position: absolute;      left: 0;      top: 10px;      width: 8px;      height: 8px;      background-color: #2563eb;      border-radius: 50%;    }    .transform-arrow {      display: flex;      align-items: center;      margin: 10px 0;    }    .transform-from {      color: #e53e3e;      font-weight: 500;    }    .transform-to {      color: #2f855a;      font-weight: 500;    }    .arrow {      color: #2563eb;      margin: 0 10px;    }
</style>
