<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="8つの方法⑤ OODA（実験）文化" :current-page="14" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="header"><div class="method-number">5</div><div><h1 class="method-title">OODA（実験）文化</h1><p class="method-subtitle">計画重視のPDCAから、即応型のOODAサイクルへ</p></div></div><div class="content-grid"><div class="content-section"><div class="section-title"><i class="fas fa-bullseye"></i><p>ねらい</p></div><div class="section-content"><div class="transform-arrow"><p class="transform-from">PDCA（計画）文化</p><p class="arrow"><i class="fas fa-long-arrow-alt-right"></i></p><p class="transform-to">OODA（実験）文化</p></div><p>完璧な計画を立ててから実行するPDCAサイクルから、観察・状況判断・即決断・即実行のOODAループへと転換。素早い試行錯誤と学習を促進します。</p></div></div><div class="content-section"><div class="section-title"><i class="fas fa-hammer"></i><p>実践</p></div><div class="section-content"><ul class="bullet-list"><li><p>「小さく早く試す」風土の醸成と実践</p></li><li><p>デイリーレトロスペクティブの導入</p></li><li><p>「とりあえずやってみる」を奨励する表彰</p></li><li><p>実験のための小規模予算枠の設定</p></li></ul></div></div><div class="content-section"><div class="section-title"><i class="fas fa-cogs"></i><p>仕組み</p></div><div class="section-content"><ul class="bullet-list"><li><p>行動スピードと学びを評価基準に組み込む</p></li><li><p>複雑な決裁プロセスの簡略化</p></li><li><p>月間MVP賞・チャレンジ賞で実践者を称賛</p></li><li><p>「完璧な準備より素早い検証」の重視</p></li></ul></div></div><div class="content-section"><div class="section-title"><i class="fas fa-chart-line"></i><p>期待効果</p></div><div class="section-content"><ul class="bullet-list"><li><p>市場変化への適応力と意思決定速度の向上</p></li><li><p>イノベーション創出と学習サイクルの加速</p></li><li><p>失敗から学ぶ組織文化の浸透</p></li><li><p>過度な完璧主義からの脱却</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 40px;    }    .header {      display: flex;      align-items: center;      margin-bottom: 40px;    }    .method-number {      width: 80px;      height: 80px;      background-color: #2563eb;      border-radius: 50%;      color: white;      font-size: 36px;      font-weight: 900;      display: flex;      align-items: center;      justify-content: center;      margin-right: 20px;    }    .method-title {      font-size: 36px;      font-weight: 700;      color: #1a365d;    }    .method-subtitle {      font-size: 22px;      color: #4a5568;      margin-top: 4px;    }    .content-grid {      display: grid;      grid-template-columns: repeat(2, 1fr);      grid-template-rows: repeat(2, 1fr);      gap: 30px;      flex: 1;    }    .content-section {      background-color: #f8fafc;      border-radius: 12px;      padding: 24px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);    }    .section-title {      font-size: 20px;      font-weight: 700;      color: #2563eb;      margin-bottom: 16px;      display: flex;      align-items: center;    }    .section-title i {      margin-right: 10px;    }    .section-content {      font-size: 18px;      color: #333;      line-height: 1.6;    }    .bullet-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .bullet-list li {      position: relative;      padding-left: 24px;      margin-bottom: 12px;    }    .bullet-list li:before {      content: "";      position: absolute;      left: 0;      top: 10px;      width: 8px;      height: 8px;      background-color: #2563eb;      border-radius: 50%;    }    .transform-arrow {      display: flex;      align-items: center;      margin: 10px 0;    }    .transform-from {      color: #e53e3e;      font-weight: 500;    }    .transform-to {      color: #2f855a;      font-weight: 500;    }    .arrow {      color: #2563eb;      margin: 0 10px;    }
</style>
