<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="8つの方法⑥ 自発の文化" :current-page="15" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="header"><div class="method-number">6</div><div><h1 class="method-title">自発の文化</h1><p class="method-subtitle">管理の文化から、主体性と自律の文化へ</p></div></div><div class="content-grid"><div class="content-section"><div class="section-title"><i class="fas fa-bullseye"></i><p>ねらい</p></div><div class="section-content"><div class="transform-arrow"><p class="transform-from">管理の文化</p><p class="arrow"><i class="fas fa-long-arrow-alt-right"></i></p><p class="transform-to">自発の文化</p></div><p>指示されて動く受動的な組織から、メンバー自らが考え主体的に行動する組織へと転換します。上からの管理ではなく、信頼をベースに自律性を高める文化を醸成します。</p></div></div><div class="content-section"><div class="section-title"><i class="fas fa-hammer"></i><p>実践</p></div><div class="section-content"><ul class="bullet-list"><li><p>「やっていい」と背中を押す「お守りワード」の共有と浸透</p></li><li><p>管理よりも「任せる→見守る」リーダーシップスタイルの推進</p></li><li><p>MYパーパスワークを通じた自己認識と動機付け強化</p></li></ul></div></div><div class="content-section"><div class="section-title"><i class="fas fa-cogs"></i><p>仕組み</p></div><div class="section-content"><ul class="bullet-list"><li><p>申請・承認プロセスの簡便化と権限委譲の拡大</p></li><li><p>部門を超えた越境活動を許容・奨励する制度</p></li><li><p>同僚からの推薦による表彰・フィードバック制度</p></li></ul></div></div><div class="content-section"><div class="section-title"><i class="fas fa-chart-line"></i><p>期待効果</p></div><div class="section-content"><ul class="bullet-list"><li><p>提案・改善行動の自発的な増加と組織全体の活性化</p></li><li><p>自ら考え動くリーダー人材の育成と組織力強化</p></li><li><p>エンゲージメント向上と「自分ゴト」意識の醸成</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 40px;    }    .header {      display: flex;      align-items: center;      margin-bottom: 40px;    }    .method-number {      width: 80px;      height: 80px;      background-color: #2563eb;      border-radius: 50%;      color: white;      font-size: 36px;      font-weight: 900;      display: flex;      align-items: center;      justify-content: center;      margin-right: 20px;    }    .method-title {      font-size: 36px;      font-weight: 700;      color: #1a365d;    }    .method-subtitle {      font-size: 22px;      color: #4a5568;      margin-top: 4px;    }    .content-grid {      display: grid;      grid-template-columns: repeat(2, 1fr);      grid-template-rows: repeat(2, 1fr);      gap: 30px;      flex: 1;    }    .content-section {      background-color: #f8fafc;      border-radius: 12px;      padding: 24px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);    }    .section-title {      font-size: 20px;      font-weight: 700;      color: #2563eb;      margin-bottom: 16px;      display: flex;      align-items: center;    }    .section-title i {      margin-right: 10px;    }    .section-content {      font-size: 18px;      color: #333;      line-height: 1.6;    }    .bullet-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .bullet-list li {      position: relative;      padding-left: 24px;      margin-bottom: 12px;    }    .bullet-list li:before {      content: "";      position: absolute;      left: 0;      top: 10px;      width: 8px;      height: 8px;      background-color: #2563eb;      border-radius: 50%;    }    .transform-arrow {      display: flex;      align-items: center;      margin: 10px 0;    }    .transform-from {      color: #e53e3e;      font-weight: 500;    }    .transform-to {      color: #2f855a;      font-weight: 500;    }    .arrow {      color: #2563eb;      margin: 0 10px;    }
</style>
