<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="8つの方法⑦ P/L（KGI）文化" :current-page="16" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="header"><div class="method-number">7</div><div><h1 class="method-title">P/L（KGI）文化</h1><p class="method-subtitle">KPI偏重から全体成果・価値重視の文化へ</p></div></div><div class="content-grid"><div class="content-section"><div class="section-title"><i class="fas fa-bullseye"></i><p>ねらい</p></div><div class="section-content"><div class="transform-arrow"><p class="transform-from">KPI文化</p><p class="arrow"><i class="fas fa-long-arrow-alt-right"></i></p><p class="transform-to">P/L（KGI）文化</p></div><p>指標（KPI）数字やタスクだけを追うのではなく、最終成果・顧客価値（P/L・KGI）を意識した判断・行動を重視する思考へと転換します。</p></div></div><div class="content-section"><div class="section-title"><i class="fas fa-hammer"></i><p>実践</p></div><div class="section-content"><ul class="bullet-list"><li><p>KPIは最小限に絞り込み、成果指標（KGI）を優先する</p></li><li><p>目標設定はP/Lに連動させ、全体価値を重視する</p></li><li><p>指標設計に「仮説→検証」のアプローチを取り入れる</p></li></ul></div></div><div class="content-section"><div class="section-title"><i class="fas fa-cogs"></i><p>仕組み</p></div><div class="section-content"><ul class="bullet-list"><li><p>売上等の単一KPIより顧客満足や収益全体を評価基準に</p></li><li><p>短期指標と長期価値創出の両立を促す評価体系</p></li><li><p>部門間の壁を超えた全体最適を促す会議体・情報共有</p></li></ul></div></div><div class="content-section"><div class="section-title"><i class="fas fa-chart-line"></i><p>期待効果</p></div><div class="section-content"><ul class="bullet-list"><li><p>部分最適から全体最適志向への転換</p></li><li><p>短期的な数値達成よりも持続的な成果創出へ</p></li><li><p>事業価値に基づく意思決定力の強化</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 40px;    }    .header {      display: flex;      align-items: center;      margin-bottom: 40px;    }    .method-number {      width: 80px;      height: 80px;      background-color: #2563eb;      border-radius: 50%;      color: white;      font-size: 36px;      font-weight: 900;      display: flex;      align-items: center;      justify-content: center;      margin-right: 20px;    }    .method-title {      font-size: 36px;      font-weight: 700;      color: #1a365d;    }    .method-subtitle {      font-size: 22px;      color: #4a5568;      margin-top: 4px;    }    .content-grid {      display: grid;      grid-template-columns: repeat(2, 1fr);      grid-template-rows: repeat(2, 1fr);      gap: 30px;      flex: 1;    }    .content-section {      background-color: #f8fafc;      border-radius: 12px;      padding: 24px;      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);    }    .section-title {      font-size: 20px;      font-weight: 700;      color: #2563eb;      margin-bottom: 16px;      display: flex;      align-items: center;    }    .section-title i {      margin-right: 10px;    }    .section-content {      font-size: 18px;      color: #333;      line-height: 1.6;    }    .bullet-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .bullet-list li {      position: relative;      padding-left: 24px;      margin-bottom: 12px;    }    .bullet-list li:before {      content: "";      position: absolute;      left: 0;      top: 10px;      width: 8px;      height: 8px;      background-color: #2563eb;      border-radius: 50%;    }    .transform-arrow {      display: flex;      align-items: center;      margin: 10px 0;    }    .transform-from {      color: #e53e3e;      font-weight: 500;    }    .transform-to {      color: #2f855a;      font-weight: 500;    }    .arrow {      color: #2563eb;      margin: 0 10px;    }
</style>
