<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="実践のポイントとまとめ" :current-page="18" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="slide-header"><h1 class="title">実践のポイントとまとめ</h1><div class="accent-line"></div></div><div class="content-section"><ul class="bullet-list"><li><span class="bullet-category">くどいほど発信を続ける</span><p class="sub-bullet">ビジョンやお守りワードは何度も繰り返し伝える。自然と定着するまで諦めないこと</p></li><li><span class="bullet-category">小さな成功を称賛し共有</span><p class="sub-bullet">わずかな成功や挑戦も見逃さず表彰・SNS等で拡散。積み重ねが大きな変化を生む</p></li><li><span class="bullet-category">多チャネルで長期浸透</span><p class="sub-bullet">面談・SNS・動画・ワークショップ・座談会など様々な手段を駆使して広める</p></li><li><span class="bullet-category">8つの心がまえを日常に埋め込む</span><p class="sub-bullet">表彰制度・パブコメ・オープン会議・MYパーパスワークなど日々の活動に組み込む</p></li></ul></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;      color: #333;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 60px;    }    .slide-header {      margin-bottom: 40px;    }    .title {      font-size: 36px;      font-weight: 700;      color: #1a365d;      margin-bottom: 16px;    }    .accent-line {      width: 80px;      height: 4px;      background-color: #60a5fa;      margin-bottom: 40px;    }    .content-section {      flex: 1;    }    .bullet-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .bullet-list li {      position: relative;      padding-left: 28px;      margin-bottom: 24px;      font-size: 24px;      line-height: 1.5;    }    .bullet-list li:before {      content: "";      position: absolute;      left: 0;      top: 12px;      width: 10px;      height: 10px;      background-color: #60a5fa;      border-radius: 50%;    }    .bullet-category {      font-weight: 700;      color: #1a365d;    }    .sub-bullet {      font-size: 20px;      margin-top: 8px;      margin-left: 28px;      line-height: 1.4;    }
</style>
