<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="SOMPOでの実践事例" :current-page="19" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="slide-header"><h1 class="title">SOMPOでの実践事例</h1><div class="accent-line"></div></div><div class="content-section"><ul class="bullet-list"><li><span class="bullet-category">パブリックコメント導入：</span> 制度・ルールを全員参加型で共創<p class="sub-bullet">従来トップダウンだった人事給与・評価制度を社員主導で策定</p></li><li><span class="bullet-category">週次経営MTGのオープン化：</span> 役員のみから全職員へ拡大<p class="sub-bullet">情報共有の範囲と質が大幅に向上、透明性の確保</p></li><li><span class="bullet-category">表彰制度の刷新：</span> 社長賞・チャレンジ賞・月間MVP賞の新設<p class="sub-bullet">小さな挑戦も評価し、"やっていい"の空気を醸成</p></li><li><span class="bullet-category">MVV再策定とMYパーパス：</span> 現場発起の新たな価値観形成<p class="sub-bullet">社員一人ひとりが自分のパーパスを見直し実践する文化へ</p></li><li><span class="bullet-category">成果：</span> モチベーション向上・情報透明性・参加感の醸成<p class="sub-bullet">「自分たちの組織を自分たちで変えられる」実感が全社に拡大</p></li></ul></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;      color: #333;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 60px;    }    .slide-header {      margin-bottom: 40px;    }    .title {      font-size: 36px;      font-weight: 700;      color: #1a365d;      margin-bottom: 16px;    }    .accent-line {      width: 80px;      height: 4px;      background-color: #60a5fa;      margin-bottom: 40px;    }    .content-section {      flex: 1;    }    .bullet-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .bullet-list li {      position: relative;      padding-left: 28px;      margin-bottom: 24px;      font-size: 24px;      line-height: 1.5;    }    .bullet-list li:before {      content: "";      position: absolute;      left: 0;      top: 12px;      width: 10px;      height: 10px;      background-color: #60a5fa;      border-radius: 50%;    }    .bullet-category {      font-weight: 700;      color: #1a365d;    }    .sub-bullet {      font-size: 20px;      margin-top: 8px;      margin-left: 28px;      line-height: 1.4;    }
</style>
