<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="本書の概要と対象読者" :current-page="2" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="slide-header"><h1 class="title">本書の概要と対象読者</h1><div class="accent-line"></div></div><div class="content-section"><ul class="bullet-list"><li><span class="bullet-category">概要：</span> 悪い同調圧力→よい同調圧力への転換で「全員総活躍」を実現する実践書</li><li><span class="bullet-category">背景：</span> 30年超・1500人規模の組織での実証と学び<p class="sub-bullet">SOMPOグループでの実践から生まれた、組織変革の具体的メソッド</p></li><li><span class="bullet-category">対象読者：</span> 経営者/管理職/人事/現場リーダー/個人<p class="sub-bullet">組織文化の変革や個人のやる気を引き出したいすべての方</p></li><li><span class="bullet-category">得られる変化：</span> 心理的安全性・自発性・現場主導・学習する組織の実現<p class="sub-bullet">「やっちゃだめ」から「やっていい」への転換で、組織全体の活力が向上</p></li></ul></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;      color: #333;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 60px;    }    .slide-header {      margin-bottom: 40px;    }    .title {      font-size: 36px;      font-weight: 700;      color: #1a365d;      margin-bottom: 16px;    }    .accent-line {      width: 80px;      height: 4px;      background-color: #60a5fa;      margin-bottom: 40px;    }    .content-section {      flex: 1;    }    .bullet-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .bullet-list li {      position: relative;      padding-left: 28px;      margin-bottom: 24px;      font-size: 24px;      line-height: 1.5;    }    .bullet-list li:before {      content: "";      position: absolute;      left: 0;      top: 12px;      width: 10px;      height: 10px;      background-color: #60a5fa;      border-radius: 50%;    }    .bullet-category {      font-weight: 700;      color: #1a365d;    }    .sub-bullet {      font-size: 20px;      margin-top: 8px;      margin-left: 28px;      line-height: 1.4;    }
</style>
