<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="締め（Next Action）" :current-page="20" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><h1 class="title">締め（Next Action）</h1><div class="accent-line"></div><div class="key-message"><p>"やっていい"の同調圧力が人と組織を動かす</p></div><div class="steps-section"><h2 class="steps-title"><i class="fas fa-forward"></i><p>明日からの3ステップ</p></h2><div class="steps-container"><div class="step"><div class="step-number">1</div><h3 class="step-title">お守りワードを決める</h3><div class="step-content"><p>あなたとチームの"やっていい"を体現する言葉を明確にし、繰り返し発信する。あなたの指針となる言葉は何か？</p></div></div><div class="step"><div class="step-number">2</div><h3 class="step-title">MYパーパスを書く</h3><div class="step-content"><p>WANT（内発的動機）、MUST（社会的責務）、CAN（保有能力）の3要素から自分の存在意義を言語化する</p></div></div><div class="step"><div class="step-number">3</div><h3 class="step-title">小さな表彰の場を作る</h3><div class="step-content"><p>チャレンジ賞やMVP制度など、挑戦を称える仕組みやパブリックコメントの場を設計する</p></div></div></div></div><div class="action-declaration"><h2 class="action-title"><i class="fas fa-pen"></i><p>行動宣言：今日、何を始める？</p></h2><div class="action-field"><p>あなたの"やっていい"宣言をここに書き込んでください...</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: #f0f4f8;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 50px;    }    .title {      font-size: 38px;      font-weight: 900;      color: #1a365d;      margin-bottom: 16px;    }    .key-message {      font-size: 32px;      font-weight: 700;      color: #2563eb;      margin-bottom: 30px;      line-height: 1.4;      padding: 16px;      border-left: 6px solid #2563eb;      background-color: white;      border-radius: 0 8px 8px 0;    }    .steps-section {      margin: 20px 0 40px 0;    }    .steps-title {      font-size: 24px;      font-weight: 700;      color: #1a365d;      margin-bottom: 20px;      display: flex;      align-items: center;    }    .steps-title i {      margin-right: 12px;      color: #2563eb;    }    .steps-container {      display: flex;      justify-content: space-between;      gap: 20px;    }    .step {      flex: 1;      background-color: white;      padding: 24px;      border-radius: 12px;      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.05);      position: relative;    }    .step-number {      position: absolute;      top: -15px;      left: -15px;      width: 40px;      height: 40px;      background-color: #2563eb;      border-radius: 50%;      color: white;      font-size: 20px;      font-weight: 700;      display: flex;      align-items: center;      justify-content: center;    }    .step-title {      font-size: 20px;      font-weight: 700;      color: #1a365d;      margin-bottom: 12px;      padding-left: 10px;    }    .step-content {      font-size: 16px;      color: #4a5568;      line-height: 1.6;    }    .action-declaration {      background-color: white;      border-radius: 12px;      padding: 24px;      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.05);      margin-top: 10px;      border-top: 4px solid #2f855a;    }    .action-title {      font-size: 22px;      font-weight: 700;      color: #2f855a;      margin-bottom: 16px;      display: flex;      align-items: center;    }    .action-title i {      margin-right: 12px;    }    .action-field {      background-color: #f8fafc;      border: 2px dashed #cbd5e0;      border-radius: 8px;      padding: 16px;      min-height: 80px;      font-size: 18px;      color: #718096;      display: flex;      align-items: center;      justify-content: center;    }    .accent-line {      width: 100px;      height: 4px;      background-color: #2563eb;      margin-bottom: 30px;    }
</style>
