<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="全体像と目次" :current-page="3" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="slide-header"><h1 class="title">全体像と目次</h1><div class="accent-line"></div></div><div class="content-section"><div class="left-column"><h2 class="column-title">章構成</h2><ul class="chapter-list"><li data-number="1"><p>なぜ全員総活躍が可能か</p></li><li data-number="2"><p>お守りワードをつくる</p></li><li data-number="3"><p>実感をつくる</p></li><li data-number="4"><p>イベントで加速</p></li><li data-number="5"><p>8つの心がまえで浸透</p></li></ul></div><div class="right-column"><h2 class="column-title">8つの課題 → 8つの方法（心がまえ）</h2><div class="transformation-container"><div class="transformation-item"><div class="transform-from"><p>トップダウン</p></div><div class="transform-arrow"><i class="fas fa-long-arrow-alt-right"></i></div><div class="transform-to"><p>ボトムアップ</p></div></div><div class="transformation-item"><div class="transform-from"><p>本社が主役</p></div><div class="transform-arrow"><i class="fas fa-long-arrow-alt-right"></i></div><div class="transform-to"><p>現場が主役</p></div></div><div class="transformation-item"><div class="transform-from"><p>クローズ文化</p></div><div class="transform-arrow"><i class="fas fa-long-arrow-alt-right"></i></div><div class="transform-to"><p>オープン文化</p></div></div><div class="transformation-item"><div class="transform-from"><p>PDCA（計画）文化</p></div><div class="transform-arrow"><i class="fas fa-long-arrow-alt-right"></i></div><div class="transform-to"><p>OODA（実験）文化</p></div></div><div class="transformation-item"><div class="transform-from"><p>管理の文化</p></div><div class="transform-arrow"><i class="fas fa-long-arrow-alt-right"></i></div><div class="transform-to"><p>自発の文化</p></div></div><div class="transformation-item"><div class="transform-from"><p>評価偏重</p></div><div class="transform-arrow"><i class="fas fa-long-arrow-alt-right"></i></div><div class="transform-to"><p>評価→評判</p></div></div><div class="transformation-item"><div class="transform-from"><p>KPI文化</p></div><div class="transform-arrow"><i class="fas fa-long-arrow-alt-right"></i></div><div class="transform-to"><p>P/L（KGI）文化</p></div></div><div class="transformation-item"><div class="transform-from"><p>恐れの文化</p></div><div class="transform-arrow"><i class="fas fa-long-arrow-alt-right"></i></div><div class="transform-to"><p>赦しの文化</p></div></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;      color: #333;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 40px;    }    .slide-header {      margin-bottom: 30px;    }    .title {      font-size: 36px;      font-weight: 700;      color: #1a365d;      margin-bottom: 16px;    }    .accent-line {      width: 80px;      height: 4px;      background-color: #60a5fa;      margin-bottom: 30px;    }    .content-section {      flex: 1;      display: flex;      gap: 40px;    }    .left-column, .right-column {      flex: 1;    }    .chapter-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .chapter-list li {      position: relative;      padding: 15px 0 15px 40px;      font-size: 22px;      line-height: 1.4;      border-left: 3px solid #60a5fa;      margin-bottom: 15px;    }    .chapter-list li::before {      content: attr(data-number);      position: absolute;      left: -15px;      top: 50%;      transform: translateY(-50%);      width: 30px;      height: 30px;      background-color: #60a5fa;      border-radius: 50%;      display: flex;      align-items: center;      justify-content: center;      color: white;      font-weight: 700;    }    .column-title {      font-size: 24px;      font-weight: 700;      color: #1a365d;      margin-bottom: 20px;      text-align: center;    }    .transformation-container {      display: flex;      flex-direction: column;      gap: 10px;    }    .transformation-item {      display: flex;      align-items: center;      margin-bottom: 10px;    }    .transform-from, .transform-to {      flex: 1;      padding: 10px;      border-radius: 6px;      font-size: 16px;      font-weight: 500;      text-align: center;    }    .transform-from {      background-color: #fee2e2;      color: #7f1d1d;    }    .transform-to {      background-color: #dcfce7;      color: #14532d;    }    .transform-arrow {      padding: 0 15px;      color: #60a5fa;      font-size: 20px;    }
</style>
