<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="なぜ今「やっていい」が必要なのか" :current-page="4" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><h1 class="headline">なぜ今<span class="headline-accent">「やっていい」</span>が<br/>必要なのか</h1><div class="accent-line"></div><div class="key-points"><div class="point-item"><div class="point-icon"><i class="fas fa-exclamation-triangle"></i></div><div class="point-content"><h2 class="point-title">日本企業の停滞要因</h2><p class="point-description">管理偏重・硬直化した組織構造・発言できない風土が、<br/>イノベーションと成長の妨げになっている</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-users"></i></div><div class="point-content"><h2 class="point-title">2:6:2の法則の打破</h2><p class="point-description">組織の中間層6割を動かすには、<br/>「やっちゃだめ」から「やっていい」への空気の転換が鍵</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-handshake"></i></div><div class="point-content"><h2 class="point-title">信頼が個の才能を引き出す</h2><p class="point-description">言語化（お守りワード）と仕掛け（イベント・表彰）で<br/>信頼関係を構築し、個々の能力を最大限に引き出す</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: #f0f4f8;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 60px;    }    .headline {      font-size: 48px;      font-weight: 900;      color: #1a365d;      margin-bottom: 20px;      line-height: 1.2;    }    .headline-accent {      color: #2563eb;    }    .subtitle {      font-size: 24px;      font-weight: 500;      color: #4a5568;      margin-bottom: 50px;    }    .accent-line {      width: 100px;      height: 6px;      background-color: #2563eb;      margin-bottom: 50px;    }    .key-points {      display: flex;      flex-direction: column;      gap: 30px;      margin-top: 30px;    }    .point-item {      display: flex;      align-items: flex-start;      gap: 20px;    }    .point-icon {      background-color: #2563eb;      color: white;      width: 60px;      height: 60px;      border-radius: 50%;      display: flex;      align-items: center;      justify-content: center;      font-size: 24px;      flex-shrink: 0;    }    .point-content {      flex: 1;    }    .point-title {      font-size: 24px;      font-weight: 700;      color: #1a365d;      margin-bottom: 8px;    }    .point-description {      font-size: 18px;      color: #4a5568;      line-height: 1.5;    }
</style>
