<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="8つの課題（As-Is）" :current-page="5" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="slide-header"><h1 class="title">8つの課題（As-Is）</h1><div class="accent-line"></div></div><div class="content-section"><div class="left-column"><ul class="bullet-list"><li><span class="bullet-category">トップダウン</span><span class="sub-bullet">現場の意見より上からの指示が優先される組織構造</span></li><li><span class="bullet-category">本社が主役</span><span class="sub-bullet">現場ではなく本社中心の意思決定・運営</span></li><li><span class="bullet-category">クローズ文化</span><span class="sub-bullet">情報や会議が限られた人だけに共有される</span></li><li><span class="bullet-category">PDCA（計画）文化</span><span class="sub-bullet">計画重視で実行前の準備に時間をかけすぎる</span></li></ul></div><div class="right-column"><ul class="bullet-list"><li><span class="bullet-category">管理の文化</span><span class="sub-bullet">自発性より監視・統制が重視される運営</span></li><li><span class="bullet-category">評価偏重</span><span class="sub-bullet">数値評価に基づく格付けが行動を縛る</span></li><li><span class="bullet-category">KPI文化</span><span class="sub-bullet">成果全体より部分的な指標達成が優先される</span></li><li><span class="bullet-category">恐れの文化</span><span class="sub-bullet">失敗を恐れて新しい挑戦が抑制される風土</span></li></ul></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;      color: #333;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 60px;    }    .slide-header {      margin-bottom: 40px;    }    .title {      font-size: 36px;      font-weight: 700;      color: #1a365d;      margin-bottom: 16px;    }    .accent-line {      width: 80px;      height: 4px;      background-color: #60a5fa;      margin-bottom: 40px;    }    .content-section {      flex: 1;      display: flex;    }    .left-column, .right-column {      flex: 1;    }    .left-column {      margin-right: 30px;    }    .bullet-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .bullet-list li {      position: relative;      padding-left: 28px;      margin-bottom: 24px;      font-size: 24px;      line-height: 1.4;    }    .bullet-list li:before {      content: "";      position: absolute;      left: 0;      top: 12px;      width: 10px;      height: 10px;      background-color: #60a5fa;      border-radius: 50%;    }    .bullet-category {      font-weight: 700;      color: #1a365d;    }    .sub-bullet {      font-size: 18px;      margin-top: 6px;      line-height: 1.4;      color: #555;      display: block;    }
</style>
