<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="お守りワードとは" :current-page="6" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><h1 class="headline"><span class="headline-accent">お守りワード</span>とは</h1><div class="accent-line"></div><div class="key-points"><div class="point-item"><div class="point-icon"><i class="fas fa-shield-alt"></i></div><div class="point-content"><h2 class="point-title">「やっていい」を体現する合言葉</h2><p class="point-description">組織やチームが向かうべき方向性を示し、<br/>「やっていい」を実感させる指針となる言葉</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-bullhorn"></i></div><div class="point-content"><h2 class="point-title">多面的・継続的な発信が鍵</h2><p class="point-description">まずは自分を支える言葉として作り、<br/>面談・SNS・動画・朝礼などあらゆる手段で繰り返し伝える</p></div></div><div class="point-item"><div class="point-icon"><i class="fas fa-award"></i></div><div class="point-content"><h2 class="point-title">小さな成功の共有と称賛</h2><p class="point-description">「お守りワード」に沿った小さな成功事例を見つけ、<br/>褒め、共有することで実感と文化が醸成される</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: #f0f4f8;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 60px;    }    .headline {      font-size: 48px;      font-weight: 900;      color: #1a365d;      margin-bottom: 20px;      line-height: 1.2;    }    .headline-accent {      color: #2563eb;    }    .subtitle {      font-size: 24px;      font-weight: 500;      color: #4a5568;      margin-bottom: 50px;    }    .accent-line {      width: 100px;      height: 6px;      background-color: #2563eb;      margin-bottom: 50px;    }    .key-points {      display: flex;      flex-direction: column;      gap: 30px;      margin-top: 30px;    }    .point-item {      display: flex;      align-items: flex-start;      gap: 20px;    }    .point-icon {      background-color: #2563eb;      color: white;      width: 60px;      height: 60px;      border-radius: 50%;      display: flex;      align-items: center;      justify-content: center;      font-size: 24px;      flex-shrink: 0;    }    .point-content {      flex: 1;    }    .point-title {      font-size: 24px;      font-weight: 700;      color: #1a365d;      margin-bottom: 8px;    }    .point-description {      font-size: 18px;      color: #4a5568;      line-height: 1.5;    }
</style>
