<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="MYパーパスの作成（WANT/MUST/CAN）" :current-page="7" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="slide-header"><h1 class="title">MYパーパスの作成（WANT/MUST/CAN）</h1><div class="accent-line"></div></div><div class="content-section"><div class="framework-column"><ul class="bullet-list"><li><span class="bullet-category">WANT（内発的動機）：</span> 心がポジティブに動いた理由・体験<p class="sub-bullet">「自分がワクワクする」「楽しい」「やりがいを感じる」瞬間から価値観を発見</p></li><li><span class="bullet-category">MUST（社会的責務）：</span> 憤りや悔しさの源・使命<p class="sub-bullet">「悔しい」「怒り」「悲しい」といったネガティブな感情から社会的責務を発見</p></li><li><span class="bullet-category">CAN（保有能力）：</span> 成功/修羅場で得た力・強み<p class="sub-bullet">困難を乗り越えた体験や成功体験から、自分の強みや能力を言語化</p></li><li><span class="bullet-category">統合：</span> 3要素をつなげてMYパーパスを文章化<p class="sub-bullet">自分らしさを表現するキャッチコピーを添えて完成させる</p></li></ul></div><div class="example-column"><p class="example-title">【例】</p><p class="example-content"><strong>WANT：</strong> 仲間が活躍する場をつくるのが好き</p><p class="example-content"><strong>MUST：</strong> すべての人が尊重され活躍できる社会であるべき</p><p class="example-content"><strong>CAN：</strong> 人の個性を見極め、活躍の場をつくる力</p><div class="arrow-down">↓</div><div class="purpose-statement">「自分がいることで周囲の人が幸せになる」</div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;      color: #333;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 60px;    }    .slide-header {      margin-bottom: 40px;    }    .title {      font-size: 36px;      font-weight: 700;      color: #1a365d;      margin-bottom: 16px;    }    .accent-line {      width: 80px;      height: 4px;      background-color: #60a5fa;      margin-bottom: 40px;    }    .content-section {      flex: 1;      display: flex;    }    .framework-column {      flex: 2;    }    .example-column {      flex: 1;      margin-left: 40px;      background-color: #f0f9ff;      border-radius: 8px;      padding: 20px;    }    .bullet-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .bullet-list li {      position: relative;      padding-left: 28px;      margin-bottom: 24px;      font-size: 24px;      line-height: 1.5;    }    .bullet-list li:before {      content: "";      position: absolute;      left: 0;      top: 12px;      width: 10px;      height: 10px;      background-color: #60a5fa;      border-radius: 50%;    }    .bullet-category {      font-weight: 700;      color: #1a365d;    }    .sub-bullet {      font-size: 20px;      margin-top: 8px;      margin-left: 28px;      line-height: 1.4;    }    .example-title {      font-weight: 700;      font-size: 22px;      color: #1a365d;      margin-bottom: 16px;    }    .example-content {      font-size: 20px;      line-height: 1.5;    }    .arrow-down {      text-align: center;      font-size: 24px;      color: #60a5fa;      margin: 12px 0;    }    .purpose-statement {      background-color: #1a365d;      color: white;      padding: 12px 16px;      border-radius: 6px;      font-size: 22px;      font-weight: 500;      margin-top: 16px;      text-align: center;    }
</style>
