<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="お守りワードで実感を作る" :current-page="8" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="slide-header"><h1 class="title">お守りワードで"実感"を作る</h1><div class="accent-line"></div></div><div class="content-section"><ul class="bullet-list"><li><span class="bullet-category">全員面談・トップ発信：</span><p class="sub-bullet">社員全員との対話やリーダーから繰り返し発信することで浸透を図る</p></li><li><span class="bullet-category">多面的な"見える化"：</span><p class="sub-bullet">社内SNS、動画配信、朝礼など様々なメディアで「お守りワード」を可視化</p></li><li><span class="bullet-category">MYパーパスの共有：</span><p class="sub-bullet">ワークショップで各自のMYパーパスを宣言し、共有の場を設ける</p></li><li><span class="bullet-category">エピソードとの結合：</span><p class="sub-bullet">具体的なストーリーと結び付けることで記憶に残りやすくする</p></li><li><span class="bullet-category">定着サイクル：</span><p class="sub-bullet">発信→体験→称賛→再発信のサイクルを回し続けることで文化として根付く</p></li></ul></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;      color: #333;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 60px;    }    .slide-header {      margin-bottom: 40px;    }    .title {      font-size: 36px;      font-weight: 700;      color: #1a365d;      margin-bottom: 16px;    }    .accent-line {      width: 80px;      height: 4px;      background-color: #60a5fa;      margin-bottom: 40px;    }    .content-section {      flex: 1;    }    .bullet-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .bullet-list li {      position: relative;      padding-left: 28px;      margin-bottom: 24px;      font-size: 24px;      line-height: 1.5;    }    .bullet-list li:before {      content: "";      position: absolute;      left: 0;      top: 12px;      width: 10px;      height: 10px;      background-color: #60a5fa;      border-radius: 50%;    }    .bullet-category {      font-weight: 700;      color: #1a365d;    }    .sub-bullet {      font-size: 20px;      margin-top: 8px;      margin-left: 28px;      line-height: 1.4;    }
</style>
