<template>
  <SlidePageWrapper slide-id="B0FCDSJ9ZL" page-title="イベントで加速する" :current-page="9" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="slide-header"><h1 class="title">"やっていい"を加速するイベント</h1><div class="accent-line"></div></div><div class="content-section"><ul class="bullet-list"><li><span class="bullet-category">表彰：</span> 社長賞/チャレンジ賞/月間MVP など<p class="sub-bullet">失敗も含めた挑戦を称える、申請簡便で敷居が低い表彰制度</p></li><li><span class="bullet-category">参加型：</span> ハッカソン/公開PT/パブリックコメント<p class="sub-bullet">誰でも自由参加できるボトムアップ型の意思決定・制度設計の場</p></li><li><span class="bullet-category">会議のオープン化：</span> オブザーブ参加拡大<p class="sub-bullet">経営会議等を全職員に開放し、意思決定プロセスを透明化</p></li><li><span class="bullet-category">称賛の可視化：</span> サンクスカード/社内SNS<p class="sub-bullet">小さなチャレンジや成功を日常的に共有・称賛する仕組み</p></li></ul></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {      font-family: 'Noto Sans JP', sans-serif;      margin: 0;      padding: 0;    }    .slide-container {      width: 1280px;      min-height: 720px;      display: flex;      overflow: hidden;      background-color: white;      color: #333;    }    .content-wrapper {      flex: 1;      display: flex;      flex-direction: column;      padding: 60px;    }    .slide-header {      margin-bottom: 40px;    }    .title {      font-size: 36px;      font-weight: 700;      color: #1a365d;      margin-bottom: 16px;    }    .accent-line {      width: 80px;      height: 4px;      background-color: #60a5fa;      margin-bottom: 40px;    }    .content-section {      flex: 1;    }    .bullet-list {      list-style-type: none;      padding: 0;      margin: 0;    }    .bullet-list li {      position: relative;      padding-left: 28px;      margin-bottom: 24px;      font-size: 24px;      line-height: 1.5;    }    .bullet-list li:before {      content: "";      position: absolute;      left: 0;      top: 12px;      width: 10px;      height: 10px;      background-color: #60a5fa;      border-radius: 50%;    }    .bullet-category {      font-weight: 700;      color: #1a365d;    }    .sub-bullet {      font-size: 20px;      margin-top: 8px;      margin-left: 28px;      line-height: 1.4;    }
</style>
