<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="アクティブラーニング 学校教育の理想と現実" :current-page="1" :total-pages="20">
<div class="slide-container"><div class="book-cover"></div><div class="content"><div class="title-box"><h1 class="text-5xl font-bold mb-6">アクティブラーニング</h1><h2 class="text-4xl font-bold mb-8">学校教育の理想と現実</h2><p class="text-2xl text-gray-600 mb-6">2020年教育改革の先はバラ色の未来なのか？</p><p class="text-xl text-gray-600">学力は向上するのか？学力格差はどうなるのか？</p><p class="text-xl text-gray-600">学校や教師の負担は？新しい大学入試は？</p></div></div><div class="footer"><p class="text-2xl font-medium mb-1">小針 誠</p><p class="text-lg text-gray-600">講談社現代新書</p></div><div class="accent-line"></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            font-family: 'Noto Sans JP', sans-serif;            margin: 0;            padding: 0;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            flex-direction: column;            background-color: #f8f9fa;            color: #333;            position: relative;            overflow: hidden;        }        .book-cover {            position: absolute;            top: 0;            right: 0;            width: 420px;            height: 720px;            background-color: #2c3e50;        }        .content {            flex: 1;            display: flex;            flex-direction: column;            justify-content: center;            padding: 60px;            padding-right: 440px;            z-index: 10;        }        .title-box {            border-left: 8px solid #2c3e50;            padding-left: 20px;            margin-bottom: 40px;        }        .footer {            position: absolute;            bottom: 0;            left: 0;            width: 100%;            padding: 30px 60px;            z-index: 10;        }        .accent-line {            position: absolute;            bottom: 0;            left: 0;            height: 12px;            width: 100%;            background-color: #3498db;        }
</style>
