<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="第4章(1) 平成教育史：新しい学力観と生きる力" :current-page="10" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">第4章(1) 平成教育史：新しい学力観と生きる力</h1><div class="accent-line"></div></div><div class="content"><div class="main-content"><div class="left-column"><div class="definition-box"><p class="text-xl font-medium mb-2"><i class="fas fa-clipboard-list text-blue-500 mr-2"></i>新しい学力観</p><p class="ml-6">知識・技能の習得に加え、思考力・判断力・表現力および関心・意欲・態度を重視する学力概念</p></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-history text-blue-500 mr-2"></i>平成教育改革の流れ</p><div class="ml-6"><div class="timeline-point"><div class="timeline-year">1989年</div><div class="timeline-content"><p>新学習指導要領（新しい学力観の導入）</p></div></div><div class="timeline-point"><div class="timeline-year">1992年</div><div class="timeline-content"><p>「生活科」新設（小学校低学年の社会科・理科を統合）</p></div></div><div class="timeline-point"><div class="timeline-year">1996年</div><div class="timeline-content"><p>中教審「生きる力」提言</p></div></div><div class="timeline-point"><div class="timeline-year">1998年</div><div class="timeline-content"><p>学習指導要領改訂（「ゆとり」と「生きる力」）</p></div></div></div></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-clipboard-check text-blue-500 mr-2"></i>観点別評価の導入</p><ul class="custom-list"><li><p>「関心・意欲・態度」「思考・判断」「技能・表現」「知識・理解」の4観点</p></li><li><p>学習プロセスと態度の評価重視</p></li><li><p>多面的な学力評価への転換</p></li></ul></div></div><div class="right-column"><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-seedling text-green-600 mr-2"></i>「生きる力」の理念</p><ul class="custom-list"><li><p>確かな学力</p></li><li><p>豊かな人間性</p></li><li><p>健康・体力</p></li><li><p>変化に対応する能力</p></li><li><p>自己実現・社会参画力</p></li></ul></div><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-chalkboard-teacher text-yellow-500 mr-2"></i>生活科の特徴</p><ul class="custom-list"><li><p>体験的・活動的な学習</p></li><li><p>児童の興味・関心を重視</p></li><li><p>教科の枠を超えた合科的指導</p></li></ul></div><div class="key-point"><p class="text-lg font-medium mb-2"><i class="fas fa-exclamation-triangle text-red-500 mr-2"></i>課題と批判</p><ul class="custom-list"><li><p>基礎学力の確実な保障への懸念</p></li><li><p>観点別評価の運用負担の増加</p></li><li><p>「生きる力」概念の抽象性と検証難</p></li><li><p>家庭環境による格差拡大の懸念</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        font-family: 'Noto Sans JP', sans-serif;        margin: 0;        padding: 0;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f8f9fa;        color: #333;        position: relative;        overflow: hidden;    }    .header {        background-color: #2c3e50;        color: white;        padding: 20px 60px;        position: relative;    }    .content {        flex: 1;        display: flex;        flex-direction: column;        padding: 30px 60px;        z-index: 10;    }    .main-content {        display: flex;        flex: 1;    }    .left-column {        flex: 3;        padding-right: 30px;    }    .right-column {        flex: 2;        display: flex;        flex-direction: column;    }    .info-box {        background-color: #edf2f7;        border-radius: 8px;        padding: 20px;        margin-bottom: 20px;        border-left: 4px solid #3498db;    }    .key-point {        background-color: #ebf8ff;        border-left: 4px solid #2b6cb0;        padding: 15px;        margin-top: 20px;        border-radius: 0 8px 8px 0;    }    .accent-line {        position: absolute;        bottom: 0;        left: 0;        height: 8px;        width: 100%;        background-color: #3498db;    }    .definition-box {        background-color: #f0f4f8;        border: 1px solid #cbd5e0;        border-radius: 8px;        padding: 15px;        margin-bottom: 20px;    }    ul.custom-list {        list-style-type: none;        padding-left: 0;    }    ul.custom-list li {        position: relative;        padding-left: 25px;        margin-bottom: 12px;    }    ul.custom-list li:before {        content: "";        position: absolute;        left: 0;        top: 10px;        width: 8px;        height: 8px;        background-color: #3498db;        border-radius: 50%;    }    .timeline-point {        display: flex;        margin-bottom: 15px;    }    .timeline-year {        min-width: 80px;        font-weight: 500;        color: #2c3e50;    }    .timeline-content {        flex: 1;    }
</style>
