<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="第4章(2) 総合的な学習の時間とPISAショック" :current-page="11" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">第4章(2) 総合的な学習の時間とPISAショック</h1><div class="accent-line"></div></div><div class="content"><div class="main-content"><div class="left-column"><div class="definition-box"><p class="text-xl font-medium mb-2"><i class="fas fa-book-open text-blue-500 mr-2"></i>総合的な学習の時間</p><p class="ml-6">1998年の学習指導要領改訂で新設された、教科横断的・探究的な学習の時間</p></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-search text-blue-500 mr-2"></i>総合学習の特徴</p><ul class="custom-list"><li><p>探究活動：児童・生徒の興味関心に基づく課題解決学習</p></li><li><p>教科横断的：複数の教科にまたがるテーマ設定</p></li><li><p>地域連携：地域の人材・素材を活用した学習</p></li><li><p>体験重視：実体験を通じた学びの促進</p></li></ul></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-chart-line text-blue-500 mr-2"></i>PISAショックとは</p><div class="timeline-box"><div class="timeline-item"><p class="font-medium">2000年〜2003年</p><p>OECD・PISA調査で日本の読解力・応用力低下が判明</p></div><div class="timeline-item"><p class="font-medium">2003年〜2007年</p><p>「脱ゆとり」「確かな学力」への政策転換</p></div><div class="timeline-item"><p class="font-medium">2008年〜</p><p>学習指導要領改訂で授業時数増加と学力向上重視</p></div></div></div></div><div class="right-column"><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-comments text-yellow-500 mr-2"></i>現場の声</p><ul class="custom-list"><li><p>準備・運営の負担が大きい</p></li><li><p>成果の可視化・評価が困難</p></li><li><p>基礎学力との両立に苦慮</p></li><li><p>教科書がなく指導に不安</p></li></ul><p class="mt-2 text-sm text-gray-600">※全国の教員アンケート結果より</p></div><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-sync-alt text-green-600 mr-2"></i>振り子の揺り戻し</p><p>探究・体験 → 知識・技能の基礎固め → アクティブラーニング再注目</p><p class="mt-2">総合的な学習の時間の縮減（2008年）と再評価（2017年〜）</p></div><div class="key-point"><p class="text-lg font-medium mb-2"><i class="fas fa-lightbulb text-red-500 mr-2"></i>重要な示唆</p><ul class="custom-list"><li><p>基礎と探究は対立軸ではなく相補的</p></li><li><p>教師の裁量・負担への配慮が不可欠</p></li><li><p>教育政策の「振り子」が現場を翻弄</p></li><li><p>PDCAサイクルを伴わない改革の危険性</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        font-family: 'Noto Sans JP', sans-serif;        margin: 0;        padding: 0;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f8f9fa;        color: #333;        position: relative;        overflow: hidden;    }    .header {        background-color: #2c3e50;        color: white;        padding: 20px 60px;        position: relative;    }    .content {        flex: 1;        display: flex;        flex-direction: column;        padding: 30px 60px;        z-index: 10;    }    .main-content {        display: flex;        flex: 1;    }    .left-column {        flex: 3;        padding-right: 30px;    }    .right-column {        flex: 2;        display: flex;        flex-direction: column;    }    .info-box {        background-color: #edf2f7;        border-radius: 8px;        padding: 20px;        margin-bottom: 20px;        border-left: 4px solid #3498db;    }    .key-point {        background-color: #ebf8ff;        border-left: 4px solid #2b6cb0;        padding: 15px;        margin-top: 20px;        border-radius: 0 8px 8px 0;    }    .accent-line {        position: absolute;        bottom: 0;        left: 0;        height: 8px;        width: 100%;        background-color: #3498db;    }    .definition-box {        background-color: #f0f4f8;        border: 1px solid #cbd5e0;        border-radius: 8px;        padding: 15px;        margin-bottom: 20px;    }    ul.custom-list {        list-style-type: none;        padding-left: 0;    }    ul.custom-list li {        position: relative;        padding-left: 25px;        margin-bottom: 12px;    }    ul.custom-list li:before {        content: "";        position: absolute;        left: 0;        top: 10px;        width: 8px;        height: 8px;        background-color: #3498db;        border-radius: 50%;    }    .timeline-box {        background-color: #f8f9fa;        border: 1px solid #e2e8f0;        border-radius: 8px;        padding: 15px;        margin-bottom: 20px;    }    .timeline-item {        padding-left: 25px;        position: relative;        margin-bottom: 10px;    }    .timeline-item:before {        content: "";        position: absolute;        left: 0;        top: 10px;        width: 10px;        height: 10px;        background-color: #4299e1;        border-radius: 50%;    }    .timeline-item:after {        content: "";        position: absolute;        left: 5px;        top: 20px;        width: 2px;        height: calc(100% + 10px);        background-color: #a0aec0;    }    .timeline-item:last-child:after {        display: none;    }
</style>
