<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="第5章(2) 実践上の課題" :current-page="13" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">第5章(2) 実践上の課題（教室で実践できるのか）</h1><div class="accent-line"></div></div><div class="content"><div class="main-content"><div class="left-column"><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-school text-blue-500 mr-2"></i>クラスサイズ・時間割・評価負荷</p><ul class="custom-list"><li><p>日本の一般的な学級規模（30〜40人）でのAL実践の困難性</p></li><li><p>50分授業枠での「主体的・対話的で深い学び」の時間的制約</p></li><li><p>教員の評価業務負担増（観察・記録・フィードバック・評価の複雑化）</p></li></ul></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-users-cog text-blue-500 mr-2"></i>多様な学力・意欲・言語背景への支援設計</p><ul class="custom-list"><li><p>基礎学力に差がある集団での討論・探究活動の難しさ</p></li><li><p>学習意欲の低い生徒・消極的な生徒への働きかけと参加保障</p></li><li><p>文化的・言語的背景の多様化への対応（外国籍児童・発達特性等）</p></li><li><p>格差拡大のリスク：意欲・学力の高い層と低い層の二極化</p></li></ul></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-chalkboard-teacher text-blue-500 mr-2"></i>授業スキル：教師の専門性</p><ul class="custom-list"><li><p>「問いの質」設計と段階的な思考促進のファシリテーション</p></li><li><p>対話・グループ活動の構造化と形骸化防止</p></li><li><p>メタ認知（振り返り・思考の可視化）指導の専門性</p></li><li><p>教員養成・研修体制の不足と現場での孤立</p></li></ul></div></div><div class="right-column"><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-search text-purple-600 mr-2"></i>学びの見取り</p><p>プロセス評価と成果評価の整合性</p><ul class="custom-list mt-3"><li><p>発言・活動の質を可視化する評価手法</p></li><li><p>思考過程を評価できるルーブリック開発</p></li><li><p>一斉テストと活動評価のバランス</p></li></ul></div><div class="challenge-box"><p class="text-lg font-medium mb-2"><i class="fas fa-exclamation-circle text-red-600 mr-2"></i>歴史的に繰り返された問題</p><p>成城小学校ドルトン・プランでも:</p><ul class="custom-list mt-3"><li><p>意欲ある子どもと消極的な子どもの格差拡大</p></li><li><p>教員の支援不足と負担増大</p></li><li><p>形式的な自主活動への形骸化</p></li></ul></div><div class="key-point"><p class="text-lg font-medium mb-2"><i class="fas fa-lightbulb text-yellow-500 mr-2"></i>対応の方向性</p><ul class="custom-list"><li><p>小グループ編成・ティームティーチング</p></li><li><p>基礎と探究の二段構造設計</p></li><li><p>デジタル技術活用による個別化支援</p></li><li><p>段階的導入と検証による修正</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        font-family: 'Noto Sans JP', sans-serif;        margin: 0;        padding: 0;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f8f9fa;        color: #333;        position: relative;        overflow: hidden;    }    .header {        background-color: #2c3e50;        color: white;        padding: 20px 60px;        position: relative;    }    .content {        flex: 1;        display: flex;        flex-direction: column;        padding: 30px 60px;        z-index: 10;    }    .main-content {        display: flex;        flex: 1;    }    .left-column {        flex: 3;        padding-right: 30px;    }    .right-column {        flex: 2;        display: flex;        flex-direction: column;    }    .info-box {        background-color: #edf2f7;        border-radius: 8px;        padding: 20px;        margin-bottom: 20px;        border-left: 4px solid #3498db;    }    .key-point {        background-color: #ebf8ff;        border-left: 4px solid #2b6cb0;        padding: 15px;        margin-top: 20px;        border-radius: 0 8px 8px 0;    }    .accent-line {        position: absolute;        bottom: 0;        left: 0;        height: 8px;        width: 100%;        background-color: #3498db;    }    .definition-box {        background-color: #f0f4f8;        border: 1px solid #cbd5e0;        border-radius: 8px;        padding: 15px;        margin-bottom: 20px;    }    ul.custom-list {        list-style-type: none;        padding-left: 0;    }    ul.custom-list li {        position: relative;        padding-left: 25px;        margin-bottom: 12px;    }    ul.custom-list li:before {        content: "";        position: absolute;        left: 0;        top: 10px;        width: 8px;        height: 8px;        background-color: #3498db;        border-radius: 50%;    }    .challenge-box {        background-color: #fff5f5;        border-left: 4px solid #e53e3e;        padding: 15px;        margin-top: 20px;        border-radius: 0 8px 8px 0;    }
</style>
