<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="第5章(3) 運用上・倫理上の課題" :current-page="14" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">第5章(3) 運用上・倫理上の課題</h1><div class="accent-line"></div></div><div class="content"><div class="main-content"><div class="left-column"><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-cogs text-blue-500 mr-2"></i>運用上の課題</p><ul class="custom-list"><li><p>一律導入のリスク：学校・地域・児童生徒の多様性を無視</p></li><li><p>形式主義化：「見た目」のアクティブ化に終始</p></li><li><p>チェックリスト化：本質より形式に集中し、創造性を阻害</p></li><li><p>カリキュラム・マネジメントの複雑化：教員の業務負担増加</p></li><li><p>評価の困難：プロセスと成果の不一致、公平性の担保</p></li></ul></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-balance-scale text-blue-500 mr-2"></i>倫理上の課題</p><ul class="custom-list"><li><p>主体性の"強制"：矛盾する「やらされる主体性」</p></li><li><p>全体主義的逸脱：集団圧力による批判精神の抑制リスク</p></li><li><p>公平性の懸念：家庭背景・基礎学力による格差拡大</p></li><li><p>インクルージョンの課題：沈黙する学習者、多様な認知特性への配慮</p></li></ul></div><div class="warning-box"><p class="text-lg font-medium mb-2"><i class="fas fa-exclamation-triangle text-red-500 mr-2"></i>映画『ザ・ウェーブ』事例</p><p>主体性と協働を重視した授業実践が、全体主義的な心理と集団圧力に変質し、批判的思考や個の尊重が失われた実例（p.83）</p></div></div><div class="right-column"><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-sitemap text-purple-600 mr-2"></i>ガバナンスの課題</p><ul class="custom-list"><li><p>学校裁量と説明責任のバランス</p></li><li><p>教育政策の「上からの改革」の限界</p></li><li><p>現場と政策間の対話不足</p></li></ul></div><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-users text-green-600 mr-2"></i>安全・多様性の担保</p><p>発言や参加に差がある学習環境での公平性</p><p class="mt-2">多様な認知特性・言語背景を持つ学習者への配慮</p><p class="mt-2">「静かに学ぶ権利」の保障</p></div><div class="key-point"><p class="text-lg font-medium mb-2"><i class="fas fa-lightbulb text-yellow-500 mr-2"></i>重要な視点</p><ul class="custom-list"><li><p>良薬にも毒薬にも：設計と運用次第</p></li><li><p>批判的思考を育む環境の確保</p></li><li><p>多様性を尊重する柔軟な実装</p></li><li><p>形式より学びの本質を重視</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        font-family: 'Noto Sans JP', sans-serif;        margin: 0;        padding: 0;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f8f9fa;        color: #333;        position: relative;        overflow: hidden;    }    .header {        background-color: #2c3e50;        color: white;        padding: 20px 60px;        position: relative;    }    .content {        flex: 1;        display: flex;        flex-direction: column;        padding: 30px 60px;        z-index: 10;    }    .main-content {        display: flex;        flex: 1;    }    .left-column {        flex: 3;        padding-right: 30px;    }    .right-column {        flex: 2;        display: flex;        flex-direction: column;    }    .info-box {        background-color: #edf2f7;        border-radius: 8px;        padding: 20px;        margin-bottom: 20px;        border-left: 4px solid #3498db;    }    .key-point {        background-color: #ebf8ff;        border-left: 4px solid #2b6cb0;        padding: 15px;        margin-top: 20px;        border-radius: 0 8px 8px 0;    }    .accent-line {        position: absolute;        bottom: 0;        left: 0;        height: 8px;        width: 100%;        background-color: #3498db;    }    .definition-box {        background-color: #f0f4f8;        border: 1px solid #cbd5e0;        border-radius: 8px;        padding: 15px;        margin-bottom: 20px;    }    ul.custom-list {        list-style-type: none;        padding-left: 0;    }    ul.custom-list li {        position: relative;        padding-left: 25px;        margin-bottom: 12px;    }    ul.custom-list li:before {        content: "";        position: absolute;        left: 0;        top: 10px;        width: 8px;        height: 8px;        background-color: #3498db;        border-radius: 50%;    }    .warning-box {        background-color: #fff5f5;        border-left: 4px solid #e53e3e;        padding: 15px;        margin-top: 20px;        border-radius: 0 8px 8px 0;    }
</style>
