<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="キーセンテンス集" :current-page="18" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">キーセンテンス集</h1><p class="subtitle">本書を貫く重要なメッセージ</p><div class="accent-line"></div></div><div class="content"><div class="quote-container"><div class="quote-box"><div class="quote-icon"><i class="fas fa-balance-scale"></i></div><div class="quote-content"><p class="quote-text">「<span class="quote-highlight">理想論が先行するとき</span>、現実が追いついているかを常に問う。」</p><p class="quote-context">教育改革の理想と現実のギャップを見極める基本姿勢</p></div></div><div class="quote-box"><div class="quote-icon"><i class="fas fa-flask"></i></div><div class="quote-content"><p class="quote-text">「教育は<span class="quote-highlight">良薬にも毒薬</span>にもなり得る—設計と運用次第である。」</p><p class="quote-context">アクティブラーニングの両義性・注意点</p></div></div><div class="quote-box"><div class="quote-icon"><i class="fas fa-history"></i></div><div class="quote-content"><p class="quote-text">「<span class="quote-highlight">五つの幻想を検証</span>し、歴史から謙虚に学ぶ。」</p><p class="quote-context">AL導入の前提を疑い、過去の教育史から教訓を得る</p></div></div><div class="quote-box"><div class="quote-icon"><i class="fas fa-users"></i></div><div class="quote-content"><p class="quote-text">「教育や学びの主人公は、<span class="quote-highlight">学校現場の教師と子どもたち</span>である。」</p><p class="quote-context">政策・理念より現場と児童生徒を中心に据える視点</p></div></div><div class="quote-box"><div class="quote-icon"><i class="fas fa-search"></i></div><div class="quote-content"><p class="quote-text">「<span class="quote-highlight">未来に対する根拠のない希望や絶望ではなく</span>、歴史から謙虚に学ぶ姿勢や知性を大切にしたい。」</p><p class="quote-context">教育実践における歴史認識と検証の重要性</p></div></div></div><div class="footer"><p>『アクティブラーニング 学校教育の理想と現実』小針誠 著（講談社現代新書）</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        font-family: 'Noto Sans JP', sans-serif;        margin: 0;        padding: 0;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f8f9fa;        color: #333;        position: relative;        overflow: hidden;    }    .header {        background-color: #2c3e50;        color: white;        padding: 20px 60px;        position: relative;    }    .content {        flex: 1;        display: flex;        flex-direction: column;        padding: 30px 60px;        z-index: 10;    }    .quote-container {        display: flex;        flex-direction: column;        gap: 25px;        margin-top: 20px;    }    .quote-box {        background-color: #ffffff;        border-left: 5px solid #3498db;        padding: 20px;        border-radius: 0 8px 8px 0;        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);        display: flex;        align-items: center;        transition: transform 0.3s ease;        position: relative;    }    .quote-box:hover {        transform: translateX(5px);    }    .quote-icon {        color: #3498db;        font-size: 24px;        margin-right: 20px;        min-width: 30px;        display: flex;        justify-content: center;    }    .quote-content {        flex: 1;    }    .quote-text {        font-size: 20px;        line-height: 1.6;        margin-bottom: 5px;    }    .quote-context {        color: #666;        font-size: 14px;        font-style: italic;    }    .accent-line {        position: absolute;        bottom: 0;        left: 0;        height: 8px;        width: 100%;        background-color: #3498db;    }    .subtitle {        font-size: 18px;        color: #cbd5e0;        margin-top: 8px;    }    .footer {        text-align: center;        padding: 15px;        color: #718096;        font-size: 14px;        border-top: 1px solid #e2e8f0;        margin-top: 20px;    }    .quote-highlight {        color: #3498db;        font-weight: bold;    }
</style>
