<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="重要用語集" :current-page="19" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">重要用語集</h1><div class="accent-line"></div></div><div class="content"><div class="main-content"><div class="left-column"><div class="category-title"><i class="fas fa-lightbulb mr-2"></i>現代の学習理論</div><div class="term-box al-term"><div class="term-title"><i class="fas fa-graduation-cap"></i><p>アクティブラーニング</p></div><p>学習者の主体的な参加を取り入れた教授・学習法の総称。一方向的な知識伝達型講義を聴くという（受動的）学習を乗り越える能動的な学習。討論、ディベート、グループワークなどを通じて、認知的、倫理的、社会的能力を育成する。</p></div><div class="term-box al-term"><div class="term-title"><i class="fas fa-comments"></i><p>主体的・対話的で深い学び</p></div><p>2017年の学習指導要領改訂で導入された概念。「アクティブラーニング」から日本の教育文脈に合わせた表現へ。「何を学ぶか」だけでなく「どのように学ぶか」を重視し、主体性・対話性・深い理解の3要素を強調。</p></div><div class="term-box al-term"><div class="term-title"><i class="fas fa-layer-group"></i><p>学力の三要素</p></div><p>①知識・技能の習得、②思考力・判断力・表現力等の育成、③学びに向かう力・人間性等の涵養。2007年の学校教育法改正で規定され、バランスのとれた資質・能力の育成を目指す。</p></div><div class="term-box policy-term"><div class="term-title"><i class="fas fa-sync-alt"></i><p>カリキュラム・マネジメント</p></div><p>学校の教育目標実現に向けた教育課程の編成・実施・評価・改善の一体的・継続的な取組。教科横断的な視点、PDCAサイクルの確立、外部資源の活用の三つの側面から捉える。</p></div></div><div class="right-column"><div class="category-title"><i class="fas fa-history mr-2"></i>歴史的実践・政策</div><div class="term-box history-term"><div class="term-title"><i class="fas fa-book"></i><p>ドルトン・プラン</p></div><p>1920年代にヘレン・パーカーストが考案した教育方法。個別学習を基本とし、生徒の自由・自立・協働を重視。成城小学校が日本で初めて導入。課題別の個人進度学習と教科の枠を超えた総合的な学習活動を特徴とする。</p></div><div class="term-box history-term"><div class="term-title"><i class="fas fa-users"></i><p>生活単元学習</p></div><p>戦後新教育で導入された学習形態。児童の生活経験を基盤にした総合的な学習単元を構成。「はいまわる経験主義」と批判される一方、児童の興味関心を引き出す意義があった。</p></div><div class="term-box history-term"><div class="term-title"><i class="fas fa-sitemap"></i><p>コア・カリキュラム</p></div><p>社会機能に基づいて編成された中核的学習経験を「コア」とし、それを中心に各教科を関連づける教育課程。戦後の経験主義教育で重視された。児童の生活や社会問題を中心に据えた統合的な学習を展開。</p></div><div class="term-box policy-term"><div class="term-title"><i class="fas fa-chart-line"></i><p>PISAショック</p></div><p>2003年のOECD学習到達度調査（PISA）で日本の順位が低下したことによる衝撃。「ゆとり教育」への批判が高まり、「確かな学力」の育成へと教育政策が転換。思考力・活用力を重視する流れがアクティブラーニング導入の背景に。</p></div></div></div><div class="text-center mt-4"><p class="text-sm text-gray-600">※本書を通して繰り返し登場する重要な概念・用語です。各用語の歴史的背景と現代的意義を理解することが重要です。</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        font-family: 'Noto Sans JP', sans-serif;        margin: 0;        padding: 0;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f8f9fa;        color: #333;        position: relative;        overflow: hidden;    }    .header {        background-color: #2c3e50;        color: white;        padding: 20px 60px;        position: relative;    }    .content {        flex: 1;        display: flex;        flex-direction: column;        padding: 30px 60px;        z-index: 10;    }    .main-content {        display: flex;        flex: 1;    }    .left-column {        flex: 1;        padding-right: 20px;    }    .right-column {        flex: 1;        padding-left: 20px;    }    .term-box {        background-color: #edf2f7;        border-radius: 8px;        padding: 15px;        margin-bottom: 15px;        position: relative;        border-left: 4px solid;    }    .term-title {        font-weight: bold;        display: flex;        align-items: center;        margin-bottom: 8px;        border-bottom: 1px solid #cbd5e0;        padding-bottom: 5px;    }    .term-title i {        margin-right: 10px;    }    .accent-line {        position: absolute;        bottom: 0;        left: 0;        height: 8px;        width: 100%;        background-color: #3498db;    }    .category-title {        font-weight: bold;        margin: 0 0 15px 0;        padding: 5px 10px;        background-color: #2c3e50;        color: white;        border-radius: 4px;        display: inline-block;    }    .al-term {        border-left-color: #3498db;    }    .al-term .term-title i {        color: #3498db;    }    .history-term {        border-left-color: #e74c3c;    }    .history-term .term-title i {        color: #e74c3c;    }    .policy-term {        border-left-color: #2ecc71;    }    .policy-term .term-title i {        color: #2ecc71;    }
</style>
