<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="本書の概要・対象読者・読後の変化" :current-page="2" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">本書の概要・対象読者・読後の変化</h1><div class="accent-line"></div></div><div class="content"><div class="w-full"><div class="flex flex-wrap -mx-3"><div class="section w-1/2"><div class="section-title text-xl"><i class="fas fa-book-open"></i><p>目的</p></div><div class="section-content"><p class="mb-4">アクティブラーニング（AL）／「主体的・対話的で深い学び」をめぐる"五つの幻想"を歴史と現場から検証</p></div></div><div class="section w-1/2"><div class="section-title text-xl"><i class="fas fa-history"></i><p>背景</p></div><div class="section-content"><p class="mb-4">2020年教育改革・政策スローガン化・現場との乖離</p></div></div><div class="section w-1/2"><div class="section-title text-xl"><i class="fas fa-users"></i><p>対象読者</p></div><div class="section-content"><ul class="custom-list"><li><p>教員・管理職・教育委員会</p></li><li><p>保護者・学生</p></li><li><p>教育政策に関心のある一般</p></li></ul></div></div><div class="section w-1/2"><div class="section-title text-xl"><i class="fas fa-lightbulb"></i><p>読後の変化（期待）</p></div><div class="section-content"><ul class="custom-list"><li><p>幻想を疑い、根拠ベースで設計</p></li><li><p>学力の三要素に基づく評価の再設計</p></li><li><p>現場主義・多様性尊重・検証文化の醸成</p></li></ul></div></div></div><div class="mt-8 p-4 bg-blue-50 rounded-lg border-l-4 border-blue-400"><p class="text-lg">「アクティブラーニング」導入は、単なる教育政策なのか、それとも教育改革なのか。<br/>本書は歴史的視点から理想と現実のギャップを問い直す一冊です。</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            font-family: 'Noto Sans JP', sans-serif;            margin: 0;            padding: 0;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            flex-direction: column;            background-color: #f8f9fa;            color: #333;            position: relative;            overflow: hidden;        }        .header {            background-color: #2c3e50;            color: white;            padding: 20px 60px;            position: relative;        }        .content {            flex: 1;            display: flex;            padding: 40px 60px;            z-index: 10;        }        .section {            flex: 1;            padding: 15px;        }        .section-title {            font-weight: bold;            display: flex;            align-items: center;            margin-bottom: 15px;            border-bottom: 3px solid #3498db;            padding-bottom: 5px;        }        .section-title i {            margin-right: 10px;            color: #3498db;        }        .section-content {            padding-left: 35px;        }        .accent-line {            position: absolute;            bottom: 0;            left: 0;            height: 8px;            width: 100%;            background-color: #3498db;        }        ul.custom-list {            list-style-type: none;            padding-left: 0;        }        ul.custom-list li {            position: relative;            padding-left: 25px;            margin-bottom: 10px;        }        ul.custom-list li:before {            content: "";            position: absolute;            left: 0;            top: 10px;            width: 10px;            height: 10px;            background-color: #3498db;            border-radius: 50%;        }
</style>
