<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="結び：主要な提言と今後の展望" :current-page="20" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">結び：主要な提言と今後の展望</h1><div class="accent-line"></div></div><div class="content"><div class="main-content"><div class="left-column"><div class="suggestion-box"><div class="suggestion-title text-xl"><i class="fas fa-lightbulb"></i><p>主要な提言</p></div><ul class="suggestion-list proposal-list"><li><i class="fas fa-balance-scale"></i><p><strong>基礎と探究の両立</strong>：ミニマム保障と探究的学びの深化の両輪で学力格差に対応</p></li><li><i class="fas fa-clipboard-check"></i><p><strong>条件整備と段階導入</strong>：一律導入ではなく学校・地域の実態に応じた柔軟な展開</p></li><li><i class="fas fa-chalkboard-teacher"></i><p><strong>現場主義の徹底</strong>：教師の裁量・専門性・多様性を尊重した実践を</p></li><li><i class="fas fa-chart-line"></i><p><strong>検証文化の確立</strong>：小規模実験→評価→改善のサイクルで持続可能な改革へ</p></li></ul></div><div class="quote-box"><p>「教育や学びの主人公は、政治家でも行政でも学者でもなく、学校現場の教師と子どもたち自身である」</p></div><div class="summary-box"><p><strong>基本姿勢</strong>：歴史から謙虚に学び、現実を丁寧に分析し、理想と現実のギャップを常に点検する</p></div></div><div class="right-column"><div class="suggestion-box"><div class="suggestion-title text-xl"><i class="fas fa-binoculars"></i><p>今後の展望</p></div><ul class="suggestion-list outlook-list"><li><i class="fas fa-users"></i><p><strong>多様性と包摂</strong>：様々な学力・背景・特性の児童生徒が共に学べる教室づくり</p></li><li><i class="fas fa-brain"></i><p><strong>批判的思考の育成</strong>：権威や前提を疑い検証できる市民としての基礎力</p></li><li><i class="fas fa-hand-holding-heart"></i><p><strong>内発的動機づけ</strong>：強制ではなく子どもの好奇心や探究心を育む環境</p></li><li><i class="fas fa-exchange-alt"></i><p><strong>対話と協働の場</strong>：現場・研究者・行政の垣根を越えた連携と検証</p></li></ul><div class="summary-box mt-4"><p><strong>変革の方向性</strong>：トップダウンではなく現場発のボトムアップ改革</p><p>教育は「良薬」にも「毒薬」にもなり得る—設計と運用次第である</p></div></div></div></div><div class="conclusion-banner"><p>アクティブラーニングは万能ではない—歴史的検証と現場に根ざした批判的視点から再構築を</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        font-family: 'Noto Sans JP', sans-serif;        margin: 0;        padding: 0;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f8f9fa;        color: #333;        position: relative;        overflow: hidden;    }    .header {        background-color: #2c3e50;        color: white;        padding: 20px 60px;        position: relative;    }    .content {        flex: 1;        display: flex;        flex-direction: column;        padding: 30px 60px;        z-index: 10;    }    .main-content {        display: flex;        flex: 1;    }    .left-column {        flex: 1;        padding-right: 30px;    }    .right-column {        flex: 1;        padding-left: 30px;    }    .suggestion-box {        background-color: #edf2f7;        border-radius: 8px;        padding: 20px;        margin-bottom: 20px;        position: relative;    }    .suggestion-title {        font-weight: bold;        display: flex;        align-items: center;        margin-bottom: 15px;        border-bottom: 2px solid #3498db;        padding-bottom: 5px;    }    .suggestion-title i {        margin-right: 10px;        color: #3498db;    }    .suggestion-list {        list-style-type: none;        padding-left: 0;    }    .suggestion-list li {        position: relative;        padding-left: 30px;        margin-bottom: 12px;        display: flex;        align-items: flex-start;    }    .suggestion-list li i {        position: absolute;        left: 0;        top: 4px;        width: 20px;        text-align: center;    }    .proposal-list li i {        color: #2b6cb0;    }    .outlook-list li i {        color: #38a169;    }    .accent-line {        position: absolute;        bottom: 0;        left: 0;        height: 8px;        width: 100%;        background-color: #3498db;    }    .summary-box {        background-color: #ebf8ff;        border-left: 4px solid #3498db;        padding: 15px;        margin-top: 20px;        border-radius: 0 8px 8px 0;    }    .quote-box {        background-color: #f7fafc;        border-left: 4px solid #718096;        padding: 15px;        margin: 20px 0;        border-radius: 0 8px 8px 0;        font-style: italic;    }    .conclusion-banner {        background-color: #2a4365;        color: white;        padding: 15px;        text-align: center;        margin-top: 20px;        border-radius: 8px;        font-weight: bold;    }
</style>
