<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="全体構成（各章の大枠）" :current-page="3" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">全体構成（各章の大枠）</h1><div class="accent-line"></div></div><div class="content"><div class="w-full relative"><div class="timeline-connector"></div><div class="chapter-section"><div class="chapter-title text-xl"><i class="fas fa-question-circle"></i><p>第1章：ALとは何か／五つの幻想</p></div><div class="chapter-content"><ul class="custom-list"><li><p>アクティブラーニングの定義と背景</p></li><li><p>五つの幻想：未来社会の唯一解か？活動=主体性か？</p></li><li><p>パッシブからアクティブへの転換の意味</p></li></ul></div></div><div class="chapter-section"><div class="chapter-title text-xl"><i class="fas fa-history"></i><p>第2章：近代教育史の〈AL〉—大正新教育・戦時下</p></div><div class="chapter-content"><ul class="custom-list"><li><p>近代学校の矛盾と「教育改造」</p></li><li><p>成城小学校の自学自習（ドルトン・プラン）</p></li><li><p>奈良女高師附属小学校の学習法—理念と実践のギャップ</p></li></ul></div></div><div class="chapter-section"><div class="chapter-title text-xl"><i class="fas fa-school"></i><p>第3章：戦後教育史の〈AL〉—問題解決学習・民間教育研究</p></div><div class="chapter-content"><ul class="custom-list"><li><p>戦後新教育・コア・カリキュラムの展開</p></li><li><p>「はいまわる経験主義」と学力低下論争</p></li><li><p>班集団づくり—協働と排除のジレンマ</p></li></ul></div></div><div class="chapter-section"><div class="chapter-title text-xl"><i class="fas fa-chart-line"></i><p>第4章：平成教育史の〈AL〉—新しい学力観・総合学習・PISA</p></div><div class="chapter-content"><ul class="custom-list"><li><p>「新しい学力観」と「生きる力」の理念</p></li><li><p>総合的な学習の時間の導入と課題</p></li><li><p>PISAショックから「確かな学力」へ</p></li></ul></div></div><div class="chapter-section"><div class="chapter-title text-xl"><i class="fas fa-lightbulb"></i><p>第5章：未来のAL—実践・運用・倫理の課題と提言</p></div><div class="chapter-content"><ul class="custom-list"><li><p>歴史から何を学ぶか—繰り返されるパターン</p></li><li><p>実践・運用・倫理上の三つの課題</p></li><li><p>アクティブラーニングの未来と提言</p></li></ul></div></div><div class="mt-4 px-4 py-3 bg-blue-50 rounded-lg border-l-4 border-blue-400"><p class="text-lg">巻末資料：学習指導要領の変遷、主要文献一覧</p><p class="mt-2">本書は、明治・大正期から令和にいたる教育改革の波を丁寧に分析し、現代の改革を相対化します。</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {            font-family: 'Noto Sans JP', sans-serif;            margin: 0;            padding: 0;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            flex-direction: column;            background-color: #f8f9fa;            color: #333;            position: relative;            overflow: hidden;        }        .header {            background-color: #2c3e50;            color: white;            padding: 20px 60px;            position: relative;        }        .content {            flex: 1;            display: flex;            padding: 30px 60px;            z-index: 10;        }        .chapter-section {            margin-bottom: 15px;            padding: 10px;            border-left: 4px solid #3498db;            background-color: rgba(52, 152, 219, 0.05);        }        .chapter-title {            font-weight: bold;            display: flex;            align-items: center;            margin-bottom: 10px;            color: #2c3e50;        }        .chapter-title i {            margin-right: 10px;            color: #3498db;            font-size: 1.2rem;        }        .chapter-content {            padding-left: 35px;        }        .accent-line {            position: absolute;            bottom: 0;            left: 0;            height: 8px;            width: 100%;            background-color: #3498db;        }        ul.custom-list {            list-style-type: none;            padding-left: 0;            margin-top: 5px;        }        ul.custom-list li {            position: relative;            padding-left: 20px;            margin-bottom: 8px;        }        ul.custom-list li:before {            content: "";            position: absolute;            left: 0;            top: 8px;            width: 8px;            height: 8px;            background-color: #3498db;            border-radius: 50%;        }        .timeline-connector {            position: absolute;            left: 20px;            top: 35px;            bottom: 35px;            width: 2px;            background-color: #d1d5db;            z-index: 1;        }
</style>
