<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="第1章(1) アクティブラーニングとは何か" :current-page="4" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">第1章(1) アクティブラーニングとは何か</h1><div class="accent-line"></div></div><div class="content"><div class="main-content"><div class="left-column"><div class="definition-box"><p class="text-xl font-medium mb-2"><i class="fas fa-quote-left text-blue-500 mr-2"></i>定義</p><p class="ml-6">学習者の主体性・対話・深い学びを促す授業改善の総称</p></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-history text-blue-500 mr-2"></i>政策文脈</p><ul class="custom-list"><li><p>アクティブラーニング → 「主体的・対話的で深い学び」への用語転換</p></li><li><p>2020年教育改革における中心的概念として位置づけ</p></li><li><p>学習指導要領での明確化と教員研修の強化</p></li></ul></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-bullseye text-blue-500 mr-2"></i>狙い</p><ul class="custom-list"><li><p>知識・技能の活用力強化</p></li><li><p>思考力・判断力・表現力の育成</p></li><li><p>学びに向かう力・人間性の伸長</p></li><li><p>社会変化への対応力養成</p></li></ul></div></div><div class="right-column"><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-lightbulb text-yellow-500 mr-2"></i>学習者の役割転換</p><p>従来：知識の「受容者」</p><p class="mt-2">AL導入後：知識の「構成者」「意味づけ者」</p></div><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-chalkboard-teacher text-green-600 mr-2"></i>教師の役割転換</p><p>従来：知識の「伝達者」</p><p class="mt-2">AL導入後：学びの「デザイナー」「ファシリテーター」</p></div><div class="key-point"><p class="text-lg font-medium mb-2"><i class="fas fa-exclamation-triangle text-red-500 mr-2"></i>留意点</p><ul class="custom-list"><li><p>活動≠学び（形式だけでは効果限定的）</p></li><li><p>条件整備・評価設計が不可欠</p></li><li><p>基礎知識と探究のバランス必須</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        font-family: 'Noto Sans JP', sans-serif;        margin: 0;        padding: 0;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f8f9fa;        color: #333;        position: relative;        overflow: hidden;    }    .header {        background-color: #2c3e50;        color: white;        padding: 20px 60px;        position: relative;    }    .content {        flex: 1;        display: flex;        flex-direction: column;        padding: 30px 60px;        z-index: 10;    }    .main-content {        display: flex;        flex: 1;    }    .left-column {        flex: 3;        padding-right: 30px;    }    .right-column {        flex: 2;        display: flex;        flex-direction: column;    }    .info-box {        background-color: #edf2f7;        border-radius: 8px;        padding: 20px;        margin-bottom: 20px;        border-left: 4px solid #3498db;    }    .key-point {        background-color: #ebf8ff;        border-left: 4px solid #2b6cb0;        padding: 15px;        margin-top: 20px;        border-radius: 0 8px 8px 0;    }    .accent-line {        position: absolute;        bottom: 0;        left: 0;        height: 8px;        width: 100%;        background-color: #3498db;    }    .definition-box {        background-color: #f0f4f8;        border: 1px solid #cbd5e0;        border-radius: 8px;        padding: 15px;        margin-bottom: 20px;    }    ul.custom-list {        list-style-type: none;        padding-left: 0;    }    ul.custom-list li {        position: relative;        padding-left: 25px;        margin-bottom: 12px;    }    ul.custom-list li:before {        content: "";        position: absolute;        left: 0;        top: 10px;        width: 8px;        height: 8px;        background-color: #3498db;        border-radius: 50%;    }
</style>
