<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="第1章(2) 五つの幻想（要点）" :current-page="5" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">第1章(2) 五つの幻想（要点）</h1><div class="accent-line"></div></div><div class="content"><div class="main-content"><div class="left-column"><p class="text-xl font-medium mb-4"><i class="fas fa-exclamation-circle text-red-500 mr-2"></i>アクティブラーニングをめぐる五つの幻想</p><div class="myth-box"><p><span class="myth-number">幻想1:</span> <strong>ALは未来社会の唯一解</strong></p><p class="ml-8 text-sm">「未来社会に必要だから」という根拠の脆弱性。社会変化と教育変化の直線的な関係性への疑問。</p></div><div class="myth-box"><p><span class="myth-number">幻想2:</span> <strong>活動すれば主体性が自動的に育つ</strong></p><p class="ml-8 text-sm">外的な活動の活性化が必ずしも内的な主体性・能動性に結びつかない現実。形式と実質のギャップ。</p></div><div class="myth-box"><p><span class="myth-number">幻想3:</span> <strong>学校で体験すれば学力が必ず伸びる</strong></p><p class="ml-8 text-sm">AL導入と学力向上の因果関係の不確実さ。基礎学力がある子ほど恩恵を受け、格差が拡大する可能性。</p></div><div class="myth-box"><p><span class="myth-number">幻想4:</span> <strong>教師研修でどこでも実現できる</strong></p><p class="ml-8 text-sm">教育実践の困難を教師の意欲や力量不足に帰する責任転嫁。現実の制約条件（時間・空間・人数）の軽視。</p></div><div class="myth-box"><p><span class="myth-number">幻想5:</span> <strong>国策として一律推進が最善</strong></p><p class="ml-8 text-sm">教育政策としての正当性への無批判な受容。多様性・現場裁量の軽視。歴史的教訓の不十分な検証。</p></div></div><div class="right-column"><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-search text-blue-500 mr-2"></i>検証の視点</p><ul class="custom-list"><li><p>歴史的実績（類似実践の帰結）</p></li><li><p>実証データ（学力・意欲との相関）</p></li><li><p>現場条件（実現可能性の精査）</p></li><li><p>倫理・統治（全体主義的リスク）</p></li></ul></div><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-balance-scale text-purple-600 mr-2"></i>疑問のバランス</p><p>全面否定ではなく、肯定的側面を認めつつも、根拠なき楽観論や政策的一元化への批判的検証が必要</p></div><div class="key-point"><p class="text-lg font-medium mb-2"><i class="fas fa-quote-right text-green-600 mr-2"></i>著者の主張</p><p>"いずれの前提についても、本当にそうなのか、疑って考える必要があるのではないでしょうか"</p><p class="mt-2 text-sm">理想論が先行し、現実が追いついているかを常に問い直す姿勢が重要</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        font-family: 'Noto Sans JP', sans-serif;        margin: 0;        padding: 0;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f8f9fa;        color: #333;        position: relative;        overflow: hidden;    }    .header {        background-color: #2c3e50;        color: white;        padding: 20px 60px;        position: relative;    }    .content {        flex: 1;        display: flex;        flex-direction: column;        padding: 30px 60px;        z-index: 10;    }    .main-content {        display: flex;        flex: 1;    }    .left-column {        flex: 3;        padding-right: 30px;    }    .right-column {        flex: 2;        display: flex;        flex-direction: column;    }    .info-box {        background-color: #edf2f7;        border-radius: 8px;        padding: 20px;        margin-bottom: 20px;        border-left: 4px solid #3498db;    }    .key-point {        background-color: #ebf8ff;        border-left: 4px solid #2b6cb0;        padding: 15px;        margin-top: 20px;        border-radius: 0 8px 8px 0;    }    .accent-line {        position: absolute;        bottom: 0;        left: 0;        height: 8px;        width: 100%;        background-color: #3498db;    }    .definition-box {        background-color: #f0f4f8;        border: 1px solid #cbd5e0;        border-radius: 8px;        padding: 15px;        margin-bottom: 20px;    }    ul.custom-list {        list-style-type: none;        padding-left: 0;    }    ul.custom-list li {        position: relative;        padding-left: 25px;        margin-bottom: 12px;    }    ul.custom-list li:before {        content: "";        position: absolute;        left: 0;        top: 10px;        width: 8px;        height: 8px;        background-color: #3498db;        border-radius: 50%;    }    .myth-box {        background-color: #fff0f3;        border-left: 4px solid #e53e3e;        padding: 12px;        margin-bottom: 15px;        border-radius: 0 8px 8px 0;    }    .myth-number {        font-weight: bold;        color: #e53e3e;        margin-right: 8px;    }
</style>
