<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="第2章(1) 近代教育史：大正新教育と教育改造" :current-page="6" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">第2章(1) 近代教育史：大正新教育と教育改造</h1><div class="accent-line"></div></div><div class="content"><div class="main-content"><div class="left-column"><div class="definition-box"><p class="text-xl font-medium mb-2"><i class="fas fa-landmark text-blue-500 mr-2"></i>近代学校の矛盾と「教育改造」</p><p class="ml-6">明治期の「一斉教授」「詰め込み」への反省から、児童中心主義・経験主義による教育改革</p></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-book-open text-blue-500 mr-2"></i>新教育運動の特徴</p><ul class="custom-list"><li><p>児童の自発性・主体性の尊重</p></li><li><p>経験や活動を通じた学び</p></li><li><p>個性と創造性の重視</p></li><li><p>画一的・一斉指導からの脱却</p></li></ul></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-history text-blue-500 mr-2"></i>主な展開（大正・昭和初期）</p><div class="timeline"><div class="timeline-item"><p><span class="timeline-year">1910年代～</span> 私立学校を中心とした実験的取り組み</p></div><div class="timeline-item"><p><span class="timeline-year">1919年</span> 本邦初の〈AL〉指導書「自学輔導の原理及実際」刊行</p></div><div class="timeline-item"><p><span class="timeline-year">1920年代</span> 成城小学校、奈良女高師附属小学校の実践</p></div><div class="timeline-item"><p><span class="timeline-year">1930年代</span> 国家主義的教育への転換と継承の両面性</p></div></div></div></div><div class="right-column"><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-lightbulb text-yellow-500 mr-2"></i>時代背景</p><p>第一次世界大戦後の社会変化</p><p class="mt-2">デューイなど海外教育思想の影響</p><p class="mt-2">大正デモクラシー・自由主義の風潮</p></div><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-check-circle text-green-600 mr-2"></i>成果</p><ul class="custom-list"><li><p>児童の学習意欲向上</p></li><li><p>探究の芽生え</p></li><li><p>教師の教育観変革</p></li></ul></div><div class="key-point"><p class="text-lg font-medium mb-2"><i class="fas fa-exclamation-triangle text-red-500 mr-2"></i>限界と課題</p><ul class="custom-list"><li><p>家庭背景による学力格差の拡大</p></li><li><p>教員の負担増大</p></li><li><p>指導の形骸化・マニュアル化</p></li><li><p>私立・特別な学校での限定的実践</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        font-family: 'Noto Sans JP', sans-serif;        margin: 0;        padding: 0;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f8f9fa;        color: #333;        position: relative;        overflow: hidden;    }    .header {        background-color: #2c3e50;        color: white;        padding: 20px 60px;        position: relative;    }    .content {        flex: 1;        display: flex;        flex-direction: column;        padding: 30px 60px;        z-index: 10;    }    .main-content {        display: flex;        flex: 1;    }    .left-column {        flex: 3;        padding-right: 30px;    }    .right-column {        flex: 2;        display: flex;        flex-direction: column;    }    .info-box {        background-color: #edf2f7;        border-radius: 8px;        padding: 20px;        margin-bottom: 20px;        border-left: 4px solid #3498db;    }    .key-point {        background-color: #ebf8ff;        border-left: 4px solid #2b6cb0;        padding: 15px;        margin-top: 20px;        border-radius: 0 8px 8px 0;    }    .accent-line {        position: absolute;        bottom: 0;        left: 0;        height: 8px;        width: 100%;        background-color: #3498db;    }    .definition-box {        background-color: #f0f4f8;        border: 1px solid #cbd5e0;        border-radius: 8px;        padding: 15px;        margin-bottom: 20px;    }    ul.custom-list {        list-style-type: none;        padding-left: 0;    }    ul.custom-list li {        position: relative;        padding-left: 25px;        margin-bottom: 12px;    }    ul.custom-list li:before {        content: "";        position: absolute;        left: 0;        top: 10px;        width: 8px;        height: 8px;        background-color: #3498db;        border-radius: 50%;    }    .timeline {        position: relative;        padding-left: 30px;        margin-bottom: 20px;        border-left: 2px solid #cbd5e0;    }    .timeline-item {        position: relative;        margin-bottom: 15px;    }    .timeline-item:before {        content: "";        position: absolute;        left: -36px;        top: 5px;        width: 12px;        height: 12px;        background-color: #3498db;        border-radius: 50%;        border: 2px solid #f8f9fa;    }    .timeline-year {        font-weight: 600;        color: #2c3e50;    }
</style>
