<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="第2章(2) 成城小ドルトン・プラン／奈良の学習法と課題" :current-page="7" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">第2章(2) 成城小ドルトン・プラン／奈良の学習法と課題</h1><div class="accent-line"></div></div><div class="content"><div class="main-content"><div class="left-column"><div class="school-box"><p class="text-xl font-medium mb-2"><i class="fas fa-school text-blue-500 mr-2"></i>成城小学校：自学自習（ドルトン・プラン）</p><ul class="custom-list"><li><p>1924年〜：沢柳政太郎が私立学校で導入</p></li><li><p>特徴：個別学習カード・自己進度調整・教科担任制</p></li><li><p>理念：「学ぶことを学ぶ」「自ら調べ考える力」の育成</p></li><li><p>実態：優秀児童は大きく伸びる一方、低意欲・低学力層は遅れが拡大</p></li><li><p>格差：家庭背景による学力・意欲の二極化が顕著に</p></li></ul></div><div class="school-box"><p class="text-xl font-medium mb-2"><i class="fas fa-school text-blue-500 mr-2"></i>奈良女高師附属小：「奈良の学習法」</p><ul class="custom-list"><li><p>1920年代：木下竹治主導の独自学習法</p></li><li><p>特徴：合科学習・自学即ち独自学習・相互学習</p></li><li><p>構成：児童の自由な学習→相互発表・協議→教師による整理</p></li><li><p>課題：池田小菊訓導による内部批判—「騒然とした教室」「偏った発言機会」</p></li><li><p>実態：理想と実践のギャップ、一部児童のみ活性化</p></li></ul></div></div><div class="right-column"><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-check-circle text-green-600 mr-2"></i>両校の革新的取り組み</p><ul class="custom-list"><li><p>児童主体の学習デザイン</p></li><li><p>教科書偏重からの脱却</p></li><li><p>個性・関心重視の探究</p></li><li><p>教師の指導者から支援者への転換</p></li></ul></div><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-exclamation-circle text-red-500 mr-2"></i>実践上の課題</p><ul class="custom-list"><li><p>進度差の拡大・格差の固定化</p></li><li><p>教師の支援力・対応力に依存</p></li><li><p>基礎学力保障との両立困難</p></li><li><p>恵まれた環境（小規模・高学歴家庭）での成功例</p></li></ul></div><div class="key-point"><p class="text-lg font-medium mb-2"><i class="fas fa-lightbulb text-yellow-500 mr-2"></i>共通の教訓</p><ul class="custom-list"><li><p>意欲・基礎学力の異質性に配慮</p></li><li><p>教師の熟達と支援体制が鍵</p></li><li><p>理念先行は形骸化を招く</p></li><li><p>「底が見えそうな」実践設計を</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        font-family: 'Noto Sans JP', sans-serif;        margin: 0;        padding: 0;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f8f9fa;        color: #333;        position: relative;        overflow: hidden;    }    .header {        background-color: #2c3e50;        color: white;        padding: 20px 60px;        position: relative;    }    .content {        flex: 1;        display: flex;        flex-direction: column;        padding: 30px 60px;        z-index: 10;    }    .main-content {        display: flex;        flex: 1;    }    .left-column {        flex: 3;        padding-right: 30px;    }    .right-column {        flex: 2;        display: flex;        flex-direction: column;    }    .info-box {        background-color: #edf2f7;        border-radius: 8px;        padding: 20px;        margin-bottom: 20px;        border-left: 4px solid #3498db;    }    .key-point {        background-color: #ebf8ff;        border-left: 4px solid #2b6cb0;        padding: 15px;        margin-top: 20px;        border-radius: 0 8px 8px 0;    }    .accent-line {        position: absolute;        bottom: 0;        left: 0;        height: 8px;        width: 100%;        background-color: #3498db;    }    .definition-box {        background-color: #f0f4f8;        border: 1px solid #cbd5e0;        border-radius: 8px;        padding: 15px;        margin-bottom: 20px;    }    ul.custom-list {        list-style-type: none;        padding-left: 0;    }    ul.custom-list li {        position: relative;        padding-left: 25px;        margin-bottom: 12px;    }    ul.custom-list li:before {        content: "";        position: absolute;        left: 0;        top: 10px;        width: 8px;        height: 8px;        background-color: #3498db;        border-radius: 50%;    }    .school-box {        border-bottom: 1px solid #e2e8f0;        padding-bottom: 15px;        margin-bottom: 15px;    }
</style>
