<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="第3章(1) 戦後教育史：問題解決学習とコア・カリキュラム" :current-page="8" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">第3章(1) 戦後教育史：問題解決学習とコア・カリキュラム</h1><div class="accent-line"></div></div><div class="content"><div class="main-content"><div class="left-column"><div class="definition-box"><p class="text-xl font-medium mb-2"><i class="fas fa-book-open text-blue-500 mr-2"></i>戦後新教育</p><p class="ml-6">民主主義教育の理念のもと、問題解決学習、生活単元学習、コア・カリキュラムを中心とした教育改革</p></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-sync-alt text-blue-500 mr-2"></i>背景と発展</p><ul class="custom-list"><li><p>戦前教育の反省と民主化への志向</p></li><li><p>GHQの教育改革指針と影響</p></li><li><p>デューイの経験主義教育思想の導入</p></li><li><p>「教師中心」から「子ども中心」の教育へ</p></li></ul></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-puzzle-piece text-blue-500 mr-2"></i>学習指導要領（試案）の特質</p><ul class="custom-list"><li><p>1947年に「試案」として登場—法的拘束力なし</p></li><li><p>現場教師の自主性・創意工夫を尊重</p></li><li><p>経験カリキュラムの推奨</p></li><li><p>社会生活に必要な能力育成を重視</p></li></ul></div></div><div class="right-column"><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-project-diagram text-green-600 mr-2"></i>コア・カリキュラム</p><p>「社会機能」「生活経験」を中核(コア)とし、教科の枠を超えた総合的な学習を編成する教育計画</p><p class="mt-2">実践例：千葉師範附属小学校「社会科を中心とする経験カリキュラム」</p></div><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-search text-purple-600 mr-2"></i>問題解決学習／生活単元学習</p><p>子どもが直面する生活上の問題を発見・解決していくプロセス重視の学習形態</p><p class="mt-2">特徴：調査・発表・話し合いを通じた主体的な探究</p></div><div class="key-point"><p class="text-lg font-medium mb-2"><i class="fas fa-exclamation-triangle text-red-500 mr-2"></i>課題と批判</p><ul class="custom-list"><li><p>学力保障と経験主義のバランス難</p></li><li><p>教員の負担増と指導技術の課題</p></li><li><p>「はいまわる経験主義」との批判</p></li><li><p>学力差の拡大傾向</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        font-family: 'Noto Sans JP', sans-serif;        margin: 0;        padding: 0;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f8f9fa;        color: #333;        position: relative;        overflow: hidden;    }    .header {        background-color: #2c3e50;        color: white;        padding: 20px 60px;        position: relative;    }    .content {        flex: 1;        display: flex;        flex-direction: column;        padding: 30px 60px;        z-index: 10;    }    .main-content {        display: flex;        flex: 1;    }    .left-column {        flex: 3;        padding-right: 30px;    }    .right-column {        flex: 2;        display: flex;        flex-direction: column;    }    .info-box {        background-color: #edf2f7;        border-radius: 8px;        padding: 20px;        margin-bottom: 20px;        border-left: 4px solid #3498db;    }    .key-point {        background-color: #ebf8ff;        border-left: 4px solid #2b6cb0;        padding: 15px;        margin-top: 20px;        border-radius: 0 8px 8px 0;    }    .accent-line {        position: absolute;        bottom: 0;        left: 0;        height: 8px;        width: 100%;        background-color: #3498db;    }    .definition-box {        background-color: #f0f4f8;        border: 1px solid #cbd5e0;        border-radius: 8px;        padding: 15px;        margin-bottom: 20px;    }    ul.custom-list {        list-style-type: none;        padding-left: 0;    }    ul.custom-list li {        position: relative;        padding-left: 25px;        margin-bottom: 12px;    }    ul.custom-list li:before {        content: "";        position: absolute;        left: 0;        top: 10px;        width: 8px;        height: 8px;        background-color: #3498db;        border-radius: 50%;    }
</style>
