<template>
  <SlidePageWrapper slide-id="B07BDDN43G" page-title="第3章(2) 学力低下論争・民間教育研究・集団主義の逆説" :current-page="9" :total-pages="20">
<div class="slide-container"><div class="header"><h1 class="text-3xl font-bold">第3章(2) 学力低下論争・民間教育研究・集団主義の逆説</h1><div class="accent-line"></div></div><div class="content"><div class="main-content"><div class="left-column"><div class="definition-box"><p class="text-xl font-medium mb-2"><i class="fas fa-balance-scale text-blue-500 mr-2"></i>学力低下論争</p><ul class="custom-list"><li><p>「久保調査」による戦後教育批判（戦前との比較で学力低下を主張）</p></li><li><p>比較枠組み・測定方法の妥当性に問題（調査条件・難易度の不均衡）</p></li><li><p>「はいまわる経験主義」批判と系統主義への揺り戻し</p></li></ul></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-users text-blue-500 mr-2"></i>民間教育研究運動</p><ul class="custom-list"><li><p>生活教育・生活綴方運動など現場発の実践</p></li><li><p>教師の自主的・創造的な授業研究と共有</p></li><li><p>成果：現場の自律性・専門性の向上、児童中心の実践モデル</p></li><li><p>課題：教員の負担増、継続性の確保、普及の難しさ</p></li></ul></div><div class="mb-6"><p class="text-xl font-medium mb-2"><i class="fas fa-exclamation-circle text-red-500 mr-2"></i>集団主義教育の逆説</p><ul class="custom-list"><li><p>班集団づくり：協働を通じた民主性育成の意図</p></li><li><p>実態：相互監視・同調圧力・排除の構造化</p></li><li><p>全体主義的傾向：個性の抑制、批判的思考の阻害</p></li></ul></div></div><div class="right-column"><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-chart-line text-purple-600 mr-2"></i>学力論争の背景</p><p>経験主義教育の弊害を強調し、伝統的な「知識・技能」重視への回帰を求める声</p><p class="mt-2">実証データによる検証の欠如、イデオロギー論争化の傾向</p></div><div class="info-box"><p class="text-lg font-medium mb-2"><i class="fas fa-lightbulb text-yellow-500 mr-2"></i>民間教育研究の意義</p><p>「下から」の教育改革、教師の専門性尊重</p><p class="mt-2">「上から」の制度改革との相克、現場の創意工夫と政策のギャップ</p></div><div class="warning-box"><p class="text-lg font-medium mb-2"><i class="fas fa-exclamation-triangle text-red-500 mr-2"></i>示唆される教訓</p><ul class="custom-list"><li><p>個の尊重と集団活動のバランス</p></li><li><p>安全な参加と批判の保障</p></li><li><p>評価の多元性と公平性の担保</p></li><li><p>多様性・包摂性の確保が不可欠</p></li></ul></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body {        font-family: 'Noto Sans JP', sans-serif;        margin: 0;        padding: 0;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        flex-direction: column;        background-color: #f8f9fa;        color: #333;        position: relative;        overflow: hidden;    }    .header {        background-color: #2c3e50;        color: white;        padding: 20px 60px;        position: relative;    }    .content {        flex: 1;        display: flex;        flex-direction: column;        padding: 30px 60px;        z-index: 10;    }    .main-content {        display: flex;        flex: 1;    }    .left-column {        flex: 3;        padding-right: 30px;    }    .right-column {        flex: 2;        display: flex;        flex-direction: column;    }    .info-box {        background-color: #edf2f7;        border-radius: 8px;        padding: 20px;        margin-bottom: 20px;        border-left: 4px solid #3498db;    }    .key-point {        background-color: #ebf8ff;        border-left: 4px solid #2b6cb0;        padding: 15px;        margin-top: 20px;        border-radius: 0 8px 8px 0;    }    .accent-line {        position: absolute;        bottom: 0;        left: 0;        height: 8px;        width: 100%;        background-color: #3498db;    }    .definition-box {        background-color: #f0f4f8;        border: 1px solid #cbd5e0;        border-radius: 8px;        padding: 15px;        margin-bottom: 20px;    }    ul.custom-list {        list-style-type: none;        padding-left: 0;    }    ul.custom-list li {        position: relative;        padding-left: 25px;        margin-bottom: 12px;    }    ul.custom-list li:before {        content: "";        position: absolute;        left: 0;        top: 10px;        width: 8px;        height: 8px;        background-color: #3498db;        border-radius: 50%;    }    .warning-box {        background-color: #fff5f5;        border-left: 4px solid #e53e3e;        padding: 15px;        margin-top: 20px;        border-radius: 0 8px 8px 0;    }
</style>
