<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="1" :total-pages="20">
<div class="slide-container"><div class="decoration decoration-top-right">?</div><div class="decoration decoration-bottom-left">?</div><div class="content-wrapper"><div class="title-container"><p class="title">いま、あなたに必要なのは<br/>答えじゃない。問いの力だ。</p><p class="subtitle">〜 正解のない時代を生き抜くための思考法 〜</p></div><div class="author-container"><p class="author">岸良 裕司</p><p class="position">Goldratt Japan CEO</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            position: relative;            overflow: hidden;            background-color: #f8f9fa;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            justify-content: center;            align-items: center;            padding: 40px;            z-index: 10;        }        .title {            font-size: 54px;            font-weight: 900;            line-height: 1.3;            color: #2c3e50;            text-align: center;            margin-bottom: 30px;        }        .subtitle {            font-size: 28px;            font-weight: 500;            color: #3498db;            text-align: center;            margin-bottom: 60px;        }        .author {            font-size: 24px;            font-weight: 700;            color: #34495e;            text-align: center;            margin-top: 20px;        }        .position {            font-size: 18px;            color: #7f8c8d;            text-align: center;            margin-top: 5px;        }        .decoration {            position: absolute;            font-size: 400px;            opacity: 0.05;            color: #3498db;            z-index: 1;        }        .decoration-top-right {            top: -100px;            right: -50px;            transform: rotate(15deg);        }        .decoration-bottom-left {            bottom: -100px;            left: -50px;            transform: rotate(-15deg);        }
</style>
