<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="10" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="header"><div class="chapter-badge">Chapter 3</div><h1 class="title">正解をつくる</h1></div><div class="content"><div class="main-content"><div class="key-points"><div class="key-point"><div class="key-icon"><i class="fas fa-check-circle"></i></div><p class="key-text">正解＝目標達成かつ副作用なし</p></div><div class="key-point"><div class="key-icon"><i class="fas fa-th-large"></i></div><p class="key-text">4象限評価：目標達成×副作用の有無で解決策の質を判断</p></div><div class="key-point"><div class="key-icon"><i class="fas fa-lightbulb"></i></div><p class="key-text">結果から学ぶ：思ったより悪い/良い結果にも学びがある</p></div></div></div><div class="visual-element"><div class="grid-visual"><div class="grid-item item-good"><p>目標達成<br/>✕<br/>副作用なし<br/><br/>良い解決策</p></div><div class="grid-item item-bad"><p>目標達成<br/>✕<br/>副作用あり<br/><br/>悪い解決策</p></div><div class="grid-item item-useless"><p>目標未達成<br/>✕<br/>副作用なし<br/><br/>解決策とはいえない</p></div><div class="grid-item item-worst"><p>目標未達成<br/>✕<br/>副作用あり<br/><br/>問題外</p></div></div></div></div><div class="footer-quote"><p>「解決策には<span class="quote-highlight">目標達成</span>と<span class="quote-highlight">副作用なし</span>という2つの条件が必要。どちらが欠けても『良い解決策』とはいえない」</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        position: relative;        overflow: hidden;        background-color: #f8f9fa;    }    .content-wrapper {        flex: 1;        display: flex;        flex-direction: column;        padding: 40px 80px;        z-index: 10;    }    .header {        display: flex;        align-items: center;        margin-bottom: 50px;    }    .chapter-badge {        background-color: #3498db;        color: white;        font-size: 26px;        font-weight: 700;        padding: 12px 24px;        border-radius: 8px;        margin-right: 25px;    }    .title {        font-size: 48px;        font-weight: 900;        color: #2c3e50;        line-height: 1.2;    }    .content {        display: flex;        flex: 1;    }    .main-content {        flex: 2;        display: flex;        flex-direction: column;        justify-content: center;    }    .key-points {        display: flex;        flex-direction: column;        gap: 30px;    }    .key-point {        display: flex;        align-items: flex-start;    }    .key-icon {        color: #3498db;        font-size: 28px;        margin-right: 20px;        margin-top: 5px;    }    .key-text {        font-size: 28px;        font-weight: 500;        color: #34495e;        line-height: 1.4;    }    .visual-element {        flex: 1;        display: flex;        justify-content: center;        align-items: center;    }    .grid-visual {        display: grid;        grid-template-columns: 1fr 1fr;        grid-template-rows: 1fr 1fr;        gap: 10px;        width: 300px;        height: 300px;    }    .grid-item {        display: flex;        justify-content: center;        align-items: center;        padding: 15px;        border-radius: 8px;        font-weight: 700;        text-align: center;        font-size: 16px;    }    .item-good {        background-color: rgba(46, 204, 113, 0.2);        color: #27ae60;    }    .item-bad {        background-color: rgba(231, 76, 60, 0.2);        color: #c0392b;    }    .item-useless {        background-color: rgba(241, 196, 15, 0.2);        color: #f39c12;    }    .item-worst {        background-color: rgba(155, 89, 182, 0.2);        color: #8e44ad;    }    .footer-quote {        font-size: 18px;        font-style: italic;        color: #7f8c8d;        margin-top: 40px;        text-align: right;    }    .quote-highlight {        color: #3498db;        font-weight: 700;    }
</style>
