<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="11" :total-pages="20">
<div class="slide-container"><div class="decoration decoration-right">?</div><div class="content-wrapper"><h1 class="title">Chapter 3｜副作用を未然防止（中編）</h1><div class="bullet-points"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-question-circle"></i></div><div class="bullet-text"><p class="bullet-title">「気因解利」の4つの問い</p><p class="bullet-content">副作用を事前に防ぐための問いかけ</p><div class="sub-bullets"><div class="sub-bullet-item"><div class="sub-bullet-icon"><i class="fas fa-angle-right"></i></div><p class="sub-bullet-content"><strong>気</strong>がかりなことはありますか？</p></div><div class="sub-bullet-item"><div class="sub-bullet-icon"><i class="fas fa-angle-right"></i></div><p class="sub-bullet-content">その<strong>因</strong>は何でしょうか？</p></div><div class="sub-bullet-item"><div class="sub-bullet-icon"><i class="fas fa-angle-right"></i></div><p class="sub-bullet-content">その原因を<strong>解</strong>消する方法はありますか？</p></div><div class="sub-bullet-item"><div class="sub-bullet-icon"><i class="fas fa-angle-right"></i></div><p class="sub-bullet-content">気がかりが解消するとどんな<strong>利</strong>点がありますか？</p></div></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-bullseye"></i></div><div class="bullet-text"><p class="bullet-title">予防的な問いの効果</p><p class="bullet-content">懸念を事前に顕在化→原因特定→解消策立案→利点確認の流れで、副作用を未然に防ぎ、解決策を強化できる</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-sync-alt"></i></div><div class="bullet-text"><p class="bullet-title">抵抗勢力は応援勢力</p><p class="bullet-content">反対する人の懸念を「気因解利」で丁寧に聞き出し、対応することで、抵抗勢力が最大の応援者に変わる。批判や抵抗は解決策を改善する貴重な情報源</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            position: relative;            overflow: hidden;            background-color: #f8f9fa;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title {            font-size: 42px;            font-weight: 800;            color: #2c3e50;            margin-bottom: 40px;            position: relative;            padding-bottom: 15px;        }        .title:after {            content: '';            position: absolute;            bottom: 0;            left: 0;            width: 100px;            height: 4px;            background-color: #3498db;        }        .bullet-points {            display: flex;            flex-direction: column;            gap: 30px;        }        .bullet-item {            display: flex;            align-items: flex-start;        }        .bullet-icon {            color: #3498db;            font-size: 20px;            margin-right: 16px;            margin-top: 4px;        }        .bullet-text {            flex: 1;        }        .bullet-title {            font-size: 24px;            font-weight: 700;            color: #34495e;            margin-bottom: 8px;        }        .bullet-content {            font-size: 20px;            color: #5d6d7e;            line-height: 1.6;        }        .decoration {            position: absolute;            font-size: 240px;            opacity: 0.03;            color: #3498db;            z-index: 1;        }        .decoration-right {            bottom: -60px;            right: -40px;            transform: rotate(15deg);        }        .sub-bullets {            margin-left: 20px;            margin-top: 10px;        }        .sub-bullet-item {            display: flex;            align-items: flex-start;            margin-bottom: 10px;        }        .sub-bullet-icon {            color: #7fb3d5;            font-size: 16px;            margin-right: 12px;            margin-top: 4px;        }        .sub-bullet-content {            font-size: 18px;            color: #5d6d7e;        }
</style>
