<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="12" :total-pages="20">
<div class="slide-container"><div class="decoration decoration-right">?</div><div class="content-wrapper"><h1 class="title">Chapter 3｜相手の立場で考える（後編）</h1><div class="bullet-points"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-exchange-alt"></i></div><div class="bullet-text"><p class="bullet-title">相手の問題定義を理解する</p><p class="bullet-content">「相手の『望ましくない現象』は何ですか？」「相手の『望ましい現象』は何ですか？」このギャップが相手の問題</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-lightbulb"></i></div><div class="bullet-text"><p class="bullet-title">暗黙知→形式知の4つの問い</p><p class="bullet-content">①どういう前提がありますか？ ②どういう行動を取るのですか？ ③どういう結果を期待するのですか？ ④その結果が起きる理由はなんですか？</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-book"></i></div><div class="bullet-text"><p class="bullet-title">Episode 06：伝説の営業マンの知恵を継承</p><p class="bullet-content">クレーム対応を「顧客に貸しを作る機会」と捉えた営業トップの暗黙知を4つの問いで形式知化。若手が実践し成果を上げた事例</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            position: relative;            overflow: hidden;            background-color: #f8f9fa;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title {            font-size: 42px;            font-weight: 800;            color: #2c3e50;            margin-bottom: 40px;            position: relative;            padding-bottom: 15px;        }        .title:after {            content: '';            position: absolute;            bottom: 0;            left: 0;            width: 100px;            height: 4px;            background-color: #3498db;        }        .bullet-points {            display: flex;            flex-direction: column;            gap: 30px;        }        .bullet-item {            display: flex;            align-items: flex-start;        }        .bullet-icon {            color: #3498db;            font-size: 20px;            margin-right: 16px;            margin-top: 4px;        }        .bullet-text {            flex: 1;        }        .bullet-title {            font-size: 24px;            font-weight: 700;            color: #34495e;            margin-bottom: 8px;        }        .bullet-content {            font-size: 20px;            color: #5d6d7e;            line-height: 1.6;        }        .decoration {            position: absolute;            font-size: 240px;            opacity: 0.03;            color: #3498db;            z-index: 1;        }        .decoration-right {            bottom: -60px;            right: -40px;            transform: rotate(15deg);        }
</style>
