<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="13" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="header"><div class="chapter-badge">Chapter 4</div><h1 class="title">なぜ目標が必要なのか</h1></div><div class="content"><div class="main-content"><div class="key-points"><div class="key-point"><div class="key-icon"><i class="fas fa-exclamation-triangle"></i></div><p class="key-text">やってはいけない目標設定：他者評価起点・手段の目的化・具体性のない抽象論</p></div><div class="key-point"><div class="key-icon"><i class="fas fa-user-tie"></i></div><p class="key-text">Episode 07：「できるやつと見られたい」という見栄の目標が成長を阻害</p></div><div class="key-point"><div class="key-icon"><i class="fas fa-lightbulb"></i></div><p class="key-text">「あなたの人生の目標は何？」の問いで「会社の名医」を目標に変革</p></div></div></div><div class="visual-element"><div class="question-mark">?</div></div></div><div class="footer-quote"><p>「目的なき競争から目標に向かう行動へ。<span class="quote-highlight">他者の評価</span>ではなく<span class="quote-highlight">自分の成長</span>にフォーカスした時、真の変化が始まる」</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        position: relative;        overflow: hidden;        background-color: #f8f9fa;    }    .content-wrapper {        flex: 1;        display: flex;        flex-direction: column;        padding: 40px 80px;        z-index: 10;    }    .header {        display: flex;        align-items: center;        margin-bottom: 50px;    }    .chapter-badge {        background-color: #3498db;        color: white;        font-size: 26px;        font-weight: 700;        padding: 12px 24px;        border-radius: 8px;        margin-right: 25px;    }    .title {        font-size: 48px;        font-weight: 900;        color: #2c3e50;        line-height: 1.2;    }    .content {        display: flex;        flex: 1;    }    .main-content {        flex: 2;        display: flex;        flex-direction: column;        justify-content: center;    }    .key-points {        display: flex;        flex-direction: column;        gap: 30px;    }    .key-point {        display: flex;        align-items: flex-start;    }    .key-icon {        color: #3498db;        font-size: 28px;        margin-right: 20px;        margin-top: 5px;    }    .key-text {        font-size: 28px;        font-weight: 500;        color: #34495e;        line-height: 1.4;    }    .visual-element {        flex: 1;        display: flex;        justify-content: center;        align-items: center;    }    .question-mark {        font-size: 280px;        font-weight: 900;        color: rgba(52, 152, 219, 0.1);    }    .footer-quote {        font-size: 18px;        font-style: italic;        color: #7f8c8d;        margin-top: 40px;        text-align: right;    }    .quote-highlight {        color: #3498db;        font-weight: 700;    }
</style>
