<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="14" :total-pages="20">
<div class="slide-container"><div class="decoration decoration-right">?</div><div class="content-wrapper"><h1 class="title">Chapter 4｜人生の目標を考える</h1><div class="bullet-points"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-question-circle"></i></div><div class="bullet-text"><p class="bullet-title">人生の目標を考えるための3つの問い</p><p class="bullet-content">次の3ステップで目標を明確にする</p><div class="sub-bullet"><div class="sub-bullet-icon"><i class="fas fa-angle-right"></i></div><p class="sub-bullet-text">「重大な望ましくない現象は何か？」</p></div><div class="sub-bullet"><div class="sub-bullet-icon"><i class="fas fa-angle-right"></i></div><p class="sub-bullet-text">「どういう状況になればスゴイと思えるか？」</p></div><div class="sub-bullet"><div class="sub-bullet-icon"><i class="fas fa-angle-right"></i></div><p class="sub-bullet-text">「スゴイと思える状況を一言で言うと？」</p></div></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-mountain"></i></div><div class="bullet-text"><p class="bullet-title">高い目標が成長を生む理由</p><p class="bullet-content">生涯かけて達成できないほど高い目標が効果的</p><div class="sub-bullet"><div class="sub-bullet-icon"><i class="fas fa-angle-right"></i></div><p class="sub-bullet-text">達成不可能に見える目標こそが想像を超えた成長を促す</p></div><div class="sub-bullet"><div class="sub-bullet-icon"><i class="fas fa-angle-right"></i></div><p class="sub-bullet-text">仕事と人生の目標が重なるとモチベーションが持続する</p></div><div class="sub-bullet"><div class="sub-bullet-icon"><i class="fas fa-angle-right"></i></div><p class="sub-bullet-text">目標に向かう過程で得られる経験こそが真の成長</p></div></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            position: relative;            overflow: hidden;            background-color: #f8f9fa;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title {            font-size: 42px;            font-weight: 800;            color: #2c3e50;            margin-bottom: 40px;            position: relative;            padding-bottom: 15px;        }        .title:after {            content: '';            position: absolute;            bottom: 0;            left: 0;            width: 100px;            height: 4px;            background-color: #3498db;        }        .bullet-points {            display: flex;            flex-direction: column;            gap: 30px;        }        .bullet-item {            display: flex;            align-items: flex-start;        }        .bullet-icon {            color: #3498db;            font-size: 20px;            margin-right: 16px;            margin-top: 4px;        }        .bullet-text {            flex: 1;        }        .bullet-title {            font-size: 24px;            font-weight: 700;            color: #34495e;            margin-bottom: 8px;        }        .bullet-content {            font-size: 20px;            color: #5d6d7e;            line-height: 1.6;        }        .sub-bullet {            display: flex;            margin-top: 12px;            margin-left: 15px;            align-items: flex-start;        }        .sub-bullet-icon {            color: #3498db;            font-size: 16px;            margin-right: 12px;            margin-top: 4px;        }        .sub-bullet-text {            font-size: 18px;            color: #5d6d7e;        }        .decoration {            position: absolute;            font-size: 240px;            opacity: 0.03;            color: #3498db;            z-index: 1;        }        .decoration-right {            bottom: -60px;            right: -40px;            transform: rotate(15deg);        }
</style>
