<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="15" :total-pages="20">
<div class="slide-container"><div class="decoration decoration-right">?</div><div class="content-wrapper"><h1 class="title">Chapter 4｜目標達成への道のり</h1><div class="bullet-points"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-road"></i></div><div class="bullet-text"><p class="bullet-title">目標達成への3つの問い</p><p class="bullet-content">①重大な望ましくない現象は何か？<br/>②どういう状況になればスゴイと思えるか？<br/>③達成するために何をするか？</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-briefcase"></i></div><div class="bullet-text"><p class="bullet-title">Episode 08：会社は何のために私を雇ったか？</p><p class="bullet-content">著者の社会人人生を決定づけた問い。自信喪失から脱却し、前例打破に挑戦するきっかけとなった。既成概念を超え、新たな成果を上げる原動力に。</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-graduation-cap"></i></div><div class="bullet-text"><p class="bullet-title">Episode 09：ゴールドラット博士からの宿題</p><p class="bullet-content">「Surpass Me! (私を超えなさい！)」という挑戦。著者は「教科書に載る人生」を目標設定し、3つの問いで具体的な行動計画に落とし込み実行へ。</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            position: relative;            overflow: hidden;            background-color: #f8f9fa;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title {            font-size: 42px;            font-weight: 800;            color: #2c3e50;            margin-bottom: 40px;            position: relative;            padding-bottom: 15px;        }        .title:after {            content: '';            position: absolute;            bottom: 0;            left: 0;            width: 100px;            height: 4px;            background-color: #3498db;        }        .bullet-points {            display: flex;            flex-direction: column;            gap: 30px;        }        .bullet-item {            display: flex;            align-items: flex-start;        }        .bullet-icon {            color: #3498db;            font-size: 20px;            margin-right: 16px;            margin-top: 4px;        }        .bullet-text {            flex: 1;        }        .bullet-title {            font-size: 24px;            font-weight: 700;            color: #34495e;            margin-bottom: 8px;        }        .bullet-content {            font-size: 20px;            color: #5d6d7e;            line-height: 1.6;        }        .decoration {            position: absolute;            font-size: 240px;            opacity: 0.03;            color: #3498db;            z-index: 1;        }        .decoration-right {            bottom: -60px;            right: -40px;            transform: rotate(15deg);        }
</style>
