<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="16" :total-pages="20">
<div class="slide-container"><div class="decoration decoration-right">?</div><div class="content-wrapper"><h1 class="title">Chapter 4｜プロフェッショナルとは</h1><div class="bullet-points"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-tv"></i></div><div class="bullet-text"><p class="bullet-title">Episode 10：最後の問いの力</p><p class="bullet-content">NHK番組「プロフェッショナル 仕事の流儀」の最後に投げかけられる質問「プロフェッショナルとは？」が様々な知見と学びを生み出す。</p><p class="quote">「プロフェッショナルとは、本番に備えて常に訓練を怠らない人」（著者回答）</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-dumbbell"></i></div><div class="bullet-text"><p class="bullet-title">問いは筋トレ：継続的な訓練の重要性</p><p class="bullet-content">質問は筋力と同じく訓練で鍛えられる。良い問いのパターンを繰り返し実践することで、思考の質と効果が向上する。</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-sync-alt"></i></div><div class="bullet-text"><p class="bullet-title">日常での実践サイクル</p><p class="bullet-content">問いのテンプレート（4つの問い、3つの問いなど）を日々の仕事や生活に組み込み、実践→振り返り→改善のサイクルを回す。</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-arrow-alt-circle-up"></i></div><div class="bullet-text"><p class="bullet-title">高い目標と現実のギャップを埋める</p><p class="bullet-content">目標達成のための問いを持ち続けることで、現在地と理想の間を埋める具体的行動が明確になる。問いは成長の原動力となる。</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            position: relative;            overflow: hidden;            background-color: #f8f9fa;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title {            font-size: 42px;            font-weight: 800;            color: #2c3e50;            margin-bottom: 40px;            position: relative;            padding-bottom: 15px;        }        .title:after {            content: '';            position: absolute;            bottom: 0;            left: 0;            width: 100px;            height: 4px;            background-color: #3498db;        }        .bullet-points {            display: flex;            flex-direction: column;            gap: 30px;        }        .bullet-item {            display: flex;            align-items: flex-start;        }        .bullet-icon {            color: #3498db;            font-size: 20px;            margin-right: 16px;            margin-top: 4px;        }        .bullet-text {            flex: 1;        }        .bullet-title {            font-size: 24px;            font-weight: 700;            color: #34495e;            margin-bottom: 8px;        }        .bullet-content {            font-size: 20px;            color: #5d6d7e;            line-height: 1.6;        }        .decoration {            position: absolute;            font-size: 240px;            opacity: 0.03;            color: #3498db;            z-index: 1;        }        .decoration-right {            bottom: -60px;            right: -40px;            transform: rotate(15deg);        }        .quote {            font-style: italic;            padding: 15px;            background-color: rgba(52, 152, 219, 0.05);            border-left: 4px solid #3498db;            margin: 10px 0;            color: #34495e;        }
</style>
