<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="17" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="header"><div class="chapter-badge">Epilogue</div><h1 class="title">訓練すれば誰でも天才になれる</h1></div><div class="content"><div class="main-content"><div class="key-points"><div class="key-point"><div class="key-icon"><i class="fas fa-brain"></i></div><p class="key-text">能力は訓練で鍛えられる（頭も筋肉と同様に）</p></div><div class="key-point"><div class="key-icon"><i class="fas fa-shield-alt"></i></div><p class="key-text">ダークサイド回避：防衛反応を感じたら謝意と問いの再設計を</p></div><div class="key-point"><div class="key-icon"><i class="fas fa-compass"></i></div><p class="key-text">原点の2問い：目標は何か？ 達成のためにどんな質問をするか？</p></div></div></div><div class="visual-element"><div class="genius-icon"><i class="fas fa-lightbulb"></i></div></div></div><div class="footer-quote"><p>「鍛え抜かれたボディビルダーの体は、生まれつきではない。何年もの訓練で鍛え上げて自らつくったのだ。<span class="quote-highlight">頭も同じように何年もの訓練で鍛え上げることができる</span>」 — ゴールドラット博士</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        position: relative;        overflow: hidden;        background-color: #f8f9fa;    }    .content-wrapper {        flex: 1;        display: flex;        flex-direction: column;        padding: 40px 80px;        z-index: 10;    }    .header {        display: flex;        align-items: center;        margin-bottom: 50px;    }    .chapter-badge {        background-color: #3498db;        color: white;        font-size: 26px;        font-weight: 700;        padding: 12px 24px;        border-radius: 8px;        margin-right: 25px;    }    .title {        font-size: 48px;        font-weight: 900;        color: #2c3e50;        line-height: 1.2;    }    .content {        display: flex;        flex: 1;    }    .main-content {        flex: 2;        display: flex;        flex-direction: column;        justify-content: center;    }    .key-points {        display: flex;        flex-direction: column;        gap: 30px;    }    .key-point {        display: flex;        align-items: flex-start;    }    .key-icon {        color: #3498db;        font-size: 28px;        margin-right: 20px;        margin-top: 5px;    }    .key-text {        font-size: 28px;        font-weight: 500;        color: #34495e;        line-height: 1.4;    }    .visual-element {        flex: 1;        display: flex;        justify-content: center;        align-items: center;    }    .genius-icon {        font-size: 280px;        font-weight: 900;        color: rgba(52, 152, 219, 0.1);    }    .footer-quote {        font-size: 18px;        font-style: italic;        color: #7f8c8d;        margin-top: 40px;        text-align: right;    }    .quote-highlight {        color: #3498db;        font-weight: 700;    }
</style>
