<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="18" :total-pages="20">
<div class="slide-container"><div class="large-quote-mark">"</div><div class="content-wrapper"><h1 class="title">キーセンテンス集</h1><div class="quotes-container"><div class="quote-card"><div class="quote-icon quote-icon-left"><i class="fas fa-quote-left"></i></div><div class="quote-icon quote-icon-right"><i class="fas fa-quote-right"></i></div><p class="quote-text"><span class="quote-highlight">良い問いなくして良い答えなし</span>。誤った問いからは良い答えは見つからない。</p><p class="quote-source">— Chapter 1</p></div><div class="quote-card"><div class="quote-icon quote-icon-left"><i class="fas fa-quote-left"></i></div><div class="quote-icon quote-icon-right"><i class="fas fa-quote-right"></i></div><p class="quote-text">正解のない時代、<span class="quote-highlight">問う力が基礎スキル</span>。自分で問いを立てて、答えを出すことが要求される。</p><p class="quote-source">— Prologue</p></div><div class="quote-card highlight"><div class="quote-icon quote-icon-left"><i class="fas fa-quote-left"></i></div><div class="quote-icon quote-icon-right"><i class="fas fa-quote-right"></i></div><p class="quote-text"><span class="quote-highlight">学ぶことの最大の障害は答えを教えることではないか？</span>それは、自分で答えを見つける機会を永久に奪ってしまうからである。</p><p class="quote-source">— エリヤフ・M・ゴールドラット博士</p></div><div class="quote-card"><div class="quote-icon quote-icon-left"><i class="fas fa-quote-left"></i></div><div class="quote-icon quote-icon-right"><i class="fas fa-quote-right"></i></div><p class="quote-text">人への<span class="quote-highlight">『なぜ？』は用法注意</span>。自己防衛本能を刺激し、問題解決から遠ざけることもある。</p><p class="quote-source">— Chapter 1</p></div><div class="quote-card"><div class="quote-icon quote-icon-left"><i class="fas fa-quote-left"></i></div><div class="quote-icon quote-icon-right"><i class="fas fa-quote-right"></i></div><p class="quote-text"><span class="quote-highlight">望ましくない現象から理想を導く</span>。人はマイナスに敏感で、そこから共感と目標が生まれる。</p><p class="quote-source">— Chapter 2</p></div><div class="quote-card highlight"><div class="quote-icon quote-icon-left"><i class="fas fa-quote-left"></i></div><div class="quote-icon quote-icon-right"><i class="fas fa-quote-right"></i></div><p class="quote-text"><span class="quote-highlight">訓練すれば誰でも天才になれる</span>。頭も筋肉と同じように何年もの訓練で鍛え上げることができる。</p><p class="quote-source">— エリヤフ・M・ゴールドラット博士</p></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        position: relative;        overflow: hidden;        background-color: #f8f9fa;    }    .content-wrapper {        flex: 1;        display: flex;        flex-direction: column;        padding: 50px 70px;        z-index: 10;    }    .title {        font-size: 42px;        font-weight: 800;        color: #2c3e50;        margin-bottom: 40px;        position: relative;        padding-bottom: 15px;    }    .title:after {        content: '';        position: absolute;        bottom: 0;        left: 0;        width: 100px;        height: 4px;        background-color: #3498db;    }    .quotes-container {        display: flex;        flex-wrap: wrap;        gap: 25px;        flex: 1;    }    .quote-card {        flex-basis: calc(50% - 25px);        padding: 20px 25px;        border-left: 4px solid #3498db;        background-color: rgba(52, 152, 219, 0.05);        border-radius: 0 6px 6px 0;        position: relative;    }    .quote-card.highlight {        border-left-color: #e74c3c;        background-color: rgba(231, 76, 60, 0.05);    }    .quote-icon {        position: absolute;        font-size: 40px;        opacity: 0.1;        color: #3498db;    }    .quote-card.highlight .quote-icon {        color: #e74c3c;    }    .quote-icon-left {        top: 10px;        left: 10px;    }    .quote-icon-right {        bottom: 10px;        right: 10px;    }    .quote-text {        font-size: 20px;        line-height: 1.6;        color: #34495e;        margin-bottom: 10px;        position: relative;        z-index: 2;    }    .quote-source {        font-size: 16px;        font-weight: 500;        color: #7f8c8d;        text-align: right;    }    .quote-highlight {        font-weight: 700;        color: #3498db;    }    .highlight .quote-highlight {        color: #e74c3c;    }    .large-quote-mark {        position: absolute;        font-size: 340px;        opacity: 0.03;        color: #3498db;        z-index: 1;        right: -40px;        bottom: -60px;    }
</style>
