<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="2" :total-pages="20">
<div class="slide-container"><div class="decoration decoration-right">?</div><div class="content-wrapper"><h1 class="title">本書の概要と対象読者</h1><div class="bullet-points"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-book-open"></i></div><div class="bullet-text"><p class="bullet-title">概要</p><p class="bullet-content">答えよりも『問い』に価値を置く実践的ガイド</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-lightbulb"></i></div><div class="bullet-text"><p class="bullet-title">背景</p><p class="bullet-content">正解のない社会で、自ら問いを立てて答えを創る力が必須</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-users"></i></div><div class="bullet-text"><p class="bullet-title">対象</p><p class="bullet-content">学生〜社会人、企業・行政・教育関係者、問題解決が必要なすべての人</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-chart-line"></i></div><div class="bullet-text"><p class="bullet-title">読後に期待する変化</p><p class="bullet-content">目的志向の思考・再現可能な問題解決・自律的な目標設定</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            position: relative;            overflow: hidden;            background-color: #f8f9fa;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title {            font-size: 42px;            font-weight: 800;            color: #2c3e50;            margin-bottom: 40px;            position: relative;            padding-bottom: 15px;        }        .title:after {            content: '';            position: absolute;            bottom: 0;            left: 0;            width: 100px;            height: 4px;            background-color: #3498db;        }        .bullet-points {            display: flex;            flex-direction: column;            gap: 30px;        }        .bullet-item {            display: flex;            align-items: flex-start;        }        .bullet-icon {            color: #3498db;            font-size: 20px;            margin-right: 16px;            margin-top: 4px;        }        .bullet-text {            flex: 1;        }        .bullet-title {            font-size: 24px;            font-weight: 700;            color: #34495e;            margin-bottom: 8px;        }        .bullet-content {            font-size: 20px;            color: #5d6d7e;            line-height: 1.6;        }        .decoration {            position: absolute;            font-size: 240px;            opacity: 0.03;            color: #3498db;            z-index: 1;        }        .decoration-right {            bottom: -60px;            right: -40px;            transform: rotate(15deg);        }
</style>
