<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="20" :total-pages="20">
<div class="slide-container"><div class="large-question-mark">?</div><div class="content-wrapper"><h1 class="title">締め｜あなたの問いは何ですか？</h1><div class="action-container"><div class="action-set set-1"><div class="action-set-header"><div class="action-set-icon"><i class="fas fa-question-circle"></i></div><h2 class="action-set-title">読者への問いかけ</h2></div><div class="action-list"><div class="action-item"><div class="action-number">1</div><p class="action-text">いま最も解きたい課題は何かを一つ選ぶ</p></div><div class="action-item"><div class="action-number">2</div><p class="action-text">課題における「望ましくない現象」と「望ましい現象」を書き出す</p></div><div class="action-item"><div class="action-number">3</div><p class="action-text">問題を正確に定義する（現状と目標のギャップ）</p></div><div class="action-item"><div class="action-number">4</div><p class="action-text">本当の目標は何か？それを達成するにはどうすればよいか？</p></div></div></div><div class="action-set set-2"><div class="action-set-header"><div class="action-set-icon"><i class="fas fa-walking"></i></div><h2 class="action-set-title">実践への呼びかけ</h2></div><div class="action-list"><div class="action-item"><div class="action-number">1</div><p class="action-text">まずは『学びを深める4つの問い』で1サイクル実践してみる</p></div><div class="action-item"><div class="action-number">2</div><p class="action-text">自分の目標を「3つの問い」で見つめ直してみる</p></div><div class="action-item"><div class="action-number">3</div><p class="action-text">小さな問題解決に「気因解利」を適用してみる</p></div><div class="action-item"><div class="action-number">4</div><p class="action-text">振り返りを明日につなげ、問いの筋トレを継続する</p></div></div></div></div><div class="closing-message"><p>訓練すれば誰でも天才になれる ― 問いの力を鍛え続けよう</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        position: relative;        overflow: hidden;        background-color: #f8f9fa;    }    .content-wrapper {        flex: 1;        display: flex;        flex-direction: column;        padding: 50px 60px;        z-index: 10;    }    .title {        font-size: 42px;        font-weight: 800;        color: #2c3e50;        margin-bottom: 30px;        position: relative;        padding-bottom: 15px;    }    .title:after {        content: '';        position: absolute;        bottom: 0;        left: 0;        width: 100px;        height: 4px;        background-color: #9b59b6;    }    .action-container {        display: flex;        flex-direction: column;        gap: 25px;        flex: 1;    }    .action-set {        background-color: rgba(155, 89, 182, 0.05);        border-radius: 8px;        padding: 20px;        border-left: 5px solid #9b59b6;    }    .action-set.set-2 {        border-left-color: #f39c12;    }    .action-set-header {        display: flex;        align-items: center;        margin-bottom: 15px;    }    .action-set-icon {        width: 40px;        height: 40px;        display: flex;        justify-content: center;        align-items: center;        background-color: #9b59b6;        color: white;        font-size: 20px;        border-radius: 50%;        margin-right: 15px;    }    .action-set.set-2 .action-set-icon {        background-color: #f39c12;    }    .action-set-title {        font-size: 22px;        font-weight: 700;        color: #34495e;    }    .action-list {        display: flex;        flex-direction: column;        gap: 12px;        padding-left: 55px;    }    .action-item {        display: flex;        align-items: center;    }    .action-number {        width: 26px;        height: 26px;        display: flex;        justify-content: center;        align-items: center;        background-color: #9b59b6;        color: white;        font-size: 14px;        font-weight: 700;        border-radius: 50%;        margin-right: 12px;    }    .action-set.set-2 .action-number {        background-color: #f39c12;    }    .action-text {        font-size: 18px;        font-weight: 500;        color: #2c3e50;        flex: 1;    }    .large-question-mark {        position: absolute;        font-size: 340px;        opacity: 0.03;        color: #9b59b6;        z-index: 1;        right: -40px;        bottom: -60px;    }    .closing-message {        text-align: center;        font-size: 24px;        font-weight: 700;        color: #34495e;        margin-top: 30px;        padding: 15px;        background-color: rgba(155, 89, 182, 0.1);        border-radius: 8px;    }
</style>
