<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="3" :total-pages="20">
<div class="slide-container"><div class="decoration decoration-bottom-right">?</div><div class="content-wrapper"><h1 class="title">目次</h1><div class="toc-container"><div class="toc-item"><div class="toc-icon"><i class="fas fa-book-open"></i></div><div class="toc-number">Prologue</div><div class="toc-text">ブレークスルーを生む<span class="toc-highlight">『問いの力』</span></div></div><div class="toc-item"><div class="toc-icon"><i class="fas fa-exclamation-triangle"></i></div><div class="toc-number">Chapter 1</div><div class="toc-text">悪い問い</div></div><div class="toc-item"><div class="toc-icon"><i class="fas fa-lightbulb"></i></div><div class="toc-number">Chapter 2</div><div class="toc-text">良い問い</div></div><div class="toc-item"><div class="toc-icon"><i class="fas fa-check-circle"></i></div><div class="toc-number">Chapter 3</div><div class="toc-text">正解をつくる</div></div><div class="toc-item"><div class="toc-icon"><i class="fas fa-bullseye"></i></div><div class="toc-number">Chapter 4</div><div class="toc-text">成長し続けられる目標設定</div></div><div class="toc-item"><div class="toc-icon"><i class="fas fa-star"></i></div><div class="toc-number">Epilogue</div><div class="toc-text">訓練すれば誰でも天才になれる</div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        position: relative;        overflow: hidden;        background-color: #f8f9fa;    }    .content-wrapper {        flex: 1;        display: flex;        flex-direction: column;        padding: 60px 80px;        z-index: 10;    }    .title {        font-size: 42px;        font-weight: 800;        color: #2c3e50;        margin-bottom: 40px;        position: relative;        padding-bottom: 15px;    }    .title:after {        content: '';        position: absolute;        bottom: 0;        left: 0;        width: 100px;        height: 4px;        background-color: #3498db;    }    .toc-container {        display: flex;        flex-direction: column;        gap: 25px;        margin-left: 20px;    }    .toc-item {        display: flex;        align-items: center;    }    .toc-number {        font-size: 22px;        font-weight: 700;        color: #3498db;        min-width: 120px;    }    .toc-text {        font-size: 26px;        font-weight: 600;        color: #2c3e50;    }    .toc-icon {        color: #3498db;        font-size: 26px;        margin-right: 20px;        width: 30px;        text-align: center;    }    .toc-highlight {        color: #e74c3c;        font-weight: 700;    }    .decoration {        position: absolute;        font-size: 240px;        opacity: 0.03;        color: #3498db;        z-index: 1;    }    .decoration-bottom-right {        bottom: -60px;        right: -40px;        transform: rotate(15deg);    }
</style>
