<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="4" :total-pages="20">
<div class="slide-container"><div class="content-wrapper"><div class="header"><div class="chapter-badge">Prologue</div><h1 class="title">問いの力とは</h1></div><div class="content"><div class="main-content"><div class="key-points"><div class="key-point"><div class="key-icon"><i class="fas fa-book"></i></div><p class="key-text">寓話『アリとキリギリス』：前提を疑う問いが未来を変える</p></div><div class="key-point"><div class="key-icon"><i class="fas fa-globe"></i></div><p class="key-text">正解のない社会：自分で問いを立て、答えを創る能力が標準に</p></div><div class="key-point"><div class="key-icon"><i class="fas fa-quote-right"></i></div><p class="key-text">ゴールドラット博士：「人が考えるようになるには、『！』より『？』のほうが良い」</p></div></div></div><div class="visual-element"><div class="question-mark">?</div></div></div><div class="footer-quote"><p>「学ぶことの最大の障害は<span class="quote-highlight">答えを教えること</span>ではないか？それは、<span class="quote-highlight">自分で答えを見つける機会を永久に奪ってしまう</span>からである」 — エリヤフ・M・ゴールドラット</p></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {        margin: 0;        padding: 0;        font-family: 'Noto Sans JP', sans-serif;    }    .slide-container {        width: 1280px;        min-height: 720px;        display: flex;        position: relative;        overflow: hidden;        background-color: #f8f9fa;    }    .content-wrapper {        flex: 1;        display: flex;        flex-direction: column;        padding: 40px 80px;        z-index: 10;    }    .header {        display: flex;        align-items: center;        margin-bottom: 50px;    }    .chapter-badge {        background-color: #3498db;        color: white;        font-size: 26px;        font-weight: 700;        padding: 12px 24px;        border-radius: 8px;        margin-right: 25px;    }    .title {        font-size: 48px;        font-weight: 900;        color: #2c3e50;        line-height: 1.2;    }    .content {        display: flex;        flex: 1;    }    .main-content {        flex: 2;        display: flex;        flex-direction: column;        justify-content: center;    }    .key-points {        display: flex;        flex-direction: column;        gap: 30px;    }    .key-point {        display: flex;        align-items: flex-start;    }    .key-icon {        color: #3498db;        font-size: 28px;        margin-right: 20px;        margin-top: 5px;    }    .key-text {        font-size: 28px;        font-weight: 500;        color: #34495e;        line-height: 1.4;    }    .visual-element {        flex: 1;        display: flex;        justify-content: center;        align-items: center;    }    .question-mark {        font-size: 280px;        font-weight: 900;        color: rgba(52, 152, 219, 0.1);    }    .footer-quote {        font-size: 18px;        font-style: italic;        color: #7f8c8d;        margin-top: 40px;        text-align: right;    }    .quote-highlight {        color: #3498db;        font-weight: 700;    }
</style>
