<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="5" :total-pages="20">
<div class="slide-container"><div class="decoration decoration-right">!</div><div class="content-wrapper"><h1 class="title">Chapter 1｜悪い問いとは（前編）</h1><div class="bullet-points"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-exclamation-triangle"></i></div><div class="bullet-text"><p class="bullet-title">質問に潜む危険</p><p class="bullet-content">「問いの力」は諸刃の剣。使い方を誤ると相手を傷つけるだけでなく、自らも傷つき取り返しのつかない事態に</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-times-circle"></i></div><div class="bullet-text"><p class="bullet-title">悪い問いの定義</p><p class="bullet-content">「問題解決につながらない。それどころか問題解決から遠ざかる問いは『悪い問い』である」</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-clipboard-list"></i></div><div class="bullet-text"><p class="bullet-title">悪い問いの典型的特徴</p><p class="bullet-content">・相手の言い訳を引き出してしまう<br/>・自責や落ち込みを誘発する<br/>・怒りを買い、人間関係を悪化させる</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            position: relative;            overflow: hidden;            background-color: #f8f9fa;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title {            font-size: 42px;            font-weight: 800;            color: #2c3e50;            margin-bottom: 40px;            position: relative;            padding-bottom: 15px;        }        .title:after {            content: '';            position: absolute;            bottom: 0;            left: 0;            width: 100px;            height: 4px;            background-color: #e74c3c;        }        .bullet-points {            display: flex;            flex-direction: column;            gap: 30px;        }        .bullet-item {            display: flex;            align-items: flex-start;        }        .bullet-icon {            color: #e74c3c;            font-size: 20px;            margin-right: 16px;            margin-top: 4px;        }        .bullet-text {            flex: 1;        }        .bullet-title {            font-size: 24px;            font-weight: 700;            color: #34495e;            margin-bottom: 8px;        }        .bullet-content {            font-size: 20px;            color: #5d6d7e;            line-height: 1.6;        }        .decoration {            position: absolute;            font-size: 240px;            opacity: 0.03;            color: #e74c3c;            z-index: 1;        }        .decoration-right {            bottom: -60px;            right: -40px;            transform: rotate(15deg);        }
</style>
