<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="7" :total-pages="20">
<div class="slide-container"><div class="decoration decoration-right">?</div><div class="content-wrapper"><h1 class="title">Chapter 2｜問題の定義（前編）</h1><div class="bullet-points"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-square-root-alt"></i></div><div class="bullet-text"><p class="bullet-title">問題とは「現状と目標のギャップ」</p><p class="bullet-content">「問題を正確に定義しなさい。そうすれば、問題は半分解決したのも同じだ」</p><p class="bullet-content">日本工業規格(JIS)：問題とは「設定してある目標と現実との、対策して克服する必要のあるギャップ」</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-medal"></i></div><div class="bullet-text"><p class="bullet-title">Episode 01：山下泰裕氏の目標設定</p><p class="bullet-content">柔道家・山下泰裕氏の例：「勝つこと」より「理想の柔道を追求」という目標</p><p class="bullet-content">「自分はどういう柔道をしたいのか？」という問いが、前人未到の203連勝という成果を生んだ</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-bullseye"></i></div><div class="bullet-text"><p class="bullet-title">目標なくして良い問いなし</p><p class="bullet-content">目標が設定できなければ、良い問いをつくることはできない</p><p class="bullet-content">目標につながる「問い」が問題解決の鍵となる</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            position: relative;            overflow: hidden;            background-color: #f8f9fa;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title {            font-size: 42px;            font-weight: 800;            color: #2c3e50;            margin-bottom: 40px;            position: relative;            padding-bottom: 15px;        }        .title:after {            content: '';            position: absolute;            bottom: 0;            left: 0;            width: 100px;            height: 4px;            background-color: #3498db;        }        .bullet-points {            display: flex;            flex-direction: column;            gap: 30px;        }        .bullet-item {            display: flex;            align-items: flex-start;        }        .bullet-icon {            color: #3498db;            font-size: 20px;            margin-right: 16px;            margin-top: 4px;        }        .bullet-text {            flex: 1;        }        .bullet-title {            font-size: 24px;            font-weight: 700;            color: #34495e;            margin-bottom: 8px;        }        .bullet-content {            font-size: 20px;            color: #5d6d7e;            line-height: 1.6;        }        .decoration {            position: absolute;            font-size: 240px;            opacity: 0.03;            color: #3498db;            z-index: 1;        }        .decoration-right {            bottom: -60px;            right: -40px;            transform: rotate(15deg);        }        .quote {            font-style: italic;            color: #7f8c8d;            padding-left: 20px;            border-left: 3px solid #3498db;            margin: 10px 0;        }
</style>
