<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="8" :total-pages="20">
<div class="slide-container"><div class="decoration decoration-right">?</div><div class="content-wrapper"><h1 class="title">Chapter 2｜良い問いを作る手順（中編）</h1><div class="bullet-points"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-list-ol"></i></div><div class="bullet-text"><p class="bullet-title">良い問いの2ステップ</p><p class="bullet-content">1.「目標は何か？」<br/>2.「目標を達成するためにはどうしたらいいか？」<br/>この2つを順番に考えるだけで良い問いができあがる</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-exclamation-circle"></i></div><div class="bullet-text"><p class="bullet-title">問題定義の3つの問い</p><p class="bullet-content">・「望ましくない現象は何ですか？」（現状把握）<br/>・「望ましい現象は何ですか？」（目標設定）<br/>・「このギャップが問題ですよね？」（問題明確化）</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-lightbulb"></i></div><div class="bullet-text"><p class="bullet-title">望ましくない現象を問う重要性</p><p class="bullet-content">・人はマイナスに敏感で、現実の痛みを具体的に語りやすい<br/>・最初に「望ましくない現象」を聞くと、自然に「望ましい現象」を考えやすくなる<br/>・共通認識が形成され、より効果的な問題解決に繋がる</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            position: relative;            overflow: hidden;            background-color: #f8f9fa;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title {            font-size: 42px;            font-weight: 800;            color: #2c3e50;            margin-bottom: 40px;            position: relative;            padding-bottom: 15px;        }        .title:after {            content: '';            position: absolute;            bottom: 0;            left: 0;            width: 100px;            height: 4px;            background-color: #3498db;        }        .bullet-points {            display: flex;            flex-direction: column;            gap: 30px;        }        .bullet-item {            display: flex;            align-items: flex-start;        }        .bullet-icon {            color: #3498db;            font-size: 20px;            margin-right: 16px;            margin-top: 4px;        }        .bullet-text {            flex: 1;        }        .bullet-title {            font-size: 24px;            font-weight: 700;            color: #34495e;            margin-bottom: 8px;        }        .bullet-content {            font-size: 20px;            color: #5d6d7e;            line-height: 1.6;        }        .decoration {            position: absolute;            font-size: 240px;            opacity: 0.03;            color: #3498db;            z-index: 1;        }        .decoration-right {            bottom: -60px;            right: -40px;            transform: rotate(15deg);        }
</style>
