<template>
  <SlidePageWrapper slide-id="B0BX2VFT58" page-title="いま、あなたに必要なのは答えじゃない。問いの力だ。" :current-page="9" :total-pages="20">
<div class="slide-container"><div class="decoration decoration-right">?</div><div class="content-wrapper"><h1 class="title">Chapter 2｜エピソードから学ぶ（後編）</h1><div class="bullet-points"><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-laptop"></i></div><div class="bullet-text"><p class="bullet-title">Episode 02：手段と目的の取り違え</p><p class="bullet-content">「SCMシステムの導入」が目的化。「目的は何ですか？」という問いで本来の目標（リードタイム半減、在庫半減、顧客サービス向上）を明確化し、根本解決策を発見</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-users"></i></div><div class="bullet-text"><p class="bullet-title">Episode 03：会議の本質を問う</p><p class="bullet-content">「会議効率化」という手段が目的化。会議の本来の目的は"みんなで会って解決策を生み出す場"と再定義することで、不毛な会議から成果の出る会議へ</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-exclamation-triangle"></i></div><div class="bullet-text"><p class="bullet-title">Episode 04：危険な自責の問い</p><p class="bullet-content">「なぜ目標が達成できないんだ」という自責の問いはメンタルヘルスを悪化させる危険性。意義ある目標を持つことが再生のきっかけに</p></div></div><div class="bullet-item"><div class="bullet-icon"><i class="fas fa-clock"></i></div><div class="bullet-text"><p class="bullet-title">Episode 05：60秒黙る</p><p class="bullet-content">答えを教えるのではなく、「何か助けられることはないか？」と問い、60秒黙って考える時間を与える。現場から創造的な解決策が生まれ、人が成長する</p></div></div></div></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {            margin: 0;            padding: 0;            font-family: 'Noto Sans JP', sans-serif;        }        .slide-container {            width: 1280px;            min-height: 720px;            display: flex;            position: relative;            overflow: hidden;            background-color: #f8f9fa;        }        .content-wrapper {            flex: 1;            display: flex;            flex-direction: column;            padding: 60px 80px;            z-index: 10;        }        .title {            font-size: 42px;            font-weight: 800;            color: #2c3e50;            margin-bottom: 40px;            position: relative;            padding-bottom: 15px;        }        .title:after {            content: '';            position: absolute;            bottom: 0;            left: 0;            width: 100px;            height: 4px;            background-color: #3498db;        }        .bullet-points {            display: flex;            flex-direction: column;            gap: 25px;        }        .bullet-item {            display: flex;            align-items: flex-start;        }        .bullet-icon {            color: #3498db;            font-size: 20px;            margin-right: 16px;            margin-top: 4px;        }        .bullet-text {            flex: 1;        }        .bullet-title {            font-size: 24px;            font-weight: 700;            color: #34495e;            margin-bottom: 8px;        }        .bullet-content {            font-size: 20px;            color: #5d6d7e;            line-height: 1.6;        }        .decoration {            position: absolute;            font-size: 240px;            opacity: 0.03;            color: #3498db;            z-index: 1;        }        .decoration-right {            bottom: -60px;            right: -40px;            transform: rotate(15deg);        }
</style>
