<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="第3章｜'裏目'に出る気遣いとは" :current-page="10" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- 背景の大きな章番号 --><div class="chapter-number text-[300px] font-bold">3</div><!-- ヘッダー部分 --><div class="mb-12 relative"><p class="slide-title text-4xl font-bold">第3章｜"裏目"に出る気遣いとは</p><div class="accent-line mt-4"></div></div><!-- 主要ポイント部分 --><div class="flex flex-col gap-10 max-w-3xl z-10 relative"><!-- ポイント1 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-exchange-alt fa-lg"></i></div><div class="flex-1"><div class="point-item pl-4"><p class="text-xl font-medium text-gray-800 mb-2">意図と受け手の解釈のズレが原因</p><p class="text-gray-600">送り手の「良かれと思って」が、受け手には「負担・押し付け・距離感の侵害」に感じられる</p></div></div></div><!-- ポイント2 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-mask fa-lg"></i></div><div class="flex-1"><div class="point-item pl-4"><p class="text-xl font-medium text-gray-800 mb-2">"見える善意"に寄り過ぎると本質を外す</p><p class="text-gray-600">表層の気遣い・形だけの配慮は、相手のニーズや状況に合わない場合が多い</p></div></div></div><!-- ポイント3 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-balance-scale fa-lg"></i></div><div class="flex-1"><div class="point-item pl-4"><p class="text-xl font-medium text-gray-800 mb-2">判断軸：状況・関係性・相手の選好</p><p class="text-gray-600">気遣いは一律ではなく、TPOや関係性、相手の好みに応じて微調整する必要がある</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-200 text-center"><p class="text-sm text-gray-500">気遣いがなぜ裏目に出るのか、理解していますか？</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .chapter-number {      font-family: 'Noto Serif JP', serif;      color: #e53e3e;      opacity: 0.1;      position: absolute;      top: 0;      left: 0;      z-index: 0;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;      position: relative;      z-index: 1;    }    .accent-line {      width: 100px;      height: 4px;      background-color: #e53e3e;      margin-bottom: 30px;    }    .point-item {      border-left: 3px solid #e53e3e;    }    .icon-box {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }
</style>
