<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="第3章①｜見えるところに気合い／愛想は'かけられてから'" :current-page="11" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-10"><p class="slide-title text-3xl font-bold">第3章①｜見えるところに気合い／愛想は"かけられてから"</p><div class="accent-line mt-4"></div></div><!-- 箇条書きコンテンツ部分 --><div class="flex flex-col gap-8 max-w-4xl"><!-- ポイント1: 見えるところに気合い --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-eye fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">表層の整えすぎ→行為の目的を見失う</p><p class="bullet-content">相手に見えるところだけを過剰に飾り立てると、本来の気遣いの目的（相手の心地よさや便利さ）が後回しになり、不自然さを感じさせます。</p><p class="bullet-content mt-2"><span class="font-bold text-indigo-700">代替：</span> 要所では清潔感や丁寧さを保ちつつ、見た目よりも相手の実質的な満足を優先する姿勢を持ちましょう。</p></div></div></div><!-- ポイント2: 愛想は"かけられてから" --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-smile fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">常時ハイテンション→相手のペースを乱す</p><p class="bullet-content">必要以上に愛想よく振る舞い続けると、相手に疲労感や違和感を与え、会話や関係の自然なリズムを崩してしまいます。</p><p class="bullet-content mt-2"><span class="font-bold text-indigo-700">代替：</span> 基本は自然体で、相手から話しかけられたときに適切な明るさや反応で応える方が、相手も安心して自分のペースを保てます。</p></div></div></div><!-- ポイント3: 具体例 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-lightbulb fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">実践例：バランス感覚が鍵</p><p class="bullet-content">接客の場面では笑顔と丁寧さを基本としつつも、顧客の様子に合わせて対応の強弱をつける。休息したい様子の顧客には必要最小限の会話で、逆に話したそうな顧客には積極的なコミュニケーションを心がける。</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">自然体の姿勢こそが、真の気遣いの第一歩です</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .bullet-item {      border-left: 3px solid #e53e3e;    }    .icon-box {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }    .bullet-title {      color: #1a365d;      font-weight: 600;    }    .bullet-content {      color: #4a5568;    }
</style>
