<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="第3章②｜体調、話題、メールの気遣い" :current-page="12" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-10"><p class="slide-title text-3xl font-bold">第3章②｜体調、話題、メールの気遣い</p><div class="accent-line mt-4"></div></div><!-- 箇条書きコンテンツ部分 --><div class="flex flex-col gap-8 max-w-4xl"><!-- ポイント1: 体調への声かけ --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-heart-pulse fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">体調配慮はプライバシー侵襲になり得る</p><p class="bullet-content"><span class="problem">問題点：</span> 見た目の変化に即反応し「具合悪いの？」と聞くことが、相手の負担やプライバシー侵害に</p><p class="bullet-content mt-2"><span class="solution">代替案：</span> 観察と選択肢提示を基本に。「何かできることはある？」など、相手が話したい時に話せる余白を作る</p></div></div></div><!-- ポイント2: 話題提供のしすぎ --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-comments fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">話題を連射→負担増。必要十分でOK</p><p class="bullet-content"><span class="problem">問題点：</span> 会話を盛り上げようと次々話題を振ると、相手は反応する義務感や疲労感を抱く</p><p class="bullet-content mt-2"><span class="solution">代替案：</span> 1〜2つの話題で相手の反応を見て、会話が自然に広がる流れを尊重。無理に話題作りをしない</p></div></div></div><!-- ポイント3: メール簡潔すぎ --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-envelope fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">"要件のみ"メール連発→冷たさの印象</p><p class="bullet-content"><span class="problem">問題点：</span> 効率優先の簡潔すぎるビジネスメールが、機械的で冷淡な印象を与える</p><p class="bullet-content mt-2"><span class="solution">代替案：</span> 簡潔さを保ちつつも、「お疲れ様です」や季節の挨拶など、ひと言の温度感を添えると関係性が育つ</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">相手の状況・プライバシー・心理的安全を尊重する配慮が大切です</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .bullet-item {      border-left: 3px solid #e53e3e;    }    .icon-box {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }    .bullet-title {      color: #1a365d;      font-weight: 600;    }    .bullet-content {      color: #4a5568;    }    .problem {      color: #e53e3e;      font-weight: 500;    }    .solution {      color: #2b6cb0;      font-weight: 500;    }
</style>
