<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="第4章①｜会話の気遣い：相槌・同意・沈黙" :current-page="13" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-10"><p class="slide-title text-3xl font-bold">第4章①｜会話の気遣い：相槌・同意・沈黙</p><div class="accent-line mt-4"></div></div><!-- 箇条書きコンテンツ部分 --><div class="flex flex-col gap-8 max-w-4xl"><!-- ポイント1: 相槌 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-comments fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">相槌は頻度とバリエーションを調整</p><p class="bullet-content">「はい」「そうですね」などの単調な繰り返しや、過剰な相槌は不自然さや形式的印象を与えます。タイミングや場に合わせた多様な表現と適度な頻度が重要です。</p></div></div></div><!-- ポイント2: 同意フレーズ --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-thumbs-up fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">同意フレーズの多用に注意</p><p class="bullet-content">「そうですよね」などの同意表現の多用は、相手の意見を吟味せずに賛同する思考停止と捉えられることも。時には「なるほど」など中立的な反応や、自分の考えを添えることで対話が深まります。</p></div></div></div><!-- ポイント3: 沈黙 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-pause-circle fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">沈黙は敵ではない</p><p class="bullet-content">会話の沈黙に不安を感じて埋めようとしがちですが、沈黙は観察・思考・整理の時間として有効です。相手の表情や場の空気を読み、次の一歩を考える余白として活用しましょう。</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">自然体の会話から信頼関係が生まれます</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .bullet-item {      border-left: 3px solid #e53e3e;    }    .icon-box {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }    .bullet-title {      color: #1a365d;      font-weight: 600;    }    .bullet-content {      color: #4a5568;    }
</style>
