<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="第4章②｜雑談の入り口／切り上げ方／オンライン" :current-page="14" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-10"><p class="slide-title text-3xl font-bold">第4章②｜雑談の入り口／切り上げ方／オンライン</p><div class="accent-line mt-4"></div></div><!-- 箇条書きコンテンツ部分 --><div class="flex flex-col gap-8 max-w-4xl"><!-- ポイント1: 雑談の入り口 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-door-open fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">入り口：近況・天気・場に関する共通項から軽く</p><p class="bullet-content">難しく考えすぎず、天候や季節の話題、その場の状況など誰もが答えやすい共通の話題から始めると自然。「最近どうですか？」は相手によっては負担に感じることも</p></div></div></div><!-- ポイント2: 切り上げ方 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-hourglass-end fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">切り上げ：時間・次予定を理由に、区切りを明確に</p><p class="bullet-content">「お話の途中で申し訳ありません」と前置きし、時間や次の予定を理由に自然に切り上げる。謝りすぎず、さりげなく明確な終了サインを出すのがポイント</p></div></div></div><!-- ポイント3: オンライン会議 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-video fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">オンライン：相槌はややオーバー目＋非言語を意識</p><p class="bullet-content">対面より反応が伝わりにくいため、うなずきや表情はやや大げさに。カメラをONにする、視線をカメラに向ける、音声が途切れても焦らないなど、オンライン特有の配慮を</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">会話の始まりと終わりにこそ、真の気遣いが表れます</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .bullet-item {      border-left: 3px solid #e53e3e;    }    .icon-box {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }    .bullet-title {      color: #1a365d;      font-weight: 600;    }    .bullet-content {      color: #4a5568;    }
</style>
