<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="第5章｜多様性時代の気遣い" :current-page="15" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-10"><p class="slide-title text-3xl font-bold">第5章｜多様性時代の気遣い</p><div class="accent-line mt-4"></div></div><!-- 箇条書きコンテンツ部分 --><div class="flex flex-col gap-8 max-w-4xl"><!-- ポイント1: 常識の押し付け回避 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-globe-asia fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">"自分の常識"の押し付けを避ける</p><p class="bullet-content">「当たり前」は人それぞれ。文化・宗教・食習慣・働き方など、多様な背景を持つ人々との関わりでは、自分の価値観を絶対視せず、相手の「普通」も尊重する姿勢が重要です</p></div></div></div><!-- ポイント2: 文化・宗教配慮 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-hands fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">わからないは聞く：事前確認と選択肢提示</p><p class="bullet-content">食事制限・礼拝時間・休日習慣など、配慮すべき事項は「察する」より「確認する」。複数の選択肢を用意し、相手が選びやすい環境を整えることが真の気遣いです</p></div></div></div><!-- ポイント3: メール・会議の柔軟性 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-comments fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">コミュニケーションスタイルの多様性を理解</p><p class="bullet-content">メール・挨拶・会議運用のカルチャー差に留意し、一律のルールを押し付けず、状況に応じた柔軟なスタイルを選択。形式よりも相手の理解と快適さを優先しましょう</p></div></div></div><!-- ポイント4: 互いの尊重 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-handshake fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">互いに尊重し、場のルールは合意形成で</p><p class="bullet-content">「正しい・間違い」の二項対立ではなく、互いの背景や価値観を尊重した上で、共に心地よい関係性を築くための対話を大切に。多様性は視野を広げる機会と捉えましょう</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">多様性の時代こそ、自分の「当たり前」を問い直す姿勢が大切です</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .bullet-item {      border-left: 3px solid #e53e3e;    }    .icon-box {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }    .bullet-title {      color: #1a365d;      font-weight: 600;    }    .bullet-content {      color: #4a5568;    }
</style>
