<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="第6章｜さりげない気遣いとは" :current-page="16" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- 背景の大きな章番号 --><div class="chapter-number text-[300px] font-bold">6</div><!-- ヘッダー部分 --><div class="mb-12 relative"><p class="slide-title text-4xl font-bold">第6章｜さりげない気遣いとは</p><div class="accent-line mt-4"></div></div><!-- 主要ポイント部分 --><div class="flex flex-col gap-10 max-w-3xl z-10 relative"><!-- ポイント1 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-feather-alt fa-lg"></i></div><div class="flex-1"><div class="point-item pl-4"><p class="text-xl font-medium text-gray-800 mb-2">自然体の配慮</p><p class="text-gray-600">出しゃばらない、相手の自律を尊重する。必要以上に介入せず、相手のペースを守る</p></div></div></div><!-- ポイント2 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-hands-helping fa-lg"></i></div><div class="flex-1"><div class="point-item pl-4"><p class="text-xl font-medium text-gray-800 mb-2">小さな行為の積み重ね</p><p class="text-gray-600">"してあげた感"を出さない、目立たない配慮の集積。相手が気づかないくらいの自然さが理想</p></div></div></div><!-- ポイント3 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-heart fa-lg"></i></div><div class="flex-1"><div class="point-item pl-4"><p class="text-xl font-medium text-gray-800 mb-2">心地よさと安心の優先</p><p class="text-gray-600">評価や見返りではなく、その場の空気感、相手の安心感を最優先にした振る舞い</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-200 text-center"><p class="text-sm text-gray-500">大人の気配りとは、見えないところにこそ真価がある</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .chapter-number {      font-family: 'Noto Serif JP', serif;      color: #e53e3e;      opacity: 0.1;      position: absolute;      top: 0;      left: 0;      z-index: 0;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;      position: relative;      z-index: 1;    }    .accent-line {      width: 100px;      height: 4px;      background-color: #e53e3e;      margin-bottom: 30px;    }    .point-item {      border-left: 3px solid #e53e3e;    }    .icon-box {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }
</style>
