<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="第6章①｜日常の配慮エピソード" :current-page="17" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-10"><p class="slide-title text-3xl font-bold">第6章①｜日常の配慮エピソード</p><div class="accent-line mt-4"></div></div><!-- 箇条書きコンテンツ部分 --><div class="flex flex-col gap-8 max-w-4xl"><!-- ポイント1: エレベーター --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-door-open fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">エレベーター：ドアを即閉しない、後続への配慮</p><p class="bullet-content">ドアを閉めるボタンを慌てて押さず、後ろから来る人がいないか確認。また降りる際は、次に乗る人のためにドアを少し長めに開けておく心遣い。</p></div></div></div><!-- ポイント2: 洗面台 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-sink fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">共有スペース：濡れた洗面台をひと拭き</p><p class="bullet-content">公共の洗面台が濡れていたら、自分のためだけでなく後に使う人のために紙タオルで軽く拭いておく。「掃除された」という印象ではなく、さりげない配慮として。</p></div></div></div><!-- ポイント3: 時間配慮 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-clock fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">時間配慮：時計やスマホを何度も見ない</p><p class="bullet-content">会話中や会議中、相手の話を聞きながら何度も腕時計やスマホを見るのは「早く終わらせたい」という印象を与える。時間を気にする場合でも、露骨な仕草は控えましょう。</p></div></div></div><!-- ポイント4: 手土産 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-gift fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">手土産：否定語ではなく前向きな一言を添える</p><p class="bullet-content">「つまらないものですが」などの否定的な言葉を添えるのではなく、「お口に合うと嬉しいです」など前向きな一言を添えることで、贈る側も受け取る側も気持ちよく手土産を楽しめます。</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">大人のさりげない気遣いは、目立たないからこそ心に残ります</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .bullet-item {      border-left: 3px solid #e53e3e;    }    .icon-box {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }    .bullet-title {      color: #1a365d;      font-weight: 600;    }    .bullet-content {      color: #4a5568;    }
</style>
