<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="第6章②｜ビジネスの配慮エピソード" :current-page="18" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-10"><p class="slide-title text-3xl font-bold">第6章②｜ビジネスの配慮エピソード</p><div class="accent-line mt-4"></div></div><!-- 箇条書きコンテンツ部分 --><div class="flex flex-col gap-8 max-w-4xl"><!-- ポイント1: 名前で呼ぶ --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-user-tag fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">名前で呼ぶ：初対面から"名前"を会話に織り込む</p><p class="bullet-content">相手の名前を適度に会話の中で使うことで親近感が生まれます。初対面でも、挨拶時に名前を確認し、その後の会話で自然に取り入れることが効果的です</p></div></div></div><!-- ポイント2: 状況報告 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-info-circle fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">状況報告：待ち時間が生じたら進捗を短く共有</p><p class="bullet-content">相手を待たせる状況では、「あと何分かかる」「現在どういう状況か」を簡潔に伝えることで不安や不満を軽減。情報共有は最大の気遣いです</p></div></div></div><!-- ポイント3: 幹事への感謝 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-hands-helping fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">幹事・主催へのねぎらいと言語化された感謝</p><p class="bullet-content">イベントや会議の準備をした人への「ありがとう」を明確に伝える。具体的に「〇〇の準備、ありがとうございました」と言語化することで、感謝が確実に伝わります</p></div></div></div><!-- ポイント4: 指導 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-chalkboard-teacher fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">指導：一言で要点→必要に応じて丁寧版へ切替</p><p class="bullet-content">後輩や部下への指導は、まず簡潔に要点を伝え、理解度や状況に応じて詳細な説明に切り替える。相手の理解度や時間的制約を尊重した柔軟な指導が心地よい職場を作ります</p></div></div></div><!-- ポイント5: 感情コントロール --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-balance-scale fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">感情コントロール：怒りを直接ぶつけない</p><p class="bullet-content">不満や怒りを感じても、一呼吸置いて冷静になってから対応する。感情的にならず、事実と改善点を整理して伝えることで、建設的な関係が維持できます</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">ビジネスシーンでの配慮は、相手の立場を想像し自分なら何を望むかを考えることから</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .bullet-item {      border-left: 3px solid #e53e3e;    }    .icon-box {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }    .bullet-title {      color: #1a365d;      font-weight: 600;    }    .bullet-content {      color: #4a5568;    }
</style>
