<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="キーセンテンス・用語集" :current-page="19" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-8"><p class="slide-title text-3xl font-bold">キーセンテンス・用語集</p><div class="accent-line mt-4"></div></div><!-- 用語コンテンツ部分 --><div class="flex flex-col gap-6 max-w-4xl"><!-- 用語1: 返報性の法則 --><div class="flex items-start gap-6"><div class="icon-circle flex-shrink-0"><i class="fas fa-sync-alt fa-lg"></i></div><div class="flex-1"><div class="key-term p-4"><p class="key-term-title text-xl mb-1">返報性の法則</p><p class="key-term-content">好意は返したくなる心理的作用。ただし気遣いは見返り前提で行わず、純粋な思いやりから生まれる行為であるべき。</p></div></div></div><!-- 用語2: 相手本位 --><div class="flex items-start gap-6"><div class="icon-circle flex-shrink-0"><i class="fas fa-user-check fa-lg"></i></div><div class="flex-1"><div class="key-term p-4"><p class="key-term-title text-xl mb-1">相手本位</p><p class="key-term-content">基準は「相手が助かる／嬉しいか」。自分の満足や自己PRではなく、相手の立場で考え行動することが真の気遣い。</p></div></div></div><!-- 用語3: 強制しない気遣い --><div class="flex items-start gap-6"><div class="icon-circle flex-shrink-0"><i class="fas fa-hand-paper fa-lg"></i></div><div class="flex-1"><div class="key-term p-4"><p class="key-term-title text-xl mb-1">強制しない気遣い</p><p class="key-term-content">反応やお返しを求めない・介入しない。相手の自律性を尊重し、押し付けにならない配慮が重要。</p></div></div></div><!-- 用語4: すべての人に好かれない --><div class="flex items-start gap-6"><div class="icon-circle flex-shrink-0"><i class="fas fa-users fa-lg"></i></div><div class="flex-1"><div class="key-term p-4"><p class="key-term-title text-xl mb-1">すべての人に好かれない</p><p class="key-term-content">評価はコントロール不能。全員から良い評価を得ようとするのは不可能であり、自分の軸を持ちながら気遣うことが大切。</p></div></div></div><!-- 用語5: さりげなさ --><div class="flex items-start gap-6"><div class="icon-circle flex-shrink-0"><i class="fas fa-feather-alt fa-lg"></i></div><div class="flex-1"><div class="key-term p-4"><p class="key-term-title text-xl mb-1">さりげなさ</p><p class="key-term-content">自律を奪わず、静かに環境を整える配慮。大人の気遣いは「してあげた感」を出さず、相手が心地よく過ごせる空間を自然に作る。</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">本書を通して学ぶ、相手本位の気配りの本質</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .key-term {      border-left: 3px solid #e53e3e;      border-radius: 0 8px 8px 0;      background-color: rgba(237, 242, 247, 0.5);    }    .key-term-title {      color: #1a365d;      font-weight: 600;      font-family: 'Noto Serif JP', serif;    }    .key-term-content {      color: #4a5568;    }    .icon-circle {      width: 54px;      height: 54px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);    }
</style>
