<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="本書の概要・背景・対象読者" :current-page="2" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-10"><p class="slide-title text-3xl font-bold">本書の概要・背景・対象読者</p><div class="accent-line mt-4"></div></div><!-- コンテンツ部分：2カラムレイアウト --><div class="flex flex-1 gap-10"><!-- 左カラム：4つのセクション --><div class="w-1/2 flex flex-col gap-8"><!-- 背景 --><div class="flex items-start gap-4"><div class="icon-circle flex-shrink-0"><i class="fas fa-history fa-lg"></i></div><div><p class="section-title text-xl mb-2">背景</p><p class="section-content">気遣いの"やりすぎ"や方向違いが相手に負担・違和感を与えるケースが増加。特に日本では「思いやり」が逆に相手を困らせることも。</p></div></div><!-- 目的 --><div class="flex items-start gap-4"><div class="icon-circle flex-shrink-0"><i class="fas fa-bullseye fa-lg"></i></div><div><p class="section-title text-xl mb-2">目的</p><p class="section-content">相手本位の視点に立ち、実践で役立つ"ちょうどいい"配慮を身につける。「やりすぎ」「裏目に出る」気遣いを見直す。</p></div></div></div><!-- 右カラム：残りのセクション --><div class="w-1/2 flex flex-col gap-8"><!-- 対象読者 --><div class="flex items-start gap-4"><div class="icon-circle flex-shrink-0"><i class="fas fa-users fa-lg"></i></div><div><p class="section-title text-xl mb-2">対象読者</p><p class="section-content">・社会人全般／管理職・リーダー<br/>・接客・顧客対応職<br/>・新人育成に携わる人<br/>・気遣いでストレスを感じている方</p></div></div><!-- 読後の変化 --><div class="flex items-start gap-4"><div class="icon-circle flex-shrink-0"><i class="fas fa-lightbulb fa-lg"></i></div><div><p class="section-title text-xl mb-2">読後の変化</p><p class="section-content">・押し付けない気遣いにシフト<br/>・会話・メール・場づくりが洗練<br/>・多様性に強い配慮力<br/>・自然体で"ちょうどいい"関係構築</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">元ANA客室乗務員・人材教育講師 三上ナナエ著</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .section-title {      color: #1a365d;      font-weight: 600;    }    .section-content {      color: #4a5568;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .icon-circle {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }
</style>
