<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="まとめ・行動への呼びかけ" :current-page="20" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-10"><p class="slide-title text-3xl font-bold">まとめ・行動への呼びかけ</p><div class="accent-line mt-4"></div></div><!-- 箇条書きコンテンツ部分 --><div class="flex flex-col gap-8 max-w-4xl"><!-- ポイント1: 本書の核 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-book fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">本書の核：やりすぎない、押し付けない、相手本位の配慮</p><p class="bullet-content">「よかれと思う気遣い」が逆効果になるケースを理解し、相手の立場に立った適切な気遣いを心がけましょう</p></div></div></div><!-- ポイント2: 明日からのチェックリスト --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-clipboard-check fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">明日からのチェックリスト</p><p class="bullet-content">1) 目的は何か？ - 形式的でなく本質的な理由を考える<br/>2) 相手は楽になるか？ - 負担を増やしていないか確認<br/>3) 見返りを期待していないか？ - 純粋な思いやりか点検<br/>4) 選択肢を提示したか？ - 押し付けではなく自律尊重<br/>5) 自然体で振る舞えているか？ - 過剰演出していないか</p></div></div></div><!-- ポイント3: ゴール --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-flag fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">ゴール：関係の安心・信頼・自律を育てる気遣いへ</p><p class="bullet-content">相手本位のさりげない気遣いは、人間関係を豊かにし、互いを尊重する文化を育てます。真の「気遣いの達人」を目指しましょう</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">三上ナナエ著『その気遣い、むしろ無礼になってます！』より</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .bullet-item {      border-left: 3px solid #e53e3e;    }    .icon-box {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }    .bullet-title {      color: #1a365d;      font-weight: 600;    }    .bullet-content {      color: #4a5568;    }
</style>
