<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="全体構成（目次）" :current-page="3" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-10"><p class="slide-title text-3xl font-bold">全体構成（目次）</p><div class="accent-line mt-4"></div></div><!-- 目次コンテンツ部分 --><div class="flex flex-col gap-8 mt-6 max-w-4xl mx-auto"><!-- 第1章 --><div class="chapter-item flex items-center"><div class="flex items-center w-16"><p class="chapter-number text-3xl">1</p></div><div class="dotted-line"></div><div class="flex-1"><p class="chapter-title text-xl">気遣いの心構え・基本姿勢</p></div></div><!-- 第2章 --><div class="chapter-item flex items-center"><div class="flex items-center w-16"><p class="chapter-number text-3xl">2</p></div><div class="dotted-line"></div><div class="flex-1"><p class="chapter-title text-xl">ついやってしまう「やりすぎ」気遣い</p></div></div><!-- 第3章 --><div class="chapter-item flex items-center"><div class="flex items-center w-16"><p class="chapter-number text-3xl">3</p></div><div class="dotted-line"></div><div class="flex-1"><p class="chapter-title text-xl">気を利かせたつもりが「裏目に出る」気遣い</p></div></div><!-- 第4章 --><div class="chapter-item flex items-center"><div class="flex items-center w-16"><p class="chapter-number text-3xl">4</p></div><div class="dotted-line"></div><div class="flex-1"><p class="chapter-title text-xl">なかなか距離が縮まらない「会話」の気遣い</p></div></div><!-- 第5章 --><div class="chapter-item flex items-center"><div class="flex items-center w-16"><p class="chapter-number text-3xl">5</p></div><div class="dotted-line"></div><div class="flex-1"><p class="chapter-title text-xl">多様性時代の「勘違い」気遣い</p></div></div><!-- 第6章 --><div class="chapter-item flex items-center"><div class="flex items-center w-16"><p class="chapter-number text-3xl">6</p></div><div class="dotted-line"></div><div class="flex-1"><p class="chapter-title text-xl">これぞ大人のさりげない気遣い！エピソード集</p></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">目次から始まる6章構成で、具体例やエピソードを交えながら「本物の気配り」を解説します</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .chapter-number {      color: #e53e3e;      font-weight: 700;      font-family: 'Noto Serif JP', serif;    }    .chapter-title {      color: #1a365d;      font-weight: 500;      font-family: 'Noto Sans JP', sans-serif;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .dotted-line {      flex-grow: 1;      height: 1px;      border-bottom: 2px dotted #cbd5e0;      margin: 0 15px;    }    .chapter-item {      transition: all 0.3s ease;    }    .chapter-item:hover {      transform: translateX(10px);    }
</style>
