<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="第1章｜重要な心構え" :current-page="5" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-10"><p class="slide-title text-3xl font-bold">第1章｜重要な心構え</p><div class="accent-line mt-4"></div></div><!-- 箇条書きコンテンツ部分 --><div class="flex flex-col gap-8 max-w-4xl"><!-- ポイント1: 返報性の法則 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-sync-alt fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">返報性の法則を知りつつ、見返り前提で動かない</p><p class="bullet-content">相手が好意に報いる心理を理解しつつも、自分の行動はそれを期待せず純粋に相手のために行う姿勢が大切です</p></div></div></div><!-- ポイント2: すべての人に好かれない --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-users fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">すべての人に好かれようとしない</p><p class="bullet-content">全員からの評価を得ようとするのは不可能。評価はコントロール不能なものと理解し、自分の基準で行動する勇気を持ちましょう</p></div></div></div><!-- ポイント3: 自己PRチェック --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-clipboard-check fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">自己PRや自己満足になっていないかセルフチェック</p><p class="bullet-content">「この行動は相手のため？それとも自分のアピールのため？」と定期的に自問し、気遣いの本質を見失わないようにする</p></div></div></div><!-- ポイント4: 目的思考 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-bullseye fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">目的思考：何のために"いま"それをするのか？</p><p class="bullet-content">形式的・習慣的な気遣いではなく、「なぜ今この行動が必要か」という目的を明確にすることで、真に役立つ気遣いが実現できます</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">相手本位の心構えが、気遣いの質を高めます</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .bullet-item {      border-left: 3px solid #e53e3e;    }    .icon-box {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }    .bullet-title {      color: #1a365d;      font-weight: 600;    }    .bullet-content {      color: #4a5568;    }
</style>
