<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="第2章①｜お返しのしすぎ／相手に気遣わせない'しすぎ'" :current-page="7" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-10"><p class="slide-title text-3xl font-bold">第2章①｜お返しのしすぎ／相手に気遣わせない"しすぎ"</p><div class="accent-line mt-4"></div></div><!-- 箇条書きコンテンツ部分 --><div class="flex flex-col gap-8 max-w-4xl"><!-- ポイント1: お返しのしすぎの問題点 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-exchange-alt fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">すぐにお返し → 取引化・負担化のリスク</p><p class="bullet-content">相手の好意にすぐ返そうとすると、「貸し借り」のような関係になり、気遣いが義務的な印象に。結果、相手に「気を遣わせてしまった」と負担を与えます。</p></div></div></div><!-- ポイント2: お返しのしすぎの代替案 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-check-circle fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">代替案：お返しは文脈に応じて時期と形を吟味</p><p class="bullet-content">即時返礼ではなく、タイミングを見計らい、相手が本当に喜ぶ形でのお返しを考える。純粋な感謝の気持ちを表現し、相手の負担にならないよう配慮します。</p></div></div></div><!-- ポイント3: 相手に気遣わせないしすぎの問題点 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-hand-holding fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">何でも先回りして相手に気を遣わせない → 主導権を奪い、遠慮を増やす</p><p class="bullet-content">相手の行動や選択の機会を奪うことで、かえって関係性に壁ができたり、相手が自分の本当の気持ちを表現しづらくなったりします。</p></div></div></div><!-- ポイント4: 相手に気遣わせないしすぎの代替案 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-balance-scale fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">代替案：相手の申し出や裁量を尊重</p><p class="bullet-content">相手が気遣いを示したいときは、素直に受け入れる勇気も必要。双方向の気遣いが信頼関係を深め、健全な人間関係を築く基盤となります。</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">「ちょうどいい」関係性のために、過剰な気遣いは控えましょう</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .bullet-item {      border-left: 3px solid #e53e3e;    }    .icon-box {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }    .bullet-title {      color: #1a365d;      font-weight: 600;    }    .bullet-content {      color: #4a5568;    }
</style>
