<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="第2章②｜同調しすぎ／未依頼アドバイス" :current-page="8" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-10"><p class="slide-title text-3xl font-bold">第2章②｜同調しすぎ／未依頼アドバイス</p><div class="accent-line mt-4"></div></div><!-- 箇条書きコンテンツ部分 --><div class="flex flex-col gap-8 max-w-4xl"><!-- ポイント1: 同調しすぎ --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-thumbs-up fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">何でも相手に合わせる→不透明な人・責任回避と映る</p><p class="bullet-content">常に「そうですね」「おっしゃる通りです」と同調するばかりでは、自分の意見がない人、責任を取りたくない人と思われがち。相手はあなたの本音や価値観を知りたいと思っています。</p></div></div></div><!-- ポイント2: 代替案（同調） --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-exchange-alt fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">代替：自分の見解は根拠とともに簡潔に</p><p class="bullet-content">同調する場面と自分の意見を伝える場面を区別し、意見を述べる際は「〜と考えています、理由は〜です」と根拠も添えることで建設的な関係が築けます。</p></div></div></div><!-- ポイント3: 未依頼アドバイス --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-comment-medical fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">頼まれていない助言→"よけいなお世話"になりがち</p><p class="bullet-content">相手が求めていないのに「こうした方がいい」と助言すると、相手の能力や判断を信頼していないと受け取られ、不快感や距離感を生じさせることがあります。</p></div></div></div><!-- ポイント4: 代替案（アドバイス） --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-lightbulb fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">代替：助言は依頼・許可・ニーズを確認</p><p class="bullet-content">「もし良ければ、私の考えをお伝えしてもいいですか？」など、まず許可を得る。または「何かお手伝いできることはありますか？」と相手のニーズを確認してから提案する。</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">相手の自律性を尊重し、対等な関係を築く気遣いが重要です</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .bullet-item {      border-left: 3px solid #e53e3e;    }    .icon-box {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }    .bullet-title {      color: #1a365d;      font-weight: 600;    }    .bullet-content {      color: #4a5568;    }
</style>
