<template>
  <SlidePageWrapper slide-id="B095RG8WGZ" page-title="第2章③｜贈り物多発／恐縮お礼／型通りマナー" :current-page="9" :total-pages="20">
<div class="slide-container flex flex-col p-14"><!-- ヘッダー部分 --><div class="mb-10"><p class="slide-title text-3xl font-bold">第2章③｜贈り物多発／恐縮お礼／型通りマナー</p><div class="accent-line mt-4"></div></div><!-- 箇条書きコンテンツ部分 --><div class="flex flex-col gap-8 max-w-4xl"><!-- ポイント1: 贈り物多発 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-gift fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">理由なき贈与の頻発→戸惑いと負担</p><p class="bullet-content">特別な理由もなく物をあげすぎると、相手は保管の負担やお返しの義務感に困惑。目的が不明確なプレゼントは気遣いではなく、気苦労の種になりがちです</p></div></div></div><!-- ポイント2: 恐縮お礼 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-pray fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">「悪いです」等の恐縮過多→相手に否定返答を強いる</p><p class="bullet-content">過剰な謙遜や恐縮の言葉は、相手に「そんなことないですよ」と返すよう強制し、会話の負担に。感謝は素直に、前向きな表現で伝えるのが望ましいです</p></div></div></div><!-- ポイント3: 型通りマナー --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-book fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">型通り一辺倒→状況不適合の堅苦しさ</p><p class="bullet-content">「つまらないものですが」といった型通りのマナーに固執すると、逆に相手を不快にしたり、距離感を生み出すことも。状況や相手との関係性に応じた柔軟さが必要です</p></div></div></div><!-- ポイント4: 代替案 --><div class="flex items-start gap-6"><div class="icon-box flex-shrink-0"><i class="fas fa-lightbulb fa-lg"></i></div><div class="flex-1"><div class="bullet-item pl-4"><p class="bullet-title text-xl mb-2">代替：目的の明確化と状況適応</p><p class="bullet-content">贈り物は目的と頻度を最適化／お礼は「お役に立てて嬉しいです」など前向きな表現／マナーも状況に応じて形式より実質を重視／心からの思いを素直に伝える工夫を</p></div></div></div></div><!-- フッター部分 --><div class="mt-auto pt-6 border-t border-gray-300"><p class="text-sm text-gray-500 text-center">行き過ぎた謙遜や形式主義よりも、自然体の気遣いが心に届きます</p></div></div>
  </SlidePageWrapper>
</template>

<style scoped>
body, html {      margin: 0;      padding: 0;      width: 100%;      height: 100%;    }    .slide-container {      width: 1280px;      min-height: 720px;      background-color: #f7f3ed;      position: relative;      overflow: hidden;      font-family: 'Noto Sans JP', sans-serif;    }    .slide-title {      font-family: 'Noto Serif JP', serif;      color: #1a365d;    }    .accent-line {      width: 80px;      height: 3px;      background-color: #e53e3e;    }    .bullet-item {      border-left: 3px solid #e53e3e;    }    .icon-box {      width: 50px;      height: 50px;      border-radius: 50%;      background-color: #edf2f7;      display: flex;      align-items: center;      justify-content: center;      color: #1a365d;    }    .bullet-title {      color: #1a365d;      font-weight: 600;    }    .bullet-content {      color: #4a5568;    }
</style>
